

expected_output = {
    'interfaces': {
        'GigabitEthernet0/0/0/0': {
            'interface': 'GigabitEthernet0/0/0/0',
            'neighbors': {
                '2001:db8:8548:1::1': {
                    'age': '82',
                    'ip': '2001:db8:8548:1::1',
                    'link_layer_address': 'fa16.3eff.c4d3',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': 'Y',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'dynamic',
                },
                '2001:db8:8548:1::22': {
                    'age': '-',
                    'ip': '2001:db8:8548:1::22',
                    'link_layer_address': 'aaaa.beff.6b6b',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': 'Y',
                    'dynamic': '-',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'static',
                },
                'fe80::f816:3eff:feff:c4d3': {
                    'age': '158',
                    'ip': 'fe80::f816:3eff:feff:c4d3',
                    'link_layer_address': 'fa16.3eff.c4d3',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': 'Y',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'dynamic',
                },
                'Mcast adjacency': {
                    'age': '-',
                    'ip': 'Mcast adjacency',
                    'link_layer_address': '0000.0000.0000',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': '-',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'other',
                },
            },
        },
        'GigabitEthernet0/0/0/3': {
            'interface': 'GigabitEthernet0/0/0/3',
            'neighbors': {
                '2001:db8:c8d1:4::3': {
                    'age': '114',
                    'ip': '2001:db8:c8d1:4::3',
                    'link_layer_address': '5e01.c0ff.0209',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': 'Y',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'dynamic',
                },
                'fe80::5c01:c0ff:feff:209': {
                    'age': '12',
                    'ip': 'fe80::5c01:c0ff:feff:209',
                    'link_layer_address': '5e01.c0ff.0209',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': 'Y',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'dynamic',
                },
                'Mcast adjacency': {
                    'age': '-',
                    'ip': 'Mcast adjacency',
                    'link_layer_address': '0000.0000.0000',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': '-',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'other',
                },
            },
        },
        'GigabitEthernet0/0/0/2': {
            'interface': 'GigabitEthernet0/0/0/2',
            'neighbors': {
                '2001:db8:c56d:4::3': {
                    'age': '1',
                    'ip': '2001:db8:c56d:4::3',
                    'link_layer_address': '5e01.c0ff.0209',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': 'Y',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'dynamic',
                },
                'fe80::5c01:c0ff:feff:209': {
                    'age': '12',
                    'ip': 'fe80::5c01:c0ff:feff:209',
                    'link_layer_address': '5e01.c0ff.0209',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': 'Y',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'dynamic',
                },
                'Mcast adjacency': {
                    'age': '-',
                    'ip': 'Mcast adjacency',
                    'link_layer_address': '0000.0000.0000',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': '-',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'other',
                },
            },
        },
        'GigabitEthernet0/0/0/1': {
            'interface': 'GigabitEthernet0/0/0/1',
            'neighbors': {
                '2001:db8:888c:1::1': {
                    'age': '4',
                    'ip': '2001:db8:888c:1::1',
                    'link_layer_address': 'fa16.3eff.f679',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': 'Y',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'dynamic',
                },
                '2001:db8:888c:1::22': {
                    'age': '-',
                    'ip': '2001:db8:888c:1::22',
                    'link_layer_address': 'dddd.beff.9a9a',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': 'Y',
                    'dynamic': '-',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'static',
                },
                'fe80::f816:3eff:feff:f679': {
                    'age': '37',
                    'ip': 'fe80::f816:3eff:feff:f679',
                    'link_layer_address': 'fa16.3eff.f679',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': 'Y',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'dynamic',
                },
                'Mcast adjacency': {
                    'age': '-',
                    'ip': 'Mcast adjacency',
                    'link_layer_address': '0000.0000.0000',
                    'neighbor_state': 'REACH',
                    'location': '0/0/CPU0',
                    'static': '-',
                    'dynamic': '-',
                    'sync': '-',
                    'serg_flags': 'ff',
                    'origin': 'other',
                },
            },
        },
    },
}
