expected_output = {
    "interfaces":{
        "FortyGigabitEthernet1/1/1":{
            "authentication_periodic":True,
            "authentication_timer_reauthenticate":6000,
            "access_session_host_mode":"multi-host",
            "access_session":"closed",
            "access_session_port_control":"auto",
            "dot1x_pae":"both",
            "dot1x_timeout_quiet_period":"70",
            "dot1x_timeout_server_timeout":"67",
            "dot1x_timeout_tx_period":"78",
            "dot1x_timeout_supp_timeout":87,
            "dot1x_max_req":6,
            "dot1x_authenticator_eap_profile":"Self",
            "dot1x_timeout_held_period":63,
            "dot1x_credentials":"EAPTLSCRED-IOSCA",
            "dot1x_supplicant_eap_profile":"Self"
        }
    }
}