expected_output = {
    "global_policy": {
        "service_policy": {
            "global_policy": {
                "class_map": {
                    "inspection_default": {
                        "inspect": {
                            "dns": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "inspect_map": "preset_dns_map",
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                            "esmtp": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "inspect_map": "_default_esmtp_map",
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                            "ftp": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                            "h323 h225": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "inspect_map": "_default_h323_map",
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "tcp_proxy": {"bytes_dropped": 0, "bytes_in_buffer": 0},
                                "v6_fail_close": 0,
                            },
                            "h323 ras": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "inspect_map": "_default_h323_map",
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                            "ip-options": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "inspect_map": "_default_ip_options_map",
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                            "netbios": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                            "rsh": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                            "rtsp": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "tcp_proxy": {"bytes_dropped": 0, "bytes_in_buffer": 0},
                                "v6_fail_close": 0,
                            },
                            "sip": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "tcp_proxy": {"bytes_dropped": 0, "bytes_in_buffer": 0},
                                "v6_fail_close": 0,
                            },
                            "skinny": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "tcp_proxy": {"bytes_dropped": 0, "bytes_in_buffer": 0},
                                "v6_fail_close": 0,
                            },
                            "sqlnet": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                            "sunrpc": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "tcp_proxy": {"bytes_dropped": 0, "bytes_in_buffer": 0},
                                "v6_fail_close": 0,
                            },
                            "tftp": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                            "xdmcp": {
                                "drop": 0,
                                "five_minute_pkt_rate": 0,
                                "lock_fail": 0,
                                "packet": 0,
                                "reset_drop": 0,
                                "sctp_drop_override": 0,
                                "v6_fail_close": 0,
                            },
                        }
                    }
                }
            }
        }
    }
}
