expected_output = {
    "cts_rb_count": {
        1: {
            "src_group": "*",
            "dst_group": "*",
            "sw_denied_count": 0,
            "hw_denied_count": 0,
            "sw_permit_count": 2,
            "hw_permit_count": 30802626587,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
        2: {
            "src_group": "2",
            "dst_group": "0",
            "sw_denied_count": 0,
            "hw_denied_count": 4794060,
            "sw_permit_count": 0,
            "hw_permit_count": 0,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
        3: {
            "src_group": "7",
            "dst_group": "0",
            "sw_denied_count": 0,
            "hw_denied_count": 0,
            "sw_permit_count": 0,
            "hw_permit_count": 0,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
        4: {
            "src_group": "99",
            "dst_group": "0",
            "sw_denied_count": 0,
            "hw_denied_count": 0,
            "sw_permit_count": 0,
            "hw_permit_count": 0,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
        5: {
            "src_group": "100",
            "dst_group": "0",
            "sw_denied_count": 0,
            "hw_denied_count": 0,
            "sw_permit_count": 0,
            "hw_permit_count": 0,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
        6: {
            "src_group": "103",
            "dst_group": "0",
            "sw_denied_count": 0,
            "hw_denied_count": 0,
            "sw_permit_count": 0,
            "hw_permit_count": 0,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
        7: {
            "src_group": "104",
            "dst_group": "0",
            "sw_denied_count": 0,
            "hw_denied_count": 0,
            "sw_permit_count": 0,
            "hw_permit_count": 0,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
        8: {
            "src_group": "2",
            "dst_group": "2",
            "sw_denied_count": 0,
            "hw_denied_count": 4,
            "sw_permit_count": 0,
            "hw_permit_count": 0,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
        9: {
            "src_group": "7",
            "dst_group": "2",
            "sw_denied_count": 0,
            "hw_denied_count": 0,
            "sw_permit_count": 0,
            "hw_permit_count": 0,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
        10: {
            "src_group": "99",
            "dst_group": "2",
            "sw_denied_count": 0,
            "hw_denied_count": 0,
            "sw_permit_count": 0,
            "hw_permit_count": 0,
            "sw_monitor_count": 0,
            "hw_monitor_count": 0,
        },
    }
}
