expected_output={
'asic': {'0': {'name': {'ALLOW_DOT1Q_EXCEPTION_COUNT': {'current': 348,
                                                         'delta': 0,
                                                         'prev': 348},
                         'ALLOW_NATIVE_EXCEPTION_COUNT': {'current': 0,
                                                          'delta': 0,
                                                          'prev': 0},
                         'ALLOW_PRIORITY_TAGGED_EXCEPTION_COUNT': {'current': 0,
                                                                   'delta': 0,
                                                                   'prev': 0},
                         'ALLOW_UNKNOWN_ETHER_TYPE_EXCEPTION': {'current': 0,
                                                                'delta': 0,
                                                                'prev': 0},
                         'AUTH_DRIVEN_DROP': {'current': 0,
                                              'delta': 0,
                                              'prev': 0},
                         'BLOCK_FORWARD': {'current': 351,
                                           'delta': 0,
                                           'prev': 351},
                         'COPY_TO_CPU': {'current': 0, 'delta': 0, 'prev': 0},
                         'CTS_FILTERED_EXCEPTION': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'DEJA_VU_CHECK_FAILED': {'current': 0,
                                                  'delta': 0,
                                                  'prev': 0},
                         'DENY_BRIDGE': {'current': 0, 'delta': 0, 'prev': 0},
                         'DENY_NO_IP_UNREACHABLE': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'DENY_ROUTE': {'current': 0, 'delta': 0, 'prev': 0},
                         'EGR_HARDWARE_PARSE_EXCEPTION': {'current': 0,
                                                          'delta': 0,
                                                          'prev': 0},
                         'EGR_L3_ERROR': {'current': 0, 'delta': 0, 'prev': 0},
                         'EGR_L4_ERROR': {'current': 0, 'delta': 0, 'prev': 0},
                         'EGR_L5_ERROR': {'current': 0, 'delta': 0, 'prev': 0},
                         'EGR_SHOW_FORWARD_DROP': {'current': 0,
                                                   'delta': 0,
                                                   'prev': 0},
                         'FPM_DROP_PACKET': {'current': 0,
                                             'delta': 0,
                                             'prev': 0},
                         'FRAGMENTING_IPV4_WITH_OPTIONS': {'current': 0,
                                                           'delta': 0,
                                                           'prev': 0},
                         'FRAGMENTING_IPV6_WITH_EXTENSIONS': {'current': 0,
                                                              'delta': 0,
                                                              'prev': 0},
                         'ICMP_REDIRECT': {'current': 0, 'delta': 0, 'prev': 0},
                         'IGR_EXCEPTION_31': {'current': 0,
                                              'delta': 0,
                                              'prev': 0},
                         'IGR_EXCEPTION_HARDWARE_PARSE_EXCEPTION': {'current': 0,
                                                                    'delta': 0,
                                                                    'prev': 0},
                         'IGR_EXCEPTION_INVALID_VLAN_DROP': {'current': 0,
                                                             'delta': 0,
                                                             'prev': 0},
                         'IGR_EXCEPTION_L4_ERROR': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'IGR_EXCEPTION_L5_ERROR': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'IGR_MISC_FATAL_ERROR': {'current': 2994279,
                                                  'delta': 0,
                                                  'prev': 2994279},
                         'IPV4_CHECKSUM_ERROR': {'current': 0,
                                                 'delta': 0,
                                                 'prev': 0},
                         'IP_MULTICAST_TTL_REACHED_ZERO': {'current': 0,
                                                           'delta': 0,
                                                           'prev': 0},
                         'IP_SOURCE_GUARD_VIOLATION': {'current': 0,
                                                       'delta': 0,
                                                       'prev': 0},
                         'IP_UNICAST_TTL_REACHED_ZERO': {'current': 0,
                                                         'delta': 0,
                                                         'prev': 0},
                         'LINK_LOCAL_CHECK_FAIL_L3M_VALID': {'current': 0,
                                                             'delta': 0,
                                                             'prev': 0},
                         'LINK_LOCAL_CHECK_FAIL_NOT_NO_IP_UNREACHABLE': {'current': 0,
                                                                         'delta': 0,
                                                                         'prev': 0},
                         'LINK_LOCAL_CHECK_FAIL_NO_IP_UNREACHABLE': {'current': 0,
                                                                     'delta': 0,
                                                                     'prev': 0},
                         'MISC_FATAL_ERROR': {'current': 0,
                                              'delta': 0,
                                              'prev': 0},
                         'MTU_FAIL_DROP_BRIDGED': {'current': 0,
                                                   'delta': 0,
                                                   'prev': 0},
                         'MTU_FAIL_DROP_BRIDGED_IP_ROUTED': {'current': 0,
                                                             'delta': 0,
                                                             'prev': 0},
                         'MTU_FAIL_ERSPAN': {'current': 0,
                                             'delta': 0,
                                             'prev': 0},
                         'MTU_FAIL_PUNT_TO_CPU_NOT_NO_IP_UNREACHABLE': {'current': 0,
                                                                        'delta': 0,
                                                                        'prev': 0},
                         'MTU_FAIL_PUNT_TO_CPU_NO_IP_UNREACHABLE': {'current': 0,
                                                                    'delta': 0,
                                                                    'prev': 0},
                         'NOT_VLAN_LOAD_BALANCE_GROUP_ALLOWED': {'current': 0,
                                                                 'delta': 0,
                                                                 'prev': 0},
                         'NO_EXCEPTION': {'current': 354757713,
                                          'delta': 2193,
                                          'prev': 354755520},
                         'PKT_DROP_COUNT': {'current': 2994630,
                                            'delta': 0,
                                            'prev': 2994630},
                         'POLICER_DROP': {'current': 0, 'delta': 0, 'prev': 0},
                         'PROTECTED_PORT_DROP': {'current': 0,
                                                 'delta': 0,
                                                 'prev': 0},
                         'PRUNED': {'current': 0, 'delta': 0, 'prev': 0},
                         'PVLAN_COMMUNITY_CHECK_FAILED': {'current': 0,
                                                          'delta': 0,
                                                          'prev': 0},
                         'PVLAN_ISOLATED_CHECK_FAILED': {'current': 0,
                                                         'delta': 0,
                                                         'prev': 0},
                         'ROUTED_AND_IP_OPTIONS_EXCEPTION': {'current': 2,
                                                             'delta': 0,
                                                             'prev': 2},
                         'RPF_MULTICAST_FAIL': {'current': 0,
                                                'delta': 0,
                                                'prev': 0},
                         'RPF_UNICAST_CHECK_INCOMPLETE': {'current': 0,
                                                          'delta': 0,
                                                          'prev': 0},
                         'RPF_UNICAST_FAIL': {'current': 0,
                                              'delta': 0,
                                              'prev': 0},
                         'RPF_UNICAST_FAIL_SUPPRESS': {'current': 0,
                                                       'delta': 0,
                                                       'prev': 0},
                         'RSPAN_DROP': {'current': 0, 'delta': 0, 'prev': 0},
                         'SECURE_L3IF_LEARNING_VIOLATION': {'current': 0,
                                                            'delta': 0,
                                                            'prev': 0},
                         'SGT_CACHING_NEEDED': {'current': 0,
                                                'delta': 0,
                                                'prev': 0},
                         'SIA_TTL_ZERO': {'current': 0, 'delta': 0, 'prev': 0},
                         'SOURCE_ROUTE_EXCEPTION': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'SPLIT_HORIZON_DROP': {'current': 0,
                                                'delta': 0,
                                                'prev': 0},
                         'STATIC_IP_VIOLATION': {'current': 0,
                                                 'delta': 0,
                                                 'prev': 0},
                         'STATIC_MAC_VIOLATION': {'current': 0,
                                                  'delta': 0,
                                                  'prev': 0},
                         'STP_OR_FLEXLINK_DROP': {'current': 0,
                                                  'delta': 0,
                                                  'prev': 0},
                         'SYSTEM_TTL_DROP': {'current': 0,
                                             'delta': 0,
                                             'prev': 0},
                         'VLAN_LOADBALANCE_GROUP_DENY': {'current': 0,
                                                         'delta': 0,
                                                         'prev': 0}}},
          '1': {'name': {'ALLOW_DOT1Q_EXCEPTION_COUNT': {'current': 0,
                                                         'delta': 0,
                                                         'prev': 0},
                         'ALLOW_NATIVE_EXCEPTION_COUNT': {'current': 12,
                                                          'delta': 4,
                                                          'prev': 8},
                         'ALLOW_PRIORITY_TAGGED_EXCEPTION_COUNT': {'current': 0,
                                                                   'delta': 0,
                                                                   'prev': 0},
                         'ALLOW_UNKNOWN_ETHER_TYPE_EXCEPTION': {'current': 0,
                                                                'delta': 0,
                                                                'prev': 0},
                         'AUTH_DRIVEN_DROP': {'current': 0,
                                              'delta': 0,
                                              'prev': 0},
                         'BLOCK_FORWARD': {'current': 14,
                                           'delta': 4,
                                           'prev': 10},
                         'COPY_TO_CPU': {'current': 0, 'delta': 0, 'prev': 0},
                         'CTS_FILTERED_EXCEPTION': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'DEJA_VU_CHECK_FAILED': {'current': 0,
                                                  'delta': 0,
                                                  'prev': 0},
                         'DENY_BRIDGE': {'current': 0, 'delta': 0, 'prev': 0},
                         'DENY_NO_IP_UNREACHABLE': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'DENY_ROUTE': {'current': 0, 'delta': 0, 'prev': 0},
                         'EGR_HARDWARE_PARSE_EXCEPTION': {'current': 0,
                                                          'delta': 0,
                                                          'prev': 0},
                         'EGR_L3_ERROR': {'current': 0, 'delta': 0, 'prev': 0},
                         'EGR_L4_ERROR': {'current': 0, 'delta': 0, 'prev': 0},
                         'EGR_L5_ERROR': {'current': 0, 'delta': 0, 'prev': 0},
                         'EGR_SHOW_FORWARD_DROP': {'current': 0,
                                                   'delta': 0,
                                                   'prev': 0},
                         'FPM_DROP_PACKET': {'current': 0,
                                             'delta': 0,
                                             'prev': 0},
                         'FRAGMENTING_IPV4_WITH_OPTIONS': {'current': 0,
                                                           'delta': 0,
                                                           'prev': 0},
                         'FRAGMENTING_IPV6_WITH_EXTENSIONS': {'current': 0,
                                                              'delta': 0,
                                                              'prev': 0},
                         'ICMP_REDIRECT': {'current': 0, 'delta': 0, 'prev': 0},
                         'IGR_EXCEPTION_31': {'current': 0,
                                              'delta': 0,
                                              'prev': 0},
                         'IGR_EXCEPTION_HARDWARE_PARSE_EXCEPTION': {'current': 0,
                                                                    'delta': 0,
                                                                    'prev': 0},
                         'IGR_EXCEPTION_INVALID_VLAN_DROP': {'current': 0,
                                                             'delta': 0,
                                                             'prev': 0},
                         'IGR_EXCEPTION_L4_ERROR': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'IGR_EXCEPTION_L5_ERROR': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'IGR_MISC_FATAL_ERROR': {'current': 9635990,
                                                  'delta': 0,
                                                  'prev': 9635990},
                         'IPV4_CHECKSUM_ERROR': {'current': 0,
                                                 'delta': 0,
                                                 'prev': 0},
                         'IP_MULTICAST_TTL_REACHED_ZERO': {'current': 0,
                                                           'delta': 0,
                                                           'prev': 0},
                         'IP_SOURCE_GUARD_VIOLATION': {'current': 0,
                                                       'delta': 0,
                                                       'prev': 0},
                         'IP_UNICAST_TTL_REACHED_ZERO': {'current': 1671059,
                                                         'delta': 0,
                                                         'prev': 1671059},
                         'LINK_LOCAL_CHECK_FAIL_L3M_VALID': {'current': 0,
                                                             'delta': 0,
                                                             'prev': 0},
                         'LINK_LOCAL_CHECK_FAIL_NOT_NO_IP_UNREACHABLE': {'current': 0,
                                                                         'delta': 0,
                                                                         'prev': 0},
                         'LINK_LOCAL_CHECK_FAIL_NO_IP_UNREACHABLE': {'current': 0,
                                                                     'delta': 0,
                                                                     'prev': 0},
                         'MISC_FATAL_ERROR': {'current': 0,
                                              'delta': 0,
                                              'prev': 0},
                         'MTU_FAIL_DROP_BRIDGED': {'current': 0,
                                                   'delta': 0,
                                                   'prev': 0},
                         'MTU_FAIL_DROP_BRIDGED_IP_ROUTED': {'current': 0,
                                                             'delta': 0,
                                                             'prev': 0},
                         'MTU_FAIL_ERSPAN': {'current': 0,
                                             'delta': 0,
                                             'prev': 0},
                         'MTU_FAIL_PUNT_TO_CPU_NOT_NO_IP_UNREACHABLE': {'current': 383267722,
                                                                        'delta': 183748,
                                                                        'prev': 383083974},
                         'MTU_FAIL_PUNT_TO_CPU_NO_IP_UNREACHABLE': {'current': 383267722,
                                                                    'delta': 183750,
                                                                    'prev': 383083972},
                         'NOT_VLAN_LOAD_BALANCE_GROUP_ALLOWED': {'current': 0,
                                                                 'delta': 0,
                                                                 'prev': 0},
                         'NO_EXCEPTION': {'current': 1229125589,
                                          'delta': 308194892,
                                          'prev': 920930697},
                         'PKT_DROP_COUNT': {'current': 394574785,
                                            'delta': 183754,
                                            'prev': 394391031},
                         'POLICER_DROP': {'current': 0, 'delta': 0, 'prev': 0},
                         'PROTECTED_PORT_DROP': {'current': 0,
                                                 'delta': 0,
                                                 'prev': 0},
                         'PRUNED': {'current': 0, 'delta': 0, 'prev': 0},
                         'PVLAN_COMMUNITY_CHECK_FAILED': {'current': 0,
                                                          'delta': 0,
                                                          'prev': 0},
                         'PVLAN_ISOLATED_CHECK_FAILED': {'current': 0,
                                                         'delta': 0,
                                                         'prev': 0},
                         'ROUTED_AND_IP_OPTIONS_EXCEPTION': {'current': 0,
                                                             'delta': 0,
                                                             'prev': 0},
                         'RPF_MULTICAST_FAIL': {'current': 0,
                                                'delta': 0,
                                                'prev': 0},
                         'RPF_UNICAST_CHECK_INCOMPLETE': {'current': 0,
                                                          'delta': 0,
                                                          'prev': 0},
                         'RPF_UNICAST_FAIL': {'current': 0,
                                              'delta': 0,
                                              'prev': 0},
                         'RPF_UNICAST_FAIL_SUPPRESS': {'current': 0,
                                                       'delta': 0,
                                                       'prev': 0},
                         'RSPAN_DROP': {'current': 0, 'delta': 0, 'prev': 0},
                         'SECURE_L3IF_LEARNING_VIOLATION': {'current': 0,
                                                            'delta': 0,
                                                            'prev': 0},
                         'SGT_CACHING_NEEDED': {'current': 0,
                                                'delta': 0,
                                                'prev': 0},
                         'SIA_TTL_ZERO': {'current': 0, 'delta': 0, 'prev': 0},
                         'SOURCE_ROUTE_EXCEPTION': {'current': 0,
                                                    'delta': 0,
                                                    'prev': 0},
                         'SPLIT_HORIZON_DROP': {'current': 0,
                                                'delta': 0,
                                                'prev': 0},
                         'STATIC_IP_VIOLATION': {'current': 0,
                                                 'delta': 0,
                                                 'prev': 0},
                         'STATIC_MAC_VIOLATION': {'current': 0,
                                                  'delta': 0,
                                                  'prev': 0},
                         'STP_OR_FLEXLINK_DROP': {'current': 0,
                                                  'delta': 0,
                                                  'prev': 0},
                         'SYSTEM_TTL_DROP': {'current': 0,
                                             'delta': 0,
                                             'prev': 0},
                         'VLAN_LOADBALANCE_GROUP_DENY': {'current': 0,
                                                         'delta': 0,
                                                         'prev': 0}}}}}

