expected_output = {
    "interfaces": {
        "GigabitEthernet2/1": {
            "statistics": {
                "lastrxsrcmac": "d481.d7ff.4e83",
                "txtotal": 4821,
                "rxinvalid": 0,
                "txreqid": 1018,
                "rxtotal": 3918,
                "rxlogoff": 237,
                "rxrespid": 287,
                "rxversion": 1,
                "rxresp": 3147,
                "txreq": 3391,
                "rxstart": 212,
                "rxlenerr": 0,
            },
            "interface": "GigabitEthernet2/1",
        },
        "GigabitEthernet2/2": {
            "statistics": {
                "lastrxsrcmac": "2899.faff.cefe",
                "txtotal": 3148,
                "rxinvalid": 0,
                "txreqid": 525,
                "rxtotal": 2742,
                "rxlogoff": 71,
                "rxrespid": 220,
                "rxversion": 1,
                "rxresp": 2307,
                "txreq": 2480,
                "rxstart": 124,
                "rxlenerr": 0,
            },
            "interface": "GigabitEthernet2/2",
        },
        "GigabitEthernet2/3": {
            "statistics": {
                "lastrxsrcmac": "103a.34ff.be24",
                "txtotal": 3057,
                "rxinvalid": 0,
                "txreqid": 449,
                "rxtotal": 2746,
                "rxlogoff": 87,
                "rxrespid": 222,
                "rxversion": 1,
                "rxresp": 2290,
                "txreq": 2471,
                "rxstart": 111,
                "rxlenerr": 0,
            },
            "interface": "GigabitEthernet2/3",
        },
        "GigabitEthernet2/4": {
            "statistics": {
                "lastrxsrcmac": "0d01.f8ff.8324",
                "txtotal": 4304,
                "rxinvalid": 0,
                "txreqid": 902,
                "rxtotal": 3441,
                "rxlogoff": 0,
                "rxrespid": 298,
                "rxversion": 1,
                "rxresp": 2972,
                "txreq": 3214,
                "rxstart": 125,
                "rxlenerr": 0,
            },
            "interface": "GigabitEthernet2/4",
        },
    }
}
