expected_output = {
    "ipv4": {},
    "ipv6": {
        1: {
            "tunnel_id": 1,
            "fvrf": "none",
            "ivrf": "none",
            "status": "READY",
            "local_ip": "2001:DB8:1101::131",
            "local_port": 500,
            "remote_ip": "2001:DB8:1201::122",
            "remote_port": 500,
            "encryption": "AES-CBC",
            "keysize": 256,
            "prf": "SHA512",
            "hash": "SHA512",
            "dh_group": 21,
            "auth_sign": "PSK",
            "auth_verify": "PSK",
            "pqc": "ML-KEM-1024",
            "life_time": 86400,
            "active_time": 218,
            "ce_id": 0,
            "session_id": 3,
            "local_spi": "4CF87E32B25302C0",
            "remote_spi": "96254131FD306002"
        },
        2: {
            "tunnel_id": 2,
            "fvrf": "none",
            "ivrf": "none",
            "status": "READY",
            "local_ip": "2001:DB8:1101::131",
            "local_port": 500,
            "remote_ip": "2001:DB8:1202::123",
            "remote_port": 500,
            "encryption": "AES-CBC",
            "keysize": 256,
            "prf": "SHA512",
            "hash": "SHA512",
            "dh_group": 21,
            "auth_sign": "PSK",
            "auth_verify": "PSK",
            "pqc": "ML-KEM-1024",
            "life_time": 86400,
            "active_time": 207,
            "ce_id": 0,
            "session_id": 4,
            "local_spi": "DE66CA8E9F3AB6BD",
            "remote_spi": "DB3CED85555E739D"
        }
    }
}