expected_output = {
    'inventory_item_index': {
        0: {
            'description': 'nexus7700 c7706 (6 slot) chassis fan module',
            'name': 'slot 38',
            'pid': 'N77-C7706-FAN',
            'sn': 'DCH212300ZQ',
            'vid': 'V01',
        },
        1: {
            'description': 'nexus7700 c7706 (6 slot) chassis fan module',
            'name': 'slot 39',
            'pid': 'N77-C7706-FAN',
            'sn': 'DCH212300ZR',
            'vid': 'V01',
        },
        2: {
            'description': 'n2k-c2248tp-e-1ge  chassis',
            'name': 'fex 106 chassis',
            'pid': 'N2K-C2248TP-E-1GE',
            'sn': 'FOX2129PR28',
            'vid': 'V03',
        },
        3: {
            'description': 'fabric extender module: 48x1ge, 4x10ge supervisor',
            'name': 'fex 106 module 1',
            'pid': 'N2K-C2248TP-E-1GE',
            'sn': 'FOC21306SY6',
            'vid': 'V03',
        },
        4: {
            'description': 'fabric extender fan module',
            'name': 'fex 106 fan 1',
            'pid': 'N2K-C2248-FAN',
            'sn': 'N/A',
            'vid': 'N/A',
        },
        5: {
            'description': 'fabric extender ac power supply',
            'name': 'fex 106 power supply 1',
            'pid': 'N2200-PAC-400W',
            'sn': 'DCA21265683',
            'vid': 'V06',
        },
        6: {
            'description': 'fabric extender ac power supply',
            'name': 'fex 106 power supply 2',
            'pid': 'N2200-PAC-400W',
            'sn': 'DCA21265681',
            'vid': 'V06',
        },
        7: {
            'description': 'n2k-c2248tp-e-1ge  chassis',
            'name': 'fex 108 chassis',
            'pid': 'N2K-C2248TP-E-1GE',
            'sn': 'FOX2131P982',
            'vid': 'V03',
        },
        8: {
            'description': 'fabric extender module: 48x1ge, 4x10ge supervisor',
            'name': 'fex 108 module 1',
            'pid': 'N2K-C2248TP-E-1GE',
            'sn': 'FOC21306TAS',
            'vid': 'V03',
        },
        9: {
            'description': 'fabric extender fan module',
            'name': 'fex 108 fan 1',
            'pid': 'N2K-C2248-FAN',
            'sn': 'N/A',
            'vid': 'N/A',
        },
    },
}