expected_output = {
    "list_of_neighbors": [
        "10.16.2.2",
        "10.36.3.3",
        "10.4.6.6",
        "10.66.6.6",
        "10.64.4.4",
        "10.100.5.5",
        "2001:DB8:4:6::6",
        "2001:DB8:20:4:6::6",
    ],
    "vrf": {
        "default": {
            "neighbor": {
                "10.16.2.2": {
                    "remote_as": 100,
                    "link": "internal",
                    "shutdown": False,
                    "address_family": {
                        "vpnv4 unicast": {
                            "session_state": "Established",
                            "up_time": "01:10:35",
                            "last_read": "00:00:04",
                            "last_write": "00:00:09",
                            "current_time": "0x530449",
                        }
                    },
                    "bgp_version": 4,
                    "router_id": "10.16.2.2",
                    "session_state": "Established",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "route_refresh": "advertised and received(new)",
                        "four_octets_asn": "advertised and received",
                        "vpnv4_unicast": "advertised and received",
                        "vpnv6_unicast": "advertised and received",
                        "graceful_restart": "received",
                        "remote_restart_timer": 120,
                        "graceful_restart_af_advertised_by_peer": [
                            "vpnv4 unicast",
                            "vpnv6 unicast",
                        ],
                        "enhanced_refresh": "advertised",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "sent": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 11,
                                "keepalives": 75,
                                "route_refresh": 0,
                                "total": 87,
                            },
                            "received": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 6,
                                "keepalives": 74,
                                "route_refresh": 0,
                                "total": 81,
                            },
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                        }
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 0,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "10.16.2.2",
                        "connection": {
                            "established": 1,
                            "dropped": 0,
                            "last_reset": "never",
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "disabled",
                        "connection_state": "estab",
                        "io_status": 1,
                        "unread_input_bytes": 0,
                        "ecn_connection": "disabled",
                        "minimum_incoming_ttl": 0,
                        "outgoing_ttl": 255,
                        "transport": {
                            "local_host": "10.64.4.4",
                            "local_port": "35281",
                            "foreign_host": "10.16.2.2",
                            "foreign_port": "179",
                            "mss": 536,
                        },
                        "connection_tableid": 0,
                        "maximum_output_segment_queue_size": 50,
                        "enqueued_packets": {
                            "retransmit_packet": 0,
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                        },
                        "iss": 55023811,
                        "snduna": 55027115,
                        "sndnxt": 55027115,
                        "irs": 109992783,
                        "rcvnxt": 109995158,
                        "sndwnd": 16616,
                        "snd_scale": 0,
                        "maxrcvwnd": 16384,
                        "rcvwnd": 16327,
                        "rcv_scale": 0,
                        "delrcvwnd": 57,
                        "srtt": 1000,
                        "rtto": 1003,
                        "rtv": 3,
                        "krtt": 0,
                        "min_rtt": 4,
                        "max_rtt": 1000,
                        "ack_hold": 200,
                        "uptime": 4236258,
                        "sent_idletime": 4349,
                        "receive_idletime": 4549,
                        "status_flags": "active open",
                        "option_flags": "nagle, path mtu capable",
                        "ip_precedence_value": 6,
                        "datagram": {
                            "datagram_received": {
                                "value": 164,
                                "out_of_order": 0,
                                "with_data": 80,
                                "total_data": 2374,
                            },
                            "datagram_sent": {
                                "value": 166,
                                "retransmit": 0,
                                "fastretransmit": 0,
                                "partialack": 0,
                                "second_congestion": 0,
                                "with_data": 87,
                                "total_data": 3303,
                            },
                        },
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "fast_lock_acquisition_failures": 0,
                        "lock_slow_path": 0,
                        "tcp_semaphore": "0x1286E7EC",
                        "tcp_semaphore_status": "FREE",
                    },
                    "bgp_event_timer": {
                        "starts": {
                            "retrans": 86,
                            "timewait": 0,
                            "ackhold": 80,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 1,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "wakeups": {
                            "retrans": 0,
                            "timewait": 0,
                            "ackhold": 72,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 1,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "next": {
                            "retrans": "0x0",
                            "timewait": "0x0",
                            "ackhold": "0x0",
                            "sendwnd": "0x0",
                            "keepalive": "0x0",
                            "giveup": "0x0",
                            "pmtuager": "0x0",
                            "deadwait": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                        },
                    },
                },
                "10.36.3.3": {
                    "remote_as": 100,
                    "link": "internal",
                    "shutdown": False,
                    "address_family": {
                        "vpnv4 unicast": {
                            "session_state": "Established",
                            "up_time": "01:10:41",
                            "last_read": "00:00:04",
                            "last_write": "00:00:43",
                            "current_time": "0x530638",
                        }
                    },
                    "bgp_version": 4,
                    "router_id": "10.36.3.3",
                    "session_state": "Established",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "route_refresh": "advertised and received(new)",
                        "four_octets_asn": "advertised and received",
                        "vpnv4_unicast": "advertised and received",
                        "vpnv6_unicast": "advertised and received",
                        "graceful_restart": "received",
                        "remote_restart_timer": 120,
                        "graceful_restart_af_advertised_by_peer": [
                            "vpnv4 unicast",
                            "vpnv6 unicast",
                        ],
                        "enhanced_refresh": "advertised",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "sent": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 11,
                                "keepalives": 75,
                                "route_refresh": 0,
                                "total": 87,
                            },
                            "received": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 6,
                                "keepalives": 74,
                                "route_refresh": 0,
                                "total": 81,
                            },
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                        }
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 0,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "10.36.3.3",
                        "connection": {
                            "established": 1,
                            "dropped": 0,
                            "last_reset": "never",
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "disabled",
                        "connection_state": "estab",
                        "io_status": 1,
                        "unread_input_bytes": 0,
                        "ecn_connection": "disabled",
                        "minimum_incoming_ttl": 0,
                        "outgoing_ttl": 255,
                        "transport": {
                            "local_host": "10.64.4.4",
                            "local_port": "56031",
                            "foreign_host": "10.36.3.3",
                            "foreign_port": "179",
                            "mss": 536,
                        },
                        "connection_tableid": 0,
                        "maximum_output_segment_queue_size": 50,
                        "enqueued_packets": {
                            "retransmit_packet": 0,
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                        },
                        "iss": 2116369173,
                        "snduna": 2116372477,
                        "sndnxt": 2116372477,
                        "irs": 4033842748,
                        "rcvnxt": 4033845123,
                        "sndwnd": 16616,
                        "snd_scale": 0,
                        "maxrcvwnd": 16384,
                        "rcvwnd": 16327,
                        "rcv_scale": 0,
                        "delrcvwnd": 57,
                        "srtt": 1000,
                        "rtto": 1003,
                        "rtv": 3,
                        "krtt": 0,
                        "min_rtt": 3,
                        "max_rtt": 1000,
                        "ack_hold": 200,
                        "uptime": 4243393,
                        "sent_idletime": 5375,
                        "receive_idletime": 5575,
                        "status_flags": "active open",
                        "option_flags": "nagle, path mtu capable",
                        "ip_precedence_value": 6,
                        "datagram": {
                            "datagram_received": {
                                "value": 165,
                                "out_of_order": 0,
                                "with_data": 80,
                                "total_data": 2374,
                            },
                            "datagram_sent": {
                                "value": 167,
                                "retransmit": 0,
                                "fastretransmit": 0,
                                "partialack": 0,
                                "second_congestion": 0,
                                "with_data": 87,
                                "total_data": 3303,
                            },
                        },
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "fast_lock_acquisition_failures": 0,
                        "lock_slow_path": 0,
                        "tcp_semaphore": "0x1286E85C",
                        "tcp_semaphore_status": "FREE",
                    },
                    "bgp_event_timer": {
                        "starts": {
                            "retrans": 86,
                            "timewait": 0,
                            "ackhold": 80,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 1,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "wakeups": {
                            "retrans": 0,
                            "timewait": 0,
                            "ackhold": 73,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 1,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "next": {
                            "retrans": "0x0",
                            "timewait": "0x0",
                            "ackhold": "0x0",
                            "sendwnd": "0x0",
                            "keepalive": "0x0",
                            "giveup": "0x0",
                            "pmtuager": "0x0",
                            "deadwait": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                        },
                    },
                },
                "10.64.4.4": {
                    "remote_as": 100,
                    "link": "internal",
                    "shutdown": False,
                    "address_family": {
                        "vpnv6 unicast": {
                            "session_state": "Established",
                            "up_time": "01:10:38",
                            "last_read": "00:00:07",
                            "last_write": "00:00:12",
                            "current_time": "0x530FF5",
                        }
                    },
                    "description": "router2222222",
                    "bgp_version": 4,
                    "router_id": "10.64.4.4",
                    "session_state": "Established",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "route_refresh": "advertised and received(new)",
                        "four_octets_asn": "advertised and received",
                        "vpnv4_unicast": "advertised and received",
                        "vpnv6_unicast": "advertised and received",
                        "graceful_restart": "received",
                        "remote_restart_timer": 120,
                        "graceful_restart_af_advertised_by_peer": [
                            "vpnv4 unicast",
                            "vpnv6 unicast",
                        ],
                        "enhanced_refresh": "advertised",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "sent": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 11,
                                "keepalives": 75,
                                "route_refresh": 0,
                                "total": 87,
                            },
                            "received": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 6,
                                "keepalives": 74,
                                "route_refresh": 0,
                                "total": 81,
                            },
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                        }
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 0,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "10.16.2.2",
                        "connection": {
                            "established": 1,
                            "dropped": 0,
                            "last_reset": "never",
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "disabled",
                        "connection_state": "estab",
                        "io_status": 1,
                        "unread_input_bytes": 0,
                        "ecn_connection": "disabled",
                        "minimum_incoming_ttl": 0,
                        "outgoing_ttl": 255,
                        "transport": {
                            "local_host": "10.64.4.4",
                            "local_port": "35281",
                            "foreign_host": "10.16.2.2",
                            "foreign_port": "179",
                            "mss": 536,
                        },
                        "connection_tableid": 0,
                        "maximum_output_segment_queue_size": 50,
                        "enqueued_packets": {
                            "retransmit_packet": 0,
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                        },
                        "iss": 55023811,
                        "snduna": 55027115,
                        "sndnxt": 55027115,
                        "irs": 109992783,
                        "rcvnxt": 109995158,
                        "sndwnd": 16616,
                        "snd_scale": 0,
                        "maxrcvwnd": 16384,
                        "rcvwnd": 16327,
                        "rcv_scale": 0,
                        "delrcvwnd": 57,
                        "srtt": 1000,
                        "rtto": 1003,
                        "rtv": 3,
                        "krtt": 0,
                        "min_rtt": 4,
                        "max_rtt": 1000,
                        "ack_hold": 200,
                        "uptime": 4239741,
                        "sent_idletime": 7832,
                        "receive_idletime": 8032,
                        "status_flags": "active open",
                        "option_flags": "nagle, path mtu capable",
                        "ip_precedence_value": 6,
                        "datagram": {
                            "datagram_received": {
                                "value": 164,
                                "out_of_order": 0,
                                "with_data": 80,
                                "total_data": 2374,
                            },
                            "datagram_sent": {
                                "value": 166,
                                "retransmit": 0,
                                "fastretransmit": 0,
                                "partialack": 0,
                                "second_congestion": 0,
                                "with_data": 87,
                                "total_data": 3303,
                            },
                        },
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "fast_lock_acquisition_failures": 0,
                        "lock_slow_path": 0,
                        "tcp_semaphore": "0x1286E7EC",
                        "tcp_semaphore_status": "FREE",
                    },
                    "bgp_event_timer": {
                        "starts": {
                            "retrans": 86,
                            "timewait": 0,
                            "ackhold": 80,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 1,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "wakeups": {
                            "retrans": 0,
                            "timewait": 0,
                            "ackhold": 72,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 1,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "next": {
                            "retrans": "0x0",
                            "timewait": "0x0",
                            "ackhold": "0x0",
                            "sendwnd": "0x0",
                            "keepalive": "0x0",
                            "giveup": "0x0",
                            "pmtuager": "0x0",
                            "deadwait": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                        },
                    },
                },
                "10.100.5.5": {
                    "remote_as": 100,
                    "link": "internal",
                    "shutdown": False,
                    "address_family": {
                        "vpnv6 unicast": {
                            "session_state": "Established",
                            "up_time": "01:10:44",
                            "last_read": "00:00:08",
                            "last_write": "00:00:47",
                            "current_time": "0x5313D8",
                        }
                    },
                    "bgp_version": 4,
                    "router_id": "10.100.5.5",
                    "session_state": "Established",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "route_refresh": "advertised and received(new)",
                        "four_octets_asn": "advertised and received",
                        "vpnv4_unicast": "advertised and received",
                        "vpnv6_unicast": "advertised and received",
                        "graceful_restart": "received",
                        "remote_restart_timer": 120,
                        "graceful_restart_af_advertised_by_peer": [
                            "vpnv4 unicast",
                            "vpnv6 unicast",
                        ],
                        "enhanced_refresh": "advertised",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "sent": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 11,
                                "keepalives": 75,
                                "route_refresh": 0,
                                "total": 87,
                            },
                            "received": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 6,
                                "keepalives": 74,
                                "route_refresh": 0,
                                "total": 81,
                            },
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                        }
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 0,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "10.36.3.3",
                        "connection": {
                            "established": 1,
                            "dropped": 0,
                            "last_reset": "never",
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "disabled",
                        "connection_state": "estab",
                        "io_status": 1,
                        "unread_input_bytes": 0,
                        "ecn_connection": "disabled",
                        "minimum_incoming_ttl": 0,
                        "outgoing_ttl": 255,
                        "transport": {
                            "local_host": "10.64.4.4",
                            "local_port": "56031",
                            "foreign_host": "10.36.3.3",
                            "foreign_port": "179",
                            "mss": 536,
                        },
                        "connection_tableid": 0,
                        "maximum_output_segment_queue_size": 50,
                        "enqueued_packets": {
                            "retransmit_packet": 0,
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                        },
                        "iss": 2116369173,
                        "snduna": 2116372477,
                        "sndnxt": 2116372477,
                        "irs": 4033842748,
                        "rcvnxt": 4033845123,
                        "sndwnd": 16616,
                        "snd_scale": 0,
                        "maxrcvwnd": 16384,
                        "rcvwnd": 16327,
                        "rcv_scale": 0,
                        "delrcvwnd": 57,
                        "srtt": 1000,
                        "rtto": 1003,
                        "rtv": 3,
                        "krtt": 0,
                        "min_rtt": 3,
                        "max_rtt": 1000,
                        "ack_hold": 200,
                        "uptime": 4246385,
                        "sent_idletime": 8367,
                        "receive_idletime": 8567,
                        "status_flags": "active open",
                        "option_flags": "nagle, path mtu capable",
                        "ip_precedence_value": 6,
                        "datagram": {
                            "datagram_received": {
                                "value": 165,
                                "out_of_order": 0,
                                "with_data": 80,
                                "total_data": 2374,
                            },
                            "datagram_sent": {
                                "value": 167,
                                "retransmit": 0,
                                "fastretransmit": 0,
                                "partialack": 0,
                                "second_congestion": 0,
                                "with_data": 87,
                                "total_data": 3303,
                            },
                        },
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "fast_lock_acquisition_failures": 0,
                        "lock_slow_path": 0,
                        "tcp_semaphore": "0x1286E85C",
                        "tcp_semaphore_status": "FREE",
                    },
                    "bgp_event_timer": {
                        "starts": {
                            "retrans": 86,
                            "timewait": 0,
                            "ackhold": 80,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 1,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "wakeups": {
                            "retrans": 0,
                            "timewait": 0,
                            "ackhold": 73,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 1,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "next": {
                            "retrans": "0x0",
                            "timewait": "0x0",
                            "ackhold": "0x0",
                            "sendwnd": "0x0",
                            "keepalive": "0x0",
                            "giveup": "0x0",
                            "pmtuager": "0x0",
                            "deadwait": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                        },
                    },
                },
            }
        },
        "VRF1": {
            "neighbor": {
                "10.4.6.6": {
                    "remote_as": 300,
                    "link": "external",
                    "shutdown": True,
                    "address_family": {
                        "vpnv4 unicast": {
                            "session_state": "Established",
                            "up_time": "01:01:59",
                            "last_read": "00:00:33",
                            "last_write": "00:00:30",
                            "current_time": "0x530A19",
                        }
                    },
                    "bgp_version": 4,
                    "router_id": "10.4.6.6",
                    "session_state": "Established",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "route_refresh": "advertised",
                        "four_octets_asn": "advertised",
                        "ipv4_unicast": "advertised and received",
                        "enhanced_refresh": "advertised",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "sent": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 3,
                                "keepalives": 69,
                                "route_refresh": 0,
                                "total": 73,
                            },
                            "received": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 1,
                                "keepalives": 64,
                                "route_refresh": 0,
                                "total": 66,
                            },
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                        }
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 0,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "10.4.6.6",
                        "connection": {
                            "established": 2,
                            "dropped": 1,
                            "last_reset": "01:02:11",
                            "reset_reason": "Peer closed the session of session 1",
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "disabled",
                        "connection_state": "estab",
                        "io_status": 1,
                        "unread_input_bytes": 0,
                        "ecn_connection": "disabled",
                        "minimum_incoming_ttl": 0,
                        "outgoing_ttl": 1,
                        "transport": {
                            "local_host": "10.4.6.4",
                            "local_port": "179",
                            "foreign_host": "10.4.6.6",
                            "foreign_port": "11010",
                            "mss": 1460,
                        },
                        "connection_tableid": 1,
                        "maximum_output_segment_queue_size": 50,
                        "enqueued_packets": {
                            "retransmit_packet": 0,
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                        },
                        "iss": 271842,
                        "snduna": 273380,
                        "sndnxt": 273380,
                        "irs": 930048172,
                        "rcvnxt": 930049503,
                        "sndwnd": 32000,
                        "snd_scale": 0,
                        "maxrcvwnd": 16384,
                        "rcvwnd": 15054,
                        "rcv_scale": 0,
                        "delrcvwnd": 1330,
                        "srtt": 1000,
                        "rtto": 1003,
                        "rtv": 3,
                        "krtt": 0,
                        "min_rtt": 1,
                        "max_rtt": 1000,
                        "ack_hold": 200,
                        "uptime": 3720132,
                        "sent_idletime": 31107,
                        "receive_idletime": 30999,
                        "status_flags": "passive open, gen tcbs",
                        "option_flags": "VRF id set, nagle, path mtu capable",
                        "ip_precedence_value": 6,
                        "datagram": {
                            "datagram_received": {
                                "value": 137,
                                "out_of_order": 0,
                                "with_data": 66,
                                "total_data": 1330,
                            },
                            "datagram_sent": {
                                "value": 138,
                                "retransmit": 0,
                                "fastretransmit": 0,
                                "partialack": 0,
                                "second_congestion": 0,
                                "with_data": 72,
                                "total_data": 1537,
                            },
                        },
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "fast_lock_acquisition_failures": 0,
                        "lock_slow_path": 0,
                        "tcp_semaphore": "0x1286E62C",
                        "tcp_semaphore_status": "FREE",
                    },
                    "bgp_event_timer": {
                        "starts": {
                            "retrans": 71,
                            "timewait": 0,
                            "ackhold": 66,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "wakeups": {
                            "retrans": 0,
                            "timewait": 0,
                            "ackhold": 64,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "next": {
                            "retrans": "0x0",
                            "timewait": "0x0",
                            "ackhold": "0x0",
                            "sendwnd": "0x0",
                            "keepalive": "0x0",
                            "giveup": "0x0",
                            "pmtuager": "0x0",
                            "deadwait": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                        },
                    },
                },
                "2001:DB8:4:6::6": {
                    "remote_as": 300,
                    "link": "external",
                    "shutdown": False,
                    "address_family": {
                        "vpnv6 unicast": {
                            "session_state": "Established",
                            "up_time": "01:01:58",
                            "last_read": "00:00:32",
                            "last_write": "00:00:06",
                            "current_time": "0x5315CE",
                        }
                    },
                    "bgp_version": 4,
                    "router_id": "10.4.6.6",
                    "session_state": "Established",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "route_refresh": "advertised",
                        "four_octets_asn": "advertised",
                        "ipv6_unicast": "advertised and received",
                        "enhanced_refresh": "advertised",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "sent": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 3,
                                "keepalives": 70,
                                "route_refresh": 0,
                                "total": 74,
                            },
                            "received": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 1,
                                "keepalives": 64,
                                "route_refresh": 0,
                                "total": 66,
                            },
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                        }
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 0,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "2001:DB8:4:6::6",
                        "connection": {
                            "established": 2,
                            "dropped": 1,
                            "last_reset": "01:05:12",
                            "reset_reason": "Active open failed",
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "disabled",
                        "connection_state": "estab",
                        "io_status": 1,
                        "unread_input_bytes": 0,
                        "ecn_connection": "disabled",
                        "minimum_incoming_ttl": 0,
                        "outgoing_ttl": 1,
                        "transport": {
                            "local_host": "2001:DB8:4:6::4",
                            "local_port": "179",
                            "foreign_host": "2001:DB8:4:6::6",
                            "foreign_port": "11003",
                            "mss": 1440,
                        },
                        "connection_tableid": 503316481,
                        "maximum_output_segment_queue_size": 50,
                        "enqueued_packets": {
                            "retransmit_packet": 0,
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                        },
                        "iss": 164676617,
                        "snduna": 164678296,
                        "sndnxt": 164678296,
                        "irs": 1797203329,
                        "rcvnxt": 1797204710,
                        "sndwnd": 32000,
                        "snd_scale": 0,
                        "maxrcvwnd": 16384,
                        "rcvwnd": 15004,
                        "rcv_scale": 0,
                        "delrcvwnd": 1380,
                        "srtt": 1000,
                        "rtto": 1003,
                        "rtv": 3,
                        "krtt": 0,
                        "min_rtt": 1,
                        "max_rtt": 1000,
                        "ack_hold": 200,
                        "uptime": 3718683,
                        "sent_idletime": 6954,
                        "receive_idletime": 6849,
                        "status_flags": "passive open, gen tcbs",
                        "option_flags": "VRF id set, nagle, path mtu capable",
                        "ip_precedence_value": 6,
                        "datagram": {
                            "datagram_received": {
                                "value": 138,
                                "out_of_order": 0,
                                "with_data": 66,
                                "total_data": 1380,
                            },
                            "datagram_sent": {
                                "value": 139,
                                "retransmit": 0,
                                "fastretransmit": 0,
                                "partialack": 0,
                                "second_congestion": 0,
                                "with_data": 139,
                                "total_data": 7246,
                            },
                        },
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "fast_lock_acquisition_failures": 0,
                        "lock_slow_path": 0,
                        "tcp_semaphore": "0x1286E9AC",
                        "tcp_semaphore_status": "FREE",
                    },
                    "bgp_event_timer": {
                        "starts": {
                            "retrans": 72,
                            "timewait": 0,
                            "ackhold": 66,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "wakeups": {
                            "retrans": 0,
                            "timewait": 0,
                            "ackhold": 64,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "next": {
                            "retrans": "0x0",
                            "timewait": "0x0",
                            "ackhold": "0x0",
                            "sendwnd": "0x0",
                            "keepalive": "0x0",
                            "giveup": "0x0",
                            "pmtuager": "0x0",
                            "deadwait": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                        },
                    },
                },
            }
        },
        "VRF2": {
            "neighbor": {
                "10.66.6.6": {
                    "remote_as": 400,
                    "link": "external",
                    "shutdown": False,
                    "address_family": {
                        "vpnv4 unicast": {
                            "session_state": "Established",
                            "up_time": "01:01:51",
                            "last_read": "00:00:24",
                            "last_write": "00:00:21",
                            "current_time": "0x530C0D",
                        },
                        "vpnv6 unicast": {},
                    },
                    "bgp_version": 4,
                    "router_id": "10.66.6.6",
                    "session_state": "Established",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "route_refresh": "advertised",
                        "four_octets_asn": "advertised",
                        "ipv4_unicast": "advertised and received",
                        "enhanced_refresh": "advertised",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "sent": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 1,
                                "keepalives": 69,
                                "route_refresh": 0,
                                "total": 71,
                            },
                            "received": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 1,
                                "keepalives": 64,
                                "route_refresh": 0,
                                "total": 66,
                            },
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                        }
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 0,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "10.66.6.6",
                        "connection": {
                            "established": 2,
                            "dropped": 1,
                            "last_reset": "01:05:09",
                            "reset_reason": "Active open failed",
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "disabled",
                        "connection_state": "estab",
                        "io_status": 1,
                        "unread_input_bytes": 0,
                        "ecn_connection": "disabled",
                        "minimum_incoming_ttl": 0,
                        "outgoing_ttl": 1,
                        "transport": {
                            "local_host": "10.66.6.4",
                            "local_port": "179",
                            "foreign_host": "10.66.6.6",
                            "foreign_port": "11003",
                            "mss": 1460,
                        },
                        "connection_tableid": 2,
                        "maximum_output_segment_queue_size": 50,
                        "enqueued_packets": {
                            "retransmit_packet": 0,
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                        },
                        "iss": 2048397580,
                        "snduna": 2048398972,
                        "sndnxt": 2048398972,
                        "irs": 213294715,
                        "rcvnxt": 213296046,
                        "sndwnd": 32000,
                        "snd_scale": 0,
                        "maxrcvwnd": 16384,
                        "rcvwnd": 15054,
                        "rcv_scale": 0,
                        "delrcvwnd": 1330,
                        "srtt": 1000,
                        "rtto": 1003,
                        "rtv": 3,
                        "krtt": 0,
                        "min_rtt": 2,
                        "max_rtt": 1000,
                        "ack_hold": 200,
                        "uptime": 3712326,
                        "sent_idletime": 21866,
                        "receive_idletime": 21765,
                        "status_flags": "passive open, gen tcbs",
                        "option_flags": "VRF id set, nagle, path mtu capable",
                        "ip_precedence_value": 6,
                        "datagram": {
                            "datagram_received": {
                                "value": 135,
                                "out_of_order": 0,
                                "with_data": 66,
                                "total_data": 1330,
                            },
                            "datagram_sent": {
                                "value": 137,
                                "retransmit": 0,
                                "fastretransmit": 0,
                                "partialack": 0,
                                "second_congestion": 0,
                                "with_data": 71,
                                "total_data": 1391,
                            },
                        },
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "fast_lock_acquisition_failures": 0,
                        "lock_slow_path": 0,
                        "tcp_semaphore": "0x1286E8CC",
                        "tcp_semaphore_status": "FREE",
                    },
                    "bgp_event_timer": {
                        "starts": {
                            "retrans": 70,
                            "timewait": 0,
                            "ackhold": 66,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "wakeups": {
                            "retrans": 0,
                            "timewait": 0,
                            "ackhold": 64,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "next": {
                            "retrans": "0x0",
                            "timewait": "0x0",
                            "ackhold": "0x0",
                            "sendwnd": "0x0",
                            "keepalive": "0x0",
                            "giveup": "0x0",
                            "pmtuager": "0x0",
                            "deadwait": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                        },
                    },
                },
                "2001:DB8:20:4:6::6": {
                    "remote_as": 400,
                    "link": "external",
                    "shutdown": False,
                    "address_family": {
                        "vpnv6 unicast": {
                            "session_state": "Idle",
                            "last_read": "00:00:22",
                            "last_write": "00:00:01",
                            "current_time": "0x5319B5",
                        },
                        "ipv4 multicast": {},
                        "l2vpn evpn": {},
                        "vpnv4 multicast": {},
                        "mvpnv4 unicast": {},
                        "mvpnv6 unicast": {},
                        "vpnv6 multicast": {},
                    },
                    "bgp_version": 4,
                    "router_id": "10.66.6.6",
                    "session_state": "Idle",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "route_refresh": "advertised",
                        "four_octets_asn": "advertised",
                        "ipv6_unicast": "advertised and received",
                        "enhanced_refresh": "advertised",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "sent": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 1,
                                "keepalives": 70,
                                "route_refresh": 0,
                                "total": 72,
                            },
                            "received": {
                                "opens": 1,
                                "notifications": 0,
                                "updates": 1,
                                "keepalives": 64,
                                "route_refresh": 0,
                                "total": 66,
                            },
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                        }
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 0,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "2001:DB8:20:4:6::6",
                        "connection": {
                            "established": 2,
                            "dropped": 1,
                            "last_reset": "01:05:13",
                            "reset_reason": "Active open failed",
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "disabled",
                        "connection_state": "estab",
                        "io_status": 1,
                        "unread_input_bytes": 0,
                        "ecn_connection": "disabled",
                        "minimum_incoming_ttl": 0,
                        "outgoing_ttl": 1,
                        "transport": {
                            "local_host": "2001:DB8:20:4:6::4",
                            "local_port": "179",
                            "foreign_host": "2001:DB8:20:4:6::6",
                            "foreign_port": "11003",
                            "mss": 1440,
                        },
                        "connection_tableid": 503316482,
                        "maximum_output_segment_queue_size": 50,
                        "enqueued_packets": {
                            "retransmit_packet": 0,
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                        },
                        "iss": 3178074389,
                        "snduna": 3178075806,
                        "sndnxt": 3178075806,
                        "irs": 693674496,
                        "rcvnxt": 693675877,
                        "sndwnd": 32000,
                        "snd_scale": 0,
                        "maxrcvwnd": 16384,
                        "rcvwnd": 15004,
                        "rcv_scale": 0,
                        "delrcvwnd": 1380,
                        "srtt": 1000,
                        "rtto": 1003,
                        "rtv": 3,
                        "krtt": 0,
                        "min_rtt": 3,
                        "max_rtt": 1000,
                        "ack_hold": 200,
                        "uptime": 3711535,
                        "sent_idletime": 2335,
                        "receive_idletime": 2277,
                        "status_flags": "passive open, gen tcbs",
                        "option_flags": "VRF id set, nagle, path mtu capable",
                        "ip_precedence_value": 6,
                        "datagram": {
                            "datagram_received": {
                                "value": 137,
                                "out_of_order": 0,
                                "with_data": 66,
                                "total_data": 1380,
                            },
                            "datagram_sent": {
                                "value": 138,
                                "retransmit": 0,
                                "fastretransmit": 0,
                                "partialack": 0,
                                "second_congestion": 0,
                                "with_data": 138,
                                "total_data": 6944,
                            },
                        },
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "fast_lock_acquisition_failures": 0,
                        "lock_slow_path": 0,
                        "tcp_semaphore": "0x1286E93C",
                        "tcp_semaphore_status": "FREE",
                    },
                    "bgp_event_timer": {
                        "starts": {
                            "retrans": 71,
                            "timewait": 0,
                            "ackhold": 66,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "wakeups": {
                            "retrans": 0,
                            "timewait": 0,
                            "ackhold": 64,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "pmtuager": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "next": {
                            "retrans": "0x0",
                            "timewait": "0x0",
                            "ackhold": "0x0",
                            "sendwnd": "0x0",
                            "keepalive": "0x0",
                            "giveup": "0x0",
                            "pmtuager": "0x0",
                            "deadwait": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                        },
                    },
                },
            }
        },
    },
}
