expected_output={
     'tunnel_id': {
         1: {
             'active_time': 2856,
             'auth_sign': 'psk',
             'auth_verify': 'psk',
             'ce_id': 1406,
             'cisco_trust_security_sgt': 'disabled',
             'dh_grp': 20,
             'dpd_configured_time': 10,
             'dynamic_route_update': 'enabled',
             'encryption': 'aes-gcm',
             'extended_authentication': 'not configured',
             'fragmentation': 'not  configured',
             'fvrf': 'none',
             'hash': 'none',
             'initiator_of_sa': 'yes',
             'ivrf': 'none',
             'keysize': 256,
             'life_time': 86400,
             'local': '4.4.4.1/4500',
             'local_id': '4.4.4.1',
             'local_next_msg_id': 288,
             'local_reg_msg_id': 288,
             'local_req_queued': 288,
             'local_spi': '409A5870608E1C87',
             'local_window': 5,
             'nat_t': 'detected inside',
             'prf': 'sha384',
             'pushed_ip': '66.6.6.4',
             'remote': '10.1.1.1/4500',
             'remote_id': '10.1.1.1',
             'remote_next_msg_id': 285,
             'remote_req_msg_id': 285,
             'remote_req_queued': 285,
             'remote_spi': '20858C98BE7EE1A9',
             'remote_subnets': [],
             'remote_window': 5,
             'retry': 2,
             'session_id': 60,
             'status': 'ready',
             'status_description': 'negotiation done',
         },
     },
 }