expected_output = {
    "table_record_index": {
        "0": {
            "avg": 0,
            "connector": "RJ45",
            "date": 200303,
            "enabled": "true",
            "ethernet_pmd": "10GBase-T SFP+",
            "fault_condition": "false",
            "fault_reason": "PM_PORT_ERRDISABLE_NONE",
            "identifier": "SFP/SFP+",
            "instant": 0,
            "internal_temp": 0,
            "interval": 0,
            "last_event_time": "Wed, 20 Mar 2024 13:31:11 " "+0000",
            "max": 0,
            "min": 0,
            "name": "TenGigabitEthernet1/4/0/17",
            "otn": "OTN_UNDEFINED",
            "present": "true",
            "serial_no": "MTC2407002X",
            "sonet": "SONET_UNKNOWN",
            "vendor": "CISCO-METHODE",
            "vendor_part": "SP7052-C",
            "vendor_rev": "A1",
        },
        "1": {
            "avg": 0,
            "connector": "RJ45",
            "date": 210510,
            "enabled": "true",
            "ethernet_pmd": "10GBase-T SFP+",
            "fault_condition": "false",
            "fault_reason": "PM_PORT_ERRDISABLE_NONE",
            "identifier": "SFP/SFP+",
            "instant": 0,
            "internal_temp": 0,
            "interval": 0,
            "last_event_time": "Wed, 20 Mar 2024 13:31:12 " "+0000",
            "max": 0,
            "min": 0,
            "name": "TenGigabitEthernet1/4/0/18",
            "otn": "OTN_UNDEFINED",
            "present": "true",
            "serial_no": "MTC25190DWE",
            "sonet": "SONET_UNKNOWN",
            "vendor": "CISCO-METHODE",
            "vendor_part": "SP7052-C",
            "vendor_rev": "A1",
        },
        "2": {
            "avg": 0,
            "connector": "Unknown",
            "date": 131031,
            "enabled": "true",
            "ethernet_pmd": "GE T",
            "fault_condition": "false",
            "fault_reason": "PM_PORT_ERRDISABLE_NONE",
            "identifier": "SFP/SFP+",
            "instant": 0,
            "internal_temp": 0,
            "interval": 0,
            "last_event_time": "Thu, 11 Apr 2024 07:29:19 " "+0000",
            "max": 0,
            "min": 0,
            "name": "TenGigabitEthernet1/4/0/26",
            "otn": "OTN_UNDEFINED",
            "present": "true",
            "serial_no": "AGM174425HM",
            "sonet": "SONET_UNKNOWN",
            "vendor": "CISCO-AVAGO",
            "vendor_part": "ABCU-5710RZ-CS4",
            "vendor_rev": "B2",
        },
        "3": {
            "avg": "6.4",
            "connector": "LC connector",
            "date": 150605,
            "enabled": "true",
            "ethernet_pmd": "SFP+ 10GBASE-SR",
            "fault_condition": "false",
            "fault_reason": "PM_PORT_ERRDISABLE_NONE",
            "identifier": "SFP/SFP+",
            "instant": "6.4",
            "internal_temp": 31,
            "interval": 30,
            "last_event_time": "Fri, 12 Apr 2024 06:10:20 " "+0000",
            "max": "6.4",
            "min": "6.4",
            "name": "TenGigabitEthernet1/4/0/33",
            "otn": "OTN_UNDEFINED",
            "present": "true",
            "serial_no": "JUR1923G8AN",
            "sonet": "SONET_UNKNOWN",
            "vendor": "CISCO-JDSU",
            "vendor_part": "PLRXPL-SC-S43-CS",
            "vendor_rev": 1,
        },
    }
}