expected_output = {
    'extended_id_fileds': {
        'address_change': 'Not Required',
        'br_max': '0x00',
        'br_min': '0x00',
        'cc_ext': '0xA5',
        'date_code': 131115,
        'diag_monitoring': 'Implemented',
        'exeternally_calibrated': 'No',
        'internally_calibrated': 'Yes',
        'options': '0x00 0x1A',
        'rx_power_measurement': 'Avg.Power',
    },
    'other_information': {
        'administrative_duplex': 'full',
        'administrative_speed': '10000',
        'chk_for_link_status': '00',
        'flow_control_receive': 'Off',
        'flow_control_send': 'Off',
        'operational_duplex': 'auto',
        'operational_speed': 'auto',
    },
    'sfp_info': {
        'cisco_part_number': 'FTLX8571D3BCL-C2',
        'connector_type': 'LC connector',
        'product_identifier': 'SFP/SFP+',
        'serial_number': 'FNS17462988',
        'vendor_name': 'CISCO-FINISAR',
        'vendor_revision': '0x41 0x20 0x20 0x20',
    },
}