expected_output = {
    "list_of_neighbors": ["172.17.211.2"],
    "vrf": {
        "VRF200": {
            "neighbor": {
                "172.17.211.2": {
                    "address_family": {
                        "vpnv4 unicast": {
                            "advertise_bit": 0,
                            "bgp_table_version": 21,
                            "current_time": "0x194B93DC",
                            "dynamic_slow_peer_recovered": "never",
                            "index": 2,
                            "last_detected_dynamic_slow_peer": "never",
                            "last_received_refresh_end_of_rib": "never",
                            "last_received_refresh_start_of_rib": "never",
                            "last_sent_refresh_end_of_rib": "never",
                            "last_sent_refresh_start_of_rib": "never",
                            "local_policy_denied_prefixes_counters": {
                                "inbound": {
                                    "bestpath_from_this_peer": "n/a",
                                    "total": 0,
                                },
                                "outbound": {"bestpath_from_this_peer": 2, "total": 2},
                            },
                            "max_nlri": 1,
                            "min_nlri": 0,
                            "neighbor_version": "21/0",
                            "output_queue_size": 0,
                            "prefix_activity_counters": {
                                "received": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 0,
                                    "prefixes_current": 1,
                                    "prefixes_total": 1,
                                    "used_as_bestpath": 1,
                                    "used_as_multipath": 0,
                                    "used_as_secondary": 0,
                                },
                                "sent": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 3,
                                    "prefixes_current": 3,
                                    "prefixes_total": 6,
                                    "used_as_bestpath": "n/a",
                                    "used_as_multipath": "n/a",
                                    "used_as_secondary": "n/a",
                                },
                            },
                            "refresh_activity_counters": {
                                "received": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                                "sent": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                            },
                            "refresh_epoch": 1,
                            "slow_peer_detection": False,
                            "slow_peer_split_update_group_dynamic": False,
                            "update_group_member": 2,
                        }
                    },
                    "bgp_event_timer": {
                        "next": {
                            "ackhold": "0x0",
                            "deadwait": "0x0",
                            "giveup": "0x0",
                            "keepalive": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                            "retrans": "0x0",
                            "sendwnd": "0x0",
                            "timewait": "0x0",
                        },
                        "starts": {
                            "ackhold": 7773,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "processq": 0,
                            "retrans": 7787,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                        "wakeups": {
                            "ackhold": 7659,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "processq": 0,
                            "retrans": 1,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "enhanced_refresh": "advertised and received",
                        "four_octets_asn": "advertised and received",
                        "ipv4_unicast": "advertised and received",
                        "route_refresh": "advertised and received(new)",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                            "received": {
                                "keepalives": 7772,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7775,
                                "updates": 2,
                            },
                            "sent": {
                                "keepalives": 7779,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7787,
                                "updates": 7,
                            },
                        }
                    },
                    "bgp_session_transport": {
                        "ack_hold": 200,
                        "address_tracking_status": "enabled",
                        "connection": {
                            "dropped": 0,
                            "established": 1,
                            "last_reset": "never",
                        },
                        "connection_state": "estab",
                        "connection_tableid": 2,
                        "datagram": {
                            "datagram_received": {
                                "out_of_order": 0,
                                "total_data": 147802,
                                "value": 15515,
                                "with_data": 7774,
                            },
                            "datagram_sent": {
                                "fastretransmit": 0,
                                "partialack": 0,
                                "retransmit": 1,
                                "second_congestion": 0,
                                "total_data": 148185,
                                "value": 15549,
                                "with_data": 7785,
                            },
                        },
                        "delrcvwnd": 38,
                        "ecn_connection": "disabled",
                        "enqueued_packets": {
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                            "retransmit_packet": 0,
                        },
                        "fast_lock_acquisition_failures": 0,
                        "graceful_restart": "disabled",
                        "io_status": 1,
                        "ip_precedence_value": 6,
                        "irs": 950953285,
                        "iss": 3848368441,
                        "krtt": 0,
                        "lock_slow_path": 0,
                        "max_rtt": 1000,
                        "maximum_output_segment_queue_size": 50,
                        "maxrcvwnd": 16384,
                        "min_rtt": 1,
                        "min_time_between_advertisement_runs": 0,
                        "minimum_incoming_ttl": 0,
                        "option_flags": "VRF id set, nagle, path mtu capable",
                        "outgoing_ttl": 1,
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "rcv_scale": 0,
                        "rcvnxt": 951101088,
                        "rcvwnd": 16346,
                        "receive_idletime": 39810,
                        "rib_route_ip": "172.17.211.2",
                        "rtto": 1003,
                        "rtv": 3,
                        "sent_idletime": 39610,
                        "snd_scale": 0,
                        "sndnxt": 3848516627,
                        "snduna": 3848516627,
                        "sndwnd": 15966,
                        "srtt": 1000,
                        "sso": False,
                        "status_flags": "active open",
                        "tcp_path_mtu_discovery": "enabled",
                        "tcp_semaphore": "0x7F59978AAE80",
                        "tcp_semaphore_status": "FREE",
                        "transport": {
                            "foreign_host": "172.17.211.2",
                            "foreign_port": "179",
                            "local_host": "172.17.211.1",
                            "local_port": "48585",
                            "mss": 1460,
                        },
                        "unread_input_bytes": 0,
                        "uptime": 424227580,
                    },
                    "bgp_version": 4,
                    "link": "external",
                    "remote_as": 65001,
                    "router_id": "172.16.1.156",
                    "session_state": "Established",
                    "shutdown": False,
                }
            }
        }
    },
}
