expected_output = {
    'fabric_ap_count': 9,
    'ap_name': {'AP-E2-7910': {'slots': '2',
                               'ap_model': 'AIR-AP3802I-E-K9',
                               'ethernet_mac': '0042.68a0.fb0a',
                               'radio_mac': '0062.ecf3.7910',
                               'location': 'default location',
                               'country': 'CH',
                               'ip_address': '10.244.0.73',
                               'state': 'Registered'},
                'AP-G3-E2C0': {'slots': '2',
                               'ap_model': 'AIR-AP1562I-E-K9',
                               'ethernet_mac': '0062.ec4a.67d4',
                               'radio_mac': '00d7.8ffe.e2c0',
                               'location': 'Global/Ecublens/Buil',
                               'country': 'CH',
                               'ip_address': '10.244.0.69',
                               'state': 'Registered'},
                'AP-E1-C8A0': {'slots': '3',
                               'ap_model': 'C9124AXE-B',
                               'ethernet_mac': '488b.0a76.1a64',
                               'radio_mac': '488b.0a78.c8a0',
                               'location': 'Global/Ecublens/Buil',
                               'country': 'US',
                               'ip_address': '2001:10b1::9',
                               'state': 'Registered'},
                'AP-E1-CBA0': {'slots': '3',
                               'ap_model': 'C9124AXE-B',
                               'ethernet_mac': '488b.0a76.1ac4',
                               'radio_mac': '488b.0a78.cba0',
                               'location': 'default location',
                               'country': 'FR',
                               'ip_address': '10.244.0.39',
                               'state': 'Downloading'},
                'AP-F5-CC00': {'slots': '2',
                               'ap_model': 'C9124AXI-B',
                               'ethernet_mac': '3c57.31c5.8fd0',
                               'radio_mac': '4ca6.4d22.cc00',
                               'location': 'default location',
                               'country': 'US',
                               'ip_address': '2001:10b1::8',
                               'state': 'Registered'},
                'AP-E6-7000': {'slots': '3',
                               'ap_model': 'C9124AXE-A',
                               'ethernet_mac': '3c57.31c5.a450',
                               'radio_mac': '4ca6.4d23.7000',
                               'location': 'Global/Ecublens/Buil',
                               'country': 'US',
                               'ip_address': '10.244.0.22',
                               'state': 'Registered'},
                'AP-D5-FC00': {'slots': '2',
                               'ap_model': 'AIR-AP1852I-B-K9',
                               'ethernet_mac': '80e8.6fd6.6560',
                               'radio_mac': '80e8.6fd7.fc00',
                               'location': 'default location',
                               'country': 'MX',
                               'ip_address': '10.244.0.53',
                               'state': 'Registered'}
                }
}
