expected_output= {
    "entries":[
        {
            "side":"LINE",
            "mdio_port":3,
            "lane_offset":3,
            "inner_eye_height_hex":"0x170115",
            "inner_eye_height":"0x17",
            "outer_eye_height_hex":"0x28252317",
            "outer_eye_height":"0x28",
            "eyerat":0.575,
            "status":0
        },
        {
            "side":"HOST",
            "mdio_port":3,
            "lane_offset":3,
            "inner_eye_height_hex":"0x1a0115",
            "inner_eye_height":"0x1a",
            "outer_eye_height_hex":"0x2124211a",
            "outer_eye_height":"0x21",
            "eyerat":0.787879,
            "status":0
        },
        {
            "side":"HOST",
            "mdio_port":2,
            "lane_offset":3,
            "inner_eye_height_hex":"0x180115",
            "inner_eye_height":"0x18",
            "outer_eye_height_hex":"0x21222019",
            "outer_eye_height":"0x21",
            "eyerat":0.727273,
            "status":0
        }
    ],
    "port":32,
    "phy_port":1,
    "ctrl":0
}