expected_output = {
    "configlet_file": "flash:configletfile1",
    "terminal": "TTY0",
    "user": "campus",
    "count": "99",
    "configlet_data":{
        "1": "vlan 60",
        "2": "vlan 40",
        "3": "name OFFICE:FACILITIES",
        "4": "vlan 15",
        "5": "name IMAGING-WIRED",
        "6": "vlan 400",
        "7": "name OFFICE:GUEST-DATA-1",
        "8": "vlan 16",
        "9": "name IMAGING-WIRELESS",
        "10": "vlan 301",
        "11": "name OFFICE:EMPLOYEE-DEV-1",
        "12": "vlan 201",
        "13": "name OFFICE:EMPLOYEE-VOIP-1",
        "14": "vlan 39",
        "15": "name OFFICE:APS",
        "16": "vlan 36",
        "17": "name QUARANTINE-WIRED",
        "18": "vlan 666",
        "19": "name OFFICE:QUARANTINE",
        "20": "vlan 19",
        "21": "name UNMANAGED-WIRED",
        "22": "vlan 613",
        "23": "name OFFICE:IT-MANAGEMENT",
        "24": "vlan 500",
        "25": "name OFFICE:LAB-1",
        "26": "vlan 37",
        "27": "name QUARANTINE-WIRELESS",
        "28": "vlan 600",
        "29": "name OFFICE:SECURITY",
        "30": "vlan 17",
        "31": "name DEVICES-WIRED",
        "32": "vlan 650",
        "33": "name OFFICE:IT-SERVICES",
        "34": "vlan 38",
        "35": "name OFFICE:CBRS",
        "36": "vlan 3",
        "37": "name INFRA:MANAGEMENT-NETWORK",
        "38": "vlan 20",
        "39": "name UNMANAGED-WIRELESS",
        "40": "vlan 18",
        "41": "name DEVICES-WIRELESS",
        "42": "vlan 101",
        "43": "name OFFICE:EMPLOYEE-DATA-1",
        "44": "no lldp tlv-select management-address",
        "45": "no lldp tlv-select system-capabilities",
        "46": "no lldp tlv-select system-description",
        "47": "lldp run",
        "48": "interface GigabitEthernet1/0/1",
        "49": "switchport mode access",
        "50": "loopdetect",
        "51": "switchport mode access",
        "52": "switchport nonegotiate",
        "53": "logging event trunk-status",
        "54": "no cdp tlv app",
        "55": "no cdp tlv location",
        "56": "spanning-tree portfast",
        "57": "ip arp inspection limit rate 50",
        "58": "ip dhcp snooping limit rate 100",
        "59": "storm-control broadcast level 20.00",
        "60": "spanning-tree bpduguard enable",
        "61": "interface GigabitEthernet1/0/3",
        "62": "switchport mode access",
        "63": "loopdetect",
        "64": "switchport mode access",
        "65": "switchport nonegotiate",
        "66": "logging event trunk-status",
        "67": "no cdp tlv app",
        "68": "no cdp tlv location",
        "69": "spanning-tree portfast",
        "70": "ip arp inspection limit rate 50",
        "71": "ip dhcp snooping limit rate 100",
        "72": "storm-control broadcast level 20.00",
        "73": "spanning-tree bpduguard enable",
        "74": "interface GigabitEthernet1/0/11",
        "75": "switchport mode access",
        "76": "loopdetect",
        "77": "switchport mode access",
        "78": "switchport nonegotiate",
        "79": "logging event trunk-status",
        "80": "no cdp tlv app",
        "81": "no cdp tlv location",
        "82": "spanning-tree portfast",
        "83": "ip arp inspection limit rate 50",
        "84": "ip dhcp snooping limit rate 100",
        "85": "storm-control broadcast level 20.00",
        "86": "spanning-tree bpduguard enable",
        "87": "interface GigabitEthernet1/0/12",
        "88": "switchport mode access",
        "89": "loopdetect",
        "90": "switchport mode access",
        "91": "switchport nonegotiate",
        "92": "logging event trunk-status",
        "93": "no cdp tlv app",
        "94": "no cdp tlv location",
        "95": "spanning-tree portfast",
        "96": "ip arp inspection limit rate 50",
        "97": "ip dhcp snooping limit rate 100",
        "98": "storm-control broadcast level 20.00",
        "99": "spanning-tree bpduguard enable"
    }
}
