expected_output={
     'tunnel_id': {
         1184: {
             'active_time': 23,
             'auth_sign': 'psk',
             'auth_verify': 'psk',
             'ce_id': 76998,
             'cisco_trust_security_sgt': 'disabled',
             'dh_grp': 16,
             'dpd_configured_time': 0,
             'dynamic_route_update': 'enabled',
             'encryption': 'aes-cbc',
             'extended_authentication': 'not configured',
             'fragmentation': 'not  configured',
             'fvrf': 'none',
             'hash': 'sha512',
             'initiator_of_sa': 'no',
             'ivrf': 'none',
             'keysize': 192,
             'life_time': 86400,
             'local': '101.0.10.2/500',
             'local_id': '101.0.10.2',
             'local_next_msg_id': 0,
             'local_reg_msg_id': 0,
             'local_req_queued': 0,
             'local_spi': '39125EA1EB1B358D',
             'local_window': 5,
             'nat_t': 'not detected',
             'prf': 'sha512',
             'remote': '100.201.33.252/500',
             'remote_id': '100.201.33.252',
             'remote_next_msg_id': 4,
             'remote_req_msg_id': 4,
             'remote_req_queued': 4,
             'remote_spi': '29C6416947D54ECA',
             'remote_subnets': [],
             'remote_window': 5,
             'retry': 0,
             'session_id': 1790326,
             'status': 'ready',
             'status_description': 'negotiation done',
         },
     },
 }