expected_output={
  "controller_vdsl": "UP",
  "daemon_status": "UP",
  "xtu_r_ds": {
    "chip_vendor": {
      "chip_vendor_id": "'RETK'",
      "chip_vendor_specific": "0x0000",
      "chip_vendor_country": "0xB500"
    },
    "modem_vendor": {
      "modem_vendor_id": "'RETK'",
      "modem_vendor_specific": "0x0000",
      "modem_vendor_country": "0xB500",
      "modem_phy_version": "G137L310"
    },
    "serial_number_far": "08-04-25",
    "trellis": "OFF",
    "sra": "enabled",
    "sra_count": 0,
    "bit_swap": "enabled",
    "bit_swap_count": "0",
    "line_attenuation": "7.9 dB",
    "signal_attenuation": "7.9 dB",
    "noise_margin": "7.0 dB",
    "attainable_rate": "0 kbits/s",
    "actual_power": "0.0 dBm",
    "total_fecc": 0,
    "total_es": 0,
    "total_ses": 0,
    "total_loss": 0,
    "total_uas": 361,
    "total_lprs": 0,
    "total_lofs": 0,
    "total_lols": 0,
    "ds_channel1": {
      "speed_(kbps)": "NA",
      "previous_speed": "NA",
      "total_cells": "NA",
      "user_cells": "NA",
      "reed_solomon_ec": "NA",
      "crc_errors": "NA",
      "header_errors": "NA",
      "interleave_(ms)": "NA",
      "actual_inp": "NA"
    },
    "ds_channel0": {
      "speed_(kbps)": "23839",
      "previous_speed": "99999",
      "total_cells": "0",
      "user_cells": "0",
      "reed_solomon_ec": "0",
      "crc_errors": "0",
      "header_errors": "0",
      "interleave_(ms)": "0.00",
      "actual_inp": "0.00"
    }
  },
  "xtu_c_us": {
    "chip_vendor": {
      "chip_vendor_id": "'BDCM'",
      "chip_vendor_specific": "0x0000",
      "chip_vendor_country": "0xB500"
    },
    "modem_vendor": {
      "modem_vendor_id": "'BDCM'",
      "modem_vendor_specific": "0x0000",
      "modem_vendor_country": "0xB500",
      "modem_phy_version": "AVM b_08-04-25 AVM b"
    },
    "serial_number_far": "AVM br u318 MIPS32 EUR",
    "trellis": "ON",
    "sra": "enabled",
    "sra_count": 0,
    "bit_swap": "enabled",
    "bit_swap_count": "0",
    "line_attenuation": "2.0 dB",
    "signal_attenuation": "3.5 dB",
    "noise_margin": "7.3 dB",
    "attainable_rate": "0 kbits/s",
    "actual_power": "0.0 dBm",
    "total_fecc": 0,
    "total_es": 0,
    "total_ses": 0,
    "total_loss": 0,
    "total_uas": 0,
    "total_lprs": 0,
    "total_lofs": 0,
    "total_lols": 0,
    "us_channel1": {
      "speed_(kbps)": "NA",
      "previous_speed": "NA",
      "total_cells": "NA",
      "user_cells": "NA",
      "reed_solomon_ec": "NA",
      "crc_errors": "NA",
      "header_errors": "NA",
      "interleave_(ms)": "NA",
      "actual_inp": "NA"
    },
    "us_channel0": {
      "speed_(kbps)": "2079",
      "previous_speed": "60015",
      "total_cells": "0",
      "user_cells": "0",
      "reed_solomon_ec": "0",
      "crc_errors": "0",
      "header_errors": "0",
      "interleave_(ms)": "0.00",
      "actual_inp": "0.00"
    }
  },
  "serial_number_near": "08-04-25 AVM br u318 MIPS32 EUR",
  "modem_version_far": "G137L310",
  "modem_status": "TC Sync (Showtime!)",
  "dsl_config_mode": "AUTO",
  "trained_mode": "G.992.5 (ADSL2+) Annex J",
  "tc_mode": "ATM",
  "selftest_result": "0x00",
  "delt_configuration": "disabled",
  "delt_state": "not running",
  "failed_full_inits": 0,
  "short_inits": 0,
  "failed_short_inits": 0,
  "modem_fw_version": "Linux(none)3.18.20#6",
  "modem_phy_version": "G137L310 AVM b_08-04-25 AVM b",
  "modem_phy_source": "System",
  "training_log": "Stopped",
  "training_log_filename": "flash:vdsllog.bin"
}
