expected_output =  {
    "fnf_statistics":{
        "num_ipc_errors":{
            "value":0,
            "id":5
        },
        "num_flow_errors":{
            "value":0,
            "id":6
        },
        "num_init_errors":{
            "value":0,
            "id":7
        },
        "num_misc_errors":{
            "value":0,
            "id":8
        },
        "num_config_errors":{
            "value":0,
            "id":9
        },
        "num_too_old_fsts_errors":{
            "value":0,
            "id":10
        },
        "num_too_old_lsts_errors":{
            "value":0,
            "id":11
        },
        "num_high_fs_errors":{
            "value":0,
            "id":12
        },
        "num_fs_ls_fixups":{
            "value":0,
            "id":13
        },
        "num_ts_status_check_errors":{
            "value":0,
            "id":14
        },
        "num_ios_msgs_rcvd":{
            "value":0,
            "id":15
        },
        "num_ios_msgs_sent":{
            "value":0,
            "id":16
        },
        "num_fman_msgs_rcvd":{
            "value":0,
            "id":17
        },
        "num_fman_msgs_sent":{
            "value":0,
            "id":18
        },
        "num_fmask_created":{
            "value":0,
            "id":19
        },
        "num_fmask_removed":{
            "value":0,
            "id":20
        },
        "num_dynamic_entry_created":{
            "value":0,
            "id":21
        },
        "num_vlan_nfl_acl_being_used":{
            "value":0,
            "id":22
        },
        "num_vlan_nfl_acl_freed":{
            "value":0,
            "id":23
        },
        "num_l3_nfl_acl_being_used":{
            "value":0,
            "id":24
        },
        "num_l3_nfl_acl_freed":{
            "value":0,
            "id":25
        },
        "num_port_nfl_acl_being_used":{
            "value":0,
            "id":26
        },
        "num_port_nfl_acl_freed":{
            "value":0,
            "id":27
        },
        "num_wlan_nfl_acl_being_used":{
            "value":0,
            "id":28
        },
        "num_wlan_nfl_acl_freed":{
            "value":0,
            "id":29
        },
        "num_monitors_created":{
            "value":0,
            "id":30
        },
        "num_monitors_removed":{
            "value":0,
            "id":31
        },
        "num_monitors_attached_to_vlan":{
            "value":0,
            "id":32
        },
        "num_monitors_attached_to_port":{
            "value":0,
            "id":33
        },
        "num_monitors_attached_to_l3":{
            "value":0,
            "id":34
        },
        "num_samplers_created":{
            "value":0,
            "id":35
        },
        "num_samplers_removed":{
            "value":0,
            "id":36
        },
        "num_exporter_created":{
            "value":0,
            "id":37
        },
        "num_exporter_removed":{
            "value":0,
            "id":38
        },
        "num_ots_flow_mon_action_ev":{
            "value":0,
            "id":39
        },
        "num_ots_flow_exp_action_ev":{
            "value":0,
            "id":40
        },
        "num_ots_ifc_mon_action_ev":{
            "value":0,
            "id":41
        },
        "num_ots_flow_cache_clear_ev":{
            "value":0,
            "id":42
        },
        "num_ots_fnf_ageing_timer_ev":{
            "value":0,
            "id":43
        },
        "num_ots_fnf_ageing_out_ev":{
            "value":0,
            "id":44
        },
        "num_ots_fnf_ageing_sm_ev":{
            "value":0,
            "id":45
        },
        "num_ots_fnf_offld_tmr_ev":{
            "value":0,
            "id":46
        },
        "num_ots_fnf_comet_ev":{
            "value":0,
            "id":47
        },
        "num_ots_get_flows_ios_ev":{
            "value":0,
            "id":48
        },
        "num_ots_ifm_if_del_ev":{
            "value":0,
            "id":49
        },
        "num_ots_cache_stats_clr_ev":{
            "value":0,
            "id":50
        },
        "num_flows_learnt":{
            "value":0,
            "id":51
        },
        "num_flow_get_dyn_ad_errors":{
            "value":0,
            "id":52
        },
        "num_flows_del_not_valid_errors":{
            "value":0,
            "id":53
        },
        "num_max_fin_rst_flows_in_ofld":{
            "value":0,
            "id":54
        },
        "num_wdavc_records_to_export":{
            "value":0,
            "id":55
        },
        "num_wdavc_records_not_exported":{
            "value":0,
            "id":56
        },
        "num_wdavc_records_no_export_mon":{
            "value":0,
            "id":57
        },
        "num_wdavc_records_export_failures":{
            "value":0,
            "id":58
        },
        "num_wdavc_alloc_gen_rec":{
            "value":0,
            "id":59
        },
        "num_wdavc_free_gen_rec":{
            "value":0,
            "id":60
        },
        "num_wdavc_inc_gen_rec_ref_cnt":{
            "value":0,
            "id":61
        },
        "num_wdavc_dec_gen_rec_ref_cnt":{
            "value":0,
            "id":62
        },
        "num_wdavc_alloc_gen_key":{
            "value":0,
            "id":63
        },
        "num_wdavc_free_gen_key":{
            "value":0,
            "id":64
        },
        "num_wdavc_alloc_gen_collect":{
            "value":0,
            "id":65
        },
        "num_wdavc_free_gen_collect":{
            "value":0,
            "id":66
        },
        "num_wdavc_alloc_rec_key":{
            "value":0,
            "id":67
        },
        "num_wdavc_free_rec_key":{
            "value":0,
            "id":68
        },
        "num_wdavc_inc_rec_key_ref_cnt":{
            "value":0,
            "id":69
        },
        "num_wdavc_dec_rec_key_ref_cnt":{
            "value":0,
            "id":70
        },
        "num_wdavc_alloc_rec_collect":{
            "value":0,
            "id":71
        },
        "num_wdavc_free_rec_collect":{
            "value":0,
            "id":72
        },
        "num_wdavc_inc_rec_collect_ref_cnt":{
            "value":0,
            "id":73
        },
        "num_wdavc_dec_rec_collect_ref_cnt":{
            "value":0,
            "id":74
        },
        "num_wdavc_alloc_gen_rec_failed":{
            "value":0,
            "id":75
        },
        "num_wdavc_alloc_gen_key_failed":{
            "value":0,
            "id":76
        },
        "num_wdavc_alloc_gen_collect_failed":{
            "value":0,
            "id":77
        },
        "num_wdavc_alloc_wdavc_key_failed":{
            "value":0,
            "id":78
        },
        "num_wdavc_alloc_wdavc_collect_failed":{
            "value":0,
            "id":79
        },
        "num_wdavc_cache_alloc_ext_field_dns_domain_name":{
            "value":0,
            "id":80
        },
        "num_wdavc_cache_free_ext_field_dns_domain_name":{
            "value":0,
            "id":81
        },
        "num_wdavc_cache_alloc_ext_field_failed_dns_domain_name":{
            "value":0,
            "id":82
        },
        "num_wdavc_cache_alloc_ext_field_http_host_name":{
            "value":0,
            "id":83
        },
        "num_wdavc_cache_free_ext_field_http_host_name":{
            "value":0,
            "id":84
        },
        "num_wdavc_cache_alloc_ext_field_failed_http_host_name":{
            "value":0,
            "id":85
        },
        "num_wdavc_cache_alloc_ext_field_ssl_common_name":{
            "value":0,
            "id":86
        },
        "num_wdavc_cache_free_ext_field_ssl_common_name":{
            "value":0,
            "id":87
        },
        "num_wdavc_cache_alloc_ext_field_failed_ssl_common_name":{
            "value":0,
            "id":88
        },
        "num_wdavc_var_len_field_alloc":{
            "value":0,
            "id":89
        },
        "num_wdavc_var_len_field_free":{
            "value":0,
            "id":90
        },
        "num_wdavc_var_len_field_alloc_fail":{
            "value":0,
            "id":91
        },
        "num_gen_flows_requests":{
            "value":0,
            "id":92
        },
        "num_gen_flows_ctxt_start":{
            "value":0,
            "id":93
        },
        "num_gen_flows_ctxt_end":{
            "value":0,
            "id":94
        },
        "num_show_flows_send_to_pi":{
            "value":0,
            "id":95
        },
        "num_gen_flows_request_errors":{
            "value":0,
            "id":96
        },
        "num_gen_flows_sm_new":{
            "value":0,
            "id":97
        },
        "num_gen_flows_sm_continue":{
            "value":0,
            "id":98
        },
        "num_gen_flows_sm_stop":{
            "value":0,
            "id":99
        },
        "num_gen_flows_sm_unknown":{
            "value":0,
            "id":100
        },
        "num_wdavc_start_pending_show":{
            "value":0,
            "id":101
        },
        "num_wdavc_handle_pending_show":{
            "value":0,
            "id":102
        },
        "num_wdavc_consumed_pending_show":{
            "value":0,
            "id":103
        },
        "num_wdavc_reuse_context_show":{
            "value":0,
            "id":104
        },
        "num_wdavc_finalize_async_show":{
            "value":0,
            "id":105
        },
        "num_wdavc_show_errors":{
            "value":0,
            "id":106
        },
        "num_wdavc_update_pending_show_cache":{
            "value":0,
            "id":107
        },
        "num_wdavc_update_pending_show_cache_fail":{
            "value":0,
            "id":108
        },
        "num_wdavc_update_pending_show_records":{
            "value":0,
            "id":109
        },
        "num_fin_rst_skip_flow_pend_del":{
            "value":0,
            "id":110
        },
        "num_wdavc_del_pend_set_same_state_warn":{
            "value":0,
            "id":111
        }
    }
}