expected_output = {
    "backbone_fast": False,
    "bpdu_filter": False,
    "bpdu_guard": False,
    "bridge_assurance": True,
    "configured_pathcost": {"method": "short"},
    "etherchannel_misconfig_guard": True,
    "extended_system_id": True,
    "loop_guard": False,
    "mode": {
        "rapid_pvst": {
            "VLAN0001": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN0115": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0116": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0118": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0119": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0121": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0180": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0501": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0502": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0503": {
                "blocking": 0,
                "forwarding": 3,
                "learning": 0,
                "listening": 0,
                "stp_active": 3,
            },
            "VLAN0506": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0508": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0509": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0510": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0511": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0512": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0513": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0514": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0515": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0516": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0517": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0518": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0521": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0522": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0540": {
                "blocking": 0,
                "forwarding": 3,
                "learning": 0,
                "listening": 0,
                "stp_active": 3,
            },
            "VLAN0601": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0602": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0603": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN0604": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0606": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN0701": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0801": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0802": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0803": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0804": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0805": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0806": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN0916": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN1111": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN1112": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN1113": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN1114": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN1115": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN1116": {
                "blocking": 0,
                "forwarding": 2,
                "learning": 0,
                "listening": 0,
                "stp_active": 2,
            },
            "VLAN1125": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN1506": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN1509": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
            "VLAN1601": {
                "blocking": 0,
                "forwarding": 1,
                "learning": 0,
                "listening": 0,
                "stp_active": 1,
            },
        }
    },
    "portfast_default": False,
    "pvst_simulation": True,
    "pvst_simulation_status": "inactive",
    "root_bridge_for": "VLAN0001, VLAN0115-VLAN0116, VLAN0118-VLAN0119, VLAN0121, VLAN0180, VLAN0501-VLAN0503, VLAN0506, VLAN0508-VLAN0518, VLAN0521-VLAN0522, VLAN0540, VLAN0601-VLAN0604, VLAN0606, VLAN0701, VLAN0801-VLAN0806, VLAN1111-VLAN1116, VLAN1506, VLAN1509, VLAN1601",
    "total_statistics": {
        "blockings": 0,
        "forwardings": 62,
        "learnings": 0,
        "listenings": 0,
        "num_of_vlans": 48,
        "stp_actives": 62,
    },
    "uplink_fast": False,
}
