expected_output = {
    "Port-channel10": {
        "port_channel": {
            "port_channel_member": True,
            "active_members": 2,
            "port_channel_member_intfs": [
                "GigabitEthernet0/0/0",
                "GigabitEthernet0/0/1",
            ],
            "num_of_pf_jumbo_supported_members": 2,
        },
        "enabled": True,
        "is_deleted": False,
        "line_protocol": "up",
        "oper_status": "up",
        "type": "GEChannel",
        "mac_address": "006b.f1ff.be9f",
        "phys_address": "006b.f1ff.be9f",
        "delay": 10,
        "mtu": 1500,
        "bandwidth": 2000000,
        "reliability": "255/255",
        "txload": "1/255",
        "rxload": "1/255",
        "encapsulations": {"encapsulation": "dot1q", "first_dot1q": "1"},
        "keepalive": 10,
        "arp_type": "arpa",
        "arp_timeout": "04:00:00",
        "last_input": "00:00:01",
        "last_output": "00:00:00",
        "output_hang": "never",
        "queues": {
            "input_queue_size": 0,
            "input_queue_max": 750,
            "input_queue_drops": 0,
            "input_queue_flushes": 0,
            "total_output_drop": 0,
            "queue_strategy": "fifo",
            "output_queue_size": 0,
            "output_queue_max": 80,
        },
        "counters": {
            "rate": {
                "load_interval": 300,
                "in_rate": 27204000,
                "in_rate_pkts": 6797,
                "out_rate": 0,
                "out_rate_pkts": 0,
            },
            "last_clear": "never",
            "in_pkts": 73017,
            "in_octets": 5016308,
            "in_no_buffer": 0,
            "in_multicast_pkts": 4557345,
            "in_broadcast_pkts": 12871133,
            "in_runts": 0,
            "in_giants": 0,
            "in_throttles": 0,
            "in_errors": 0,
            "in_crc_errors": 0,
            "in_frame": 0,
            "in_overrun": 0,
            "in_ignored": 0,
            "in_watchdog": 0,
            "in_mac_pause_frames": 0,
            "out_pkts": 5887,
            "out_octets": 377641,
            "out_underruns": 0,
            "out_errors": 0,
            "out_interface_resets": 0,
            "out_collision": 0,
            "out_unknown_protocl_drops": 0,
            "out_babble": 0,
            "out_late_collision": 0,
            "out_deferred": 0,
            "out_lost_carrier": 0,
            "out_no_carrier": 0,
            "out_mac_pause_frames": 0,
            "out_buffer_failure": 0,
            "out_buffers_swapped": 0,
        },
        "carrier_transitions": 0,
    }
}
