expected_output = {
    'mst_instances': {
        6: {
            'bridge_address': '5897.bdff.3b3a',
            'bridge_priority': 20486,
            'interfaces': {
                'GigabitEthernet1/7': {
                    'cost': 20000,
                    'counters': {
                        'bpdu_received': 0,
                        'bpdu_sent': 836828,
                    },
                    'designated_bridge_address': '5897.bdff.3b3a',
                    'designated_bridge_port_id': '128.7',
                    'designated_bridge_priority': 20486,
                    'designated_root_address': '58ac.78ff.c3f5',
                    'designated_root_cost': 2000,
                    'designated_root_priority': 8198,
                    'forward_delay': 0,
                    'forward_transitions': 1,
                    'message_expires': 0,
                    'name': 'GigabitEthernet1/7',
                    'port_id': '128.7',
                    'port_priority': 128,
                    'status': 'designated forwarding',
                },
                'TenGigabitEthernet2/10': {
                    'cost': 2000,
                    'counters': {
                        'bpdu_received': 0,
                        'bpdu_sent': 1285480,
                    },
                    'designated_bridge_address': '5897.bdff.3b3a',
                    'designated_bridge_port_id': '128.138',
                    'designated_bridge_priority': 20486,
                    'designated_root_address': '58ac.78ff.c3f5',
                    'designated_root_cost': 2000,
                    'designated_root_priority': 8198,
                    'forward_delay': 0,
                    'forward_transitions': 2,
                    'message_expires': 0,
                    'name': 'TenGigabitEthernet2/10',
                    'port_id': '128.138',
                    'port_priority': 128,
                    'status': 'designated forwarding',
                },
                'TenGigabitEthernet2/3': {
                    'cost': 2000,
                    'counters': {
                        'bpdu_received': 0,
                        'bpdu_sent': 1285495,
                    },
                    'designated_bridge_address': '5897.bdff.3b3a',
                    'designated_bridge_port_id': '128.131',
                    'designated_bridge_priority': 20486,
                    'designated_root_address': '58ac.78ff.c3f5',
                    'designated_root_cost': 2000,
                    'designated_root_priority': 8198,
                    'forward_delay': 0,
                    'forward_transitions': 2,
                    'message_expires': 0,
                    'name': 'TenGigabitEthernet2/3',
                    'port_id': '128.131',
                    'port_priority': 128,
                    'status': 'designated forwarding',
                },
                'TenGigabitEthernet2/4': {
                    'cost': 2000,
                    'counters': {
                        'bpdu_received': 0,
                        'bpdu_sent': 1285500,
                    },
                    'designated_bridge_address': '5897.bdff.3b3a',
                    'designated_bridge_port_id': '128.132',
                    'designated_bridge_priority': 20486,
                    'designated_root_address': '58ac.78ff.c3f5',
                    'designated_root_cost': 2000,
                    'designated_root_priority': 8198,
                    'forward_delay': 0,
                    'forward_transitions': 2,
                    'message_expires': 0,
                    'name': 'TenGigabitEthernet2/4',
                    'port_id': '128.132',
                    'port_priority': 128,
                    'status': 'designated forwarding',
                },
                'TenGigabitEthernet2/5': {
                    'cost': 2000,
                    'counters': {
                        'bpdu_received': 0,
                        'bpdu_sent': 1285475,
                    },
                    'designated_bridge_address': '5897.bdff.3b3a',
                    'designated_bridge_port_id': '128.133',
                    'designated_bridge_priority': 20486,
                    'designated_root_address': '58ac.78ff.c3f5',
                    'designated_root_cost': 2000,
                    'designated_root_priority': 8198,
                    'forward_delay': 0,
                    'forward_transitions': 2,
                    'message_expires': 0,
                    'name': 'TenGigabitEthernet2/5',
                    'port_id': '128.133',
                    'port_priority': 128,
                    'status': 'designated forwarding',
                },
                'TenGigabitEthernet2/6': {
                    'cost': 2000,
                    'counters': {
                        'bpdu_received': 0,
                        'bpdu_sent': 1285487,
                    },
                    'designated_bridge_address': '5897.bdff.3b3a',
                    'designated_bridge_port_id': '128.134',
                    'designated_bridge_priority': 20486,
                    'designated_root_address': '58ac.78ff.c3f5',
                    'designated_root_cost': 2000,
                    'designated_root_priority': 8198,
                    'forward_delay': 0,
                    'forward_transitions': 2,
                    'message_expires': 0,
                    'name': 'TenGigabitEthernet2/6',
                    'port_id': '128.134',
                    'port_priority': 128,
                    'status': 'designated forwarding',
                },
                'TenGigabitEthernet2/7': {
                    'cost': 2000,
                    'counters': {
                        'bpdu_received': 0,
                        'bpdu_sent': 1285497,
                    },
                    'designated_bridge_address': '5897.bdff.3b3a',
                    'designated_bridge_port_id': '128.135',
                    'designated_bridge_priority': 20486,
                    'designated_root_address': '58ac.78ff.c3f5',
                    'designated_root_cost': 2000,
                    'designated_root_priority': 8198,
                    'forward_delay': 0,
                    'forward_transitions': 2,
                    'message_expires': 0,
                    'name': 'TenGigabitEthernet2/7',
                    'port_id': '128.135',
                    'port_priority': 128,
                    'status': 'designated forwarding',
                },
                'TenGigabitEthernet2/8': {
                    'cost': 2000,
                    'counters': {
                        'bpdu_received': 0,
                        'bpdu_sent': 1285497,
                    },
                    'designated_bridge_address': '5897.bdff.3b3a',
                    'designated_bridge_port_id': '128.136',
                    'designated_bridge_priority': 20486,
                    'designated_root_address': '58ac.78ff.c3f5',
                    'designated_root_cost': 2000,
                    'designated_root_priority': 8198,
                    'forward_delay': 0,
                    'forward_transitions': 2,
                    'message_expires': 0,
                    'name': 'TenGigabitEthernet2/8',
                    'port_id': '128.136',
                    'port_priority': 128,
                    'status': 'designated forwarding',
                },
                'TenGigabitEthernet2/9': {
                    'cost': 2000,
                    'counters': {
                        'bpdu_received': 0,
                        'bpdu_sent': 1285494,
                    },
                    'designated_bridge_address': '5897.bdff.3b3a',
                    'designated_bridge_port_id': '128.137',
                    'designated_bridge_priority': 20486,
                    'designated_root_address': '58ac.78ff.c3f5',
                    'designated_root_cost': 2000,
                    'designated_root_priority': 8198,
                    'forward_delay': 0,
                    'forward_transitions': 2,
                    'message_expires': 0,
                    'name': 'TenGigabitEthernet2/9',
                    'port_id': '128.137',
                    'port_priority': 128,
                    'status': 'designated forwarding',
                },
            },
            'mst_id': 6,
            'root_address': '58ac.78ff.c3f5',
            'root_priority': 8198,
            'sysid': 6,
            'vlan': '500-501,504-505,507-554,556-599',
        },
    },
}
