expected_output = {
    "fpc-information": {
        "fpc": {
            "pic-detail": {
                "pic-slot": "1",
                "slot": "1",
                "pic-type": "24X10GE SFPP",
                "state": "Online",
                "pic-version": "2.35",
                "up-time": {
                    "#text": "6 hours, 24 minutes, 1 second",
                    "@junos:seconds": "23041",
                },
                "port-information": {
                    "port": [
                        {
                            "port-number": "1",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "2",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "3",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "4",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "5",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "6",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "7",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "8",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "9",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "10",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "11",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "12",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "13",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "14",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "15",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "16",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "17",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "18",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "19",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "OEM",
                            "sfp-vendor-pno": "EXSFP10GE-LRCURV",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "20",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "OEM",
                            "sfp-vendor-pno": "EXSFP10GE-LRCURV",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "21",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "AVAGO",
                            "sfp-vendor-pno": "AFCT-739ASMZ-JU1",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "22",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "OEM",
                            "sfp-vendor-pno": "EXSFP10GE-LRCURV",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                        {
                            "port-number": "23",
                            "cable-type": "10GBASE LR",
                            "fiber-mode": "SM",
                            "sfp-vendor-name": "OEM",
                            "sfp-vendor-pno": "EXSFP10GE-LRCURV",
                            "wavelength": "1310 nm",
                            "sfp-vendor-fw-ver": "0.0",
                        },
                    ]
                },
            }
        }
    }
}
