# Python
import unittest
from unittest.mock import Mock

# ATS
from ats.topology import Device
from ats.topology import loader

# Metaparser
from genie.metaparser.util.exceptions import SchemaEmptyParserError

# BigIP get_ltm_profileserver_ssl
from genie.libs.parser.bigip.get_ltm_profileserver_ssl import (
    LtmProfileServerssl,
)

# ==================================
# Unit test for parsing BigIP URL '/mgmt/tm/ltm/profile/server-ssl'
# ==================================


class FakeResponse(object):
    def json(self):
        return {
            "kind": "tm:ltm:profile:server-ssl:server-sslcollectionstate",
            "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl?ver=14.1.2.1",
            "items": [
                {
                    "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                    "name": "apm-default-serverssl",
                    "partition": "Common",
                    "fullPath": "/Common/apm-default-serverssl",
                    "generation": 1,
                    "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~apm-default-serverssl?ver=14.1.2.1",
                    "alertTimeout": "indefinite",
                    "allowExpiredCrl": "disabled",
                    "appService": "none",
                    "authenticate": "once",
                    "authenticateDepth": 9,
                    "authenticateName": "none",
                    "bypassOnClientCertFail": "disabled",
                    "bypassOnHandshakeAlert": "disabled",
                    "c3dCaCert": "none",
                    "c3dCaKey": "none",
                    "c3dCertExtensionCustomOids": [],
                    "c3dCertExtensionIncludes": [
                        "basic-constraints",
                        "extended-key-usage",
                        "key-usage",
                        "subject-alternative-name",
                    ],
                    "c3dCertLifespan": 24,
                    "caFile": "/Common/ca-bundle.crt",
                    "caFileReference": {
                        "link": "https://localhost/mgmt/tm/sys/file/ssl-cert/~Common~ca-bundle.crt?ver=14.1.2.1"
                    },
                    "cacheSize": 262144,
                    "cacheTimeout": 3600,
                    "cert": "none",
                    "chain": "none",
                    "cipherGroup": "none",
                    "ciphers": "DEFAULT",
                    "crl": "none",
                    "crlFile": "none",
                    "defaultsFrom": "/Common/serverssl",
                    "defaultsFromReference": {
                        "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                    },
                    "description": "none",
                    "expireCertResponseControl": "drop",
                    "genericAlert": "enabled",
                    "handshakeTimeout": "10",
                    "key": "none",
                    "maxActiveHandshakes": "indefinite",
                    "modSslMethods": "disabled",
                    "mode": "enabled",
                    "ocsp": "none",
                    "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                    "peerCertMode": "require",
                    "proxySsl": "disabled",
                    "proxySslPassthrough": "disabled",
                    "renegotiatePeriod": "indefinite",
                    "renegotiateSize": "indefinite",
                    "renegotiation": "enabled",
                    "retainCertificate": "true",
                    "secureRenegotiation": "request",
                    "serverName": "none",
                    "sessionMirroring": "disabled",
                    "sessionTicket": "disabled",
                    "sniDefault": "false",
                    "sniRequire": "false",
                    "sslC3d": "disabled",
                    "sslForwardProxy": "disabled",
                    "sslForwardProxyBypass": "disabled",
                    "sslForwardProxyVerifiedHandshake": "disabled",
                    "sslSignHash": "any",
                    "strictResume": "disabled",
                    "uncleanShutdown": "enabled",
                    "untrustedCertResponseControl": "drop",
                },
                {
                    "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                    "name": "crypto-client-default-serverssl",
                    "partition": "Common",
                    "fullPath": "/Common/crypto-client-default-serverssl",
                    "generation": 1,
                    "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~crypto-client-default-serverssl?ver=14.1.2.1",
                    "alertTimeout": "indefinite",
                    "allowExpiredCrl": "disabled",
                    "appService": "none",
                    "authenticate": "once",
                    "authenticateDepth": 9,
                    "authenticateName": "none",
                    "bypassOnClientCertFail": "disabled",
                    "bypassOnHandshakeAlert": "disabled",
                    "c3dCaCert": "none",
                    "c3dCaKey": "none",
                    "c3dCertExtensionCustomOids": [],
                    "c3dCertExtensionIncludes": [
                        "basic-constraints",
                        "extended-key-usage",
                        "key-usage",
                        "subject-alternative-name",
                    ],
                    "c3dCertLifespan": 24,
                    "caFile": "none",
                    "cacheSize": 0,
                    "cacheTimeout": 3600,
                    "cert": "none",
                    "chain": "none",
                    "cipherGroup": "none",
                    "ciphers": "DHE-RSA-AES256-GCM-SHA384",
                    "crl": "none",
                    "crlFile": "none",
                    "defaultsFrom": "/Common/serverssl",
                    "defaultsFromReference": {
                        "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                    },
                    "description": "none",
                    "expireCertResponseControl": "drop",
                    "genericAlert": "enabled",
                    "handshakeTimeout": "10",
                    "key": "none",
                    "maxActiveHandshakes": "indefinite",
                    "modSslMethods": "disabled",
                    "mode": "enabled",
                    "ocsp": "none",
                    "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                    "peerCertMode": "ignore",
                    "proxySsl": "disabled",
                    "proxySslPassthrough": "disabled",
                    "renegotiatePeriod": "indefinite",
                    "renegotiateSize": "indefinite",
                    "renegotiation": "enabled",
                    "retainCertificate": "true",
                    "secureRenegotiation": "require-strict",
                    "serverName": "none",
                    "sessionMirroring": "disabled",
                    "sessionTicket": "disabled",
                    "sniDefault": "false",
                    "sniRequire": "false",
                    "sslC3d": "disabled",
                    "sslForwardProxy": "disabled",
                    "sslForwardProxyBypass": "disabled",
                    "sslForwardProxyVerifiedHandshake": "disabled",
                    "sslSignHash": "any",
                    "strictResume": "disabled",
                    "uncleanShutdown": "enabled",
                    "untrustedCertResponseControl": "drop",
                },
                {
                    "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                    "name": "pcoip-default-serverssl",
                    "partition": "Common",
                    "fullPath": "/Common/pcoip-default-serverssl",
                    "generation": 1,
                    "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~pcoip-default-serverssl?ver=14.1.2.1",
                    "alertTimeout": "indefinite",
                    "allowExpiredCrl": "disabled",
                    "appService": "none",
                    "authenticate": "once",
                    "authenticateDepth": 9,
                    "authenticateName": "none",
                    "bypassOnClientCertFail": "disabled",
                    "bypassOnHandshakeAlert": "disabled",
                    "c3dCaCert": "none",
                    "c3dCaKey": "none",
                    "c3dCertExtensionCustomOids": [],
                    "c3dCertExtensionIncludes": [
                        "basic-constraints",
                        "extended-key-usage",
                        "key-usage",
                        "subject-alternative-name",
                    ],
                    "c3dCertLifespan": 24,
                    "caFile": "none",
                    "cacheSize": 262144,
                    "cacheTimeout": 3600,
                    "cert": "none",
                    "chain": "none",
                    "cipherGroup": "none",
                    "ciphers": "DEFAULT",
                    "crl": "none",
                    "crlFile": "none",
                    "defaultsFrom": "/Common/serverssl",
                    "defaultsFromReference": {
                        "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                    },
                    "description": "none",
                    "expireCertResponseControl": "drop",
                    "genericAlert": "enabled",
                    "handshakeTimeout": "10",
                    "key": "none",
                    "maxActiveHandshakes": "indefinite",
                    "modSslMethods": "disabled",
                    "mode": "enabled",
                    "ocsp": "none",
                    "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                    "peerCertMode": "ignore",
                    "proxySsl": "disabled",
                    "proxySslPassthrough": "disabled",
                    "renegotiatePeriod": "indefinite",
                    "renegotiateSize": "indefinite",
                    "renegotiation": "enabled",
                    "retainCertificate": "true",
                    "secureRenegotiation": "require-strict",
                    "serverName": "pcoip-default-sni",
                    "sessionMirroring": "disabled",
                    "sessionTicket": "disabled",
                    "sniDefault": "false",
                    "sniRequire": "false",
                    "sslC3d": "disabled",
                    "sslForwardProxy": "disabled",
                    "sslForwardProxyBypass": "disabled",
                    "sslForwardProxyVerifiedHandshake": "disabled",
                    "sslSignHash": "any",
                    "strictResume": "disabled",
                    "uncleanShutdown": "enabled",
                    "untrustedCertResponseControl": "drop",
                },
                {
                    "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                    "name": "serverssl",
                    "partition": "Common",
                    "fullPath": "/Common/serverssl",
                    "generation": 1,
                    "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1",
                    "alertTimeout": "indefinite",
                    "allowExpiredCrl": "disabled",
                    "appService": "none",
                    "authenticate": "once",
                    "authenticateDepth": 9,
                    "authenticateName": "none",
                    "bypassOnClientCertFail": "disabled",
                    "bypassOnHandshakeAlert": "disabled",
                    "c3dCaCert": "none",
                    "c3dCaKey": "none",
                    "c3dCertExtensionCustomOids": [],
                    "c3dCertExtensionIncludes": [
                        "basic-constraints",
                        "extended-key-usage",
                        "key-usage",
                        "subject-alternative-name",
                    ],
                    "c3dCertLifespan": 24,
                    "caFile": "none",
                    "cacheSize": 262144,
                    "cacheTimeout": 3600,
                    "cert": "none",
                    "chain": "none",
                    "cipherGroup": "none",
                    "ciphers": "DEFAULT",
                    "crl": "none",
                    "crlFile": "none",
                    "defaultsFrom": "none",
                    "description": "none",
                    "expireCertResponseControl": "drop",
                    "genericAlert": "enabled",
                    "handshakeTimeout": "10",
                    "key": "none",
                    "maxActiveHandshakes": "indefinite",
                    "modSslMethods": "disabled",
                    "mode": "enabled",
                    "ocsp": "none",
                    "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                    "peerCertMode": "ignore",
                    "proxySsl": "disabled",
                    "proxySslPassthrough": "disabled",
                    "renegotiatePeriod": "indefinite",
                    "renegotiateSize": "indefinite",
                    "renegotiation": "enabled",
                    "retainCertificate": "true",
                    "secureRenegotiation": "require-strict",
                    "serverName": "none",
                    "sessionMirroring": "disabled",
                    "sessionTicket": "disabled",
                    "sniDefault": "false",
                    "sniRequire": "false",
                    "sslC3d": "disabled",
                    "sslForwardProxy": "disabled",
                    "sslForwardProxyBypass": "disabled",
                    "sslForwardProxyVerifiedHandshake": "disabled",
                    "sslSignHash": "any",
                    "strictResume": "disabled",
                    "uncleanShutdown": "enabled",
                    "untrustedCertResponseControl": "drop",
                },
                {
                    "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                    "name": "serverssl-insecure-compatible",
                    "partition": "Common",
                    "fullPath": "/Common/serverssl-insecure-compatible",
                    "generation": 1,
                    "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl-insecure-compatible?ver=14.1.2.1",
                    "alertTimeout": "indefinite",
                    "allowExpiredCrl": "disabled",
                    "appService": "none",
                    "authenticate": "once",
                    "authenticateDepth": 9,
                    "authenticateName": "none",
                    "bypassOnClientCertFail": "disabled",
                    "bypassOnHandshakeAlert": "disabled",
                    "c3dCaCert": "none",
                    "c3dCaKey": "none",
                    "c3dCertExtensionCustomOids": [],
                    "c3dCertExtensionIncludes": [
                        "basic-constraints",
                        "extended-key-usage",
                        "key-usage",
                        "subject-alternative-name",
                    ],
                    "c3dCertLifespan": 24,
                    "caFile": "none",
                    "cacheSize": 262144,
                    "cacheTimeout": 3600,
                    "cert": "none",
                    "chain": "none",
                    "cipherGroup": "none",
                    "ciphers": "!EXPORT:!DH:RSA+RC4:RSA+AES:RSA+DES:RSA+3DES:ECDHE+AES:ECDHE+3DES:@SPEED",
                    "crl": "none",
                    "crlFile": "none",
                    "defaultsFrom": "/Common/serverssl",
                    "defaultsFromReference": {
                        "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                    },
                    "description": "none",
                    "expireCertResponseControl": "drop",
                    "genericAlert": "enabled",
                    "handshakeTimeout": "10",
                    "key": "none",
                    "maxActiveHandshakes": "indefinite",
                    "modSslMethods": "disabled",
                    "mode": "enabled",
                    "ocsp": "none",
                    "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                    "peerCertMode": "ignore",
                    "proxySsl": "disabled",
                    "proxySslPassthrough": "disabled",
                    "renegotiatePeriod": "indefinite",
                    "renegotiateSize": "indefinite",
                    "renegotiation": "enabled",
                    "retainCertificate": "true",
                    "secureRenegotiation": "request",
                    "serverName": "none",
                    "sessionMirroring": "disabled",
                    "sessionTicket": "disabled",
                    "sniDefault": "false",
                    "sniRequire": "false",
                    "sslC3d": "disabled",
                    "sslForwardProxy": "disabled",
                    "sslForwardProxyBypass": "disabled",
                    "sslForwardProxyVerifiedHandshake": "disabled",
                    "sslSignHash": "any",
                    "strictResume": "disabled",
                    "uncleanShutdown": "enabled",
                    "untrustedCertResponseControl": "drop",
                },
                {
                    "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                    "name": "splitsession-default-serverssl",
                    "partition": "Common",
                    "fullPath": "/Common/splitsession-default-serverssl",
                    "generation": 1,
                    "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~splitsession-default-serverssl?ver=14.1.2.1",
                    "alertTimeout": "indefinite",
                    "allowExpiredCrl": "disabled",
                    "appService": "none",
                    "authenticate": "once",
                    "authenticateDepth": 9,
                    "authenticateName": "none",
                    "bypassOnClientCertFail": "disabled",
                    "bypassOnHandshakeAlert": "disabled",
                    "c3dCaCert": "none",
                    "c3dCaKey": "none",
                    "c3dCertExtensionCustomOids": [],
                    "c3dCertExtensionIncludes": [
                        "basic-constraints",
                        "extended-key-usage",
                        "key-usage",
                        "subject-alternative-name",
                    ],
                    "c3dCertLifespan": 24,
                    "caFile": "none",
                    "cacheSize": 262144,
                    "cacheTimeout": 3600,
                    "cert": "/Common/default.crt",
                    "certReference": {
                        "link": "https://localhost/mgmt/tm/sys/file/ssl-cert/~Common~default.crt?ver=14.1.2.1"
                    },
                    "chain": "none",
                    "cipherGroup": "none",
                    "ciphers": "DEFAULT",
                    "crl": "none",
                    "crlFile": "none",
                    "defaultsFrom": "/Common/serverssl",
                    "defaultsFromReference": {
                        "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                    },
                    "description": "none",
                    "expireCertResponseControl": "drop",
                    "genericAlert": "enabled",
                    "handshakeTimeout": "10",
                    "key": "/Common/default.key",
                    "keyReference": {
                        "link": "https://localhost/mgmt/tm/sys/file/ssl-key/~Common~default.key?ver=14.1.2.1"
                    },
                    "maxActiveHandshakes": "indefinite",
                    "modSslMethods": "disabled",
                    "mode": "enabled",
                    "ocsp": "none",
                    "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                    "peerCertMode": "ignore",
                    "proxySsl": "disabled",
                    "proxySslPassthrough": "disabled",
                    "renegotiatePeriod": "indefinite",
                    "renegotiateSize": "indefinite",
                    "renegotiation": "enabled",
                    "retainCertificate": "true",
                    "secureRenegotiation": "require-strict",
                    "serverName": "none",
                    "sessionMirroring": "disabled",
                    "sessionTicket": "disabled",
                    "sniDefault": "false",
                    "sniRequire": "false",
                    "sslC3d": "disabled",
                    "sslForwardProxy": "disabled",
                    "sslForwardProxyBypass": "disabled",
                    "sslForwardProxyVerifiedHandshake": "disabled",
                    "sslSignHash": "any",
                    "strictResume": "disabled",
                    "uncleanShutdown": "enabled",
                    "untrustedCertResponseControl": "drop",
                },
                {
                    "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                    "name": "wom-default-serverssl",
                    "partition": "Common",
                    "fullPath": "/Common/wom-default-serverssl",
                    "generation": 1,
                    "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~wom-default-serverssl?ver=14.1.2.1",
                    "alertTimeout": "indefinite",
                    "allowExpiredCrl": "disabled",
                    "appService": "none",
                    "authenticate": "once",
                    "authenticateDepth": 9,
                    "authenticateName": "none",
                    "bypassOnClientCertFail": "disabled",
                    "bypassOnHandshakeAlert": "disabled",
                    "c3dCaCert": "none",
                    "c3dCaKey": "none",
                    "c3dCertExtensionCustomOids": [],
                    "c3dCertExtensionIncludes": [
                        "basic-constraints",
                        "extended-key-usage",
                        "key-usage",
                        "subject-alternative-name",
                    ],
                    "c3dCertLifespan": 24,
                    "caFile": "none",
                    "cacheSize": 262144,
                    "cacheTimeout": 3600,
                    "cert": "/Common/default.crt",
                    "certReference": {
                        "link": "https://localhost/mgmt/tm/sys/file/ssl-cert/~Common~default.crt?ver=14.1.2.1"
                    },
                    "chain": "none",
                    "cipherGroup": "none",
                    "ciphers": "DEFAULT",
                    "crl": "none",
                    "crlFile": "none",
                    "defaultsFrom": "/Common/serverssl",
                    "defaultsFromReference": {
                        "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                    },
                    "description": "none",
                    "expireCertResponseControl": "drop",
                    "genericAlert": "enabled",
                    "handshakeTimeout": "10",
                    "key": "/Common/default.key",
                    "keyReference": {
                        "link": "https://localhost/mgmt/tm/sys/file/ssl-key/~Common~default.key?ver=14.1.2.1"
                    },
                    "maxActiveHandshakes": "indefinite",
                    "modSslMethods": "disabled",
                    "mode": "disabled",
                    "ocsp": "none",
                    "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                    "peerCertMode": "ignore",
                    "proxySsl": "disabled",
                    "proxySslPassthrough": "disabled",
                    "renegotiatePeriod": "indefinite",
                    "renegotiateSize": "indefinite",
                    "renegotiation": "enabled",
                    "retainCertificate": "true",
                    "secureRenegotiation": "require-strict",
                    "serverName": "none",
                    "sessionMirroring": "disabled",
                    "sessionTicket": "disabled",
                    "sniDefault": "false",
                    "sniRequire": "false",
                    "sslC3d": "disabled",
                    "sslForwardProxy": "disabled",
                    "sslForwardProxyBypass": "disabled",
                    "sslForwardProxyVerifiedHandshake": "disabled",
                    "sslSignHash": "any",
                    "strictResume": "disabled",
                    "uncleanShutdown": "enabled",
                    "untrustedCertResponseControl": "drop",
                },
            ],
        }


class test_get_ltm_profileserver_ssl(unittest.TestCase):

    maxDiff = None

    empty_output = {"get.return_value": {}}

    golden_parsed_output = {
        "items": [
            {
                "alertTimeout": "indefinite",
                "allowExpiredCrl": "disabled",
                "appService": "none",
                "authenticate": "once",
                "authenticateDepth": 9,
                "authenticateName": "none",
                "bypassOnClientCertFail": "disabled",
                "bypassOnHandshakeAlert": "disabled",
                "c3dCaCert": "none",
                "c3dCaKey": "none",
                "c3dCertExtensionCustomOids": [],
                "c3dCertExtensionIncludes": [
                    "basic-constraints",
                    "extended-key-usage",
                    "key-usage",
                    "subject-alternative-name",
                ],
                "c3dCertLifespan": 24,
                "caFile": "/Common/ca-bundle.crt",
                "caFileReference": {
                    "link": "https://localhost/mgmt/tm/sys/file/ssl-cert/~Common~ca-bundle.crt?ver=14.1.2.1"
                },
                "cacheSize": 262144,
                "cacheTimeout": 3600,
                "cert": "none",
                "chain": "none",
                "cipherGroup": "none",
                "ciphers": "DEFAULT",
                "crl": "none",
                "crlFile": "none",
                "defaultsFrom": "/Common/serverssl",
                "defaultsFromReference": {
                    "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                },
                "description": "none",
                "expireCertResponseControl": "drop",
                "fullPath": "/Common/apm-default-serverssl",
                "generation": 1,
                "genericAlert": "enabled",
                "handshakeTimeout": "10",
                "key": "none",
                "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                "maxActiveHandshakes": "indefinite",
                "modSslMethods": "disabled",
                "mode": "enabled",
                "name": "apm-default-serverssl",
                "ocsp": "none",
                "partition": "Common",
                "peerCertMode": "require",
                "proxySsl": "disabled",
                "proxySslPassthrough": "disabled",
                "renegotiatePeriod": "indefinite",
                "renegotiateSize": "indefinite",
                "renegotiation": "enabled",
                "retainCertificate": "true",
                "secureRenegotiation": "request",
                "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~apm-default-serverssl?ver=14.1.2.1",
                "serverName": "none",
                "sessionMirroring": "disabled",
                "sessionTicket": "disabled",
                "sniDefault": "false",
                "sniRequire": "false",
                "sslC3d": "disabled",
                "sslForwardProxy": "disabled",
                "sslForwardProxyBypass": "disabled",
                "sslForwardProxyVerifiedHandshake": "disabled",
                "sslSignHash": "any",
                "strictResume": "disabled",
                "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                "uncleanShutdown": "enabled",
                "untrustedCertResponseControl": "drop",
            },
            {
                "alertTimeout": "indefinite",
                "allowExpiredCrl": "disabled",
                "appService": "none",
                "authenticate": "once",
                "authenticateDepth": 9,
                "authenticateName": "none",
                "bypassOnClientCertFail": "disabled",
                "bypassOnHandshakeAlert": "disabled",
                "c3dCaCert": "none",
                "c3dCaKey": "none",
                "c3dCertExtensionCustomOids": [],
                "c3dCertExtensionIncludes": [
                    "basic-constraints",
                    "extended-key-usage",
                    "key-usage",
                    "subject-alternative-name",
                ],
                "c3dCertLifespan": 24,
                "caFile": "none",
                "cacheSize": 0,
                "cacheTimeout": 3600,
                "cert": "none",
                "chain": "none",
                "cipherGroup": "none",
                "ciphers": "DHE-RSA-AES256-GCM-SHA384",
                "crl": "none",
                "crlFile": "none",
                "defaultsFrom": "/Common/serverssl",
                "defaultsFromReference": {
                    "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                },
                "description": "none",
                "expireCertResponseControl": "drop",
                "fullPath": "/Common/crypto-client-default-serverssl",
                "generation": 1,
                "genericAlert": "enabled",
                "handshakeTimeout": "10",
                "key": "none",
                "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                "maxActiveHandshakes": "indefinite",
                "modSslMethods": "disabled",
                "mode": "enabled",
                "name": "crypto-client-default-serverssl",
                "ocsp": "none",
                "partition": "Common",
                "peerCertMode": "ignore",
                "proxySsl": "disabled",
                "proxySslPassthrough": "disabled",
                "renegotiatePeriod": "indefinite",
                "renegotiateSize": "indefinite",
                "renegotiation": "enabled",
                "retainCertificate": "true",
                "secureRenegotiation": "require-strict",
                "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~crypto-client-default-serverssl?ver=14.1.2.1",
                "serverName": "none",
                "sessionMirroring": "disabled",
                "sessionTicket": "disabled",
                "sniDefault": "false",
                "sniRequire": "false",
                "sslC3d": "disabled",
                "sslForwardProxy": "disabled",
                "sslForwardProxyBypass": "disabled",
                "sslForwardProxyVerifiedHandshake": "disabled",
                "sslSignHash": "any",
                "strictResume": "disabled",
                "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                "uncleanShutdown": "enabled",
                "untrustedCertResponseControl": "drop",
            },
            {
                "alertTimeout": "indefinite",
                "allowExpiredCrl": "disabled",
                "appService": "none",
                "authenticate": "once",
                "authenticateDepth": 9,
                "authenticateName": "none",
                "bypassOnClientCertFail": "disabled",
                "bypassOnHandshakeAlert": "disabled",
                "c3dCaCert": "none",
                "c3dCaKey": "none",
                "c3dCertExtensionCustomOids": [],
                "c3dCertExtensionIncludes": [
                    "basic-constraints",
                    "extended-key-usage",
                    "key-usage",
                    "subject-alternative-name",
                ],
                "c3dCertLifespan": 24,
                "caFile": "none",
                "cacheSize": 262144,
                "cacheTimeout": 3600,
                "cert": "none",
                "chain": "none",
                "cipherGroup": "none",
                "ciphers": "DEFAULT",
                "crl": "none",
                "crlFile": "none",
                "defaultsFrom": "/Common/serverssl",
                "defaultsFromReference": {
                    "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                },
                "description": "none",
                "expireCertResponseControl": "drop",
                "fullPath": "/Common/pcoip-default-serverssl",
                "generation": 1,
                "genericAlert": "enabled",
                "handshakeTimeout": "10",
                "key": "none",
                "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                "maxActiveHandshakes": "indefinite",
                "modSslMethods": "disabled",
                "mode": "enabled",
                "name": "pcoip-default-serverssl",
                "ocsp": "none",
                "partition": "Common",
                "peerCertMode": "ignore",
                "proxySsl": "disabled",
                "proxySslPassthrough": "disabled",
                "renegotiatePeriod": "indefinite",
                "renegotiateSize": "indefinite",
                "renegotiation": "enabled",
                "retainCertificate": "true",
                "secureRenegotiation": "require-strict",
                "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~pcoip-default-serverssl?ver=14.1.2.1",
                "serverName": "pcoip-default-sni",
                "sessionMirroring": "disabled",
                "sessionTicket": "disabled",
                "sniDefault": "false",
                "sniRequire": "false",
                "sslC3d": "disabled",
                "sslForwardProxy": "disabled",
                "sslForwardProxyBypass": "disabled",
                "sslForwardProxyVerifiedHandshake": "disabled",
                "sslSignHash": "any",
                "strictResume": "disabled",
                "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                "uncleanShutdown": "enabled",
                "untrustedCertResponseControl": "drop",
            },
            {
                "alertTimeout": "indefinite",
                "allowExpiredCrl": "disabled",
                "appService": "none",
                "authenticate": "once",
                "authenticateDepth": 9,
                "authenticateName": "none",
                "bypassOnClientCertFail": "disabled",
                "bypassOnHandshakeAlert": "disabled",
                "c3dCaCert": "none",
                "c3dCaKey": "none",
                "c3dCertExtensionCustomOids": [],
                "c3dCertExtensionIncludes": [
                    "basic-constraints",
                    "extended-key-usage",
                    "key-usage",
                    "subject-alternative-name",
                ],
                "c3dCertLifespan": 24,
                "caFile": "none",
                "cacheSize": 262144,
                "cacheTimeout": 3600,
                "cert": "none",
                "chain": "none",
                "cipherGroup": "none",
                "ciphers": "DEFAULT",
                "crl": "none",
                "crlFile": "none",
                "defaultsFrom": "none",
                "description": "none",
                "expireCertResponseControl": "drop",
                "fullPath": "/Common/serverssl",
                "generation": 1,
                "genericAlert": "enabled",
                "handshakeTimeout": "10",
                "key": "none",
                "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                "maxActiveHandshakes": "indefinite",
                "modSslMethods": "disabled",
                "mode": "enabled",
                "name": "serverssl",
                "ocsp": "none",
                "partition": "Common",
                "peerCertMode": "ignore",
                "proxySsl": "disabled",
                "proxySslPassthrough": "disabled",
                "renegotiatePeriod": "indefinite",
                "renegotiateSize": "indefinite",
                "renegotiation": "enabled",
                "retainCertificate": "true",
                "secureRenegotiation": "require-strict",
                "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1",
                "serverName": "none",
                "sessionMirroring": "disabled",
                "sessionTicket": "disabled",
                "sniDefault": "false",
                "sniRequire": "false",
                "sslC3d": "disabled",
                "sslForwardProxy": "disabled",
                "sslForwardProxyBypass": "disabled",
                "sslForwardProxyVerifiedHandshake": "disabled",
                "sslSignHash": "any",
                "strictResume": "disabled",
                "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                "uncleanShutdown": "enabled",
                "untrustedCertResponseControl": "drop",
            },
            {
                "alertTimeout": "indefinite",
                "allowExpiredCrl": "disabled",
                "appService": "none",
                "authenticate": "once",
                "authenticateDepth": 9,
                "authenticateName": "none",
                "bypassOnClientCertFail": "disabled",
                "bypassOnHandshakeAlert": "disabled",
                "c3dCaCert": "none",
                "c3dCaKey": "none",
                "c3dCertExtensionCustomOids": [],
                "c3dCertExtensionIncludes": [
                    "basic-constraints",
                    "extended-key-usage",
                    "key-usage",
                    "subject-alternative-name",
                ],
                "c3dCertLifespan": 24,
                "caFile": "none",
                "cacheSize": 262144,
                "cacheTimeout": 3600,
                "cert": "none",
                "chain": "none",
                "cipherGroup": "none",
                "ciphers": "!EXPORT:!DH:RSA+RC4:RSA+AES:RSA+DES:RSA+3DES:ECDHE+AES:ECDHE+3DES:@SPEED",
                "crl": "none",
                "crlFile": "none",
                "defaultsFrom": "/Common/serverssl",
                "defaultsFromReference": {
                    "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                },
                "description": "none",
                "expireCertResponseControl": "drop",
                "fullPath": "/Common/serverssl-insecure-compatible",
                "generation": 1,
                "genericAlert": "enabled",
                "handshakeTimeout": "10",
                "key": "none",
                "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                "maxActiveHandshakes": "indefinite",
                "modSslMethods": "disabled",
                "mode": "enabled",
                "name": "serverssl-insecure-compatible",
                "ocsp": "none",
                "partition": "Common",
                "peerCertMode": "ignore",
                "proxySsl": "disabled",
                "proxySslPassthrough": "disabled",
                "renegotiatePeriod": "indefinite",
                "renegotiateSize": "indefinite",
                "renegotiation": "enabled",
                "retainCertificate": "true",
                "secureRenegotiation": "request",
                "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl-insecure-compatible?ver=14.1.2.1",
                "serverName": "none",
                "sessionMirroring": "disabled",
                "sessionTicket": "disabled",
                "sniDefault": "false",
                "sniRequire": "false",
                "sslC3d": "disabled",
                "sslForwardProxy": "disabled",
                "sslForwardProxyBypass": "disabled",
                "sslForwardProxyVerifiedHandshake": "disabled",
                "sslSignHash": "any",
                "strictResume": "disabled",
                "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                "uncleanShutdown": "enabled",
                "untrustedCertResponseControl": "drop",
            },
            {
                "alertTimeout": "indefinite",
                "allowExpiredCrl": "disabled",
                "appService": "none",
                "authenticate": "once",
                "authenticateDepth": 9,
                "authenticateName": "none",
                "bypassOnClientCertFail": "disabled",
                "bypassOnHandshakeAlert": "disabled",
                "c3dCaCert": "none",
                "c3dCaKey": "none",
                "c3dCertExtensionCustomOids": [],
                "c3dCertExtensionIncludes": [
                    "basic-constraints",
                    "extended-key-usage",
                    "key-usage",
                    "subject-alternative-name",
                ],
                "c3dCertLifespan": 24,
                "caFile": "none",
                "cacheSize": 262144,
                "cacheTimeout": 3600,
                "cert": "/Common/default.crt",
                "certReference": {
                    "link": "https://localhost/mgmt/tm/sys/file/ssl-cert/~Common~default.crt?ver=14.1.2.1"
                },
                "chain": "none",
                "cipherGroup": "none",
                "ciphers": "DEFAULT",
                "crl": "none",
                "crlFile": "none",
                "defaultsFrom": "/Common/serverssl",
                "defaultsFromReference": {
                    "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                },
                "description": "none",
                "expireCertResponseControl": "drop",
                "fullPath": "/Common/splitsession-default-serverssl",
                "generation": 1,
                "genericAlert": "enabled",
                "handshakeTimeout": "10",
                "key": "/Common/default.key",
                "keyReference": {
                    "link": "https://localhost/mgmt/tm/sys/file/ssl-key/~Common~default.key?ver=14.1.2.1"
                },
                "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                "maxActiveHandshakes": "indefinite",
                "modSslMethods": "disabled",
                "mode": "enabled",
                "name": "splitsession-default-serverssl",
                "ocsp": "none",
                "partition": "Common",
                "peerCertMode": "ignore",
                "proxySsl": "disabled",
                "proxySslPassthrough": "disabled",
                "renegotiatePeriod": "indefinite",
                "renegotiateSize": "indefinite",
                "renegotiation": "enabled",
                "retainCertificate": "true",
                "secureRenegotiation": "require-strict",
                "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~splitsession-default-serverssl?ver=14.1.2.1",
                "serverName": "none",
                "sessionMirroring": "disabled",
                "sessionTicket": "disabled",
                "sniDefault": "false",
                "sniRequire": "false",
                "sslC3d": "disabled",
                "sslForwardProxy": "disabled",
                "sslForwardProxyBypass": "disabled",
                "sslForwardProxyVerifiedHandshake": "disabled",
                "sslSignHash": "any",
                "strictResume": "disabled",
                "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                "uncleanShutdown": "enabled",
                "untrustedCertResponseControl": "drop",
            },
            {
                "alertTimeout": "indefinite",
                "allowExpiredCrl": "disabled",
                "appService": "none",
                "authenticate": "once",
                "authenticateDepth": 9,
                "authenticateName": "none",
                "bypassOnClientCertFail": "disabled",
                "bypassOnHandshakeAlert": "disabled",
                "c3dCaCert": "none",
                "c3dCaKey": "none",
                "c3dCertExtensionCustomOids": [],
                "c3dCertExtensionIncludes": [
                    "basic-constraints",
                    "extended-key-usage",
                    "key-usage",
                    "subject-alternative-name",
                ],
                "c3dCertLifespan": 24,
                "caFile": "none",
                "cacheSize": 262144,
                "cacheTimeout": 3600,
                "cert": "/Common/default.crt",
                "certReference": {
                    "link": "https://localhost/mgmt/tm/sys/file/ssl-cert/~Common~default.crt?ver=14.1.2.1"
                },
                "chain": "none",
                "cipherGroup": "none",
                "ciphers": "DEFAULT",
                "crl": "none",
                "crlFile": "none",
                "defaultsFrom": "/Common/serverssl",
                "defaultsFromReference": {
                    "link": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~serverssl?ver=14.1.2.1"
                },
                "description": "none",
                "expireCertResponseControl": "drop",
                "fullPath": "/Common/wom-default-serverssl",
                "generation": 1,
                "genericAlert": "enabled",
                "handshakeTimeout": "10",
                "key": "/Common/default.key",
                "keyReference": {
                    "link": "https://localhost/mgmt/tm/sys/file/ssl-key/~Common~default.key?ver=14.1.2.1"
                },
                "kind": "tm:ltm:profile:server-ssl:server-sslstate",
                "maxActiveHandshakes": "indefinite",
                "modSslMethods": "disabled",
                "mode": "disabled",
                "name": "wom-default-serverssl",
                "ocsp": "none",
                "partition": "Common",
                "peerCertMode": "ignore",
                "proxySsl": "disabled",
                "proxySslPassthrough": "disabled",
                "renegotiatePeriod": "indefinite",
                "renegotiateSize": "indefinite",
                "renegotiation": "enabled",
                "retainCertificate": "true",
                "secureRenegotiation": "require-strict",
                "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl/~Common~wom-default-serverssl?ver=14.1.2.1",
                "serverName": "none",
                "sessionMirroring": "disabled",
                "sessionTicket": "disabled",
                "sniDefault": "false",
                "sniRequire": "false",
                "sslC3d": "disabled",
                "sslForwardProxy": "disabled",
                "sslForwardProxyBypass": "disabled",
                "sslForwardProxyVerifiedHandshake": "disabled",
                "sslSignHash": "any",
                "strictResume": "disabled",
                "tmOptions": "{ dont-insert-empty-fragments no-tlsv1.3 }",
                "uncleanShutdown": "enabled",
                "untrustedCertResponseControl": "drop",
            },
        ],
        "kind": "tm:ltm:profile:server-ssl:server-sslcollectionstate",
        "selfLink": "https://localhost/mgmt/tm/ltm/profile/server-ssl?ver=14.1.2.1",
    }

    golden_output = {"get.return_value": FakeResponse()}

    # def test_empty(self):
    #     self.device1 = Mock(**self.empty_output)
    #     obj = LtmProfileServerssl(device=self.device1, alias='rest', via='rest', context='rest')
    #     with self.assertRaises(SchemaEmptyParserError):
    #         parsed_output = obj.parse()

    def test_golden(self):
        self.device = Mock(**self.golden_output)
        obj = LtmProfileServerssl(
            device=self.device, alias="rest", via="rest", context="rest"
        )
        parsed_output = obj.parse()
        self.assertEqual(parsed_output, self.golden_parsed_output)


if __name__ == "__main__":
    unittest.main()
