expected_output = {
    'nve_interface': 'nve1',
    'vni_id': 30000,
    'mcast_ip': 'N/A',
    'vni_state': 'Up',
    'vni_type': 'L3CP',
    'vlan_id': '3',
    'vni_origin': 'CLI',
    'vni_vrf': 'red',
    'l3_vlan_id': '3',
    'v4_topo_id': '0x3',
    'v6_topo_id': '0x1E000003',
    'vtep_ip': '1.1.1.2',
    'svi_if_handler': '0x2E',
    'svi_mac': '6C8B.D36D.471F',
    'trm_ipv4': 'N/A',
    'trm_ipv6': 'N/A',
    'uc_input_packets': 0,
    'uc_input_bytes': 0,
    'uc_output_packets': 0,
    'uc_output_bytes': 0,
    'mc_input_packets': 0,
    'mc_input_bytes': 0,
    'mc_output_packets': 0,
    'mc_output_bytes': 0
}
