expected_output = {
    'stackports': {
        '1/1': {
            'cable_length': 'No Cable',
            'in_loopback': 'Yes',
            'link_active': 'No',
            'link_changes_count': 0,
            'link_ok': 'Yes',
            'neighbor': 'NONE/NONE',
            'port_status': 'DOWN',
            'stackport_id': '1/1',
            'sync_ok': 'No',
        },
        '1/2': {
            'cable_length': 'No Cable',
            'in_loopback': 'Yes',
            'link_active': 'Yes',
            'link_changes_count': 0,
            'link_ok': 'Yes',
            'neighbor': '2/2',
            'port_status': 'OK',
            'stackport_id': '1/2',
            'sync_ok': 'Yes',
        },
        '2/1': {
            'cable_length': 'No Cable',
            'in_loopback': 'Yes',
            'link_active': 'Yes',
            'link_changes_count': 0,
            'link_ok': 'Yes',
            'neighbor': '3/2',
            'port_status': 'OK',
            'stackport_id': '2/1',
            'sync_ok': 'Yes',
        },
        '2/2': {
            'cable_length': 'No Cable',
            'in_loopback': 'Yes',
            'link_active': 'Yes',
            'link_changes_count': 0,
            'link_ok': 'Yes',
            'neighbor': '1/2',
            'port_status': 'OK',
            'stackport_id': '2/2',
            'sync_ok': 'Yes',
        },
        '3/1': {
            'cable_length': 'No Cable',
            'in_loopback': 'Yes',
            'link_active': 'No',
            'link_changes_count': 0,
            'link_ok': 'Yes',
            'neighbor': 'NONE/NONE',
            'port_status': 'DOWN',
            'stackport_id': '3/1',
            'sync_ok': 'No',
        },
        '3/2': {
            'cable_length': 'No Cable',
            'in_loopback': 'Yes',
            'link_active': 'Yes',
            'link_changes_count': 0,
            'link_ok': 'Yes',
            'neighbor': '2/1',
            'port_status': 'OK',
            'stackport_id': '3/2',
            'sync_ok': 'Yes',
        },
    },
}
