expected_output = {
        'version': {
            'bootldr_version': 'Cisco IOS Software, s72033_rp Software (s72033_rp-ADVENTERPRISEK9_DBG-M), Version 15.4(0.10)S, EARLY DEPLOYMENT ENGINEERING WEEKLY BUILD, synced to  BLD_DARLING_122S_040709_1301',
            'chassis': 'CISCO7606',
            'compiled_by': 'alnguyen',
            'compiled_date': 'Wed 26-Jun-13 02:21',
            'control_processor_uptime': '22 weeks, 6 days, 1 hour, 57 minutes',
            'controller': {
                'counts': 1,
                'serial': 4,
                'type': 'Enhanced FlexWAN',
            },
            'cpu': {
                'implementation': '1284',
                'l2_cache': '512KB',
                'name': 'SR71000',
                'rev': '1.2',
                'speed': '600MHz',
            },
            'curr_config_register': '0x2',
            'hostname': 'ipcore-ssr-uut2',
            'image_id': 's72033_rp-ADVENTERPRISEK9_DBG-M',
            'interfaces': {
                'gigabit_ethernet': 52,
                'serial': 4,
                'virtual_ethernet': 1,
            },
            'last_reload': {
                'reason': 'abort at PC 0x433A11BC',
                'type': 'Normal Reload',
            },
            'last_reset': 's/w',
            'main_mem': '983008',
            'memory': {
                'flash_internal_SIMM': 65536,
                'non_volatile_conf': 1917,
                'packet_buffer': 8192,
            },
            'os': 'IOS',
            'platform': 's72033_rp',
            'processor_board_id': 'FOX11140RN8',
            'processor_type': 'R7000',
            'returned_to_rom_by': 'power cycle at 03:04:03 PDT Thu May 18 2017 (SP by power on)',
            'rom': 'System Bootstrap, Version 12.2(17r)SX7, RELEASE SOFTWARE',
            'rom_version': '(fc1)',
            'system_image': 'disk0:s72033-adventerprisek9_dbg-mz.154-0.10.S-ipcore-ssr-uut2',
            'uptime': '22 weeks, 6 days, 2 hours, 1 minute',
            'version': '15.4(0.10)S',
        },
    }