expected_output = {
    "service_node_group_name":{
        "SNG-APPQOE1":{
            "service_context":"appqoe/1",
            "member_service_node_count":2,
            "service_nodes":{
                "26.126.0.1":{
                    "auto_discovered":"No",
                    "sn_belongs_to_sng":"SNG-APPQOE1",
                    "current_status_of_sn":"Alive",
                    "system_ip":"26.1.0.1",
                    "site_id":26,
                    "time_current_status_was_reached":"Mon Aug 23 12:48:32 2021",
                    "cluster_protocol_vpath_version":"1 (Bitmap recvd: 1)",
                    "cluster_protocol_incarnation_number":1,
                    "cluster_protocol_last_sent_sequence_number":1631666073,
                    "cluster_protocol_last_received_sequence_number":664135,
                    "cluster_protocol_last_received_ack_number":1631666072,
                    "health_markers":{
                        "tcp":{
                            "color":"green",
                            "percentage":43
                        },
                        "ssl":{
                            "color":"green",
                            "percentage":43
                        },
                        "dre":{
                            "color":"green",
                            "percentage":50
                        },
                        "http":{
                            "color":"red",
                            "status":"not_available"
                        }
                    }
                },
                "26.126.0.2":{
                    "auto_discovered":"No",
                    "sn_belongs_to_sng":"SNG-APPQOE1",
                    "current_status_of_sn":"Alive",
                    "system_ip":"26.1.0.2",
                    "site_id":26,
                    "time_current_status_was_reached":"Mon Aug 23 12:48:32 2021",
                    "cluster_protocol_vpath_version":"1 (Bitmap recvd: 1)",
                    "cluster_protocol_incarnation_number":1,
                    "cluster_protocol_last_sent_sequence_number":1631666074,
                    "cluster_protocol_last_received_sequence_number":662799,
                    "cluster_protocol_last_received_ack_number":1631666073,
                    "health_markers":{
                        "tcp":{
                            "color":"green",
                            "percentage":43
                        },
                        "ssl":{
                            "color":"green",
                            "percentage":43
                        },
                        "dre":{
                            "color":"green",
                            "percentage":50
                        },
                        "http":{
                            "color":"red",
                            "status":"not_available"
                        }
                    }
                }
            }
        },
        "SNG-APPQOE2":{
            "service_context":"appqoe/1",
            "member_service_node_count":1,
            "service_nodes":{
                "26.126.0.3":{
                    "auto_discovered":"No",
                    "sn_belongs_to_sng":"SNG-APPQOE2",
                    "current_status_of_sn":"Alive",
                    "system_ip":"26.1.0.3",
                    "site_id":26,
                    "time_current_status_was_reached":"Mon Aug 23 12:48:32 2021",
                    "cluster_protocol_vpath_version":"1 (Bitmap recvd: 1)",
                    "cluster_protocol_incarnation_number":1,
                    "cluster_protocol_last_sent_sequence_number":1631666075,
                    "cluster_protocol_last_received_sequence_number":661599,
                    "cluster_protocol_last_received_ack_number":1631666074,
                    "health_markers":{
                        "tcp":{
                            "color":"green",
                            "percentage":31
                        },
                        "ssl":{
                            "color":"green",
                            "percentage":37
                        },
                        "dre":{
                            "color":"green",
                            "percentage":37
                        },
                        "http":{
                            "color":"red",
                            "status":"not_available"
                        }
                    }
                }
            }
        }
    }
}
