expected_output = {
         "src":{
            "10.4.1.2":{
               "dest":{
                  "10.4.1.1":{
                     "interface":"GigabitEthernet0/0/0/0",
                     "location":"0/0/CPU0",
                     "session":{
                        "state":"UP",
                        "duration":"0d:0h:5m:50s",
                        "num_of_times_up":1,
                        "type":"PR/V4/SH",
                        "owner_info":{
                              "ipv4_static":{
                                 "desired_interval_ms":500,
                                 "desired_multiplier":6,
                                 "adjusted_interval_ms":500,
                                 "adjusted_multiplier":6
                              }
                           }
                        },
                     "received_parameters":{
                        "version":1,
                        "desired_tx_interval_ms":500,
                        "required_rx_interval_ms":500,
                        "required_echo_rx_interval_ms":0,
                        "multiplier":6,
                        "diag":"None",
                        "demand_bit":0,
                        "final_bit":0,
                        "poll_bit":0,
                        "control_bit":1,
                        "authentication_bit":0,
                        "my_discr":18,
                        "your_discr":2148532226,
                        "state":"UP"
                     },
                     "transmitted_parameters":{
                        "version":1,
                        "desired_tx_interval_ms":500,
                        "required_rx_interval_ms":500,
                        "required_echo_rx_interval_ms":1,
                        "multiplier":6,
                        "diag":"None",
                        "demand_bit":0,
                        "final_bit":0,
                        "poll_bit":0,
                        "control_bit":1,
                        "authentication_bit":0,
                        "my_discr":2148532226,
                        "your_discr":18,
                        "state":"UP"
                     },
                     "timer_vals":{
                        "local_async_tx_interval_ms":500,
                        "remote_async_tx_interval_ms":500,
                        "desired_echo_tx_interval_ms":500,
                        "local_echo_tax_interval_ms":0,
                        "echo_detection_time_ms":0,
                        "async_detection_time_ms":3000
                     },
                     "local_stats":{
                        "interval_async_packets":{
                           "Tx":{
                              "num_intervals":100,
                              "min_ms":1,
                              "max_ms":500,
                              "avg_ms":229,
                              "last_packet_transmitted_ms_ago":48
                           },
                           "Rx":{
                              "num_intervals":100,
                              "min_ms":490,
                              "max_ms":513,
                              "avg_ms":500,
                              "last_packet_received_ms_ago":304
                           }
                        },
                        "interval_echo_packets":{
                           "Tx":{
                              "num_intervals":0,
                              "min_ms":0,
                              "max_ms":0,
                              "avg_ms":0,
                              "last_packet_transmitted_ms_ago":0
                           },
                           "Rx":{
                              "num_intervals":0,
                              "min_ms":0,
                              "max_ms":0,
                              "avg_ms":0,
                              "last_packet_received_ms_ago":0
                           }
                        },
                        "latency_of_echo_packets":{
                           "num_of_packets":0,
                           "min_ms":0,
                           "max_ms":0,
                           "avg_ms":0
                        }
                     }
                  }
               }
            }
         }
      }