expected_output = {
    'active_event_list': {
        1: {
            'alert_group': 'configuration',
            'index': '/31',
            'internal': 29,
            'profile': 'CiscoTAC-1',
            'severity': 'normal',
            'subscription': 'periodic',
        },
        2: {
            'alert_group': 'crash',
            'index': '/32',
            'internal': 30,
            'profile': 'CiscoTAC-1',
            'severity': 'debugging',
            'subscription': 'normal',
        },
        3: {
            'alert_group': 'crash',
            'index': '/33',
            'internal': 31,
            'profile': 'CiscoTAC-1',
            'severity': 'debugging',
            'subscription': 'normal',
        },
        4: {
            'alert_group': 'crash',
            'index': '/34',
            'internal': 32,
            'profile': 'CiscoTAC-1',
            'severity': 'debugging',
            'subscription': 'normal',
        },
        5: {
            'alert_group': 'diagnostic',
            'index': '/35',
            'internal': 33,
            'profile': 'CiscoTAC-1',
            'severity': 'minor',
            'subscription': 'normal',
        },
        6: {
            'alert_group': 'environment',
            'index': '/36',
            'internal': 34,
            'profile': 'CiscoTAC-1',
            'severity': 'warning',
            'subscription': 'normal',
        },
        7: {
            'alert_group': 'inventory',
            'index': '/37',
            'internal': 35,
            'profile': 'CiscoTAC-1',
            'severity': 'normal',
            'subscription': 'normal',
        },
        8: {
            'alert_group': 'inventory',
            'index': '/38',
            'internal': 36,
            'profile': 'CiscoTAC-1',
            'severity': 'normal',
            'subscription': 'normal',
        },
        9: {
            'alert_group': 'inventory',
            'index': '/39',
            'internal': 37,
            'profile': 'CiscoTAC-1',
            'severity': 'normal',
            'subscription': 'periodic',
        },
        10: {
            'alert_group': 'syslog',
            'index': '/40',
            'internal': 38,
            'profile': 'CiscoTAC-1',
            'severity': 'warning',
            'subscription': 'pattern',
        },
        11: {
            'alert_group': 'syslog',
            'index': '/41',
            'internal': 39,
            'profile': 'CiscoTAC-1',
            'severity': 'major',
            'subscription': 'pattern',
        },
        12: {
            'alert_group': 'test',
            'index': '/42',
            'internal': 40,
            'profile': 'CiscoTAC-1',
            'severity': 'normal',
            'subscription': 'normal',
        },
    },
}