expected_output = {
    "entry": {
        "10.16.2.2/32": {
            "ip": "10.16.2.2",
            "mask": "32",
            "known_via": "ospf 1024",
            "distance": "95",
            "metric": "4",
            "type": "intra area",
            "update": {
                "from": "192.168.0.3",
                "interface": "GigabitEthernet2",
                "age": "00:00:14",
            },
            "sr_incoming_label": "52610",
            "paths": {
                1: {
                    "nexthop": "192.168.0.1",
                    "from": "10.16.2.2",
                    "age": "00:00:14",
                    "interface": "GigabitEthernet4",
                    "prefer_non_rib_labels": False,
                    "merge_labels": True,
                    "metric": "5",
                    "share_count": "1",
                    "mpls_label": "52610",
                    "mpls_flags": "NSF",
                    "repair_path": {
                        "repair_path": "192.168.0.2",
                        "via": "GigabitEthernet3",
                    },
                },
                2: {
                    "nexthop": "192.168.0.2",
                    "from": "10.16.2.2",
                    "age": "00:00:14",
                    "interface": "GigabitEthernet3",
                    "prefer_non_rib_labels": True,
                    "merge_labels": True,
                    "metric": "3",
                    "share_count": "5",
                    "mpls_label": "52610",
                    "mpls_flags": "NSF",
                    "repair_path": {
                        "repair_path": "192.168.0.4",
                        "via": "GigabitEthernet1",
                    },
                },
                3: {
                    "nexthop": "192.168.0.3",
                    "from": "10.16.2.2",
                    "age": "00:00:14",
                    "interface": "GigabitEthernet2",
                    "prefer_non_rib_labels": True,
                    "merge_labels": True,
                    "metric": "1",
                    "share_count": "2",
                    "mpls_label": "52610",
                    "mpls_flags": "NSF",
                    "repair_path": {
                        "repair_path": "192.168.0.1",
                        "via": "GigabitEthernet4",
                    },
                },
                4: {
                    "nexthop": "192.168.0.4",
                    "from": "10.16.2.2",
                    "age": "00:00:14",
                    "interface": "GigabitEthernet1",
                    "prefer_non_rib_labels": True,
                    "merge_labels": True,
                    "metric": "2",
                    "share_count": "1",
                    "mpls_label": "52610",
                    "mpls_flags": "NSF",
                    "repair_path": {
                        "repair_path": "192.168.0.3",
                        "via": "GigabitEthernet2",
                    },
                },
            },
        }
    },
    "total_prefixes": 4,
}
