expected_output = {
    "interfaces":{
        "TwoGigabitEthernet1/0/1":{
            "interface":"TwoGigabitEthernet1/0/1",
            "role":"IP Phone 9971",
            "name":"SEP10BD18DD4A19",
            "usage":"7.3",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TwoGigabitEthernet1/0/2":{
            "interface":"TwoGigabitEthernet1/0/2",
            "role":"IP Phone 8945",
            "name":"SEPC4143CB008F7",
            "usage":"2.6",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TwoGigabitEthernet1/0/5":{
            "interface":"TwoGigabitEthernet1/0/5",
            "role":"IP Phone 9971",
            "name":"SEP08CC68E9DC37",
            "usage":"8.5",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TwoGigabitEthernet1/0/13":{
            "interface":"TwoGigabitEthernet1/0/13",
            "role":"IP Phone 9971",
            "name":"SEP08CC68304672",
            "usage":"8.4",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TwoGigabitEthernet1/0/15":{
            "interface":"TwoGigabitEthernet1/0/15",
            "role":"IP Phone 9971",
            "name":"SEP08CC68E9DB8A",
            "usage":"7.6",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TwoGigabitEthernet1/0/24":{
            "interface":"TwoGigabitEthernet1/0/24",
            "role":"IP Phone 9971",
            "name":"SEP34BDC8C7431D",
            "usage":"8.2",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TenGigabitEthernet2/0/2":{
            "interface":"TenGigabitEthernet2/0/2",
            "role":"IP Phone 9971",
            "name":"SEP08CC6830C3B1",
            "usage":"7.7",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TenGigabitEthernet2/0/9":{
            "interface":"TenGigabitEthernet2/0/9",
            "role":"IP Phone 9951",
            "name":"SEPC40ACBE062FF",
            "usage":"7.5",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TenGigabitEthernet2/0/10":{
            "interface":"TenGigabitEthernet2/0/10",
            "role":"IP Phone 9971",
            "name":"SEP28C7CED6CE44",
            "usage":"7.7",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TenGigabitEthernet2/0/11":{
            "interface":"TenGigabitEthernet2/0/11",
            "role":"IP Phone 8945",
            "name":"SEPE0D173E0D8B5",
            "usage":"2.8",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TenGigabitEthernet2/0/12":{
            "interface":"TenGigabitEthernet2/0/12",
            "role":"IP Phone 9971",
            "name":"SEP2834A2F772FB",
            "usage":"8.3",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "GigabitEthernet3/0/3":{
            "interface":"GigabitEthernet3/0/3",
            "role":"IP Phone 9971",
            "name":"SEPD4A02A8955FC",
            "usage":"8.7",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "GigabitEthernet3/0/21":{
            "interface":"GigabitEthernet3/0/21",
            "role":"IP Phone 9971",
            "name":"SEP5C5015452E47",
            "usage":"8.3",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "GigabitEthernet3/0/23":{
            "interface":"GigabitEthernet3/0/23",
            "role":"IP Phone 9971",
            "name":"SEP6886A7C43524",
            "usage":"8.0",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        }
    },
    "device_models":{
        "104.0":{
            "usage":"104.0",
            "name":"Peer1-topo1-ott-1",
            "role":"C9300-48UXM",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"parent"
        },
        "130.0":{
            "usage":"130.0",
            "name":"Peer1-topo1-ott-2",
            "role":"C9300X-24HX",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"parent"
        },
        "78.0":{
            "usage":"78.0",
            "name":"Peer1-topo1-ott-3",
            "role":"C9300-24P",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"parent"
        },
        "consumer":420.6,
        "meter":0.0,
        "producer":0.0,
        "total":420.6,
        "count":18
    }
}