expected_output = {
   "acl_usage":{
      "acl_name":{
         "test-acl":{
            "direction":{
               "Egress":{
                  "acl_type":"IPV4",
                  "entries_used":2,
                  "feature_type":"RACL"
               },
               "Ingress":{
                  "acl_type":"IPV4",
                  "entries_used":2,
                  "feature_type":"RACL"
               }
            }
         }
      }
   }
}
