expected_output = {
   'lisp_id':{
      0:{
         'instance_id':{
            5000:{
               'eid_table':{
                  'vrf internet':{
                     'eid_prefix':{
                        '2001:88:88:1::/64':{
                           'eid':'2001:88:88:1::',
                           'mask':'64',
                           'first_published':'10:32:32',
                           'last_published':'10:32:32',
                           'exported_to':[
                              'local-eid'
                           ],
                           'publishers':{
                              '100.78.78.78':{
                                 'port':4342,
                                 'last_published':'10:32:32',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'0x3A61E299-0x9318B3F0-0x8BD15B56-0xC53DEC1D',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified'
                              },
                              '100.77.77.77':{
                                 'port':4342,
                                 'last_published':'10:32:32',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'0x3A61E299-0x9318B3F0-0x8BD15B56-0xC53DEC1D',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified'
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}