expected_output ={
   'lisp_id':{
      0:{
         'instance_id':{
            5000:{
               'eid_table':{
                  'vrf internet':{
                     'eid_prefix':{
                        '2001:51:51:1::/64':{
                           'eid':'2001:51:51:1::',
                           'mask':'64',
                           'first_published':'12:10:42',
                           'last_published':'12:10:41',
                           'exported_to':[
                              'local-eid'
                           ],
                           'publishers':{
                              '100.78.78.78':{
                                 'port':4342,
                                 'last_published':'12:10:41',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified'
                              },
                              '100.77.77.77':{
                                 'port':4342,
                                 'last_published':'12:10:42',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified'
                              }
                           }
                        },
                        '2001:88:88:1::/64':{
                           'eid':'2001:88:88:1::',
                           'mask':'64',
                           'first_published':'12:06:57',
                           'last_published':'12:06:57',
                           'exported_to':[
                              'local-eid'
                           ],
                           'publishers':{
                              '100.78.78.78':{
                                 'port':4342,
                                 'last_published':'12:06:57',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'0x3A61E299-0x9318B3F0-0x8BD15B56-0xC53DEC1D',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified'
                              },
                              '100.77.77.77':{
                                 'port':4342,
                                 'last_published':'12:06:57',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'0x3A61E299-0x9318B3F0-0x8BD15B56-0xC53DEC1D',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified'
                              }
                           }
                        },
                        '2001:172:168:1::/64':{
                           'eid':'2001:172:168:1::',
                           'mask':'64',
                           'first_published':'12:10:42',
                           'last_published':'12:10:41',
                           'exported_to':[
                              'local-eid'
                           ],
                           'publishers':{
                              '100.78.78.78':{
                                 'port':4342,
                                 'last_published':'12:10:41',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4100'
                              },
                              '100.77.77.77':{
                                 'port':4342,
                                 'last_published':'12:10:42',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4100'
                              }
                           }
                        },
                        '2001:173:168:1::/64':{
                           'eid':'2001:173:168:1::',
                           'mask':'64',
                           'first_published':'12:10:42',
                           'last_published':'12:10:41',
                           'exported_to':[
                              'local-eid'
                           ],
                           'publishers':{
                              '100.78.78.78':{
                                 'port':4342,
                                 'last_published':'12:10:41',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4101'
                              },
                              '100.77.77.77':{
                                 'port':4342,
                                 'last_published':'12:10:42',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4101'
                              }
                           }
                        },
                        '2001:182:168:1::/64':{
                           'eid':'2001:182:168:1::',
                           'mask':'64',
                           'first_published':'12:10:42',
                           'last_published':'12:10:41',
                           'exported_to':[
                              'local-eid'
                           ],
                           'publishers':{
                              '100.78.78.78':{
                                 'port':4342,
                                 'last_published':'12:10:41',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4100'
                              },
                              '100.77.77.77':{
                                 'port':4342,
                                 'last_published':'12:10:42',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4100'
                              }
                           }
                        },
                        '2001:192:168:1::/64':{
                           'eid':'2001:192:168:1::',
                           'mask':'64',
                           'first_published':'12:10:42',
                           'last_published':'12:10:41',
                           'exported_to':[
                              'local-eid'
                           ],
                           'publishers':{
                              '100.78.78.78':{
                                 'port':4342,
                                 'last_published':'12:10:41',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4100'
                              },
                              '100.77.77.77':{
                                 'port':4342,
                                 'last_published':'12:10:42',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4100'
                              }
                           }
                        },
                        '2001:193:168:1::/64':{
                           'eid':'2001:193:168:1::',
                           'mask':'64',
                           'first_published':'12:10:42',
                           'last_published':'12:10:41',
                           'exported_to':[
                              'local-eid'
                           ],
                           'publishers':{
                              '100.78.78.78':{
                                 'port':4342,
                                 'last_published':'12:10:41',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4101'
                              },
                              '100.77.77.77':{
                                 'port':4342,
                                 'last_published':'12:10:42',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified',
                                 'extranet_iid':'4101'
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}