expected_output = {
   "interface":{
      "FiftyGigE2/0/67":{
         "cgid":"0x738310",
         "no_of_classes":4,
         "tcg_ref_count":1,
         "filter_state":"UP TO DATE",
         "vmr_state":"UP TO DATE"
      }
   },
   "qos_profile_information":{
      "oid":"0x9E0",
      "ref_count":1,
      "no_of_counter":1,
      "no_of_meters":3,
      "tunnel_mode":"RE-EVALUATE",
      "need_filter_table_update":"UPTODATE",
      "dscp":{
         "0":{
            "remap":0,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "1":{
            "remap":1,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "2":{
            "remap":2,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "3":{
            "remap":3,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "4":{
            "remap":4,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "5":{
            "remap":5,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "6":{
            "remap":6,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "7":{
            "remap":7,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "8":{
            "remap":8,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "9":{
            "remap":9,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "10":{
            "remap":10,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "11":{
            "remap":11,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "12":{
            "remap":12,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "13":{
            "remap":13,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "14":{
            "remap":14,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "15":{
            "remap":15,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "16":{
            "remap":16,
            "encap":2,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "17":{
            "remap":17,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "18":{
            "remap":18,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "19":{
            "remap":19,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "20":{
            "remap":20,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "21":{
            "remap":21,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "22":{
            "remap":22,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "23":{
            "remap":23,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "24":{
            "remap":24,
            "encap":3,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "25":{
            "remap":25,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "26":{
            "remap":26,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "27":{
            "remap":27,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "28":{
            "remap":28,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "29":{
            "remap":29,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "30":{
            "remap":30,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "31":{
            "remap":31,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "32":{
            "remap":32,
            "encap":4,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "33":{
            "remap":33,
            "encap":4,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "34":{
            "remap":34,
            "encap":4,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "35":{
            "remap":35,
            "encap":4,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "36":{
            "remap":36,
            "encap":4,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "37":{
            "remap":37,
            "encap":4,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "38":{
            "remap":38,
            "encap":4,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "39":{
            "remap":39,
            "encap":4,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "40":{
            "remap":40,
            "encap":5,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "41":{
            "remap":41,
            "encap":5,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "42":{
            "remap":42,
            "encap":5,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "43":{
            "remap":43,
            "encap":5,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "44":{
            "remap":44,
            "encap":5,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "45":{
            "remap":45,
            "encap":5,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "46":{
            "remap":46,
            "encap":5,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "47":{
            "remap":47,
            "encap":5,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "48":{
            "remap":48,
            "encap":6,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "49":{
            "remap":49,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "50":{
            "remap":50,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "51":{
            "remap":51,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "52":{
            "remap":52,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "53":{
            "remap":53,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "54":{
            "remap":54,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "55":{
            "remap":55,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "56":{
            "remap":56,
            "encap":7,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "57":{
            "remap":57,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "58":{
            "remap":58,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "59":{
            "remap":59,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "60":{
            "remap":60,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "61":{
            "remap":61,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "62":{
            "remap":62,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "63":{
            "remap":63,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         }
      },
      "cos_dei":{
         "0":{
            "remap":0,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "1":{
            "remap":1,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "2":{
            "remap":2,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "3":{
            "remap":3,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "4":{
            "remap":4,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "5":{
            "remap":5,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "6":{
            "remap":6,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "7":{
            "remap":7,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "8":{
            "remap":8,
            "encap":4,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "9":{
            "remap":9,
            "encap":4,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "10":{
            "remap":10,
            "encap":5,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "11":{
            "remap":11,
            "encap":5,
            "qos_group":0,
            "tc":7,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "12":{
            "remap":12,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "13":{
            "remap":13,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "14":{
            "remap":14,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "15":{
            "remap":15,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         }
      },
      "exp":{
         "0":{
            "remap":0,
            "encap":0,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "1":{
            "remap":1,
            "encap":1,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "2":{
            "remap":2,
            "encap":2,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "3":{
            "remap":3,
            "encap":3,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "4":{
            "remap":4,
            "encap":4,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "5":{
            "remap":5,
            "encap":5,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "6":{
            "remap":6,
            "encap":6,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         },
         "7":{
            "remap":7,
            "encap":7,
            "qos_group":0,
            "tc":0,
            "dp":"G",
            "meter":"Y",
            "mc_offset":3
         }
      }
   },
   "markdown_table":{
      "oid":"0xE8E",
      "dscp":{
         "0":{
            "green":0,
            "yellow":0,
            "red":0
         },
         "1":{
            "green":1,
            "yellow":1,
            "red":1
         },
         "2":{
            "green":2,
            "yellow":2,
            "red":2
         },
         "3":{
            "green":3,
            "yellow":3,
            "red":3
         },
         "4":{
            "green":4,
            "yellow":4,
            "red":4
         },
         "5":{
            "green":5,
            "yellow":5,
            "red":5
         },
         "6":{
            "green":6,
            "yellow":6,
            "red":6
         },
         "7":{
            "green":7,
            "yellow":7,
            "red":7
         },
         "8":{
            "green":8,
            "yellow":8,
            "red":16
         },
         "9":{
            "green":9,
            "yellow":9,
            "red":9
         },
         "10":{
            "green":10,
            "yellow":10,
            "red":10
         },
         "11":{
            "green":11,
            "yellow":11,
            "red":11
         },
         "12":{
            "green":12,
            "yellow":12,
            "red":12
         },
         "13":{
            "green":13,
            "yellow":13,
            "red":13
         },
         "14":{
            "green":14,
            "yellow":14,
            "red":14
         },
         "15":{
            "green":15,
            "yellow":15,
            "red":15
         },
         "16":{
            "green":16,
            "yellow":16,
            "red":32
         },
         "17":{
            "green":17,
            "yellow":17,
            "red":17
         },
         "18":{
            "green":18,
            "yellow":18,
            "red":18
         },
         "19":{
            "green":19,
            "yellow":19,
            "red":19
         },
         "20":{
            "green":20,
            "yellow":20,
            "red":20
         },
         "21":{
            "green":21,
            "yellow":21,
            "red":21
         },
         "22":{
            "green":22,
            "yellow":22,
            "red":22
         },
         "23":{
            "green":23,
            "yellow":23,
            "red":23
         },
         "24":{
            "green":24,
            "yellow":24,
            "red":24
         },
         "25":{
            "green":25,
            "yellow":25,
            "red":25
         },
         "26":{
            "green":26,
            "yellow":26,
            "red":26
         },
         "27":{
            "green":27,
            "yellow":27,
            "red":27
         },
         "28":{
            "green":28,
            "yellow":28,
            "red":28
         },
         "29":{
            "green":29,
            "yellow":29,
            "red":29
         },
         "30":{
            "green":30,
            "yellow":30,
            "red":30
         },
         "31":{
            "green":31,
            "yellow":31,
            "red":31
         },
         "32":{
            "green":32,
            "yellow":32,
            "red":24
         },
         "33":{
            "green":33,
            "yellow":33,
            "red":33
         },
         "34":{
            "green":34,
            "yellow":34,
            "red":34
         },
         "35":{
            "green":35,
            "yellow":35,
            "red":35
         },
         "36":{
            "green":36,
            "yellow":36,
            "red":36
         },
         "37":{
            "green":37,
            "yellow":37,
            "red":37
         },
         "38":{
            "green":38,
            "yellow":38,
            "red":38
         },
         "39":{
            "green":39,
            "yellow":39,
            "red":39
         },
         "40":{
            "green":40,
            "yellow":40,
            "red":24
         },
         "41":{
            "green":41,
            "yellow":41,
            "red":41
         },
         "42":{
            "green":42,
            "yellow":42,
            "red":42
         },
         "43":{
            "green":43,
            "yellow":43,
            "red":43
         },
         "44":{
            "green":44,
            "yellow":44,
            "red":44
         },
         "45":{
            "green":45,
            "yellow":45,
            "red":45
         },
         "46":{
            "green":46,
            "yellow":46,
            "red":46
         },
         "47":{
            "green":47,
            "yellow":47,
            "red":47
         },
         "48":{
            "green":48,
            "yellow":48,
            "red":56
         },
         "49":{
            "green":49,
            "yellow":49,
            "red":49
         },
         "50":{
            "green":50,
            "yellow":50,
            "red":50
         },
         "51":{
            "green":51,
            "yellow":51,
            "red":51
         },
         "52":{
            "green":52,
            "yellow":52,
            "red":52
         },
         "53":{
            "green":53,
            "yellow":53,
            "red":53
         },
         "54":{
            "green":54,
            "yellow":54,
            "red":54
         },
         "55":{
            "green":55,
            "yellow":55,
            "red":55
         },
         "56":{
            "green":56,
            "yellow":56,
            "red":56
         },
         "57":{
            "green":57,
            "yellow":57,
            "red":57
         },
         "58":{
            "green":58,
            "yellow":58,
            "red":58
         },
         "59":{
            "green":59,
            "yellow":59,
            "red":59
         },
         "60":{
            "green":60,
            "yellow":60,
            "red":60
         },
         "61":{
            "green":61,
            "yellow":61,
            "red":61
         },
         "62":{
            "green":62,
            "yellow":62,
            "red":62
         },
         "63":{
            "green":63,
            "yellow":63,
            "red":63
         }
      },
      "pcpdei":{
         "0":{
            "green":0,
            "yellow":0,
            "red":0
         },
         "1":{
            "green":1,
            "yellow":1,
            "red":1
         },
         "2":{
            "green":2,
            "yellow":2,
            "red":2
         },
         "3":{
            "green":3,
            "yellow":3,
            "red":3
         },
         "4":{
            "green":4,
            "yellow":4,
            "red":4
         },
         "5":{
            "green":5,
            "yellow":5,
            "red":5
         },
         "6":{
            "green":6,
            "yellow":6,
            "red":6
         },
         "7":{
            "green":7,
            "yellow":7,
            "red":7
         },
         "8":{
            "green":8,
            "yellow":8,
            "red":8
         },
         "9":{
            "green":9,
            "yellow":9,
            "red":9
         },
         "10":{
            "green":10,
            "yellow":10,
            "red":10
         },
         "11":{
            "green":11,
            "yellow":11,
            "red":11
         },
         "12":{
            "green":12,
            "yellow":12,
            "red":12
         },
         "13":{
            "green":13,
            "yellow":13,
            "red":13
         },
         "14":{
            "green":14,
            "yellow":14,
            "red":14
         },
         "15":{
            "green":15,
            "yellow":15,
            "red":15
         }
      },
      "exp":{
         "0":{
            "green":0,
            "yellow":0,
            "red":0
         },
         "1":{
            "green":1,
            "yellow":1,
            "red":1
         },
         "2":{
            "green":2,
            "yellow":2,
            "red":2
         },
         "3":{
            "green":3,
            "yellow":3,
            "red":3
         },
         "4":{
            "green":4,
            "yellow":4,
            "red":4
         },
         "5":{
            "green":5,
            "yellow":5,
            "red":5
         },
         "6":{
            "green":6,
            "yellow":6,
            "red":6
         },
         "7":{
            "green":7,
            "yellow":7,
            "red":7
         }
      },
      "encapexp":{
         "0":{
            "green":0,
            "yellow":0,
            "red":0
         },
         "1":{
            "green":1,
            "yellow":1,
            "red":1
         },
         "2":{
            "green":2,
            "yellow":2,
            "red":2
         },
         "3":{
            "green":3,
            "yellow":3,
            "red":3
         },
         "4":{
            "green":4,
            "yellow":4,
            "red":4
         },
         "5":{
            "green":5,
            "yellow":5,
            "red":5
         },
         "6":{
            "green":6,
            "yellow":6,
            "red":6
         },
         "7":{
            "green":7,
            "yellow":7,
            "red":7
         }
      }
   },
   "ipv4_acl":{
      "l3_oid":"0xDE2",
      "l2_oid":"0x0",
      "number_of_aces":3,
      "ace":{
         0:{
            "class_id":"0x0",
            "ipv4_src_address":"0.0.0.0",
            "ipv4_src_mask":"0.0.0.0",
            "ipv4_dst_address":"0.0.0.0",
            "ipv4_dst_mask":"0.0.0.0",
            "protocol":"0x0",
            "protocol_mask":"0x0",
            "dscp":"0x8",
            "dscp_mask":"0x3f",
            "ttl_start":"0x0",
            "ttl_end":"0x0",
            "tcp_flags":"0x0",
            "tcp_mask":"0x0",
            "ip_flags":"0x0",
            "ip_mask":"0x0",
            "src_port_start":"0x0",
            "src_port_end":"0x0",
            "dst_port_start":"0x0",
            "dst_port_end":"0x0",
            "result_action":{
               "remark_value":"0",
               "encap_value":"0",
               "qos_group":"0",
               "traffic_class":"0",
               "drop_precedence":"G",
               "overwrite_phb":"N",
               "overwrite_qos_group":"N",
               "overwrite_encap":"N",
               "overwrite_fwd_tag":"N",
               "meter_enabled":"Y",
               "meter_counter_offset":"0"
            }
         },
         1:{
            "class_id":"0x0",
            "ipv4_src_address":"0.0.0.0",
            "ipv4_src_mask":"0.0.0.0",
            "ipv4_dst_address":"0.0.0.0",
            "ipv4_dst_mask":"0.0.0.0",
            "protocol":"0x0",
            "protocol_mask":"0x0",
            "dscp":"0x10",
            "dscp_mask":"0x3f",
            "ttl_start":"0x0",
            "ttl_end":"0x0",
            "tcp_flags":"0x0",
            "tcp_mask":"0x0",
            "ip_flags":"0x0",
            "ip_mask":"0x0",
            "src_port_start":"0x0",
            "src_port_end":"0x0",
            "dst_port_start":"0x0",
            "dst_port_end":"0x0",
            "result_action":{
               "remark_value":"0",
               "encap_value":"0",
               "qos_group":"0",
               "traffic_class":"0",
               "drop_precedence":"G",
               "overwrite_phb":"N",
               "overwrite_qos_group":"N",
               "overwrite_encap":"N",
               "overwrite_fwd_tag":"N",
               "meter_enabled":"Y",
               "meter_counter_offset":"1"
            }
         },
         2:{
            "class_id":"0x0",
            "ipv4_src_address":"0.0.0.0",
            "ipv4_src_mask":"0.0.0.0",
            "ipv4_dst_address":"0.0.0.0",
            "ipv4_dst_mask":"0.0.0.0",
            "protocol":"0x0",
            "protocol_mask":"0x0",
            "dscp":"0x28",
            "dscp_mask":"0x3f",
            "ttl_start":"0x0",
            "ttl_end":"0x0",
            "tcp_flags":"0x0",
            "tcp_mask":"0x0",
            "ip_flags":"0x0",
            "ip_mask":"0x0",
            "src_port_start":"0x0",
            "src_port_end":"0x0",
            "dst_port_start":"0x0",
            "dst_port_end":"0x0",
            "result_action":{
               "remark_value":"0",
               "encap_value":"0",
               "qos_group":"0",
               "traffic_class":"6",
               "drop_precedence":"G",
               "overwrite_phb":"Y",
               "overwrite_qos_group":"N",
               "overwrite_encap":"N",
               "overwrite_fwd_tag":"N",
               "meter_enabled":"Y",
               "meter_counter_offset":"2"
            }
         }
      }
   },
   "ipv6_acl":{
      "l3_oid":"0xE8A",
      "l2_oid":"0x0",
      "number_of_aces":3,
      "ace":{
         0:{
            "class_id":"0x0",
            "ipv6_src_address":"::",
            "ipv6_src_mask":"::",
            "ipv6_dst_address":"::",
            "ipv6_dst_mask":"::",
            "protocol":"0x0",
            "protocol_mask":"0x0",
            "dscp":"0x8",
            "dscp_mask":"0x3f",
            "ttl_start":"0x0",
            "ttl_end":"0x0",
            "tcp_flags":"0x0",
            "tcp_mask":"0x0",
            "ip_flags":"0x0",
            "ip_mask":"0x0",
            "src_port_start":"0x0",
            "src_port_end":"0x0",
            "dst_port_start":"0x0",
            "dst_port_end":"0x0",
            "result_action":{
               "remark_value":"0",
               "encap_value":"0",
               "qos_group":"0",
               "traffic_class":"0",
               "drop_precedence":"G",
               "overwrite_phb":"N",
               "overwrite_qos_group":"N",
               "overwrite_encap":"N",
               "overwrite_fwd_tag":"N",
               "meter_enabled":"Y",
               "meter_counter_offset":"0"
            }
         },
         1:{
            "class_id":"0x0",
            "ipv6_src_address":"::",
            "ipv6_src_mask":"::",
            "ipv6_dst_address":"::",
            "ipv6_dst_mask":"::",
            "protocol":"0x0",
            "protocol_mask":"0x0",
            "dscp":"0x10",
            "dscp_mask":"0x3f",
            "ttl_start":"0x0",
            "ttl_end":"0x0",
            "tcp_flags":"0x0",
            "tcp_mask":"0x0",
            "ip_flags":"0x0",
            "ip_mask":"0x0",
            "src_port_start":"0x0",
            "src_port_end":"0x0",
            "dst_port_start":"0x0",
            "dst_port_end":"0x0",
            "result_action":{
               "remark_value":"0",
               "encap_value":"0",
               "qos_group":"0",
               "traffic_class":"0",
               "drop_precedence":"G",
               "overwrite_phb":"N",
               "overwrite_qos_group":"N",
               "overwrite_encap":"N",
               "overwrite_fwd_tag":"N",
               "meter_enabled":"Y",
               "meter_counter_offset":"1"
            }
         },
         2: {
            "class_id":"0x0",
            "ipv6_src_address":"::",
            "ipv6_src_mask":"::",
            "ipv6_dst_address":"::",
            "ipv6_dst_mask":"::",
            "protocol":"0x0",
            "protocol_mask":"0x0",
            "dscp":"0x28",
            "dscp_mask":"0x3f",
            "ttl_start":"0x0",
            "ttl_end":"0x0",
            "tcp_flags":"0x0",
            "tcp_mask":"0x0",
            "ip_flags":"0x0",
            "ip_mask":"0x0",
            "src_port_start":"0x0",
            "src_port_end":"0x0",
            "dst_port_start":"0x0",
            "dst_port_end":"0x0",
            "result_action":{
               "remark_value":"0",
               "encap_value":"0",
               "qos_group":"0",
               "traffic_class":"6",
               "drop_precedence":"G",
               "overwrite_phb":"Y",
               "overwrite_qos_group":"N",
               "overwrite_encap":"N",
               "overwrite_fwd_tag":"N",
               "meter_enabled":"Y",
               "meter_counter_offset":"2"
            }
         }
      }
   },
   "bind_information":{
      "asic":0,
      "port_type":"L3",
      "meter_type":"EXACT",
      "meter_set_oid":"0xE9A",
      "no_of_meters":4,
      "meter_set_info":{
         "0":{
            "cir":975000000,
            "eir":975000000,
            "profile_oid":"0xEA0",
            "action_profile_oid":"0x11B"
         },
         "1":{
            "cir":975000000,
            "eir":975000000,
            "profile_oid":"0xEA0",
            "action_profile_oid":"0x11B"
         },
         "2":{
            "cir":487500000,
            "eir":600000000,
            "profile_oid":"0xEA5",
            "action_profile_oid":"0xEA7"
         },
         "3":{
            "cir":0,
            "eir":0,
            "profile_oid":"0xFFFFFFFF",
            "action_profile_oid":"0xFFFFFFFF"
         }
      },
      "scheduler": {
         "asic": "Argon",
         "oid": "0x989"
      },
      "voq_set": {
         "base_voq_id": 1392,
         "device": 0,
         "empty": False,
         "flush": "Flush not active",
         "oid": "0x986",
         "size": 8,
         "state": "Active"
      },
      "port_oid":"0x983",
      "system_port_oid":"0x988",
      "speed":1000000000,
      "state":"Active",
      "trust":"DSCP"
   }
}