expected_output = {
    'component': {
        'smm': {
            'shared_memory_address': '0x700000000000',
            'size_kbytes': 1028,
            'used_kbytes': 5,
            'available_kbytes': 1023,
            'ref_count': 53,
        },
        'cli': {
            'shared_memory_address': '0x700000101000',
            'size_kbytes': 204804,
            'size_type': 'non_default',
            'used_kbytes': 132224,
            'available_kbytes': 72580,
            'ref_count': 12,
        },
        'uxrib-rnh': {
            'shared_memory_address': '0x70000c902000',
            'size_kbytes': 131076,
            'size_type': 'non_default',
            'used_kbytes': 96,
            'available_kbytes': 130980,
            'ref_count': 34,
        },
        'npacl': {
            'shared_memory_address': '0x700014903000',
            'size_kbytes': 4100,
            'size_type': 'non_default',
            'used_kbytes': 4,
            'available_kbytes': 4096,
            'ref_count': 2,
        },
        'urib': {
            'shared_memory_address': '0x700014d04000',
            'size_kbytes': 3072,
            'size_type': 'dynamic',
            'max_size_kbytes': 1572868,
            'used_kbytes': 2075,
            'available_kbytes': 997,
            'ref_count': 34,
        },
        'urib-pib': {
            'shared_memory_address': '0x700074d05000',
            'size_kbytes': 1028,
            'size_type': 'non_default',
            'used_kbytes': 381,
            'available_kbytes': 647,
            'ref_count': 34,
        },
        'urib-redist': {
            'shared_memory_address': '0x700074e06000',
            'size_kbytes': 5124,
            'size_type': 'non_default',
            'used_kbytes': 428,
            'available_kbytes': 4696,
            'ref_count': 34,
        },
        'urib-ufdm': {
            'shared_memory_address': '0x700075307000',
            'size_kbytes': 8196,
            'size_type': 'non_default',
            'used_kbytes': 833,
            'available_kbytes': 7363,
            'ref_count': 1,
        },
        'u6rib': {
            'shared_memory_address': '0x700075b08000',
            'size_kbytes': 3072,
            'size_type': 'dynamic',
            'max_size_kbytes': 786436,
            'used_kbytes': 1962,
            'available_kbytes': 1110,
            'ref_count': 26,
        },
        'u6rib-pib': {
            'shared_memory_address': '0x7000a5b09000',
            'size_kbytes': 1028,
            'size_type': 'non_default',
            'used_kbytes': 445,
            'available_kbytes': 583,
            'ref_count': 26,
        },
        'u6rib-notify': {
            'shared_memory_address': '0x7000a5c0a000',
            'size_kbytes': 4100,
            'size_type': 'non_default',
            'used_kbytes': 1022,
            'available_kbytes': 3078,
            'ref_count': 26,
        },
        'am': {
            'shared_memory_address': '0x7000a600b000',
            'size_kbytes': 1028,
            'size_type': 'non_default',
            'used_kbytes': 6,
            'available_kbytes': 1022,
            'ref_count': 12,
        },
        'am_lim': {
            'shared_memory_address': '0x7000a610c000',
            'size_kbytes': 68,
            'size_type': 'non_default',
            'used_kbytes': 2,
            'available_kbytes': 66,
            'ref_count': 12,
        },
        'icmpv6': {
            'shared_memory_address': '0x7000a611d000',
            'size_kbytes': 10244,
            'size_type': 'non_default',
            'used_kbytes': 9,
            'available_kbytes': 10235,
            'ref_count': 18,
        },
        'arp': {
            'shared_memory_address': '0x7000a6b1e000',
            'size_kbytes': 12292,
            'size_type': 'non_default',
            'used_kbytes': 77,
            'available_kbytes': 12215,
            'ref_count': 8,
        },
        'ip': {
            'shared_memory_address': '0x7000a771f000',
            'size_kbytes': 10244,
            'used_kbytes': 394,
            'available_kbytes': 9850,
            'ref_count': 31,
        },
        'ipv6': {
            'shared_memory_address': '0x7000a8120000',
            'size_kbytes': 16388,
            'size_type': 'non_default',
            'used_kbytes': 135,
            'available_kbytes': 16253,
            'ref_count': 19,
        },
        'rpm': {
            'shared_memory_address': '0x7000a9121000',
            'size_kbytes': 2048,
            'size_type': 'dynamic',
            'max_size_kbytes': 61444,
            'used_kbytes': 2,
            'available_kbytes': 2046,
            'ref_count': 16,
        },
        'mld': {
            'shared_memory_address': '0x7000acd22000',
            'size_kbytes': 68,
            'used_kbytes': 0,
            'available_kbytes': 68,
            'ref_count': 2,
        },
        'igmp': {
            'shared_memory_address': '0x7000acd33000',
            'size_kbytes': 3076,
            'used_kbytes': 0,
            'available_kbytes': 3076,
            'ref_count': 2,
        },
        'mrib': {
            'shared_memory_address': '0x7000ad034000',
            'size_kbytes': 3072,
            'size_type': 'dynamic',
            'max_size_kbytes': 59396,
            'used_kbytes': 810,
            'available_kbytes': 2262,
            'ref_count': 4,
        },
        'm6rib': {
            'shared_memory_address': '0x7000b0a35000',
            'size_kbytes': 3072,
            'size_type': 'dynamic',
            'max_size_kbytes': 10244,
            'used_kbytes': 937,
            'available_kbytes': 2135,
            'ref_count': 4,
        },
        'mrib-mfdm': {
            'shared_memory_address': '0x7000b1436000',
            'size_kbytes': 6148,
            'size_type': 'non_default',
            'used_kbytes': 0,
            'available_kbytes': 6148,
            'ref_count': 1,
        },
        'm6rib-mfdm': {
            'shared_memory_address': '0x7000b1a37000',
            'size_kbytes': 6148,
            'size_type': 'non_default',
            'used_kbytes': 0,
            'available_kbytes': 6148,
            'ref_count': 1,
        },
        'mcastfwdv6': {
            'shared_memory_address': '0x7000b2038000',
            'size_kbytes': 25604,
            'size_type': 'non_default',
            'used_kbytes': 22,
            'available_kbytes': 25582,
            'ref_count': 3,
        },
        'pim': {
            'shared_memory_address': '0x7000b3939000',
            'size_kbytes': 20484,
            'used_kbytes': 22,
            'available_kbytes': 20462,
            'ref_count': 4,
        },
        'pim_ipc': {
            'shared_memory_address': '0x7000b4d3a000',
            'size_kbytes': 2048,
            'size_type': 'dynamic',
            'max_size_kbytes': 25604,
            'used_kbytes': 1,
            'available_kbytes': 2047,
            'ref_count': 2,
        },
        'mcastfwd': {
            'shared_memory_address': '0x7000b663b000',
            'size_kbytes': 61444,
            'size_type': 'non_default',
            'used_kbytes': 657,
            'available_kbytes': 60787,
            'ref_count': 3,
        },
        'pim6': {
            'shared_memory_address': '0x7000ba23c000',
            'size_kbytes': 8196,
            'used_kbytes': 23,
            'available_kbytes': 8173,
            'ref_count': 4,
        },
        'pim6_ipc': {
            'shared_memory_address': '0x7000baa3d000',
            'size_kbytes': 2048,
            'size_type': 'dynamic',
            'max_size_kbytes': 25604,
            'used_kbytes': 1,
            'available_kbytes': 2047,
            'ref_count': 2,
        },
    },
    'shared_memory_totals': {
        'size_mb': 3041,
        'used_mb': 162,
        'available_mb': 2888,
    },
}
