expected_output = {
    'interface': {
        'GigabitEthernet1/0/1': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/10': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/11': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/12': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/13': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/2': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/3': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/4': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/5': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/6': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/7': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/8': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        },
        'GigabitEthernet1/0/9': {
            'breakout_support': 'not applicable',
            'broadcast_suppression': 'percentage(0-100)',
            'channel': 'yes',
            'cos_rewrite': 'yes',
            'dot1x': 'yes',
            'duplex': 'full,half,auto',
            'fast_start': 'yes',
            'flowcontrol': 'rx-(off,on,desired),tx-(none)',
            'inline_power': 'yes',
            'model': 'C9300-24P',
            'multicast_suppression': 'percentage(0-100)',
            'multiple_media_types': 'rj45',
            'portsecure': 'yes',
            'qos_scheduling': 'rx-(not configurable on per port basis), tx-(2p6q3t)',
            'span': 'source/destination',
            'speed': '10,100,1000,auto',
            'tos_rewrite': 'yes',
            'trunk_encap_type': '802.1Q',
            'trunk_mode': 'on,off,desirable,nonegotiate',
            'type': '10/100/1000BaseTX',
            'udld': 'yes',
            'unicast_suppression': 'percentage(0-100)',
        }
    }
}