expected_output = {
    "instance": {
        "default": {
            "vrf": {
                "L3VPN-0050": {
                    "address_family": {
                        "vpnv4": {
                            "default_vrf": "L3VPN-0050",
                            "prefixes": {
                                "10.4.1.0/24": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2467",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933597",
                                },
                                "10.44.105.0/24": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "6620",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933498",
                                },
                                "172.16.100.10/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2904",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933541",
                                },
                                "172.16.100.11/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2903",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933540",
                                },
                                "172.16.100.12/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2901",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933539",
                                },
                                "172.16.100.13/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "5466",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933538",
                                },
                                "172.16.100.14/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "5465",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933537",
                                },
                                "172.16.100.15/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "5464",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933536",
                                },
                                "172.16.100.16/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2914",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933551",
                                },
                                "172.16.100.17/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2913",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933550",
                                },
                                "172.16.100.18/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2912",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933549",
                                },
                                "172.16.100.19/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2911",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933548",
                                },
                                "172.16.100.2/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "community": "62000:2",
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2468",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933598",
                                },
                                "172.16.100.20/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2910",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933547",
                                },
                                "172.16.100.21/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2909",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933546",
                                },
                                "172.16.100.22/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2908",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933545",
                                },
                                "172.16.100.23/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2907",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933544",
                                },
                                "172.16.100.24/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2923",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933559",
                                },
                                "172.16.100.25/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2922",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933558",
                                },
                                "172.16.100.26/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2920",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933557",
                                },
                                "172.16.100.27/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2919",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933556",
                                },
                                "172.16.100.28/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2918",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933555",
                                },
                                "172.16.100.29/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2917",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933554",
                                },
                                "172.16.100.3/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "5463",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933535",
                                },
                                "172.16.100.30/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2916",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933553",
                                },
                                "172.16.100.31/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2915",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933552",
                                },
                                "172.16.100.32/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "6630",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933506",
                                },
                                "172.16.100.33/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "6629",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933505",
                                },
                                "172.16.100.34/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "6627",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933504",
                                },
                                "172.16.100.35/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "6626",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933503",
                                },
                                "172.16.100.36/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "6625",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933502",
                                },
                                "172.16.100.37/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "6624",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933501",
                                },
                                "172.16.100.38/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "6623",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933500",
                                },
                                "172.16.100.4/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "5462",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933534",
                                },
                                "172.16.100.5/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "5461",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933533",
                                },
                                "172.16.100.6/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "5460",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933532",
                                },
                                "172.16.100.7/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "5459",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933531",
                                },
                                "172.16.100.8/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2906",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933543",
                                },
                                "172.16.100.9/32": {
                                    "available_path": "1",
                                    "best_path": "1",
                                    "index": {
                                        1: {
                                            "ext_community": "RT:5918:50",
                                            "gateway": "192.168.10.253",
                                            "localpref": 100,
                                            "metric": 0,
                                            "mpls_labels": {
                                                "in": "2905",
                                                "out": "nolabel",
                                            },
                                            "next_hop": "192.168.10.253",
                                            "next_hop_via": "vrf L3VPN-0050",
                                            "origin_codes": "?",
                                            "originator": "192.168.10.253",
                                            "recipient_pathid": "0",
                                            "refresh_epoch": 1,
                                            "route_info": "62000",
                                            "status_codes": "*>",
                                            "transfer_pathid": "0x0",
                                            "update_group": 724,
                                        }
                                    },
                                    "paths": "1 available, best #1, table L3VPN-0050",
                                    "table_version": "16933542",
                                },
                            },
                            "route_distinguisher": "5918:50",
                        }
                    }
                }
            }
        }
    }
}
