expected_output = {
    "mounted_on": {
        "/bootflash": {
            "available": 2165508,
            "file_system": "/dev/sda3",
            "total": 3626964,
            "use_percent": 38,
            "used": 1275552,
        },
        "/bootflash_sup-remote": {
            "available": 2266904,
            "file_system": "127.1.1.4:/bootflash/",
            "total": 3705856,
            "use_percent": 36,
            "used": 1249040,
        },
        "/cgroup": {
            "available": 0,
            "file_system": "vdccontrol",
            "total": 0,
            "use_percent": 0,
            "used": 0,
        },
        "/debug": {
            "available": 5080,
            "file_system": "none",
            "total": 5120,
            "use_percent": 1,
            "used": 40,
        },
        "/debugfs": {
            "available": 0,
            "file_system": "nodev",
            "total": 0,
            "use_percent": 0,
            "used": 0,
        },
        "/dev/icam": {
            "available": 1048576,
            "file_system": "none",
            "total": 1048576,
            "use_percent": 0,
            "used": 0,
        },
        "/dev/mqueue": {
            "available": 0,
            "file_system": "none",
            "total": 0,
            "use_percent": 0,
            "used": 0,
        },
        "/dev/pts": {
            "available": 0,
            "file_system": "devpts",
            "total": 0,
            "use_percent": 0,
            "used": 0,
        },
        "/dev/shm": {
            "available": 2688216,
            "file_system": "none",
            "total": 3145728,
            "use_percent": 15,
            "used": 457512,
        },
        "/isan": {
            "available": 1282584,
            "file_system": "none",
            "total": 2359296,
            "use_percent": 46,
            "used": 1076712,
        },
        "/logflash": {
            "available": 14524688,
            "file_system": "/dev/sdc1",
            "total": 15463828,
            "use_percent": 2,
            "used": 151940,
        },
        "/logflash_sup-remote": {
            "available": 10556344,
            "file_system": "127.1.1.4:/logflash/",
            "total": 15358896,
            "use_percent": 28,
            "used": 4020680,
        },
        "/mnt/cfg/0": {
            "available": 70413,
            "file_system": "/dev/sda5",
            "total": 75231,
            "use_percent": 2,
            "used": 722,
        },
        "/mnt/cfg/1": {
            "available": 68528,
            "file_system": "/dev/sda6",
            "total": 73243,
            "use_percent": 2,
            "used": 722,
        },
        "/mnt/fwimg": {
            "available": 111501,
            "file_system": "/dev/sdb3",
            "total": 117827,
            "use_percent": 1,
            "used": 31,
        },
        "/mnt/plog": {
            "available": 223140,
            "file_system": "/dev/sdb1",
            "total": 238782,
            "use_percent": 2,
            "used": 3102,
        },
        "/mnt/pss": {
            "available": 18949,
            "file_system": "/dev/sda4",
            "total": 35567,
            "use_percent": 44,
            "used": 14570,
        },
        "/nxos/mts": {
            "available": 4194304,
            "file_system": "none",
            "total": 4194304,
            "use_percent": 0,
            "used": 0,
        },
        "/nxos/tmp": {
            "available": 101120,
            "file_system": "none",
            "total": 102400,
            "use_percent": 2,
            "used": 1280,
        },
        "/proc": {
            "available": 0,
            "file_system": "proc",
            "total": 0,
            "use_percent": 0,
            "used": 0,
        },
        "/proc/fs/nfsd": {
            "available": 0,
            "file_system": "nfsd",
            "total": 0,
            "use_percent": 0,
            "used": 0,
        },
        "/smack": {
            "available": 0,
            "file_system": "smackfs",
            "total": 0,
            "use_percent": 0,
            "used": 0,
        },
        "/sys": {
            "available": 0,
            "file_system": "none",
            "total": 0,
            "use_percent": 0,
            "used": 0,
        },
        "/sys/kernel/security": {
            "available": 0,
            "file_system": "securityfs",
            "total": 0,
            "use_percent": 0,
            "used": 0,
        },
        "/var": {
            "available": 50716,
            "file_system": "none",
            "total": 51200,
            "use_percent": 1,
            "used": 484,
        },
        "/var/home": {
            "available": 5120,
            "file_system": "none",
            "total": 5120,
            "use_percent": 0,
            "used": 0,
        },
        "/var/sysmgr": {
            "available": 3661196,
            "file_system": "none",
            "total": 3670016,
            "use_percent": 1,
            "used": 8820,
        },
        "/var/sysmgr/ftp": {
            "available": 806064,
            "file_system": "none",
            "total": 1048576,
            "use_percent": 24,
            "used": 242512,
        },
        "/var/sysmgr/ftp/debug_logs": {
            "available": 10240,
            "file_system": "none",
            "total": 10240,
            "use_percent": 0,
            "used": 0,
        },
        "/var/sysmgr/srv_logs": {
            "available": 307200,
            "file_system": "none",
            "total": 307200,
            "use_percent": 0,
            "used": 0,
        },
        "/var/sysmgr/startup-cfg": {
            "available": 403700,
            "file_system": "none",
            "total": 409600,
            "use_percent": 2,
            "used": 5900,
        },
        "/var/volatile/log": {
            "available": 50972,
            "file_system": "none",
            "total": 51200,
            "use_percent": 1,
            "used": 228,
        },
        "/var/volatile/log/fw": {
            "available": 1048576,
            "file_system": "none",
            "total": 1048576,
            "use_percent": 0,
            "used": 0,
        },
        "/var/volatile/tmp": {
            "available": 306912,
            "file_system": "none",
            "total": 307200,
            "use_percent": 1,
            "used": 288,
        },
        "/volatile": {
            "available": 1048576,
            "file_system": "none",
            "total": 1048576,
            "use_percent": 0,
            "used": 0,
        },
    }
}