expected_output = {
    "0/0/0/18": {
        "controller_state": "Up",
        "dom_data_status": "Not Applicable",
        "fec_state": "FEC ENABLED",
        "host_squelch_status": "Enable",
        "laser_state": "N/A",
        "led_state": "Off",
        "name": "Optics 0/0/0/18",
        "optics_status": {
            "alarm_status": {"detected_alarms": []},
            "configured_dgd_higher_threshold": "0.00 ps",
            "configured_osnr_lower_threshold": "0.00 dB",
            "configured_tx_power": "0.00 dBm",
            "lane": {
                "0": {
                    "laser_bias": "0.0 mA",
                    "output_frequency": "N/A",
                    "rx_power": "0.00 dBm",
                    "tx_power": "0.00 dBm",
                },
                "1": {
                    "laser_bias": "0.0 mA",
                    "output_frequency": "N/A",
                    "rx_power": "0.00 dBm",
                    "tx_power": "0.00 dBm",
                },
                "2": {
                    "laser_bias": "0.0 mA",
                    "output_frequency": "N/A",
                    "rx_power": "0.00 dBm",
                    "tx_power": "0.00 dBm",
                },
                "3": {
                    "laser_bias": "0.0 mA",
                    "output_frequency": "N/A",
                    "rx_power": "0.00 dBm",
                    "tx_power": "0.00 dBm",
                },
                "4": {
                    "laser_bias": "0.0 mA",
                    "output_frequency": "N/A",
                    "rx_power": "0.00 dBm",
                    "tx_power": "0.00 dBm",
                },
                "5": {
                    "laser_bias": "0.0 mA",
                    "output_frequency": "N/A",
                    "rx_power": "0.00 dBm",
                    "tx_power": "0.00 dBm",
                },
                "6": {
                    "laser_bias": "0.0 mA",
                    "output_frequency": "N/A",
                    "rx_power": "0.00 dBm",
                    "tx_power": "0.00 dBm",
                },
                "7": {
                    "laser_bias": "0.0 mA",
                    "output_frequency": "N/A",
                    "rx_power": "0.00 dBm",
                    "tx_power": "0.00 dBm",
                },
            },
            "loopback_host": "None",
            "loopback_media": "None",
            "los_lol_fault_status": {},
            "optics_type": "QSFPDD 400G PASSIVE COPPER",
            "performance_monitoring": "Disable",
            "polarization_parameters": "not supported by optics",
            "temperature": "0.00 Celsius",
            "threshold_values": {
                "LBC Threshold(mA)": {
                    "high_alarm": "0.00",
                    "high_warning": "0.00",
                    "low_alarm": "0.00",
                    "low_warning": "0.00",
                    "parameter": "LBC Threshold(mA)",
                },
                "Rx Power Threshold(dBm)": {
                    "high_alarm": "0.0",
                    "high_warning": "0.0",
                    "low_alarm": "0.0",
                    "low_warning": "0.0",
                    "parameter": "Rx Power Threshold(dBm)",
                },
                "Rx Power Threshold(mW)": {
                    "high_alarm": "1.0",
                    "high_warning": "1.0",
                    "low_alarm": "1.0",
                    "low_warning": "1.0",
                    "parameter": "Rx Power Threshold(mW)",
                },
                "Temp. Threshold(celsius)": {
                    "high_alarm": "0.00",
                    "high_warning": "0.00",
                    "low_alarm": "0.00",
                    "low_warning": "0.00",
                    "parameter": "Temp. Threshold(celsius)",
                },
                "Tx Power Threshold(dBm)": {
                    "high_alarm": "0.0",
                    "high_warning": "0.0",
                    "low_alarm": "0.0",
                    "low_warning": "0.0",
                    "parameter": "Tx Power Threshold(dBm)",
                },
                "Tx Power Threshold(mW)": {
                    "high_alarm": "1.0",
                    "high_warning": "1.0",
                    "low_alarm": "1.0",
                    "low_warning": "1.0",
                    "parameter": "Tx Power Threshold(mW)",
                },
                "Voltage Threshold(volt)": {
                    "high_alarm": "0.00",
                    "high_warning": "0.00",
                    "low_alarm": "0.00",
                    "low_warning": "0.00",
                    "parameter": "Voltage Threshold(volt)",
                },
            },
            "voltage": "0.00 V",
            "wavelength": "0.00 nm",
        },
        "power_mode": "Low",
        "transceiver_vendor_details": {
            "date_code": "18/04/27",
            "form_factor": "QSFP-DD",
            "name": "TE Connectivity",
            "optics_type": "QSFPDD 400G PASSIVE COPPER",
            "oui_number": "00.22.a7",
            "part_number": "2323766-2",
            "pid": "2323766-2",
            "rev_number": "2",
            "serial_number": "18169177",
            "vid": "2",
        },
        "transport_admin_state": "In Service",
    }
}