expected_output = {
    'our_address': {
        '21.1.1.2': {
            'neighbor_address': {
                '21.1.1.1': {
                    'demand_mode': 0,
                    'elapsed_time_watermarks': '0 0',
                    'elapsed_time_watermarks_last': 0,
                    'handle': 1,
                    'hello': 500,
                    'hello_hits': 544,
                    'holddown': 2561,
                    'holddown_hits': 0,
                    'interface': 'GigabitEthernet2',
                    'last_packet': {
                        'c_bit': 1,
                        'demand_bit': 0,
                        'diagnostic': 0,
                        'final_bit': 0,
                        'length': 24,
                        'min_echo_int': 0,
                        'min_rx_int': 500000,
                        'min_tx_int': 500000,
                        'multiplier': 6,
                        'my_discr': 16,
                        'poll_bit': 0,
                        'state_bit': 'Up',
                        'version': 1,
                        'your_discr': 4097,
                    },
                    'ld_rd': '4097/16',
                    'local_diag': 0,
                    'min_rx_int': 300000,
                    'min_tx_int': 500000,
                    'multiplier': 6,
                    'poll_bit': 0,
                    'received_min_rx_int': 500000,
                    'received_multiplier': 6,
                    'registered_protocols': ['OSPF', 'CEF'],
                    'rh_rs': 'Up',
                    'rx': {
                        'avg_int_ms': 503,
                        'count': 388,
                        'last_ms_ago': 439,
                        'max_int_ms': 1997,
                        'min_int_ms': 499,
                    },
                    'session': {
                        'echo_function': False,
                        'state': 'UP',
                    },
                    'session_host': 'Software',
                    'state': 'Up',
                    'tx': {
                        'avg_int_ms': 443,
                        'count': 442,
                        'last_ms_ago': 76,
                        'max_int_ms': 1823,
                        'min_int_ms': 3,
                    },
                    'up_time': '00:03:15',
                },
            },
        },
    },
}
				