expected_output = {
    'our_address': {
        'FE80::250:56FF:FE8D:E353': {
            'neighbor_address': {
                'FE80::250:56FF:FE8D:F8BB': {
                    'demand_mode': 0,
                    'elapsed_time_watermarks': '0 0',
                    'elapsed_time_watermarks_last': 0,
                    'handle': 2,
                    'hello': 500,
                    'hello_hits': 0,
                    'holddown': 0,
                    'holddown_hits': 0,
                    'interface': 'GigabitEthernet2',
                    'last_packet': {
                        'c_bit': 0,
                        'demand_bit': 0,
                        'diagnostic': 0,
                        'final_bit': 0,
                        'length': 24,
                        'min_echo_int': 0,
                        'min_rx_int': 500000,
                        'min_tx_int': 500000,
                        'multiplier': 6,
                        'my_discr': 17,
                        'poll_bit': 0,
                        'state_bit': 'Up',
                        'version': 1,
                        'your_discr': 1,
                    },
                    'ld_rd': '1/17',
                    'local_diag': 0,
                    'min_rx_int': 300000,
                    'min_tx_int': 500000,
                    'multiplier': 6,
                    'poll_bit': 0,
                    'received_min_rx_int': 500000,
                    'received_multiplier': 6,
                    'registered_protocols': ['OSPFv3', 'CEF'],
                    'rh_rs': 'Up',
                    'session': {
                        'echo_function': False,
                        'state': 'UP',
                    },
                    'session_host': 'Hardware',
                    'state': 'Up',
                    'up_time': '00:01:42',
                },
            },
        },
    },
}
				