expected_output = {
    "acl_oid":{
        1230:{
            "acl_commands":[
                "IDENTITY_CLIENT_POLICY",
                "OVERRIDE_VLAN",
                "DROP",
                "COUNTER",
                "IPV4_CLIENT_POLICY_APPLIED",
                "IPV6_CLIENT_POLICY_APPLIED"
            ],
            "acl_match_fields":[
                "SA",
                "VLAN_OUTER",
                "VRF_GID",
                "IPV4_SIP",
                "SOURCE_SYSTEM_PORT"
            ],
            "acl_p_oid":1229,
            "identity_key_p_oid":1009
        },
        1231:{
            "acl_commands":[
                "IDENTITY_CLIENT_POLICY",
                "OVERRIDE_VLAN",
                "DROP",
                "COUNTER",
                "IPV4_CLIENT_POLICY_APPLIED",
                "IPV6_CLIENT_POLICY_APPLIED"
            ],
            "acl_match_fields":[
                "SA",
                "VLAN_OUTER",
                "VRF_GID",
                "IPV4_SIP",
                "SOURCE_SYSTEM_PORT"
            ],
            "acl_p_oid":1223,
            "identity_key_p_oid":1008
        }
    }
}