expected_output = {
   "number_of_sensors":26,
   "sensors":{
      "DB_IR3570A_1":{
         "maximum_sensor_value":2,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":16
      },
      "DB_IR3570A_2":{
         "maximum_sensor_value":1,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":17
      },
      "DB_IR3570A_3":{
         "maximum_sensor_value":5,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":18
      },
      "DB_P0V6_VTT":{
         "maximum_sensor_value":1,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":25
      },
      "DB_P1V5":{
         "maximum_sensor_value":2,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":23
      },
      "DB_P2V5_VPP":{
         "maximum_sensor_value":3,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":21
      },
      "DB_P3V3":{
         "maximum_sensor_value":3,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":20
      },
      "DB_P5V":{
         "maximum_sensor_value":5,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":19
      },
      "DB_PVCCKRHV":{
         "maximum_sensor_value":1,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":24
      },
      "DB_PVCCSCFUSESUS":{
         "maximum_sensor_value":2,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":22
      },
      "DOPP_AVDD":{
         "maximum_sensor_value":1,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":3
      },
      "DOPP_VDD":{
         "maximum_sensor_value":1,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":2
      },
      "P12V":{
         "maximum_sensor_value":12,
         "normal_range_max":12,
         "normal_range_min":0,
         "sensor_id":7
      },
      "P12V_STBY":{
         "maximum_sensor_value":12,
         "normal_range_max":12,
         "normal_range_min":0,
         "sensor_id":5
      },
      "P1V1":{
         "maximum_sensor_value":2,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":15
      },
      "P1V2":{
         "maximum_sensor_value":1,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":14
      },
      "P1V5":{
         "maximum_sensor_value":1,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":13
      },
      "P1V8":{
         "maximum_sensor_value":2,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":12
      },
      "P2V5":{
         "maximum_sensor_value":2,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":11
      },
      "P3V3":{
         "maximum_sensor_value":3,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":4
      },
      "P3V3_IRC":{
         "maximum_sensor_value":3,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":10
      },
      "P3V3_STBY":{
         "maximum_sensor_value":3,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":6
      },
      "P5V":{
         "maximum_sensor_value":5,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":9
      },
      "P7V":{
         "maximum_sensor_value":12,
         "normal_range_max":7,
         "normal_range_min":0,
         "sensor_id":8
      },
      "P_1PHY_VDDA":{
         "maximum_sensor_value":1,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":0
      },
      "P_1PHY_VDDB":{
         "maximum_sensor_value":1,
         "normal_range_max":5,
         "normal_range_min":0,
         "sensor_id":1
      }
   }
}

