expected_output = { 
    'interfaces': {
        'eth0': {
            'state': 'on',
            'mac_addr': '50:00:00:01:00:00',
            'type': 'ethernet',
            "link_state": 'link up',
            'mtu': 1500,
            'auto_negotiation': 'on',
            'speed': '1000M',
            'ipv6_autoconfig': 'Not configured',
            'duplex': 'full',
            'monitor_mode': 'Not configured',
            'link_speed': 'Not configured',
            'comments': '',
            'ipv4_address': '10.10.1.1/24',
            'ipv6_address': 'Not Configured',
            'ipv6_local_link_address': 'Not Configured',
            'statistics' :{
                'tx_bytes': 4690,
                'tx_packets': 75,
                'tx_errors' : 0,
                'tx_dropped': 0,
                'tx_overruns': 0,
                'tx_carrier': 0,
                'rx_bytes': 2979,
                'rx_packets': 41,
                'rx_errors' : 0,
                'rx_dropped': 0,
                'rx_overruns': 0,
                'rx_frame': 0,
            }
        },
        'eth1': {
            'state': 'off',
            'mac_addr': '50:00:00:01:00:01',
            'type': 'ethernet',
            "link_state": 'link down',
            'mtu': 1500,
            'auto_negotiation': 'Not configured',
            'speed': '1000M',
            'ipv6_autoconfig': 'Not configured',
            'duplex': 'full',
            'monitor_mode': 'Not configured',
            'link_speed': 'Not configured',
            'comments': '',
            'ipv4_address': '192.168.1.1/24',
            'ipv6_address': 'Not Configured',
            'ipv6_local_link_address': 'Not Configured',
            'statistics' :{
                'tx_bytes': 0,
                'tx_packets': 0,
                'tx_errors' : 0,
                'tx_dropped': 0,
                'tx_overruns': 0,
                'tx_carrier': 0,

                'rx_bytes': 0,
                'rx_packets': 0,
                'rx_errors' : 0,
                'rx_dropped': 0,
                'rx_overruns': 0,
                'rx_frame': 0,
            },
            'alias': {
                'eth1:1': {
                    'state': 'on',
                    'ipv4_address': '192.168.1.254/24'
                }
            }
        },
        'eth2': {
            'state': 'off',
            'mac_addr': '50:00:00:01:00:02',
            'type': 'ethernet',
            "link_state": 'link down',
            'mtu': 1500,
            'auto_negotiation': 'Not configured',
            'speed': '1000M',
            'ipv6_autoconfig': 'Not configured',
            'duplex': 'full',
            'monitor_mode': 'Not configured',
            'link_speed': 'Not configured',
            'comments': '',
            'ipv4_address': 'Not Configured',
            'ipv6_address': 'Not Configured',
            'ipv6_local_link_address': 'Not Configured',
            'statistics' :{
                'tx_bytes': 0,
                'tx_packets': 0,
                'tx_errors' : 0,
                'tx_dropped': 0,
                'tx_overruns': 0,
                'tx_carrier': 0,
                'rx_bytes': 0,
                'rx_packets': 0,
                'rx_errors' : 0,
                'rx_dropped': 0,
                'rx_overruns': 0,
                'rx_frame': 0,
            }
        },
        'eth3': {
            'state': 'off',
            'mac_addr': '50:00:00:01:00:03',
            'type': 'ethernet',
            "link_state": 'link down',
            'mtu': 1500,
            'auto_negotiation': 'Not configured',
            'speed': '1000M',
            'ipv6_autoconfig': 'Not configured',
            'duplex': 'full',
            'monitor_mode': 'Not configured',
            'link_speed': 'Not configured',
            'comments': '',
            'ipv4_address': 'Not Configured',
            'ipv6_address': 'Not Configured',
            'ipv6_local_link_address': 'Not Configured',
            'statistics' :{
                'tx_bytes': 0,
                'tx_packets': 0,
                'tx_errors' : 0,
                'tx_dropped': 0,
                'tx_overruns': 0,
                'tx_carrier': 0,
                'rx_bytes': 0,
                'rx_packets': 0,
                'rx_errors' : 0,
                'rx_dropped': 0,
                'rx_overruns': 0,
                'rx_frame': 0,
                }
            },
        'lo': {
            'state': 'on',
            'mac_addr': 'Not configured',
            'type': 'loopback',
            "link_state": 'not available',
            'mtu': 65536,
            'auto_negotiation': 'Not configured',
            'speed': 'N/A',
            'ipv6_autoconfig': 'Not configured',
            'duplex': 'N/A',
            'monitor_mode': 'Not configured',
            'link_speed': 'Not configured',
            'comments': '',
            'ipv4_address': '127.0.0.1/8',
            'ipv6_address': 'Not Configured',
            'ipv6_local_link_address': 'Not Configured',
            'statistics' :{
                'tx_bytes': 697645950,
                'tx_packets': 4311173,
                'tx_errors' : 0,
                'tx_dropped': 0,
                'tx_overruns': 0,
                'tx_carrier': 0,
                'rx_bytes': 697645950,
                'rx_packets': 4311173,
                'rx_errors' : 0,
                'rx_dropped': 0,
                'rx_overruns': 0,
                'rx_frame': 0,
            }
        }
    }
}
