expected_output = {
    "ap_count": 61,
    "base_mac": {
        "706d.0598.6fc0": {
            "visitors_mac": "706d.0598.0320",
            "ap_name": "AP706d.0598.0320",
            "ip_address": "10.10.116.22",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.0544.d2c0": {
            "visitors_mac": "706d.0544.1bf0",
            "ap_name": "visitors-hydra",
            "ip_address": "10.10.78.156",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.0544.d580": {
            "visitors_mac": "706d.0544.1ca0",
            "ap_name": "visitors-hydra",
            "ip_address": "10.10.82.200",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "0042.5a0a.1fb0": {
            "visitors_mac": "006b.f116.0ff0",
            "ap_name": "visitors-1815i",
            "ip_address": "10.10.139.90",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.0593.aac0": {
            "visitors_mac": "706d.0592.5148",
            "ap_name": "visitors-hydra2",
            "ip_address": "10.10.36.138",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.0593.ae20": {
            "visitors_mac": "706d.0592.5220",
            "ap_name": "visitors-hydra5",
            "ip_address": "10.10.36.138",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "00be.7506.42c0": {
            "visitors_mac": "706d.0568.44d0",
            "ap_name": "visitors-1815t",
            "ip_address": "10.10.236.197",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.05be.6890": {
            "visitors_mac": "706d.053e.e3f0",
            "ap_name": "visitors-1815i",
            "ip_address": "10.10.152.239",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.05be.adc0": {
            "visitors_mac": "706d.053e.f540",
            "ap_name": "visitors-mallorca",
            "ip_address": "10.10.40.15",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.05be.bc20": {
            "visitors_mac": "706d.053e.f8d8",
            "ap_name": "visitors-mallorca",
            "ip_address": "10.10.7.234",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.0527.bfd0": {
            "visitors_mac": "cc46.d6ff.b950",
            "ap_name": "visitors-homeap2",
            "ip_address": "10.10.216.231",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.052e.06a0": {
            "visitors_mac": "706d.052d.dd68",
            "ap_name": "visitors-hydra",
            "ip_address": "10.10.179.53",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "0c75.bd0d.5720": {
            "visitors_mac": "0c75.bd0d.4088",
            "ap_name": "visitors-farallon",
            "ip_address": "10.10.7.79",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "38ed.18cd.df40": {
            "visitors_mac": "38ed.18cc.5e30",
            "ap_name": "visitors-1852i",
            "ip_address": "10.10.158.77",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.3760": {
            "visitors_mac": "706d.05ec.e0ec",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.58.181",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.a320": {
            "visitors_mac": "706d.05ec.ee64",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.151.70",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.a8a0": {
            "visitors_mac": "706d.05ec.ef14",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.103.177",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.c500": {
            "visitors_mac": "706d.05ec.f2a0",
            "ap_name": "visitors-9105i",
            "ip_address": "10.10.171.95",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.d2a0": {
            "visitors_mac": "706d.05ec.f454",
            "ap_name": "visitors-9105i",
            "ip_address": "10.10.0.165",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.e720": {
            "visitors_mac": "706d.05ec.f6e4",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.36.57",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.e7a0": {
            "visitors_mac": "706d.05ec.f6f4",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.76.103",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.e7e0": {
            "visitors_mac": "706d.05ec.f6fc",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.224.136",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.e9c0": {
            "visitors_mac": "706d.05ec.f738",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.20.10",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.ea00": {
            "visitors_mac": "706d.05ec.f740",
            "ap_name": "visitors-9105w-LivingRM",
            "ip_address": "10.10.126.254",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.ec80": {
            "visitors_mac": "706d.05ec.f790",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.207.95",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.eee0": {
            "visitors_mac": "706d.05ec.f7dc",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.250.152",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.f0a0": {
            "visitors_mac": "706d.05ec.f814",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.238.57",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.f0c0": {
            "visitors_mac": "706d.05ec.f818",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.176.163",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.f2e0": {
            "visitors_mac": "706d.05ec.f85c",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.172.168",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.f3a0": {
            "visitors_mac": "706d.05ec.f874",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.223.162",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.f480": {
            "visitors_mac": "706d.05ec.f890",
            "ap_name": "visitors-9105w-GuestBD",
            "ip_address": "10.10.126.254",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.f8c0": {
            "visitors_mac": "706d.05ec.f918",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.208.150",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.f900": {
            "visitors_mac": "706d.05ec.f920",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.124.162",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.f920": {
            "visitors_mac": "706d.05ec.f924",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.150.239",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.f9c0": {
            "visitors_mac": "706d.05ec.f938",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.198.166",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.fa40": {
            "visitors_mac": "706d.05ec.f948",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.108.120",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.fcc0": {
            "visitors_mac": "706d.05ec.f998",
            "ap_name": "visitors-c9105",
            "ip_address": "10.10.40.223",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053a.fda0": {
            "visitors_mac": "706d.05ec.f9b4",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.71.91",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.0180": {
            "visitors_mac": "706d.05ec.fa30",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.100.242",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.04e0": {
            "visitors_mac": "706d.05ec.fa9c",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.23.46",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.0720": {
            "visitors_mac": "706d.05ec.fae4",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.105.129",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.0b00": {
            "visitors_mac": "706d.05ec.fb60",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.194.10",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.0d20": {
            "visitors_mac": "706d.05ec.fba4",
            "ap_name": "visitors-9105w",
            "ip_address": "10.108.195.48",
            "status": "Not Joined",
            "failure_phase": "Image-Download",
            "disconnect_reason": "Max Retransmission to AP",
        },
        "706d.053b.0f00": {
            "visitors_mac": "706d.05ec.fbe0",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.12.253",
            "status": "Not Joined",
            "failure_phase": "Image-Download",
            "disconnect_reason": "DTLS close alert from peer",
        },
        "706d.053b.0f20": {
            "visitors_mac": "706d.05ec.fbe4",
            "ap_name": "visitors-9105w-MB",
            "ip_address": "10.10.126.254",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.1040": {
            "visitors_mac": "706d.05ec.fc08",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.88.6",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.12a0": {
            "visitors_mac": "706d.05ec.fc54",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.138.94",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.36a0": {
            "visitors_mac": "706d.05ed.00d4",
            "ap_name": "visitors-9105w",
            "ip_address": "10.10.187.149",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.3d40": {
            "visitors_mac": "706d.05ed.01a8",
            "ap_name": "visitors-9105i",
            "ip_address": "10.10.238.103",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.3de0": {
            "visitors_mac": "706d.05ed.01bc",
            "ap_name": "visitors-9105i",
            "ip_address": "10.10.108.120",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.3ee0": {
            "visitors_mac": "706d.05ed.01dc",
            "ap_name": "visitors-9105i",
            "ip_address": "10.10.223.201",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.4060": {
            "visitors_mac": "706d.05ed.020c",
            "ap_name": "visitors-9105i",
            "ip_address": "10.10.102.15",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.053b.40c0": {
            "visitors_mac": "706d.05ed.0218",
            "ap_name": "visitors-9105i",
            "ip_address": "10.10.126.254",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.05c4.7980": {
            "visitors_mac": "706d.05e9.d9a8",
            "ap_name": "visitors-1815t",
            "ip_address": "10.10.239.55",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.05c4.9a40": {
            "visitors_mac": "706d.05e9.e1d8",
            "ap_name": "visitors-1815t",
            "ip_address": "10.10.42.87",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "706d.05c4.b3c0": {
            "visitors_mac": "706d.05e9.e838",
            "ap_name": "visitors-1815t",
            "ip_address": "10.10.112.32",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "5087.89a3.ad30": {
            "visitors_mac": "5087.8991.dc14",
            "ap_name": "visitors-homeap",
            "ip_address": "10.10.20.42",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "5087.89fc.3910": {
            "visitors_mac": "5087.89be.5c1c",
            "ap_name": "visitors-homeap",
            "ip_address": "10.10.67.248",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "7079.b3a8.4760": {
            "visitors_mac": "7079.b36b.2768",
            "ap_name": "visitors-1815t",
            "ip_address": "10.10.198.198",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "b4a4.e3cb.7cd0": {
            "visitors_mac": "1cdf.0fcb.1dbe",
            "ap_name": "visitors-homeap",
            "ip_address": "10.10.135.61",
            "status": "Not Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
        "f07f.06b2.77b0": {
            "visitors_mac": "f07f.06a0.d470",
            "ap_name": "visitors-CAP3702i",
            "ip_address": "10.10.27.77",
            "status": "Joined",
            "failure_phase": "Join",
            "disconnect_reason": "Ap auth pending",
        },
    },
}
