expected_output = {'cts_policy_server_details': {'cts-auto-cls1-ise1.cisco.com': {'app_content_type': 'json',
                                                                'domain_name': {'cts-auto-cls1-ise1.cisco.com': 'unreachable'},
                                                                'ipv4_address': {'10.76.119.180': 'unreachable',
                                                                                '10.10.10.2': 'unreachable',
                                                                                 '10.10.10.3': 'NA'},
                                                                'ipv6_address': {'2000::20': 'reachable',
                                                                                 '2000::21': 'unreachable'},
                                                                'port_num': 9063,
                                                                'retransmit_count': 3,
                                                                'server_status': 'inactive',
                                                                'timeout': 15,
                                                                'trustpoint': 'cts_tp_cts-auto-cls1-ise1.cisco.com_0',
                                                                'trustpoint_chain': 'not '
                                                                                    'configured'},
                               'cts-auto-cls1-ise2.cisco.com': {'app_content_type': 'json',
                                                                'domain_name': {'cts-auto-cls1-ise2.cisco.com': 'reachable'},
                                                                'ipv4_address': {'10.76.119.179': 'reachable'},
                                                                'port_num': 9063,
                                                                'retransmit_count': 3,
                                                                'server_status': 'active',
                                                                'timeout': 15,
                                                                'trustpoint': 'cts_tp_cts-auto-cls1-ise2.cisco.com_1',
                                                                'trustpoint_chain': 'not '
                                                                                    'configured'},
                               'cts-auto-cls1-ise3.cisco.com': {'app_content_type': 'json',
                                                                'domain_name': {'cts-auto-cls1-ise3.cisco.com': 'reachable'},
                                                                'ipv4_address': {'10.76.119.181': 'reachable'},
                                                                'port_num': 9063,
                                                                'retransmit_count': 3,
                                                                'server_status': 'inactive',
                                                                'timeout': 15,
                                                                'trustpoint': 'cts_tp_cts-auto-cls1-ise3.cisco.com_2',
                                                                'trustpoint_chain': 'not '
                                                                                    'configured'},
                               'dt-ise': {'app_content_type': 'json',
                                          'ipv4_address': {'10.76.119.180': 'reachable'},
                                          'port_num': 9063,
                                          'retransmit_count': 3,
                                          'server_status': 'inactive',
                                          'timeout': 15,
                                          'trustpoint': 'tp246',
                                          'trustpoint_chain': 'not '
                                                              'configured'}}

}