expected_output = {
    "interfaces": {
        "GigabitEthernet0/0": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/1": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/2": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/2.90": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/2.110": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/2.115": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/2.120": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/2.390": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/2.410": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/2.415": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/2.420": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/3": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/3.90": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/3.110": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/3.115": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/3.120": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/3.390": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/3.410": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/3.415": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet0/3.420": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet1/0": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet1/1": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet1/2": {"description": "", "protocol": "up", "status": "up"},
        "GigabitEthernet1/3": {"description": "", "protocol": "up", "status": "up"},
        "Loopback0": {"description": "", "protocol": "up", "status": "up"},
        "Loopback300": {"description": "", "protocol": "up", "status": "up"},
        "Port-channel12": {"description": "", "protocol": "up", "status": "up"},
        "Port-channel13": {"description": "", "protocol": "up", "status": "up"},
        "Tunnel0": {
            "description": "Pim Register Tunnel (Encap) for RP 2001:2:2:2::2",
            "protocol": "up",
            "status": "up",
        },
        "Tunnel1": {
            "description": "Pim Register Tunnel (Encap) for Embedded RP",
            "protocol": "up",
            "status": "up",
        },
        "Tunnel2": {
            "description": "Pim Register Tunnel (Encap) for RP 10.16.2.2",
            "protocol": "up",
            "status": "up",
        },
        "Tunnel3": {
            "description": "Pim Register Tunnel (Encap) for RP 10.16.2.2 on VRF VRF1",
            "protocol": "up",
            "status": "up",
        },
        "Tunnel4": {
            "description": "Pim Register Tunnel (Decap) for RP 10.4.1.1 on VRF VRF1",
            "protocol": "up",
            "status": "up",
        },
        "Tunnel5": {
            "description": "Pim Register Tunnel (Decap) for RP 10.4.1.1",
            "protocol": "up",
            "status": "up",
        },
        "Tunnel6": {
            "description": "Pim Register Tunnel (Encap) for RP 10.4.1.1 on VRF VRF1",
            "protocol": "up",
            "status": "up",
        },
        "Tunnel7": {
            "description": "Pim Register Tunnel (Encap) for RP 10.4.1.1",
            "protocol": "up",
            "status": "up",
        },
    }
}
