expected_output = {
    "interfaces":{
       "TwentyFiveGigE1/0/1":{
          "transceiver":"internally calibrated.",
          "Temp":{
             "Value":27.1,
             "HighAlarmThreshold":90.0,
             "HighWarnThreshold":85.0,
             "LowWarnThreshold":-5.0,
             "LowAlarmThreshold":-10.0
          },
          "Voltage":{
             "Value":3.31,
             "HighAlarmThreshold":3.6,
             "HighWarnThreshold":3.5,
             "LowWarnThreshold":3.05,
             "LowAlarmThreshold":3.0
          },
          "Current":{
             "Value":5.9,
             "HighAlarmThreshold":50.0,
             "HighWarnThreshold":40.0,
             "LowWarnThreshold":2.0,
             "LowAlarmThreshold":1.0
          },
          "OpticalTX":{
             "Value":-2.5,
             "HighAlarmThreshold":1.0,
             "HighWarnThreshold":0.0,
             "LowWarnThreshold":-8.3,
             "LowAlarmThreshold":-9.3
          },
          "OpticalRX":{
             "Value":-3.2,
             "HighAlarmThreshold":1.0,
             "HighWarnThreshold":0.0,
             "LowWarnThreshold":-12.1,
             "LowAlarmThreshold":-13.1
          }
       }
    }
 } 
