expected_output = {
    "GigabitEthernet0/0/0/0": {
        "int_status": "up",
        "ipv4": {
            "10.1.3.1/24": {"ip": "10.1.3.1", "prefix_length": "24"},
            "broadcast_forwarding": "disabled",
            "icmp_redirects": "never sent",
            "icmp_replies": "never sent",
            "icmp_unreachables": "always sent",
            "mtu": 1514,
            "mtu_available": 1500,
            "proxy_arp": "disabled",
            "table_id": "0xe0000000",
        },
        "multicast_groups": [
            "224.0.0.2",
            "224.0.0.1",
            "224.0.0.2",
            "224.0.0.5",
            "224.0.0.6",
        ],
        "oper_status": "up",
        "vrf": "default",
        "vrf_id": "0x60000000",
    },
    "GigabitEthernet0/0/0/1": {
        "int_status": "up",
        "ipv4": {
            "10.1.5.1/24": {"ip": "10.1.5.1", "prefix_length": "24", "route_tag": 50},
            "10.2.2.2/24": {"ip": "10.2.2.2", "prefix_length": "24", "secondary": True},
            "broadcast_forwarding": "disabled",
            "icmp_redirects": "never sent",
            "icmp_replies": "never sent",
            "icmp_unreachables": "always sent",
            "mtu": 1514,
            "mtu_available": 1500,
            "proxy_arp": "disabled",
            "table_id": "0xe0000010",
        },
        "multicast_groups": ["224.0.0.2", "224.0.0.1"],
        "oper_status": "up",
        "vrf": "VRF1",
        "vrf_id": "0x60000001",
    },
    "GigabitEthernet0/0/0/2": {
        "int_status": "up",
        "ipv4": {
            "10.186.5.1/24": {"ip": "10.186.5.1", "prefix_length": "24"},
            "broadcast_forwarding": "disabled",
            "icmp_redirects": "never sent",
            "icmp_replies": "never sent",
            "icmp_unreachables": "always sent",
            "mtu": 1514,
            "mtu_available": 1500,
            "proxy_arp": "disabled",
            "table_id": "0xe0000011",
        },
        "multicast_groups": ["224.0.0.2", "224.0.0.1"],
        "oper_status": "up",
        "vrf": "VRF2",
        "vrf_id": "0x60000002",
    },
    "GigabitEthernet0/0/0/3": {
        "int_status": "up",
        "ipv4": {
            "10.1.2.1/24": {"ip": "10.1.2.1", "prefix_length": "24"},
            "broadcast_forwarding": "disabled",
            "icmp_redirects": "never sent",
            "icmp_replies": "never sent",
            "icmp_unreachables": "always sent",
            "mtu": 1514,
            "mtu_available": 1500,
            "proxy_arp": "disabled",
            "table_id": "0xe0000000",
        },
        "multicast_groups": [
            "224.0.0.2",
            "224.0.0.1",
            "224.0.0.2",
            "224.0.0.5",
            "224.0.0.6",
        ],
        "oper_status": "up",
        "vrf": "default",
        "vrf_id": "0x60000000",
    },
    "GigabitEthernet0/0/0/4": {
        "int_status": "up",
        "ipv4": {
            "10.69.111.111/32": {"ip": "10.69.111.111", "prefix_length": "32"},
            "broadcast_forwarding": "disabled",
            "icmp_redirects": "never sent",
            "icmp_replies": "never sent",
            "icmp_unreachables": "always sent",
            "mtu": 1514,
            "mtu_available": 1500,
            "proxy_arp": "disabled",
            "table_id": "0xe0000000",
            "unnumbered": {"unnumbered_intf_ref": "Loopback11"},
        },
        "multicast_groups": ["224.0.0.2", "224.0.0.1"],
        "oper_status": "up",
        "vrf": "default",
        "vrf_id": "0x60000000",
    },
    "GigabitEthernet0/0/0/5": {
        "int_status": "shutdown",
        "oper_status": "down",
        "vrf": "default",
        "vrf_id": "0x60000000",
    },
    "GigabitEthernet0/0/0/6": {
        "int_status": "shutdown",
        "oper_status": "down",
        "vrf": "default",
        "vrf_id": "0x60000000",
    },
    "Loopback0": {
        "int_status": "up",
        "ipv4": {
            "10.4.1.1/32": {"ip": "10.4.1.1", "prefix_length": "32"},
            "broadcast_forwarding": "disabled",
            "icmp_redirects": "never sent",
            "icmp_replies": "never sent",
            "icmp_unreachables": "always sent",
            "mtu": 1500,
            "mtu_available": 1500,
            "proxy_arp": "disabled",
            "table_id": "0xe0000000",
        },
        "oper_status": "up",
        "vrf": "default",
        "vrf_id": "0x60000000",
    },
    "Loopback11": {
        "int_status": "up",
        "ipv4": {
            "10.69.111.111/32": {"ip": "10.69.111.111", "prefix_length": "32"},
            "broadcast_forwarding": "disabled",
            "icmp_redirects": "never sent",
            "icmp_replies": "never sent",
            "icmp_unreachables": "always sent",
            "mtu": 1500,
            "mtu_available": 1500,
            "proxy_arp": "disabled",
            "table_id": "0xe0000000",
        },
        "oper_status": "up",
        "vrf": "default",
        "vrf_id": "0x60000000",
    },
    "MgmtEth0/0/CPU0/0": {
        "int_status": "shutdown",
        "oper_status": "down",
        "vrf": "default",
        "vrf_id": "0x60000000",
    },
}
