expected_output = {
    "bgp-information": {
        "group-count": "14",
        "peer-count": "19",
        "bgp-peer": [
            {
                "flap-count": "0",
                "peer-address": "10.49.216.179",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Connect",
                "input-messages": "0",
            },
            {
                "flap-count": "127",
                "peer-address": "10.169.14.240",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "3w2d 4:19:15"},
                "peer-as": "65151",
                "output-messages": "221573",
                "bgp-rib": [
                    {
                        "received-prefix-count": "684",
                        "active-prefix-count": "682",
                        "name": "inet.0",
                        "suppressed-prefix-count": "0",
                        "accepted-prefix-count": "684",
                    },
                    {
                        "received-prefix-count": "2",
                        "active-prefix-count": "2",
                        "name": "inet.3",
                        "suppressed-prefix-count": "0",
                        "accepted-prefix-count": "2",
                    },
                ],
                "peer-state": "Establ",
                "input-messages": "280414",
            },
            {
                "flap-count": "0",
                "peer-address": "10.169.14.249",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65151",
                "output-messages": "0",
                "peer-state": "Active",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "10.189.5.240",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Connect",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "10.189.5.241",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Connect",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "10.189.5.242",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Active",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "10.189.5.243",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Active",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "10.189.5.245",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Active",
                "input-messages": "0",
            },
            {
                "flap-count": "44",
                "peer-address": "10.189.5.253",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "3w2d 4:18:45"},
                "peer-as": "65171",
                "output-messages": "172140",
                "bgp-rib": [
                    {
                        "received-prefix-count": "682",
                        "active-prefix-count": "0",
                        "name": "inet.0",
                        "suppressed-prefix-count": "0",
                        "accepted-prefix-count": "682",
                    }
                ],
                "peer-state": "Establ",
                "input-messages": "110832",
            },
            {
                "flap-count": "0",
                "peer-address": "10.189.6.250",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65181",
                "output-messages": "0",
                "peer-state": "Active",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "2001:db8:6be:89bb::1:140",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Connect",
                "input-messages": "0",
            },
            {
                "flap-count": "133",
                "peer-address": "2001:db8:eb18:ca45::1",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "3w2d 4:19:10"},
                "peer-as": "65151",
                "output-messages": "221571",
                "bgp-rib": [
                    {
                        "received-prefix-count": "0",
                        "active-prefix-count": "0",
                        "name": "inet6.0",
                        "suppressed-prefix-count": "0",
                        "accepted-prefix-count": "0",
                    }
                ],
                "peer-state": "Establ",
                "input-messages": "218994",
            },
            {
                "flap-count": "0",
                "peer-address": "2001:db8:eb18:ca45::11",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65151",
                "output-messages": "0",
                "peer-state": "Connect",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "2001:db8:223c:ca45::7",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Active",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "2001:db8:223c:ca45::8",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Connect",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "2001:db8:223c:ca45::9",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Connect",
                "input-messages": "0",
            },
            {
                "flap-count": "0",
                "peer-address": "2001:db8:223c:ca45::a",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65171",
                "output-messages": "0",
                "peer-state": "Connect",
                "input-messages": "0",
            },
            {
                "flap-count": "55",
                "peer-address": "2001:db8:223c:ca45::c",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "3w2d 4:27:54"},
                "peer-as": "65171",
                "output-messages": "110862",
                "bgp-rib": [
                    {
                        "received-prefix-count": "0",
                        "active-prefix-count": "0",
                        "name": "inet6.0",
                        "suppressed-prefix-count": "0",
                        "accepted-prefix-count": "0",
                    }
                ],
                "peer-state": "Establ",
                "input-messages": "110861",
            },
            {
                "flap-count": "0",
                "peer-address": "2001:db8:5961:ca45::1",
                "route-queue-count": "0",
                "elapsed-time": {"#text": "29w5d 22:42:36"},
                "peer-as": "65181",
                "output-messages": "0",
                "peer-state": "Connect",
                "input-messages": "0",
            },
        ],
        "bgp-rib": [
            {
                "active-prefix-count": "682",
                "total-prefix-count": "1366",
                "name": "inet.0",
                "damped-prefix-count": "0",
                "suppressed-prefix-count": "0",
                "pending-prefix-count": "0",
                "history-prefix-count": "0",
            },
            {
                "active-prefix-count": "2",
                "total-prefix-count": "2",
                "name": "inet.3",
                "damped-prefix-count": "0",
                "suppressed-prefix-count": "0",
                "pending-prefix-count": "0",
                "history-prefix-count": "0",
            },
            {
                "active-prefix-count": "0",
                "total-prefix-count": "0",
                "name": "inet6.0",
                "damped-prefix-count": "0",
                "suppressed-prefix-count": "0",
                "pending-prefix-count": "0",
                "history-prefix-count": "0",
            },
        ],
        "bgp-thread-mode": "BGP I/O",
        "down-peer-count": "15",
    }
}
