expected_output = {
        'slot': {
            '1': {
                'lc': {
                    'card_type': 'CEF720 48 port 10/100/1000mb Ethernet',
                    'fw_ver': '12.2(14r)S',
                    'hw_ver': '2.7',
                    'mac_address_from': '001e.4aff.ee89',
                    'mac_address_to': '001e.4aff.eeb8',
                    'model': 'WS-X6748-GE-TX',
                    'online_diag_status': 'Pass',
                    'ports': 48,
                    'slot': 1,
                    'serial_number': 'SAL1209HMW3',
                    'status': 'Ok',
                    'subslot': {
                        'WS-F6700-CFC': {
                            'hw_ver': '4.0',
                            'model': 'WS-F6700-CFC',
                            'serial_number': 'SAL1207G5V1',
                            'status': 'Ok',
                        },
                    },
                    'sw_ver': '15.4(0.10)',
                },
            },
            '2': {
                'lc': {
                    'card_type': '2 port adapter Enhanced FlexWAN',
                    'fw_ver': '15.4(0.10)S',
                    'hw_ver': '2.1',
                    'mac_address_from': '0015.2bff.e884',
                    'mac_address_to': '0015.2bff.e8c3',
                    'model': 'WS-X6582-2PA',
                    'online_diag_status': 'Pass',
                    'ports': 0,
                    'slot': 2,
                    'serial_number': 'JAE0939LYNQ',
                    'status': 'Ok',
                    'sw_ver': '15.4(0.10)S',
                },
            },
            '5': {
                'rp': {
                    'card_type': 'Supervisor Engine 720 (Hot)',
                    'fw_ver': '8.1(3',
                    'hw_ver': '4.1',
                    'mac_address_from': '0011.21ff.441a',
                    'mac_address_to': '0011.21ff.441d',
                    'model': 'WS-SUP720-3BXL',
                    'online_diag_status': 'Pass',
                    'ports': 2,
                    'slot': 5,
                    'serial_number': 'SAD09020BF8',
                    'status': 'Ok',
                    'subslot': {
                        'WS-F6K-PFC3BXL': {
                            'hw_ver': '1.4',
                            'model': 'WS-F6K-PFC3BXL',
                            'serial_number': 'SAD090301K6',
                            'status': 'Ok',
                        },
                        'WS-SUP720': {
                            'hw_ver': '2.2',
                            'model': 'WS-SUP720',
                            'serial_number': 'SAD090105M6',
                            'status': 'Ok',
                        },
                    },
                    'sw_ver': '15.4(0.10)',
                },
            },
            '6': {
                'rp': {
                    'card_type': 'Supervisor Engine 720 (Active)',
                    'fw_ver': '8.5(4',
                    'hw_ver': '5.12',
                    'mac_address_from': '0022.55ff.039b',
                    'mac_address_to': '0022.55ff.039e',
                    'model': 'WS-SUP720-3BXL',
                    'online_diag_status': 'Pass',
                    'ports': 2,
                    'slot': 6,
                    'serial_number': 'SAL15129MRC',
                    'status': 'Ok',
                    'subslot': {
                        'WS-F6K-PFC3BXL': {
                            'hw_ver': '1.11',
                            'model': 'WS-F6K-PFC3BXL',
                            'serial_number': 'SAL15129KW4',
                            'status': 'Ok',
                        },
                        'WS-SUP720': {
                            'hw_ver': '5.1',
                            'model': 'WS-SUP720',
                            'serial_number': 'SAL15045PYS',
                            'status': 'Ok',
                        },
                    },
                    'sw_ver': '15.4(0.10)',
                },
            },
        },
    }
