expected_output = {
    'entries_name': {
        'BFD ECHO IPv4': {
            'bytes_a': 2484,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'pkts_a': 22,
            'pkts_d': 0,
            'policy': 'system-cpp-police-bfd-v4',
            'pri': 19,
            'source': 'LPTSv4',
            'tc': 6
        },
        'BFD IPv4': {
            'bytes_a': 2484,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'pkts_a': 22,
            'pkts_d': 0,
            'policy': 'system-cpp-police-bfd-v4',
            'pri': 18,
            'source': 'LPTSv4',
            'tc': 6
        },
        'BFD MHOP IPv4': {
            'bytes_a': 2484,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'pkts_a': 22,
            'pkts_d': 0,
            'policy': 'system-cpp-police-bfd-v4',
            'pri': 20,
            'source': 'LPTSv4',
            'tc': 6
        },
        'BGP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-bgp-v4',
            'pri': 8,
            'source': 'LPTSv4',
            'tc': 5
        },
        'BGP established IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-bgp-v4',
            'pri': 9,
            'source': 'LPTSv4',
            'tc': 5
        },
        'DHCPv4 C to S': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-udp-v4',
            'pri': 24,
            'source': 'LPTSv4',
            'tc': 0
        },
        'DHCPv4 S to C': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-udp-v4',
            'pri': 25,
            'source': 'LPTSv4',
            'tc': 0
        },
        'DHCPv4 S to S': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-udp-v4',
            'pri': 23,
            'source': 'LPTSv4',
            'tc': 4
        },
        'DHCPv4 Server TCP Bulk Query': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-tcp-v4',
            'pri': 22,
            'source': 'LPTSv4',
            'tc': 4
        },
        'EIGRP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-igrp-v4',
            'pri': 11,
            'source': 'LPTSv4',
            'tc': 5
        },
        'GLBP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-fhrp-v4',
            'pri': 15,
            'source': 'LPTSv4',
            'tc': 4
        },
        'HSRP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-fhrp-v4',
            'pri': 14,
            'source': 'LPTSv4',
            'tc': 4
        },
        'ICMP IPv4': {
            'bytes_a': 600,
            'bytes_d': 0,
            'cir_hw': 2494,
            'cir_sw': 2500,
            'pkts_a': 5,
            'pkts_d': 0,
            'policy': 'system-cpp-police-icmp-v4',
            'pri': 1,
            'source': 'LPTSv4',
            'tc': 3
        },
        'IPV4 FRAGMENTATION': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 2494,
            'cir_sw': 2500,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-fragment-v4',
            'pri': 33,
            'source': 'LPTSv4',
            'tc': 3
        },
        'IPv4 IGMP': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-proto-snoop-v4',
            'pri': 31,
            'source': 'LPTSv4',
            'tc': 4
        },
        'IPv4 MC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-mcast-ctrl-v4',
            'pri': 32,
            'source': 'LPTSv4',
            'tc': 0
        },
        'IPv4 PIM Reg Mcast': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-mcast-register-v4',
            'pri': 30,
            'source': 'LPTSv4',
            'tc': 1
        },
        'LDP TCP DST IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-ldp-v4',
            'pri': 7,
            'source': 'LPTSv4',
            'tc': 5
        },
        'LDP TCP SRC IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-ldp-v4',
            'pri': 6,
            'source': 'LPTSv4',
            'tc': 5
        },
        'LDP UDP DST IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-ldp-v4',
            'pri': 5,
            'source': 'LPTSv4',
            'tc': 5
        },
        'LDP UDP SRC IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-ldp-v4',
            'pri': 4,
            'source': 'LPTSv4',
            'tc': 5
        },
        'MPLS OAM IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-mpls-oam',
            'pri': 21,
            'source': 'LPTSv4',
            'tc': 4
        },
        'OSPF v2 MC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-ospf-v4',
            'pri': 2,
            'source': 'LPTSv4',
            'tc': 5
        },
        'OSPF v2 UC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-ospf-v4',
            'pri': 3,
            'source': 'LPTSv4',
            'tc': 5
        },
        'PIM IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-mcast-ctrl-v4',
            'pri': 17,
            'source': 'LPTSv4',
            'tc': 4
        },
        'RIP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-rip-v4',
            'pri': 12,
            'source': 'LPTSv4',
            'tc': 5
        },
        'RSVP IPV4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-default-v4',
            'pri': 34,
            'source': 'LPTSv4',
            'tc': 5
        },
        'TCP DST PORT LISP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-lisp-ctrl',
            'pri': 29,
            'source': 'LPTSv4',
            'tc': 2
        },
        'TCP SRC PORT LISP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-lisp-ctrl',
            'pri': 28,
            'source': 'LPTSv4',
            'tc': 2
        },
        'TCP default IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-tcp-v4',
            'pri': 35,
            'source': 'LPTSv4',
            'tc': 2
        },
        'UDP DST PORT LISP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-lisp-ctrl',
            'pri': 27,
            'source': 'LPTSv4',
            'tc': 2
        },
        'UDP SRC PORT LISP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-lisp-ctrl',
            'pri': 26,
            'source': 'LPTSv4',
            'tc': 2
        },
        'UDP default IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-udp-v4',
            'pri': 36,
            'source': 'LPTSv4',
            'tc': 2
        },
        'VRRP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-police-fhrp-v4',
            'pri': 13,
            'source': 'LPTSv4',
            'tc': 4
        },
        'WCCP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'pkts_a': 0,
            'pkts_d': 0,
            'policy': 'system-cpp-default-v4',
            'pri': 16,
            'source': 'LPTSv4',
            'tc': 4
        }
    }
}