expected_output = {
        'index': {
            1: {
                'descr': 'c93xx Stack',
                'name': 'c93xx Stack',
                'pid': 'C9300-24T',
                'sn': 'FCW2347C0DB',
                'vid': 'V03',
            },
            2: {
                'descr': 'C9300-24T',
                'name': 'Switch 1',
                'pid': 'C9300-24T',
                'sn': 'FCW2347C0DB',
                'vid': 'V03',
            },
            3: {
                'descr': 'StackPort1/1',
                'name': 'StackPort1/1',
                'pid': 'STACK-T1-50CM',
                'sn': 'MOC2346A691',
                'vid': 'V01',
            },
            4: {
                'descr': 'StackPort1/2',
                'name': 'StackPort1/2',
                'pid': 'STACK-T1-50CM',
                'sn': 'MOC2346A69X',
                'vid': 'V01',
            },
            5: {
                'descr': 'Switch 1 - Power Supply A',
                'name': 'Switch 1 - Power Supply A',
                'pid': 'PWR-C1-350WAC-P',
                'sn': 'DCC2337B0K5',
                'vid': 'V01',
            },
            6: {
                'descr': '8x10G Uplink Module',
                'name': 'Switch 1 FRU Uplink Module 1',
                'pid': 'C9300-NM-8X',
                'sn': 'FOC23473K4U',
                'vid': 'V02',
            },
            7: {
                'descr': 'C9300-24T',
                'name': 'Switch 2',
                'pid': 'C9300-24T',
                'sn': 'FOC2347X0GE',
                'vid': 'V03',
            },
            8: {
                'descr': 'StackPort2/1',
                'name': 'StackPort2/1',
                'pid': 'STACK-T1-50CM',
                'sn': 'MOC2346A69X',
                'vid': 'V01',
            },
            9: {
                'descr': 'StackPort2/2',
                'name': 'StackPort2/2',
                'pid': 'STACK-T1-50CM',
                'sn': 'MOC2346A691',
                'vid': 'V01',
            },
            10: {
                'descr': 'Switch 2 - Power Supply A',
                'name': 'Switch 2 - Power Supply A',
                'pid': 'PWR-C1-350WAC-P',
                'sn': 'DCC2337B0HT',
                'vid': 'V01',
            },
            11: {
                'descr': '8x10G Uplink Module',
                'name': 'Switch 2 FRU Uplink Module 1',
                'pid': 'C9300-NM-8X',
                'sn': 'FOC23456CVT',
                'vid': 'V02',
            },
            12: {
                'descr': 'C9300-24T - Provisioned',
                'name': 'Switch 3',
                'pid': 'C9300-24T',
            },
        },
    }