expected_output={
 'ifm_feature_ref_counts': {
        'fid': '98 (AAL_FEATURE_L2_MULTICAST_IGMP)',
        'ref_count': 1,
    },
    'int_info': {
        'asic_num': 1,
        'blk_ptr': '0x7f16cd385568',
        'blk_state': 'READY',
        'client_if_id': '0x0000000013151bdb',
        'client_le': '0x7f16cd0caaa8',
        'client_type': 1,
        'create_time': '2022/09/29 12:17:16.343',
        'cur_time': '2022/09/29 12:29:36.705',
        'dns_punt': 'False',
        'if_id': '0x0000000013151bdb',
        'last_modfd_time': '2022/09/29 12:17:16.387',
        'mac': '001b.0c18.918d',
        'name': 'C320150491',
        'parent_if_id': '0x0000000000000020',
        'ref_count': 2,
        'ref_count_feature': '2 (feature Ref Counts + 1)',
        'state': 'Enabled',
        'status': 'ADD, UPD',
        'switch_num': 1,
        'type': 'WIRED_CLIENT',
    },
    'port_cts_subblk': {
        'disable_sgacl': '0x0',
        'port_sgt': '0xffff',
        'propagate': '0x0',
        'trust': '0x0',
    },
    'port_info': {
        'handle': '0x8b00013f',
        'identifier': '0x13151bdb',
        'type': 'Wired-client',
        'unit': '320150491',
    },
    'port_l2_subblk': {
        'allow_dot1q': 'No',
        'allow_native': 'No',
        'allow_priority_tag': 'No',
        'allow_unkn_bcast': 'No',
        'allow_unkn_mcast': 'Enabled',
        'allow_unkn_ucast': 'Enabled',
        'app_hosting': 'Disabled',
        'def_vlan': 0,
        'enabled': 'No',
        'ipv4_arp_snp': 'No',
        'ipv6_arp_snp': 'No',
        'jumbo_mtu': 0,
        'learning_mode': 0,
        'protected': 'No',
        'vepa': 'Disabled',
    },
    'port_logical_subblk': {
        'asic_num': '0x1',
        'client_le_handle': '0x7f16cd0caaa8',
        'client_mac': '1:0:0:0:0:0',
        'di_handle': 0,
        'dst_adj_handle': 0,
        'dst_lkp_handle': 0,
        'parent_identifier': '0x20',
        'rewr_type': '0x0',
        'ri_handle': 53,
        'src_adj_handle': '0x53',
        'src_lkp_handle': 0,
        'switch_num': '0x1',
    },
    'port_qos_subblk': {
        'def_value': 0,
        'egrs_tbl_map': '0x0',
        'ingrs_tbl_map': '0x0',
        'q_map': '0x0',
        'trust_type': '0x7',
    },
}
