

expected_output = {
    'segment_id': {
        '0001.00ff.aaab.00ff.0003': {
            'interface': {
                'Bundle-Ether3': {
                    'next_hops': ['10.154.219.84<'],
                    'es_to_bgp_gates': 'M',
                    'es_to_l2fib_gates': 'Ready',
                    'main_port': {
                        'interface': 'Bundle-Ether3',
                        'interface_mac': '00c1.64ff.a415',
                        'if_handle': '0x080002a0',
                        'state': 'Down',
                        'redundancy': 'Not Defined',
                    },
                    'esi': {
                        'type': '0',
                        'value': '01.0000.aaff.abab.0003',
                    },
                    'es_import_rt': 'aaab.00ff.0003 (Local)',
                    'source_mac': '0000.0000.0000 (N/A)',
                    'topology': {
                        'operational': 'SH',
                        'configured': 'All-active (AApF) (default)',
                    },
                    'service_carving': 'Auto-selection',
                    'peering_details': ['10.154.219.84[MOD:P:00][1]'],
                    'service_carving_results': {
                        'forwarders': 1,
                        'permanent': 0,
                        'elected': {
                            'num_of_total': 0,
                        },
                        'not_elected': {
                            'num_of_total': 1,
                        },
                    },
                    'mac_flushing_mode': 'STP-TCN',
                    'peering_timer': '3',
                    'recovery_timer': '30',
                    'carving_timer': '0',
                    'local_shg_label': '100564',
                    'remote_shg_labels': {
                        '0': {
                        },
                    },
                    'object': {
                        'EVPN ES': {
                            'base_info': {
                                'version': '0xdbdb0007',
                                'flags': '0x0',
                                'type': 7,
                                'reserved': 0,
                            },
                            'num_events': 55,
                            'event_history': {
                                1: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'ES DB Bind',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                2: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Create',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                3: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API Config Ifname Add',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                4: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                5: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API Config Local RT',
                                    'flag_1': '00000000',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                6: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'ES DB Bind',
                                    'flag_1': '00000000',
                                    'flag_2': '00010001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                7: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action L2FIB Instance Upd',
                                    'flag_1': '00000000',
                                    'flag_2': 'c1400000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                8: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                9: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API Config ESI complete',
                                    'flag_1': '00000000',
                                    'flag_2': '00000003',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                10: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API Provision',
                                    'flag_1': '00000000',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                11: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                12: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                13: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                14: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                15: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                16: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                17: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                18: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                19: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                20: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                21: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                22: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                23: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                24: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                25: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                26: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                27: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                28: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                29: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                30: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                31: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                32: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                33: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                34: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                35: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                36: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                37: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                38: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                39: {
                                    'time': 'Aug 27 09:46:04.160',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c014',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                40: {
                                    'time': 'Aug 27 09:46:04.160',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0140000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                41: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'ES DB Unbind - tid',
                                    'flag_1': '00100001',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                42: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Create RT',
                                    'flag_1': '00000000',
                                    'flag_2': 'aaab0000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                43: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Advertise RT',
                                    'flag_1': '00000000',
                                    'flag_2': '00010001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                44: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c8040000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                45: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'API BP Ifname update',
                                    'flag_1': '00000000',
                                    'flag_2': '03e803e8',
                                    'code_1': 'M',
                                    'code_2': '-',
                                },
                                46: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c8040000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                47: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'API BGP RID update',
                                    'flag_1': 'a5138011',
                                    'flag_2': '00011043',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                48: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'Action EAD/EVI',
                                    'flag_1': '00000add',
                                    'flag_2': '000103e8',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                49: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0040000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                50: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'API Recv LSD Local SHGLabel',
                                    'flag_1': '00000000',
                                    'flag_2': '000188d4',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                51: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'Action EAD/EVI',
                                    'flag_1': '00000add',
                                    'flag_2': '000103e8',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                52: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0040000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                53: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'API BGP mark / sweep',
                                    'flag_1': '00de1e7e',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                54: {
                                    'time': 'Aug 27 09:49:37.152',
                                    'event': 'Action L2FIB MP Info Upd',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                55: {
                                    'time': 'Aug 27 09:49:37.152',
                                    'event': 'API L2FIB Replay',
                                    'flag_1': '00000000',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                            },
                            'statistics': {
                                'rt': {
                                    'adv_cnt': 1,
                                    'adv_last_time': '27/08 09:49:15.582',
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'localbmac': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'esi': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'ead_es': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'ead_evi': {
                                    'adv_cnt': 2,
                                    'adv_last_time': '27/08 09:49:16.091',
                                    'adv_last_arg': '000003e8',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'mst_ag_vpw': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'df_electfw': {
                                    'adv_cnt': 1,
                                    'adv_last_time': '27/08 09:49:15.582',
                                    'adv_last_arg': '00000000',
                                },
                                'updatemac': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'macflushpe': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'macflushce': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'instance': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'mp_info': {
                                    'adv_cnt': 1,
                                    'adv_last_time': '27/08 09:49:37.024',
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                            },
                        },
                    },
                    'diagnostic_esi': 'N/A',
                    'interface_name': 'N/A',
                    'diagnostic_ifh': '0x00000000',
                    'diagnostic_flag': '0x00000043',
                    'diagnostic_es_rt': '0000.0000.0000',
                    'port_key': '0x000088d4',
                    'mac_winner': '1',
                    'number_of_evis': '1',
                    'recovery_timer_per_es': 'global',
                    'peering_timer_per_es': 'global',
                    'carving_timer_per_es': 'global',
                    'rt_advertised': '1',
                    'esi_advertised': '0',
                    'msti_state_mask': '0x0000',
                    'hrw_msti_set': '0x3',
                    'es_ead_pulse': '0',
                    'mp_advertised': '1',
                    'nve_anycastvtep': '0',
                    'nve_ingrreplic': '0',
                    'peering_done': '0',
                    'carving_done': '1',
                    'inval_redundfwd': '0x00000000/0x00000000',
                    'inval_redund_nh': '0x00000000/0x00000000',
                    'chkpt_objid': '0x0',
                    'es_ead_update': {
                        'num_rds': 0,
                    },
                },
            },
        },
        '0001.00ff.aaab.00ff.0004': {
            'interface': {
                'Bundle-Ether4': {
                    'next_hops': ['10.154.219.84<'],
                    'es_to_bgp_gates': 'Ready',
                    'es_to_l2fib_gates': 'Ready',
                    'main_port': {
                        'interface': 'Bundle-Ether4',
                        'interface_mac': '00c1.64ff.a414',
                        'if_handle': '0x080002e0',
                        'state': 'Up',
                        'redundancy': 'Not Defined',
                    },
                    'esi': {
                        'type': '0',
                        'value': '01.0000.aaff.abab.0004',
                    },
                    'es_import_rt': 'aaab.00ff.0004 (Local)',
                    'source_mac': '0000.0000.0000 (N/A)',
                    'topology': {
                        'operational': 'SH',
                        'configured': 'All-active (AApF) (default)',
                    },
                    'service_carving': 'Auto-selection',
                    'peering_details': ['10.154.219.84[MOD:P:00][1]'],
                    'service_carving_results': {
                        'forwarders': 1,
                        'permanent': 0,
                        'elected': {
                            'num_of_total': 1,
                        },
                        'not_elected': {
                            'num_of_total': 0,
                        },
                    },
                    'mac_flushing_mode': 'STP-TCN',
                    'peering_timer': '3',
                    'recovery_timer': '30',
                    'carving_timer': '0',
                    'local_shg_label': '100565',
                    'remote_shg_labels': {
                        '0': {
                        },
                    },
                    'object': {
                        'EVPN ES': {
                            'base_info': {
                                'version': '0xdbdb0007',
                                'flags': '0x0',
                                'type': 7,
                                'reserved': 0,
                            },
                            'num_events': 64,
                            'event_history': {
                                56: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API Config Ifname Add',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                57: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                58: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API Config Local RT',
                                    'flag_1': '00000000',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                59: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'ES DB Bind',
                                    'flag_1': '00000000',
                                    'flag_2': '00010001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                60: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action L2FIB Instance Upd',
                                    'flag_1': '00000000',
                                    'flag_2': 'c1400000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                61: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                62: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API Config ESI complete',
                                    'flag_1': '00000000',
                                    'flag_2': '00000003',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                63: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API Provision',
                                    'flag_1': '00000000',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                64: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                65: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                66: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                67: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                68: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                69: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                70: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                71: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                72: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                73: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                74: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                75: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                76: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                77: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                78: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                79: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                80: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                81: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                82: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                83: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                84: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                85: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                86: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                87: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                88: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                89: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                90: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c016',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                91: {
                                    'time': 'Aug 27 09:44:15.616',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0160000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                92: {
                                    'time': 'Aug 27 09:46:04.160',
                                    'event': 'Action Advertise MAC',
                                    'flag_1': '00000000',
                                    'flag_2': '0000c014',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                93: {
                                    'time': 'Aug 27 09:46:04.160',
                                    'event': 'API BGP Replay',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0140000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                94: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'ES DB Unbind - tid',
                                    'flag_1': '00100001',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                95: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Create RT',
                                    'flag_1': '00000000',
                                    'flag_2': 'aaab0000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                96: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Advertise RT',
                                    'flag_1': '00000000',
                                    'flag_2': '00010001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                97: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c8040000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                98: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'API BP Ifname update',
                                    'flag_1': '00000000',
                                    'flag_2': '03e803e8',
                                    'code_1': 'M',
                                    'code_2': '-',
                                },
                                99: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c8040000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                100: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'API BGP RID update',
                                    'flag_1': 'a5138011',
                                    'flag_2': '00011043',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                101: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'Action EAD/EVI',
                                    'flag_1': '00000add',
                                    'flag_2': '000103e8',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                102: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0040000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                103: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'API Recv LSD Local SHGLabel',
                                    'flag_1': '00000000',
                                    'flag_2': '000188d5',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                104: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'Action EAD/EVI',
                                    'flag_1': '00000add',
                                    'flag_2': '000103e8',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                105: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': 'c0040000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                106: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'API BGP mark / sweep',
                                    'flag_1': '00de1e7e',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                107: {
                                    'time': 'Aug 27 09:49:37.152',
                                    'event': 'Action L2FIB MP Info Upd',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                108: {
                                    'time': 'Aug 27 09:49:37.152',
                                    'event': 'API L2FIB Replay',
                                    'flag_1': '00000000',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                109: {
                                    'time': 'Aug 27 09:49:41.760',
                                    'event': 'Action L2FIB Instance Upd',
                                    'flag_1': '000f0001',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                110: {
                                    'time': 'Aug 27 09:49:41.760',
                                    'event': 'Action L2FIB MP Info Upd',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                111: {
                                    'time': 'Aug 27 09:49:41.760',
                                    'event': 'Action Advertise ESI',
                                    'flag_1': '00000000',
                                    'flag_2': '00010001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                112: {
                                    'time': 'Aug 27 09:49:41.760',
                                    'event': 'Action EAD/ES',
                                    'flag_1': '00000001',
                                    'flag_2': '000188d5',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                113: {
                                    'time': 'Aug 27 09:49:41.760',
                                    'event': 'Action EAD/EVI',
                                    'flag_1': '00000add',
                                    'flag_2': '000103e8',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                114: {
                                    'time': 'Aug 27 09:49:41.760',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                115: {
                                    'time': 'Aug 27 09:49:41.760',
                                    'event': 'API IM MP | AToM state',
                                    'flag_1': '00000000',
                                    'flag_2': '00320002',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                116: {
                                    'time': 'Aug 27 09:49:41.760',
                                    'event': 'Action EAD/ES',
                                    'flag_1': '00000add',
                                    'flag_2': '000b89d5',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                117: {
                                    'time': 'Aug 27 09:49:44.832',
                                    'event': 'Action L2FIB Instance Upd',
                                    'flag_1': '000f7fff',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                118: {
                                    'time': 'Aug 27 09:49:44.832',
                                    'event': 'Action L2FIB MP Info Upd',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                119: {
                                    'time': 'Aug 27 09:49:44.832',
                                    'event': 'API Peer Timer Expiry',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                            },
                            'statistics': {
                                'rt': {
                                    'adv_cnt': 1,
                                    'adv_last_time': '27/08 09:49:15.582',
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'localbmac': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'esi': {
                                    'adv_cnt': 1,
                                    'adv_last_time': '27/08 09:49:41.604',
                                    'adv_last_arg': '00000001',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'ead_es': {
                                    'adv_cnt': 1,
                                    'adv_last_time': '27/08 09:49:41.606',
                                    'adv_last_arg': '0000000a',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'ead_evi': {
                                    'adv_cnt': 3,
                                    'adv_last_time': '27/08 09:49:41.604',
                                    'adv_last_arg': '000003e8',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'mst_ag_vpw': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'df_electfw': {
                                    'adv_cnt': 1,
                                    'adv_last_time': '27/08 09:49:15.582',
                                    'adv_last_arg': '00000000',
                                },
                                'updatemac': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'macflushpe': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'macflushce': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'instance': {
                                    'adv_cnt': 2,
                                    'adv_last_time': '27/08 09:49:44.606',
                                    'adv_last_arg': '00007fff',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'mp_info': {
                                    'adv_cnt': 3,
                                    'adv_last_time': '27/08 09:49:44.606',
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                            },
                        },
                    },
                    'diagnostic_esi': 'N/A',
                    'interface_name': 'N/A',
                    'diagnostic_ifh': '0x00000000',
                    'diagnostic_flag': '0x00000043',
                    'diagnostic_es_rt': '0000.0000.0000',
                    'port_key': '0x000088d5',
                    'mac_winner': '1',
                    'number_of_evis': '1',
                    'recovery_timer_per_es': 'global',
                    'peering_timer_per_es': 'global',
                    'carving_timer_per_es': 'global',
                    'rt_advertised': '1',
                    'esi_advertised': '1',
                    'msti_state_mask': '0x7fff',
                    'hrw_msti_set': '0x3',
                    'es_ead_pulse': '0',
                    'mp_advertised': '1',
                    'nve_anycastvtep': '0',
                    'nve_ingrreplic': '0',
                    'peering_done': '1',
                    'carving_done': '1',
                    'inval_redundfwd': '0x00000000/0x00000000',
                    'inval_redund_nh': '0x00000000/0x00000000',
                    'chkpt_objid': '0x40002f18',
                    'checkpoint_info': {
                        'msti_mask': '0x7fff',
                    },
                    'es_ead_update': {
                        'num_rds': 1,
                        'rd': {
                            '10.154.219.84:1': {
                                'num_rts': 1,
                                'rt_list': ['4:1000'],
                            },
                        },
                    },
                },
            },
        },
        'N/A': {
            'interface': {
                'GigabitEthernet0/0/0/12': {
                    'next_hops': ['10.154.219.84<'],
                    'es_to_bgp_gates': 'Ready',
                    'es_to_l2fib_gates': 'Ready',
                    'main_port': {
                        'interface': 'GigabitEthernet0/0/0/12',
                        'interface_mac': '00c1.64ff.7f67',
                        'if_handle': '0x000005c0',
                        'state': 'Up',
                        'redundancy': 'Not Defined',
                    },
                    'esi': {
                        'type': 'Invalid',
                    },
                    'es_import_rt': '0000.0000.0000 (Incomplete Configuration)',
                    'source_mac': '00c1.64ff.a411 (PBB BSA, no ESI)',
                    'topology': {
                        'operational': 'SH',
                        'configured': 'Single-active (AApS) (default)',
                    },
                    'service_carving': 'Auto-selection',
                    'peering_details': ['10.154.219.84[MOD:P:00][1]'],
                    'service_carving_results': {
                        'forwarders': 1,
                        'permanent': 1,
                        'elected': {
                            'num_of_total': 0,
                        },
                        'not_elected': {
                            'num_of_total': 0,
                        },
                    },
                    'mac_flushing_mode': 'STP-TCN',
                    'peering_timer': '3',
                    'recovery_timer': '30',
                    'carving_timer': '0',
                    'local_shg_label': 'None',
                    'remote_shg_labels': {
                        '0': {
                        },
                    },
                    'object': {
                        'EVPN ES': {
                            'base_info': {
                                'version': '0xdbdb0007',
                                'flags': '0x0',
                                'type': 7,
                                'reserved': 0,
                            },
                            'num_events': 20,
                            'event_history': {
                                120: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'ES DB Bind',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                121: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Create',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                122: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action L2FIB Instance Upd',
                                    'flag_1': '000f7fff',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                123: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Advertise RT',
                                    'flag_1': 'a5138016',
                                    'flag_2': '0000ffff',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                124: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action L2FIB MP Info Upd',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                125: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': '00008001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                126: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'API BP Ifname update',
                                    'flag_1': '00000000',
                                    'flag_2': '08400000',
                                    'code_1': 'M',
                                    'code_2': '-',
                                },
                                127: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Advertise RT',
                                    'flag_1': 'a5138016',
                                    'flag_2': '0000ffff',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                128: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action L2FIB MP Info Upd',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                129: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'Action Peering Sequence',
                                    'flag_1': '00000000',
                                    'flag_2': '00008001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                130: {
                                    'time': 'Aug 27 09:49:15.648',
                                    'event': 'API BGP RID update',
                                    'flag_1': 'a5138011',
                                    'flag_2': '00010040',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                131: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'Action L2FIB MP Info Upd',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                132: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'API L2FIB Replay',
                                    'flag_1': '00000000',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                133: {
                                    'time': 'Aug 27 09:49:16.160',
                                    'event': 'API BGP mark / sweep',
                                    'flag_1': '00de1e7e',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                134: {
                                    'time': 'Aug 27 09:49:18.720',
                                    'event': 'Action L2FIB Instance Upd',
                                    'flag_1': '000f7fff',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                135: {
                                    'time': 'Aug 27 09:49:18.720',
                                    'event': 'Action L2FIB MP Info Upd',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                136: {
                                    'time': 'Aug 27 09:49:18.720',
                                    'event': 'API Peer Timer Expiry',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                137: {
                                    'time': 'Aug 27 09:49:37.152',
                                    'event': 'Action L2FIB Instance Upd',
                                    'flag_1': '000f7fff',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                138: {
                                    'time': 'Aug 27 09:49:37.152',
                                    'event': 'Action L2FIB MP Info Upd',
                                    'flag_1': '00000000',
                                    'flag_2': '00000001',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                                139: {
                                    'time': 'Aug 27 09:49:37.152',
                                    'event': 'API L2FIB Replay',
                                    'flag_1': '00000000',
                                    'flag_2': '00000000',
                                    'code_1': '-',
                                    'code_2': '-',
                                },
                            },
                            'statistics': {
                                'rt': {
                                    'adv_cnt': 2,
                                    'adv_last_time': '27/08 09:49:15.583',
                                    'adv_last_arg': 'a5138016',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'localbmac': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'esi': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'ead_es': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'ead_evi': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'mst_ag_vpw': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'df_electfw': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'updatemac': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'macflushpe': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'macflushce': {
                                    'adv_cnt': 0,
                                    'adv_last_arg': '00000000',
                                },
                                'instance': {
                                    'adv_cnt': 3,
                                    'adv_last_time': '27/08 09:49:37.025',
                                    'adv_last_arg': '00007fff',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                                'mp_info': {
                                    'adv_cnt': 5,
                                    'adv_last_time': '27/08 09:49:37.025',
                                    'adv_last_arg': '00000000',
                                    'wdw_cnt': 0,
                                    'wdw_last_arg': '00000000',
                                },
                            },
                        },
                    },
                    'diagnostic_esi': 'N/A',
                    'interface_name': 'N/A',
                    'diagnostic_ifh': '0x00000000',
                    'diagnostic_flag': '0x00000040',
                    'diagnostic_es_rt': '0000.0000.0000',
                    'port_key': '0x00000001',
                    'mac_winner': '1',
                    'number_of_evis': '1',
                    'recovery_timer_per_es': 'global',
                    'peering_timer_per_es': 'global',
                    'carving_timer_per_es': 'global',
                    'rt_advertised': '0',
                    'esi_advertised': '0',
                    'msti_state_mask': '0x7fff',
                    'hrw_msti_set': '0x3',
                    'es_ead_pulse': '0',
                    'mp_advertised': '1',
                    'nve_anycastvtep': '0',
                    'nve_ingrreplic': '0',
                    'peering_done': '1',
                    'carving_done': '1',
                    'inval_redundfwd': '0x00000000/0x00000000',
                    'inval_redund_nh': '0x00000000/0x00000000',
                    'chkpt_objid': '0x40002f58',
                    'checkpoint_info': {
                        'msti_mask': '0x7fff',
                    },
                    'es_ead_update': {
                        'num_rds': 0,
                    },
                },
            },
        },
    },
}
