expected_output = {
   "vrf":{
      "default":{
         "address_family":{
            "ipv6_unicast":{
               "prefix":"fc00:a000:1000:101::2/128",
               "last_modified":"Jan 29 05:43:06.637 for 1d04h",
               "paths":{
                  "total_available_paths":2,
                  "best_path":1,
                  "path":{
                     "1":{
                        "as_path":{
                           "Local":{
                              "bgp_peer_neighbor_ip":{
                                 "fc00:a000:1000::2":{
                                    "metric":10,
                                    "bgp_peer_neighbor_ip":"fc00:a000:1000::2",
                                    "origin_neighbors_ip":"fc00:a000:1000::11",
                                    "origin_router_id":"10.0.0.2",
                                    "if_handle":"0x00000000",
                                    "origin_metric":0,
                                    "localpref":100,
                                    "origin_codes":"i",
                                    "group_best":"group-best",
                                    "status_codes":"*>i",
                                    "received_path_id":0,
                                    "local_path_id":1,
                                    "version":1003,
                                    "originator":"10.0.0.2",
                                    "cluster_list":"10.0.0.11",
                                    "psid_type":{
                                       "L3":{
                                          "psid_type":"L3",
                                          "subtlv_count":1,
                                          "r_value":"0x00",
                                          "subtlv":{
                                             "t_value":"1",
                                             "sid_value":"fc00:c000:1002:e008::",
                                             "f_value":"0x00",
                                             "r2_value":"0x00",
                                             "behaviour":"62",
                                             "r3_value":"0x00",
                                             "sstlv_count":1,
                                             "subsubtlv":{
                                                "t":{
                                                   "1":{
                                                      "loc_blk":"32",
                                                      "loc_node":"16",
                                                      "func":"16",
                                                      "arg":"0",
                                                      "tpose_len":"0",
                                                      "tpose_offset":"0"
                                                   }
                                                }
                                             }
                                          }
                                       }
                                    }
                                 }
                              }
                           }
                        }
                     },
                     "2":{
                        "as_path":{
                           "Local":{
                              "bgp_peer_neighbor_ip":{
                                 "fc00:a000:1000::2":{
                                    "metric":10,
                                    "bgp_peer_neighbor_ip":"fc00:a000:1000::2",
                                    "origin_neighbors_ip":"fc00:a000:1000::12",
                                    "origin_router_id":"10.0.0.2",
                                    "if_handle":"0x00000000",
                                    "origin_metric":0,
                                    "localpref":100,
                                    "origin_codes":"i",
                                    "status_codes":"*",
                                    "received_path_id":0,
                                    "local_path_id":0,
                                    "version":0,
                                    "originator":"10.0.0.2",
                                    "cluster_list":"10.0.0.12",
                                    "psid_type":{
                                       "L3":{
                                          "psid_type":"L3",
                                          "subtlv_count":1,
                                          "r_value":"0x00",
                                          "subtlv":{
                                             "t_value":"1",
                                             "sid_value":"fc00:c000:1002:e008::",
                                             "f_value":"0x00",
                                             "r2_value":"0x00",
                                             "behaviour":"62",
                                             "r3_value":"0x00",
                                             "sstlv_count":1,
                                             "subsubtlv":{
                                                "t":{
                                                   "1":{
                                                      "loc_blk":"32",
                                                      "loc_node":"16",
                                                      "func":"16",
                                                      "arg":"0",
                                                      "tpose_len":"0",
                                                      "tpose_offset":"0"
                                                   }
                                                }
                                             }
                                          }
                                       }
                                    }
                                 }
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
