expected_output = {
    "interface": {
        "Tunnel100": {
            "interface_state_event_stats": {
                "r_up": 2,
                "r_up_error": 0,
                "r_down": 0,
                "r_down_error": 0,
                "r_deleted": 0,
                "r_deleted_error": 0,
            },
            "tunnel_stats": {
                "s_endpoint_addition": 264,
                "s_endpoint_addition_error": 0,
                "s_endpoint_deletion": 160,
                "s_endpoint_deletion_error": 0,
            },
            "tunnel_protection_stats": {
                "s_create_tp_socket": 0,
                "s_create_tp_socket_error": 0,
                "s_del_tp_socket": 0,
                "s_del_tp_socket_error": 0,
                "s_create_va": 0,
                "s_create_va_error": 0,
                "s_del_va": 0,
                "s_del_va_error": 0,
                "r_up": 44,
                "r_up_error": 0,
                "r_down": 19,
                "r_down_error": 0,
                "s_reset_socket": 0,
                "s_reset_socket_error": 0,
            },
            "tunnel_qos_stats": {
                "s_qos_apply": 0,
                "s_qos_apply_error": 0,
                "s_qos_remove": 0,
                "s_qos_remove_error": 0,
            },
            "rib_event_stats": {
                "s_add_route": 80,
                "s_add_route_error": 0,
                "s_del_route": 80,
                "s_del_route_error": 0,
                "s_add_nho": 0,
                "s_add_nho_error": 0,
                "s_del_nho": 0,
                "s_del_nho_error": 0,
                "s_rwatch_wo_route": 0,
                "s_rwatch_wo_route_error": 0,
                "r_route_evicted": 0,
                "r_route_evicted_error": 0,
            },
            "mpls_stats": {
                "s_label_alloc": 0,
                "s_label_alloc_error": 0,
                "s_label_release": 0,
                "s_label_release_error": 0,
                "s_mpls_ip_key_bind": 0,
                "s_mpls_ip_key_bind_error": 0,
                "s_mpls_vpn_key_bind": 0,
                "s_mpls_vpn_key_bind_error": 0,
            },
            "bfd_stats": {
                "s_client_create": 0,
                "s_client_create_error": 0,
                "s_client_destroy": 0,
                "s_client_destroy_error": 0,
                "r_session_down": 0,
                "r_session_down_error": 0,
                "r_session_up": 0,
                "r_session_up_error": 0,
            },
            "bgp_stats": {
                "s_route_export": 0,
                "s_route_export_error": 0,
                "s_route_withdrawal": 0,
                "s_route_withdrawal_error": 0,
                "s_route_import": 0,
                "s_route_import_error": 0,
                "r_imported_route_changed": 0,
                "r_imported_route_changed_error": 0,
            },
        },
        "Tunnel111": {
            "interface_state_event_stats": {
                "r_up": 3,
                "r_up_error": 0,
                "r_down": 4,
                "r_down_error": 0,
                "r_deleted": 0,
                "r_deleted_error": 0,
            },
            "tunnel_stats": {
                "s_endpoint_addition": 8,
                "s_endpoint_addition_error": 0,
                "s_endpoint_deletion": 2,
                "s_endpoint_deletion_error": 0,
            },
            "tunnel_protection_stats": {
                "s_create_tp_socket": 0,
                "s_create_tp_socket_error": 0,
                "s_del_tp_socket": 0,
                "s_del_tp_socket_error": 0,
                "s_create_va": 0,
                "s_create_va_error": 0,
                "s_del_va": 0,
                "s_del_va_error": 0,
                "r_up": 0,
                "r_up_error": 0,
                "r_down": 0,
                "r_down_error": 0,
                "s_reset_socket": 0,
                "s_reset_socket_error": 0,
            },
            "tunnel_qos_stats": {
                "s_qos_apply": 0,
                "s_qos_apply_error": 0,
                "s_qos_remove": 0,
                "s_qos_remove_error": 0,
            },
            "rib_event_stats": {
                "s_add_route": 0,
                "s_add_route_error": 0,
                "s_del_route": 0,
                "s_del_route_error": 0,
                "s_add_nho": 0,
                "s_add_nho_error": 0,
                "s_del_nho": 0,
                "s_del_nho_error": 0,
                "s_rwatch_wo_route": 0,
                "s_rwatch_wo_route_error": 0,
                "r_route_evicted": 0,
                "r_route_evicted_error": 0,
            },
            "mpls_stats": {
                "s_label_alloc": 0,
                "s_label_alloc_error": 0,
                "s_label_release": 0,
                "s_label_release_error": 0,
                "s_mpls_ip_key_bind": 0,
                "s_mpls_ip_key_bind_error": 0,
                "s_mpls_vpn_key_bind": 0,
                "s_mpls_vpn_key_bind_error": 0,
            },
            "bfd_stats": {
                "s_client_create": 0,
                "s_client_create_error": 0,
                "s_client_destroy": 0,
                "s_client_destroy_error": 0,
                "r_session_down": 0,
                "r_session_down_error": 0,
                "r_session_up": 0,
                "r_session_up_error": 0,
            },
            "bgp_stats": {
                "s_route_export": 0,
                "s_route_export_error": 0,
                "s_route_withdrawal": 0,
                "s_route_withdrawal_error": 0,
                "s_route_import": 0,
                "s_route_import_error": 0,
                "r_imported_route_changed": 0,
                "r_imported_route_changed_error": 0,
            },
        },
    }
}
