expected_output = {
    'interface': {
        'add': 10,
        'upd': 0,
        'del': 5,
        'ack': 6,
        'err': 0,
    },
    'timeout': {
        'set': 24,
        'ack': 24,
        'err': 0,
    },
    'service': {
        'set': 54,
        'ack': 54,
        'err': 0,
    },
    'modify_in_progress': {
        'set': 0,
        'ack': 0,
        'err': 0,
    },
    'esp': {
        'set': 0,
        'ack': 0,
        'err': 0,
    },
    'dnsv6': {
        'set': 1,
        'ack': 1,
        'err': 0,
    },
    'settings': {
        'set': 0,
        'ack': 0,
        'err': 0,
    },
    'pap_settings': {
        'set': 0,
        'ack': 0,
        'err': 0,
    },
    'flow_entries': {
        'set': 1,
        'ack': 1,
        'err': 0,
    },
    'pool': {
        'add': 1,
        'del': 0,
        'ack': 1,
        'err': 0,
    },
    'addr_range': {
        'add': 1,
        'upd': 0,
        'del': 0,
        'ack': 1,
        'err': 0,
    },
    'static_mapping': {
        'add': 2,
        'upd': 0,
        'del': 2,
        'ack': 0,
        'err': 0,
    },
    'dyn_mapping': {
        'add': 1,
        'upd': 0,
        'del': 0,
        'ack': 1,
        'err': 0,
    },
    'dyn_pat_mapping': {
        'add': 0,
        'del': 0,
        'ack': 0,
        'err': 0,
    },
    'porlist': {
        'add': 0,
        'del': 0,
        'ack': 0,
        'err': 0,
    },
    'logging': {
        'add': 0,
        'upd': 0,
        'del': 0,
        'ack': 0,
        'err': 0,
    },
    'per_vrf_logging': {
        'add': 0,
        'upd': 0,
        'del': 0,
        'ack': 0,
        'err': 0,
    },
    'sess_replicate': {
        'add': 1,
        'upd': 0,
        'del': 1,
        'ack': 2,
        'err': 0,
    },
    'max_entry': {
        'set': 1,
        'clr': 0,
        'ack': 1,
        'err': 0,
    },
    'ifaddr_change': {
        'notify': 0,
        'ack': 0,
        'err': 0,
    },
    'debug': {
        'set': 0,
        'clr': 0,
        'ack': 0,
        'err': 0,
    },
    'dp_static_rt': {
        'add': 0,
        'del': 0,
        'err': 0,
    },
    'dp_ipalias': {
        'add': 4,
        'del': 2,
        'err': 0,
    },
    'dp_portlist': {
        'req': 0,
        'ret': 0,
        'err': 0,
    },
    'dp_wlan_sess': {
        'est': 0,
        'term': 0,
        'err': 0,
    },
    'mib_setup': {
        'enable': 0,
        'disable': 0,
        'ack': 0,
        'err': 0,
    },
    'mib_addr_bind': {
        'query': 0,
        'reply': 0,
        'err': 0,
    },
    'misc_settings': {
        'set': 0,
        'ack': 0,
        'err': 0,
    },
    'gatekeeper_settings': {
        'set': 0,
        'ack': 0,
        'err': 0,
    },
}