expected_output=   {
    'interface': {
        'GigabitEthernet1/0/14': {
            'cisco_pd': 'No',
            'cisco_pd_detect_count': 0,
            'current_state': 'NGWC_ILP_LINK_UP_S',
            'detect_on': 'No',
            'ilp_enabled': 'Yes',
            'ilp_supported': 'Yes',
            'initialization_done': 'Yes',
            'pd_class': 'IEEE3',
            'pd_class_done': 'No',
            'pd_detected': 'Yes',
            'pd_power_state': 0,
            'pd_type': 'IEEE',
            'post': 'Yes',
            'power_denied': 'No',
            'power_is_on': 'Yes',
            'power_state': 'OK',
            'previous_state': 'NGWC_ILP_LINK_UP_S',
            'requested_power': 10250,
            'short': 0,
            'short_cnt': 0,
            'signal_pair_pwr_alloc': 0,
            'spare_pair_arch': 1,
            'spare_pair_mode': 0,
            'spare_pair_power_on': 0,
            'timer': {
                'bad_power': 'Stopped',
                'cisco_pd_detect': 'Stopped',
                'ieee_detect': 'Stopped',
                'ieee_short': 'Stopped',
                'link_down': 'Stopped',
                'power_denied': 'Stopped',
                'power_good': 'Stopped',
                'vsense': 'Stopped',
            },
        },
    },
}

