expected_output = {
   "interfaces":{
      "GigabitEthernet1/0/44":{
         "port_id":{
            "7038.eeff.50a4":{
               "neighbors":{
                  "10.10.191.112       ":{
                     "hold_time":171,
                     "capabilities":[
                        "B",
                        "T"
                     ]
                  }
               }
            }
         }
      },
      "GigabitEthernet1/0/16":{
         "port_id":{
            "7038.eeff.584d":{
               "neighbors":{
                  "10.10.191.104       ":{
                     "hold_time":166,
                     "capabilities":[
                        "B",
                        "T"
                     ]
                  }
               }
            },
            "6400.6aff.7d09":{
               "neighbors":{
                  "6400.6aff.7d09      ":{
                     "hold_time":2781
                  }
               }
            }
         }
      },
      "GigabitEthernet1/0/31":{
         "port_id":{
            "fca8.41ff.f37c":{
               "neighbors":{
                  "10.10.191.93        ":{
                     "hold_time":159,
                     "capabilities":[
                        "B",
                        "T"
                     ]
                  }
               }
            }
         }
      },
      "GigabitEthernet1/0/33":{
         "port_id":{
            "7052.c5ff.4647":{
               "neighbors":{
                  "10.10.191.91        ":{
                     "hold_time":152,
                     "capabilities":[
                        "B",
                        "T"
                     ]
                  }
               }
            },
            "d89e.f3ff.58fe":{
               "neighbors":{
                  "d89e.f3ff.58fe      ":{
                     "hold_time":3070
                  }
               }
            }
         }
      },
      "GigabitEthernet1/0/14":{
         "port_id":{
            "7038.eeff.572d":{
               "neighbors":{
                  "10.10.191.107       ":{
                     "hold_time":155,
                     "capabilities":[
                        "B",
                        "T"
                     ]
                  }
               }
            }
         }
      }
   },
   "total_entries":8
}