expected_output = {
    'bind_information': {
        'eqp_counter_oid': '0x0',
        'eqp_counter_size': 0,
        'port_internal_state': 'Active',
        'port_oid': '0x4F5',
        'port_type': 'L3',
        'speed': 40000000000,
        'system_port_oid': '0x4F9',
    },
    'qos_profile_information': {
        'cos_dei': {
            '0': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 0,
                'ile': 'Y',
                'remap': 0,
            },
            '1': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 0,
                'etos': 32,
                'ile': 'Y',
                'remap': 1,
            },
            '10': {
                'counteroffset': 0,
                'eexp': 10,
                'epcp': 5,
                'etos': 184,
                'ile': 'Y',
                'remap': 10,
            },
            '11': {
                'counteroffset': 0,
                'eexp': 11,
                'epcp': 5,
                'etos': 184,
                'ile': 'Y',
                'remap': 11,
            },
            '12': {
                'counteroffset': 0,
                'eexp': 12,
                'epcp': 6,
                'etos': 128,
                'ile': 'Y',
                'remap': 12,
            },
            '13': {
                'counteroffset': 0,
                'eexp': 13,
                'epcp': 6,
                'etos': 160,
                'ile': 'Y',
                'remap': 13,
            },
            '14': {
                'counteroffset': 0,
                'eexp': 14,
                'epcp': 7,
                'etos': 192,
                'ile': 'Y',
                'remap': 14,
            },
            '15': {
                'counteroffset': 0,
                'eexp': 15,
                'epcp': 7,
                'etos': 224,
                'ile': 'Y',
                'remap': 15,
            },
            '2': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 1,
                'etos': 64,
                'ile': 'Y',
                'remap': 2,
            },
            '3': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 1,
                'etos': 96,
                'ile': 'Y',
                'remap': 3,
            },
            '4': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 2,
                'etos': 128,
                'ile': 'Y',
                'remap': 4,
            },
            '5': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 2,
                'etos': 160,
                'ile': 'Y',
                'remap': 5,
            },
            '6': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 3,
                'etos': 192,
                'ile': 'Y',
                'remap': 6,
            },
            '7': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 3,
                'etos': 224,
                'ile': 'Y',
                'remap': 7,
            },
            '8': {
                'counteroffset': 0,
                'eexp': 8,
                'epcp': 4,
                'etos': 0,
                'ile': 'Y',
                'remap': 8,
            },
            '9': {
                'counteroffset': 0,
                'eexp': 9,
                'epcp': 4,
                'etos': 32,
                'ile': 'Y',
                'remap': 9,
            },
        },
        'dscp': {
            '0': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 0,
                'ile': 'Y',
                'remap': 0,
            },
            '1': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 4,
                'ile': 'Y',
                'remap': 1,
            },
            '10': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 1,
                'etos': 40,
                'ile': 'Y',
                'remap': 10,
            },
            '11': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 1,
                'etos': 44,
                'ile': 'Y',
                'remap': 11,
            },
            '12': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 1,
                'etos': 48,
                'ile': 'Y',
                'remap': 12,
            },
            '13': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 1,
                'etos': 52,
                'ile': 'Y',
                'remap': 13,
            },
            '14': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 1,
                'etos': 56,
                'ile': 'Y',
                'remap': 14,
            },
            '15': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 1,
                'etos': 60,
                'ile': 'Y',
                'remap': 15,
            },
            '16': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 2,
                'etos': 64,
                'ile': 'Y',
                'remap': 16,
            },
            '17': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 2,
                'etos': 68,
                'ile': 'Y',
                'remap': 17,
            },
            '18': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 2,
                'etos': 72,
                'ile': 'Y',
                'remap': 18,
            },
            '19': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 2,
                'etos': 76,
                'ile': 'Y',
                'remap': 19,
            },
            '2': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 8,
                'ile': 'Y',
                'remap': 2,
            },
            '20': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 2,
                'etos': 80,
                'ile': 'Y',
                'remap': 20,
            },
            '21': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 2,
                'etos': 84,
                'ile': 'Y',
                'remap': 21,
            },
            '22': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 2,
                'etos': 88,
                'ile': 'Y',
                'remap': 22,
            },
            '23': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 2,
                'etos': 92,
                'ile': 'Y',
                'remap': 23,
            },
            '24': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 3,
                'etos': 96,
                'ile': 'Y',
                'remap': 24,
            },
            '25': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 3,
                'etos': 100,
                'ile': 'Y',
                'remap': 25,
            },
            '26': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 3,
                'etos': 104,
                'ile': 'Y',
                'remap': 26,
            },
            '27': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 3,
                'etos': 108,
                'ile': 'Y',
                'remap': 27,
            },
            '28': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 3,
                'etos': 112,
                'ile': 'Y',
                'remap': 28,
            },
            '29': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 3,
                'etos': 116,
                'ile': 'Y',
                'remap': 29,
            },
            '3': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 12,
                'ile': 'Y',
                'remap': 3,
            },
            '30': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 3,
                'etos': 120,
                'ile': 'Y',
                'remap': 30,
            },
            '31': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 3,
                'etos': 124,
                'ile': 'Y',
                'remap': 31,
            },
            '32': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 4,
                'etos': 128,
                'ile': 'Y',
                'remap': 32,
            },
            '33': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 4,
                'etos': 132,
                'ile': 'Y',
                'remap': 33,
            },
            '34': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 4,
                'etos': 136,
                'ile': 'Y',
                'remap': 34,
            },
            '35': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 4,
                'etos': 140,
                'ile': 'Y',
                'remap': 35,
            },
            '36': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 4,
                'etos': 144,
                'ile': 'Y',
                'remap': 36,
            },
            '37': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 4,
                'etos': 148,
                'ile': 'Y',
                'remap': 37,
            },
            '38': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 4,
                'etos': 152,
                'ile': 'Y',
                'remap': 38,
            },
            '39': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 4,
                'etos': 156,
                'ile': 'Y',
                'remap': 39,
            },
            '4': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 16,
                'ile': 'Y',
                'remap': 4,
            },
            '40': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 5,
                'etos': 160,
                'ile': 'Y',
                'remap': 40,
            },
            '41': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 5,
                'etos': 164,
                'ile': 'Y',
                'remap': 41,
            },
            '42': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 5,
                'etos': 168,
                'ile': 'Y',
                'remap': 42,
            },
            '43': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 5,
                'etos': 172,
                'ile': 'Y',
                'remap': 43,
            },
            '44': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 5,
                'etos': 176,
                'ile': 'Y',
                'remap': 44,
            },
            '45': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 5,
                'etos': 180,
                'ile': 'Y',
                'remap': 45,
            },
            '46': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 5,
                'etos': 184,
                'ile': 'Y',
                'remap': 46,
            },
            '47': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 5,
                'etos': 188,
                'ile': 'Y',
                'remap': 47,
            },
            '48': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 6,
                'etos': 192,
                'ile': 'Y',
                'remap': 48,
            },
            '49': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 6,
                'etos': 196,
                'ile': 'Y',
                'remap': 49,
            },
            '5': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 20,
                'ile': 'Y',
                'remap': 5,
            },
            '50': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 6,
                'etos': 200,
                'ile': 'Y',
                'remap': 50,
            },
            '51': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 6,
                'etos': 204,
                'ile': 'Y',
                'remap': 51,
            },
            '52': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 6,
                'etos': 208,
                'ile': 'Y',
                'remap': 52,
            },
            '53': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 6,
                'etos': 212,
                'ile': 'Y',
                'remap': 53,
            },
            '54': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 6,
                'etos': 216,
                'ile': 'Y',
                'remap': 54,
            },
            '55': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 6,
                'etos': 220,
                'ile': 'Y',
                'remap': 55,
            },
            '56': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 7,
                'etos': 224,
                'ile': 'Y',
                'remap': 56,
            },
            '57': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 7,
                'etos': 228,
                'ile': 'Y',
                'remap': 57,
            },
            '58': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 7,
                'etos': 232,
                'ile': 'Y',
                'remap': 58,
            },
            '59': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 7,
                'etos': 236,
                'ile': 'Y',
                'remap': 59,
            },
            '6': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 24,
                'ile': 'Y',
                'remap': 6,
            },
            '60': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 7,
                'etos': 240,
                'ile': 'Y',
                'remap': 60,
            },
            '61': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 7,
                'etos': 244,
                'ile': 'Y',
                'remap': 61,
            },
            '62': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 7,
                'etos': 248,
                'ile': 'Y',
                'remap': 62,
            },
            '63': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 7,
                'etos': 252,
                'ile': 'Y',
                'remap': 63,
            },
            '7': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 28,
                'ile': 'Y',
                'remap': 7,
            },
            '8': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 1,
                'etos': 32,
                'ile': 'Y',
                'remap': 8,
            },
            '9': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 1,
                'etos': 36,
                'ile': 'Y',
                'remap': 9,
            },
        },
        'exp': {
            '0': {
                'counteroffset': 0,
                'eexp': 0,
                'epcp': 0,
                'etos': 0,
                'ile': 'Y',
                'remap': 0,
            },
            '1': {
                'counteroffset': 0,
                'eexp': 1,
                'epcp': 1,
                'etos': 32,
                'ile': 'Y',
                'remap': 0,
            },
            '2': {
                'counteroffset': 0,
                'eexp': 2,
                'epcp': 2,
                'etos': 64,
                'ile': 'Y',
                'remap': 0,
            },
            '3': {
                'counteroffset': 0,
                'eexp': 3,
                'epcp': 3,
                'etos': 96,
                'ile': 'Y',
                'remap': 0,
            },
            '4': {
                'counteroffset': 0,
                'eexp': 4,
                'epcp': 4,
                'etos': 128,
                'ile': 'Y',
                'remap': 0,
            },
            '5': {
                'counteroffset': 0,
                'eexp': 5,
                'epcp': 5,
                'etos': 160,
                'ile': 'Y',
                'remap': 0,
            },
            '6': {
                'counteroffset': 0,
                'eexp': 6,
                'epcp': 6,
                'etos': 192,
                'ile': 'Y',
                'remap': 0,
            },
            '7': {
                'counteroffset': 0,
                'eexp': 7,
                'epcp': 7,
                'etos': 224,
                'ile': 'Y',
                'remap': 0,
            },
        },
        'need_filter_table_update': 'CREATED',
        'no_of_counter': 0,
        'oid': '0xFF',
        'ref_count': 0,
        'tunnel_mode': 'PIPE',
    },
}