
expected_output = {
    "vrf": {
        "default": {
           "address_family": {
                "ipv6 unicast": {
                     "bgp_distance_internal_as": 200,
                     "ip": {
                          "2001:db8:1:1::1/128": {
                               "attach": "attached",
                               "best_route": {
                                    "unicast": {
                                         "nexthop": {
                                              "2001:db8:1:1::1": {
                                                   "protocol": {
                                                        "local": {
                                                             "interface": "Ethernet1/1",
                                                             "metric": "0",
                                                             "uptime": "00:15:46",
                                                             "preference": "0"}}}}}},
                               "mbest_num": "0",
                               "ubest_num": "1"
                          },
                          "2001:db8:1:1::/64": {
                               "attach": "attached",
                               "best_route": {
                                    "unicast": {
                                         "nexthop": {
                                              "2001:db8:1:1::1": {
                                                   "protocol": {
                                                        "direct": {
                                                             "interface": "Ethernet1/1",
                                                             "metric": "0",
                                                             "uptime": "00:15:46",
                                                             "preference": "0"}}}}}},
                               "mbest_num": "0",
                               "ubest_num": "1"
                          },
                          "2001:db8:2:2::2/128": {
                               "attach": "attached",
                               "best_route": {
                                    "unicast": {
                                         "nexthop": {
                                              "2001:db8:2:2::2": {
                                                   "protocol": {
                                                        "local": {
                                                             "interface": "Ethernet1/1",
                                                             "metric": "0",
                                                             "tag": "222",
                                                             "uptime": "00:15:46",
                                                             "preference": "0"}}}}}},
                               "mbest_num": "0",
                               "ubest_num": "1"
                          },
                          "2001:db8::5054:ff:fed5:63f9/128": {
                               "attach": "attached",
                               "best_route": {
                                    "unicast": {
                                         "nexthop": {
                                              "2001:db8::5054:ff:fed5:63f9": {
                                                   "protocol": {
                                                        "local": {
                                                             "interface": "Ethernet1/1",
                                                             "metric": "0",
                                                             "uptime": "00:15:46",
                                                             "preference": "0"}}}}}},
                               "mbest_num": "0",
                               "ubest_num": "1"
                          },
                          "2001:db8::/64": {
                               "attach": "attached",
                               "best_route": {
                                    "unicast": {
                                         "nexthop": {
                                              "2001:db8::5054:ff:fed5:63f9": {
                                                   "protocol": {
                                                        "direct": {
                                                             "interface": "Ethernet1/1",
                                                             "metric": "0",
                                                             "uptime": "00:15:46",
                                                             "preference": "0"}}}}}},
                               "mbest_num": "0",
                               "ubest_num": "1"
                          },
                          "2001:db8:cdc9:121::/64": {
                               "mbest_num": "0",
                               "ubest_num": "1",
                               "best_route": {
                                    "unicast": {
                                         "nexthop": {
                                              "::ffff:10.4.1.1": {
                                                   "protocol": {
                                                        "bgp": {
                                                             "uptime": "00:35:51",
                                                             "tag": "200",
                                                             "route_table": "default:IPv4",
                                                             "attribute": "internal",
                                                             "mpls": True,
                                                             "metric": "2219",
                                                             "preference": "200",
                                                             "protocol_id": "100"}}}}}}},
                          "2001:db8:2:2::/64": {
                               "attach": "attached",
                               "best_route": {
                                    "unicast": {
                                         "nexthop": {
                                              "2001:db8:2:2::2": {
                                                   "protocol": {
                                                        "direct": {
                                                             "interface": "Ethernet1/1",
                                                             "metric": "0",
                                                             "tag": "222",
                                                             "uptime": "00:15:46",
                                                             "preference": "0"}}}}}},
                               "mbest_num": "0",
                               "ubest_num": "1"}}}}},
        "VRF1": {
           "address_family": {
                "vpnv6 unicast": {
                     "bgp_distance_internal_as": 200,
                     "ip": {
                          "2001:db8:cdc9:144::/64": {
                               "mbest_num": "0",
                               "ubest_num": "1",
                               "best_route": {
                                    "unicast": {
                                         "nexthop": {
                                              "::ffff:10.4.1.1": {
                                                   "protocol": {
                                                        "bgp": {
                                                             "uptime": "00:35:51",
                                                             "tag": "200",
                                                             "mpls_vpn": True,
                                                             "attribute": "internal",
                                                             "route_table": "default:IPv4",
                                                             "metric": "2219",
                                                             "preference": "200",
                                                             "protocol_id": "100"}}}}}}}}}}}}
}
