

expected_output = {
    'vrf': {
        'otv-vrf139': {
            'address_family': {
                'vpnv6 unicast': {
                    'ip': {
                        '2001:112:1:2b3::/64': {
                            'attach': 'attached',
                            'best_route': {
                                'unicast': {
                                    'nexthop': {
                                        '2001:112:1:2b3::2': {
                                            'protocol': {
                                                'direct': {
                                                    'interface': 'Vlan1191',
                                                    'metric': '0',
                                                    'preference': '0',
                                                    'uptime': '20:58:10'}}}}}},
                            'mbest_num': '0',
                            'ubest_num': '1'},
                        '2001:112:1:2b3::1/128': {
                            'attach': 'attached',
                            'best_route': {
                                'unicast': {
                                    'nexthop': {
                                        '2001:112:1:2b3::1': {
                                            'protocol': {
                                                'hsrp': {
                                                    'interface': 'Vlan1191',
                                                     'metric': '0',
                                                     'preference': '0',
                                                     'uptime': '20:57:53'}}}}}},
                            'mbest_num': '0',
                            'ubest_num': '1'},
                        '2001:112:1:2b3::2/128': {
                            'attach': 'attached',
                            'best_route': {
                                'unicast': {
                                    'nexthop': {
                                        '2001:112:1:2b3::2': {
                                            'protocol': {
                                                'local': {
                                                'interface': 'Vlan1191',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:58:10'}}}}}},
                            'mbest_num': '0',
                            'ubest_num': '1'},
                    '2001:112:1:2b4::/64': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b4::2': {
                                        'protocol': {
                                            'direct': {
                                                'interface': 'Vlan1192',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:58:10'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b4::1/128': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b4::1': {
                                        'protocol': {
                                            'hsrp': {
                                                'interface': 'Vlan1192',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:57:53'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b4::2/128': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b4::2': {
                                        'protocol': {
                                            'local': {
                                                'interface': 'Vlan1192',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:58:10'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b5::/64': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                '2001:112:1:2b5::2': {
                                    'protocol': {
                                        'direct': {
                                            'interface': 'Vlan1193',
                                            'metric': '0',
                                            'preference': '0',
                                            'uptime': '20:58:10'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b5::1/128': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b5::1': {
                                        'protocol': {
                                            'hsrp': {
                                                'interface': 'Vlan1193',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:57:52'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b5::2/128': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b5::2': {
                                        'protocol': {
                                            'local': {
                                                'interface': 'Vlan1193',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:58:10'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b6::/64': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b6::2': {
                                        'protocol': {
                                            'direct': {
                                                'interface': 'Vlan1194',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:58:10'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b6::1/128': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b6::1': {
                                        'protocol': {
                                            'hsrp': {
                                                'interface': 'Vlan1194',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:57:52'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b6::2/128': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b6::2': {
                                        'protocol': {
                                            'local': {
                                                'interface': 'Vlan1194',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:58:10'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b7::/64': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b7::2': {
                                        'protocol': {
                                            'direct': {
                                                'interface': 'Vlan1195',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:58:10'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b7::1/128': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b7::1': {
                                        'protocol': {
                                            'hsrp': {
                                                'interface': 'Vlan1195',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:57:52'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'},
                    '2001:112:1:2b7::2/128': {
                        'attach': 'attached',
                        'best_route': {
                            'unicast': {
                                'nexthop': {
                                    '2001:112:1:2b7::2': {
                                        'protocol': {
                                            'local': {
                                                'interface': 'Vlan1195',
                                                'metric': '0',
                                                'preference': '0',
                                                'uptime': '20:58:10'}}}}}},
                        'mbest_num': '0',
                        'ubest_num': '1'}}}}}}}
