expected_output = {'oper_state': {'admin_enabled': False,
            'cert_mgmt_svc': {'admin_enabled': False, 'oper_up': False},
            'config_svc': {'admin_enabled': False, 'oper_up': False},
            'factory_reset_svc': {'admin_enabled': False,
                                    'oper_up': False,
                                    'supported': False},
            'grpc': {'admin_enabled': False, 'oper_up': False},
            'oper_up': False,
            'os_image_svc': {'admin_enabled': False,
                                'oper_up': False,
                                'supported': False},
            'provisioned': True,
            'telemetry_svc': {'admin_enabled': False, 'oper_up': False}},
'settings': {'insecure_port': 50052,
            'insecure_server': False,
            'secure_client_authentication': False,
            'secure_client_trustpoint': '',
            'secure_password_authentication': False,
            'secure_port': 9339,
            'secure_server': False,
            'secure_trustpoint': ''}}