expected_output = {
    'parameter_maps': {
        'global': {
            'name': 'global',
            'index': 1,
            'type': 'Parameter-Map',
            'global_parameter_map': True,
            'alerts': 'On',
            'audits': 'Off',
            'drop_log': 'Off',
            'log_flow': 'Off',
            'hsl_mode': 'Disabled',
            'host': '0.0.0.0:0',
            'port': 0,
            'template': '300 sec',
            'session_rate_high': 2147483647,
            'session_rate_low': 2147483647,
            'time_duration': '60 sec',
            'half_open': {
                'high': 2147483647,
                'low': 2147483647,
                'host': 4294967295,
                'host_block_time': 0,
            },
            'inactivity_times': {
                'dns': 5,
                'icmp': 10,
                'tcp': 3600,
                'udp': 30,
            },
            'inactivity_age_out_times': {
                'icmp': 10,
                'tcp': 3600,
                'udp': 30,
            },
            'tcp_timeouts': {
                'syn_wait_time': 30,
                'fin_wait_time': 1,
            },
            'tcp_ageout_timeouts': {
                'syn_wait_time': 30,
                'fin_wait_time': 1,
            },
            'tcp_rst_pkt_control': {
                'half_open': 'On',
                'half_close': 'On',
                'idle': 'On',
            },
            'udp_timeout': {
                'udp_half_open_time': 30000,
            },
            'udp_ageout_timeout': {
                'udp_half_open_time': 30000,
            },
            'max_sessions': 'Unlimited',
            'number_of_simultaneous_packet_per_sessions': 0,
            'syn_cookie_and_resource_management': {
                'global_syn_flood_limit': 4294967295,
                'global_total_session': 4294967295,
                'global_number_of_simultaneous_packet_per_session': '',
                'global_total_session_aggressive_aging': 'Disabled',
                'global_alert': 'Off',
                'global_max_incomplete': 4294967295,
                'global_max_incomplete_tcp': 4294967295,
                'global_max_incomplete_udp': 4294967295,
                'global_max_incomplete_icmp': 4294967295,
                'global_max_incomplete_aggressive_aging': 'Disabled',
                'per_box_syn_flood_limit': 4294967295,
                'per_box_total_session_aggressive_aging': 'Disabled',
                'per_box_max_incomplete': 4294967295,
                'per_box_max_incomplete_tcp': 4294967295,
                'per_box_max_incomplete_udp': 4294967295,
                'per_box_max_incomplete_icmp': 4294967295,
                'per_box_max_incomplete_aggressive_aging': 'Disabled',
            },
        },
        'vrf-default': {
            'name': 'vrf-default',
            'index': 2,
            'type': 'VRF-Parameter-Map',
            'vrf_pmap_syn_flood_limit': 4294967295,
            'vrf_pmap_total_session': 4294967295,
            'vrf_pmap_total_session_aggressive_aging': 'Disabled',
            'vrf_pmap_alert': 'Off',
            'vrf_pmap_max_incomplete': 4294967295,
            'vrf_pmap_max_incomplete_tcp': 4294967295,
            'vrf_pmap_max_incomplete_udp': 4294967295,
            'vrf_pmap_max_incomplete_icmp': 4294967295,
            'vrf_pmap_max_incomplete_aggressive_aging': 'Disabled',
        },
        'inspect-global': {
            'name': 'inspect-global',
            'index': 373,
            'type': 'inspect-global Parameter-Map',
            'alerts': 'On',
            'drop_log': 'On',
            'zone_mismatch_drop': 'Off',
            'icmp_unreachable_allowed': 'No',
            'session_reclassify_allowed': 'No',
            'vpn_zone_security': 'Off',
            'vpn_zone_allow_dia': 'Off',
            'hsl_template_timeout': 300,
            'inspect_global_syn_flood_limit': 4294967295,
            'inspect_global_total_session_aggressive_aging': 'Disabled',
            'inspect_global_max_incomplete': 0,
            'inspect_global_max_incomplete_tcp': 4294967295,
            'inspect_global_max_incomplete_udp': 4294967295,
            'inspect_global_max_incomplete_icmp': 4294967295,
            'inspect_global_max_incomplete_aggressive_aging': 'Disabled',
            'tcp_winscale_loose': 'Off',
            'application_protocol_control': {
                'dns': 'on',
                'ftp': 'on',
                'gtp': 'on',
                'H323': 'on',
                'http': 'on',
                'imap': 'on',
                'msrpc': 'on',
                'netbios': 'on',
                'pop3': 'on',
                'exec': 'on',
                'rlogin': 'on',
                'shell': 'on',
                'rtsp': 'on',
                'sip': 'on',
                'skinny': 'on',
                'smtp': 'on',
                'sunrpc': 'on',
                'tftp': 'on',
            },
        },
    }
}