expected_output = {'Access_control': 'must secure',
 'Capabilities': {'Ciphers_supported': ['GCM-AES-128',
                                        'GCM-AES-256',
                                        'GCM-AES-XPN-128',
                                        'GCM-AES-XPN-256'],
                  'Data_length_change_supported': 'yes',
                  'ICV_length': '16',
                  'Max_Rx_SA': '16',
                  'Max_Rx_SC': '8',
                  'Max_Tx_SA': '16',
                  'Max_Tx_SC': '8',
                  'PN_threshold_notification_support': 'Yes',
                  'Validate_Frames': 'strict'},
 'Cleartag_details': {'Type': 'one dot1q in clear', 'VlanId1': '5'},
 'Macsec_Data': {'Admin_Pt2Pt_MAC': 'forceTrue(1)',
                 'Cipher': 'GCM-AES-256',
                 'Confidentiality_Offset': '30',
                 'Include_SCI': 'yes',
                 'Macsec_status': 'enabled',
                 'Pt2Pt_MAC_Operational': 'no',
                 'Replay_protect_status': 'enabled',
                 'Replay_window': '0',
                 'Use_ES_Enable': 'no',
                 'Use_SCB_Enable': 'no'},
 'Receive_Secure_Channels': {'Current_AN': '1',
                             'Elapsed_time': '7w0d',
                             'Next_PN': '559',
                             'Port_Statistics': {'Ingress_badtag_pkts': '0',
                                                 'Ingress_noSCI_pkts': '0',
                                                 'Ingress_notag_pkts': '26328',
                                                 'Ingress_overrun_pkts': '0',
                                                 'Ingress_unknownSCI_pkts': '0',
                                                 'Ingress_untag_pkts': '0'},
                             'Previous_AN': '0',
                             'RX_SA_Count': '0',
                             'SAK_Unchanged': 'no',
                             'SA_Create_time': '13:52:38',
                             'SA_Start_time': '7w0d',
                             'SA_State': 'inUse(1)',
                             'SA_Statistics': {'Decrypted_Bytes': '78974',
                                               'Invalid_pkts': '0',
                                               'Notvalid_pkts': '0',
                                               'NousingSA_pkts': '0',
                                               'UnusedSA_pkts': '0',
                                               'Valid_pkts': '557',
                                               'Validated_Bytes': '0'},
                             'SCI': 'ECCE1346F902008C',
                             'SC_Statistics': {'Decrypted_Bytes': '15958621376336',
                                               'Delay_pkts': '0',
                                               'Invalid_pkts': '0',
                                               'Late_pkts': '0',
                                               'Notvalid_pkts': '0',
                                               'NousingSA_pkts': '0',
                                               'Uncheck_pkts': '0',
                                               'UnusedSA_pkts': '0',
                                               'Valid_pkts': '1776341980',
                                               'Validated_Bytes': '0'},
                             'SC_state': 'inUse(1)',
                             'Start_time': '7w0d'},
 'Transmit_Secure_Channels': {'Confidentiality': 'yes',
                              'Current_AN': '1',
                              'Elapsed_time': '7w0d',
                              'Next_PN': '558',
                              'Port_Statistics': {'Egress_long_pkts': '0',
                                                  'Egress_untag_pkts': '0'},
                              'Previous_AN': '0',
                              'SAK_Unchanged': 'no',
                              'SA_Create_time': '13:52:40',
                              'SA_Start_time': '7w0d',
                              'SA_State': 'inUse(1)',
                              'SA_Statistics': {'Auth_only_Bytes': '0',
                                                'Auth_only_Pkts': '0',
                                                'Encrypted_Bytes': '78902',
                                                'Encrypted_Pkts': '557'},
                              'SCI': 'F87A41252702008C',
                              'SC_Statistics': {'Auth_only_Bytes': '0',
                                                'Auth_only_Pkts': '0',
                                                'Encrypted_Bytes': '15955677965468',
                                                'Encrypted_Pkts': '1776014411'},
                              'SC_state': 'inUse(1)',
                              'Start_time': '7w0d'}}
