expected_output={
    "tunnel_id": {
        1: {
            "fvrf": "none",
            "ivrf": "none",
            "status": "ready",
            "remote_subnets": [],
            "local": "2001:DB8:1101::222",
            "remote": "2001:DB8:1201::222",
            "encryption": "aes-cbc",
            "keysize": 256,
            "prf": "sha512",
            "hash": "sha512",
            "dh_grp": 21,
            "auth_sign": "psk",
            "auth_verify": "psk",
            "ake": {
                "AKE1": "MLKEM1024"
            },
            "life_time": 86400,
            "active_time": 56,
            "ce_id": 0,
            "session_id": 1,
            "local_spi": "76CA165325616F2A",
            "remote_spi": "F8564E3FE3EA475B",
            "status_description": "negotiation done",
            "local_id": "2001:DB8:1101::222",
            "remote_id": "2001:DB8:1201::222",
            "local_reg_msg_id": 0,
            "remote_req_msg_id": 3,
            "local_next_msg_id": 0,
            "remote_next_msg_id": 3,
            "local_req_queued": 0,
            "remote_req_queued": 3,
            "local_window": 20,
            "remote_window": 20,
            "dpd_configured_time": 0,
            "retry": 0,
            "fragmentation": "not  configured",
            "dynamic_route_update": "enabled",
            "extended_authentication": "not configured",
            "nat_t": "not detected",
            "cisco_trust_security_sgt": "disabled",
            "initiator_of_sa": "no"
        },
        2: {
            "fvrf": "none",
            "ivrf": "none",
            "status": "ready",
            "remote_subnets": [],
            "local": "2001:DB8:1101::222",
            "remote": "2001:DB8:1202::222",
            "encryption": "aes-cbc",
            "keysize": 256,
            "prf": "sha512",
            "hash": "sha512",
            "dh_grp": 21,
            "auth_sign": "psk",
            "auth_verify": "psk",
            "ake": {
                "AKE1": "MLKEM1024"
            },
            "life_time": 86400,
            "active_time": 48,
            "ce_id": 0,
            "session_id": 2,
            "local_spi": "C43DEBB37E77992B",
            "remote_spi": "A48393A1EB310E5E",
            "status_description": "negotiation done",
            "local_id": "2001:DB8:1101::222",
            "remote_id": "2001:DB8:1202::222",
            "local_reg_msg_id": 0,
            "remote_req_msg_id": 3,
            "local_next_msg_id": 0,
            "remote_next_msg_id": 3,
            "local_req_queued": 0,
            "remote_req_queued": 3,
            "local_window": 20,
            "remote_window": 20,
            "dpd_configured_time": 0,
            "retry": 0,
            "fragmentation": "not  configured",
            "dynamic_route_update": "enabled",
            "extended_authentication": "not configured",
            "nat_t": "not detected",
            "cisco_trust_security_sgt": "disabled",
            "initiator_of_sa": "no"
        }
    }
}