expected_output={
    "tunnel_id": {
        6: {
            "local": "1.1.1.2/500",
            "remote": "2.2.2.2/500",
            "fvrf": "none",
            "ivrf": "none",
            "status": "ready",
            "remote_subnets": [],
            "qr": "qr",
            "encryption": "aes-cbc",
            "keysize": 256,
            "prf": "sha256",
            "hash": "sha256",
            "dh_grp": 14,
            "auth_sign": "psk",
            "auth_verify": "psk",
            "life_time": 86400,
            "active_time": 1757,
            "ce_id": 0,
            "session_id": 74,
            "local_spi": "4924FD2741CC90FD",
            "remote_spi": "601ED2AB91327DAE",
            "status_description": "negotiation done",
            "local_id": "1.1.1.2",
            "remote_id": "2.2.2.2",
            "local_reg_msg_id": 0,
            "remote_req_msg_id": 0,
            "local_next_msg_id": 0,
            "remote_next_msg_id": 0,
            "local_req_queued": 0,
            "remote_req_queued": 0,
            "local_window": 5,
            "remote_window": 5,
            "dpd_configured_time": 0,
            "retry": 0,
            "fragmentation": "not configured",
            "dynamic_route_update": "enabled",
            "extended_authentication": "not configured",
            "nat_t": "not detected",
            "cisco_trust_security_sgt": "disabled",
            "initiator_of_sa": "no",
            "quantum_resistance": "Enabled",
        }
    }
}
