expected_output={
    "tunnel_id": {
        1: {
            "fvrf": "none",
            "ivrf": "none",
            "status": "ready",
            "remote_subnets": [],
            "local": "2001:DB8:1101::131",
            "remote": "2001:DB8:1201::122",
            "encryption": "aes-cbc",
            "keysize": 256,
            "prf": "sha512",
            "hash": "sha512",
            "dh_grp": 21,
            "auth_sign": "psk",
            "auth_verify": "psk",
            "pqc": "ML-KEM-1024",
            "life_time": 86400,
            "active_time": 219,
            "ce_id": 0,
            "session_id": 3,
            "local_spi": "4CF87E32B25302C0",
            "remote_spi": "96254131FD306002",
            "status_description": "negotiation done",
            "local_id": "2001:DB8:1101::131",
            "remote_id": "2001:DB8:1201::122",
            "local_reg_msg_id": 0,
            "remote_req_msg_id": 3,
            "local_next_msg_id": 0,
            "remote_next_msg_id": 3,
            "local_req_queued": 0,
            "remote_req_queued": 3,
            "local_window": 20,
            "remote_window": 20,
            "dpd_configured_time": 0,
            "retry": 0,
            "fragmentation": "not  configured",
            "quantum_safe_pqc": "ML-KEM-1024",
            "dynamic_route_update": "enabled",
            "extended_authentication": "not configured",
            "nat_t": "not detected",
            "cisco_trust_security_sgt": "disabled",
            "initiator_of_sa": "no"
        },
        2: {
            "fvrf": "none",
            "ivrf": "none",
            "status": "ready",
            "remote_subnets": [],
            "local": "2001:DB8:1101::131",
            "remote": "2001:DB8:1202::123",
            "encryption": "aes-cbc",
            "keysize": 256,
            "prf": "sha512",
            "hash": "sha512",
            "dh_grp": 21,
            "auth_sign": "psk",
            "auth_verify": "psk",
            "pqc": "ML-KEM-1024",
            "life_time": 86400,
            "active_time": 208,
            "ce_id": 0,
            "session_id": 4,
            "local_spi": "DE66CA8E9F3AB6BD",
            "remote_spi": "DB3CED85555E739D",
            "status_description": "negotiation done",
            "local_id": "2001:DB8:1101::131",
            "remote_id": "2001:DB8:1202::123",
            "local_reg_msg_id": 0,
            "remote_req_msg_id": 3,
            "local_next_msg_id": 0,
            "remote_next_msg_id": 3,
            "local_req_queued": 0,
            "remote_req_queued": 3,
            "local_window": 20,
            "remote_window": 20,
            "dpd_configured_time": 0,
            "retry": 0,
            "fragmentation": "not  configured",
            "quantum_safe_pqc": "ML-KEM-1024",
            "dynamic_route_update": "enabled",
            "extended_authentication": "not configured",
            "nat_t": "not detected",
            "cisco_trust_security_sgt": "disabled",
            "initiator_of_sa": "no"
        }
    }
}