expected_output = {
    "channel": {
        "0": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 0,
            "name": "CC0 Low",
        },
        "1": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 1,
            "name": "CC0 Hi",
        },
        "10": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 10,
            "name": "CC2B Low",
        },
        "11": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 11,
            "name": "CC2B Hi",
        },
        "12": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 12,
            "name": "CC3 Low",
        },
        "13": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 13,
            "name": "CC3 Hi",
        },
        "14": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 14,
            "name": "CC3B Low",
        },
        "15": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 15,
            "name": "CC3B Hi",
        },
        "16": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 16,
            "name": "CC4 Low",
        },
        "17": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 17,
            "name": "CC4 Hi",
        },
        "18": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 18,
            "name": "CC5 Low",
        },
        "19": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 19,
            "name": "CC5 Hi",
        },
        "2": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 2,
            "name": "CC0B Low",
        },
        "20": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 20,
            "name": "RP0 Low",
        },
        "21": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 21,
            "name": "RP0 Hi",
        },
        "22": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 22,
            "name": "RP1 Low",
        },
        "23": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 23,
            "name": "RP1 Hi",
        },
        "24": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 24,
            "name": "Peer-FP Low",
        },
        "25": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 25,
            "name": "Peer-FP Hi",
        },
        "26": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 26,
            "name": "Nitrox Low",
        },
        "27": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 27,
            "name": "Nitrox Hi",
        },
        "28": {
            "drain_mode": False,
            "interface": "HT",
            "logical_channel": 0,
            "name": "HT Pkt Low",
        },
        "29": {
            "drain_mode": False,
            "interface": "HT",
            "logical_channel": 1,
            "name": "HT Pkt Hi",
        },
        "3": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 3,
            "name": "CC0B Hi",
        },
        "30": {
            "drain_mode": False,
            "interface": "HT",
            "logical_channel": 2,
            "name": "HT IPC Low",
        },
        "31": {
            "drain_mode": False,
            "interface": "HT",
            "logical_channel": 3,
            "name": "HT IPC Hi",
        },
        "32": {"name": "unmapped"},
        "33": {"name": "unmapped"},
        "34": {"name": "unmapped"},
        "35": {"name": "unmapped"},
        "36": {"name": "unmapped"},
        "37": {"name": "unmapped"},
        "38": {
            "drain_mode": False,
            "interface": "GPM",
            "logical_channel": 7,
            "name": "HighNormal",
        },
        "39": {
            "drain_mode": False,
            "interface": "GPM",
            "logical_channel": 6,
            "name": "HighPriority",
        },
        "4": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 4,
            "name": "CC1 Low",
        },
        "40": {
            "drain_mode": False,
            "interface": "GPM",
            "logical_channel": 11,
            "name": "LowNormal",
        },
        "41": {
            "drain_mode": False,
            "interface": "GPM",
            "logical_channel": 10,
            "name": "LowPriority",
        },
        "42": {
            "drain_mode": False,
            "interface": "GPM",
            "logical_channel": 12,
            "name": "InternalTrafficHiChannel",
        },
        "43": {
            "drain_mode": False,
            "interface": "GPM",
            "logical_channel": 13,
            "name": "InternalTrafficLoChannel",
        },
        "44": {
            "drain_mode": False,
            "interface": "GPM",
            "logical_channel": 14,
            "name": "AttnTrafficHiChannel",
        },
        "45": {
            "drain_mode": False,
            "interface": "GPM",
            "logical_channel": 15,
            "name": "MetaPktTrafficChannel",
        },
        "46": {"name": "unmapped"},
        "47": {"name": "unmapped"},
        "48": {"name": "unmapped"},
        "49": {"name": "unmapped"},
        "5": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 5,
            "name": "CC1 Hi",
        },
        "50": {"name": "unmapped"},
        "51": {"name": "unmapped"},
        "52": {"name": "unmapped"},
        "53": {"name": "unmapped"},
        "54": {"name": "unmapped"},
        "55": {
            "drain_mode": True,
            "interface": "GPM",
            "logical_channel": 0,
            "name": "Drain Low",
        },
        "6": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 6,
            "name": "CC1B Low",
        },
        "7": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 7,
            "name": "CC1B Hi",
        },
        "8": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 8,
            "name": "CC2 Low",
        },
        "9": {
            "drain_mode": False,
            "interface": "SPI0",
            "logical_channel": 9,
            "name": "CC2 Hi",
        },
    }
}
