

expected_output = {
    'isis': {
        'test': {
            'vrf': {
                'default': {
                    'level': {
                        'Level-1': {
                            'interfaces': {
                                'Gi0/0/0/0.115': {
                                    'system_id': {
                                        'R1_xe': {
                                            'interface': 'GigabitEthernet0/0/0/0.115',
                                            'snpa': 'fa16.3eff.4f49',
                                            'state': 'Up',
                                            'hold': '23',
                                            'changed': '22:30:27',
                                            'nsf': 'Yes',
                                            'ipv4_bfd': 'None',
                                            'ipv6_bfd': 'None'}}},
                                'Gi0/0/0/1.115': {
                                    'system_id': {
                                        'R3_nx': {
                                            'interface': 'GigabitEthernet0/0/0/1.115',
                                            'snpa': '5e00.40ff.0209',
                                            'state': 'Up',
                                            'hold': '20',
                                            'changed': '22:30:27',
                                            'nsf': 'Yes',
                                            'ipv4_bfd': 'None',
                                            'ipv6_bfd': 'None'}}}},
                            'total_adjacency_count': 2},
                        'Level-2': {
                            'interfaces': {
                                'Gi0/0/0/0.115': {
                                    'system_id': {
                                        'R1_xe': {
                                            'interface': 'GigabitEthernet0/0/0/0.115',
                                            'snpa': 'fa16.3eff.4f49',
                                            'state': 'Up',
                                            'hold': '26',
                                            'changed': '22:30:26',
                                            'nsf': 'Yes',
                                            'ipv4_bfd': 'None',
                                            'ipv6_bfd': 'None'}}},
                                'Gi0/0/0/1.115': {
                                    'system_id': {
                                        'R3_nx': {
                                            'interface': 'GigabitEthernet0/0/0/1.115',
                                            'snpa': '5e00.40ff.0209',
                                            'state': 'Up',
                                            'hold': '23',
                                            'changed': '22:30:27',
                                            'nsf': 'Yes',
                                            'ipv4_bfd': 'None',
                                            'ipv6_bfd': 'None'}}}},
                            'total_adjacency_count': 2}}}}},
        'test1': {
            'vrf': {
                'default': {
                    'level': {
                        'Level-1': {},
                        'Level-2': {}}}}}}}
