

expected_output = {
    'isis': {
        'p': {
            'vrf': {
                'default': {
                    'level': {
                        'Level-1': {
                            'interfaces': {
                                'PO0/1/0/1': {
                                    'system_id': {
                                        '12a4': {
                                            'interface': 'Port-channel0/1/0/1',
                                            'snpa': '*PtoP*',
                                            'state': 'Up',
                                            'hold': '23',
                                            'changed': '00:00:06',
                                            'nsf': 'Capable',
                                            'bfd': 'Init'}}},
                                'Gi0/6/0/2': {
                                    'system_id': {
                                        '12a4': {
                                            'interface': 'GigabitEthernet0/6/0/2',
                                            'snpa': '0004.28ff.868a',
                                            'state': 'Up',
                                            'hold': '56',
                                            'changed': '00:04:01',
                                            'nsf': 'Capable',
                                            'bfd': 'Up'}}}},
                            'total_adjacency_count': 2},
                        'Level-2': {
                            'interfaces': {
                                'PO0/1/0/1': {
                                    'system_id': {
                                        '12a4': {
                                            'interface': 'Port-channel0/1/0/1',
                                            'snpa': '*PtoP*',
                                            'state': 'Up',
                                            'hold': '23',
                                            'changed': '00:00:06',
                                            'nsf': 'Capable',
                                            'bfd': 'None'}}},
                                'Gi0/6/0/2': {
                                    'system_id': {
                                        '12a4': {
                                            'interface': 'GigabitEthernet0/6/0/2',
                                            'snpa': '0004.28ff.868a',
                                            'state': 'Up',
                                            'hold': '26',
                                            'changed': '00:00:13',
                                            'nsf': 'Capable',
                                            'bfd': 'Init'}}}},
                            'total_adjacency_count': 2}}}}}}}
