expected_output = {
   "acl_usage":{
      "ace_software":{
         "used":263,
         "vmr_max":196608
      },
      "acl_name":{
         "pbr-acl":{
            "direction":{
               "Ingress":{
                  "acl_type":"IPV4",
                  "entries_used":2,
                  "feature_type":"RACL"
               }
            }
         }
      }
   }
}
