expected_output = {
   "alarm_relay_mode":"Positive",
   "power_supply":{
      "alarm":"Enabled",
      "relay":"",
      "notifies":"Disabled",
      "syslog":"Enabled"
   },
   "temperature_primary":{
      "alarm":"Enabled",
      "threshold":{
         "max_temp":"90C",
         "min_temp":"-40C"
      },
      "relay":"MAJ",
      "notifies":"Enabled",
      "syslog":"Enabled"
   },
   "temperature_secondary":{
      "alarm":"Disabled",
      "threshold":{
         
      },
      "relay":"",
      "notifies":"Disabled",
      "syslog":"Disabled"
   },
   "sd_card":{
      "alarm":"Disabled",
      "relay":"",
      "notifies":"Disabled",
      "syslog":"Disabled"
   },
   "input_alarm_1":{
      "alarm":"Enabled",
      "relay":"",
      "notifies":"Disabled",
      "syslog":"Enabled"
   },
   "input_alarm_2":{
      "alarm":"Enabled",
      "relay":"",
      "notifies":"Disabled",
      "syslog":"Enabled"
   },
   "dlr":{
      "alarm":"Disabled",
      "relay":"",
      "notifies":"Disabled",
      "syslog":"Disabled"
   }
}
