

expected_output = {
    'clock_state': {'system_status': {'clock_state': 'unsynchronized'}},
    'total_peers': 4,
    'vrf': {'VRF1': {'peer': {'10.64.4.4': {'delay': 0.0,
                                          'local': '0.0.0.0',
                                          'mode': 'client',
                                          'poll': 256,
                                          'reach': 0,
                                          'remote': '10.64.4.4',
                                          'stratum': 16,
                                          'vrf': 'VRF1'}}},
            'default': {'peer': {'10.4.1.1': {'delay': 0.01311,
                                             'local': '0.0.0.0',
                                             'mode': 'client',
                                             'poll': 16,
                                             'reach': 377,
                                             'remote': '10.4.1.1',
                                             'stratum': 8,
                                             'vrf': 'default'},
                                 '10.16.2.2': {'delay': 0.01062,
                                             'local': '0.0.0.0',
                                             'mode': 'client',
                                             'poll': 16,
                                             'reach': 377,
                                             'remote': '10.16.2.2',
                                             'stratum': 9,
                                             'vrf': 'default'},
                                 '10.100.5.5': {'delay': 0.0,
                                             'local': '0.0.0.0',
                                             'mode': 'client',
                                             'poll': 64,
                                             'reach': 0,
                                             'remote': '10.100.5.5',
                                             'stratum': 16,
                                             'vrf': 'default'}}}}
}
