expected_output = {
     'slot':{
        2:{
            'port_group':{
                1:{
                    'port':{
                        'Hu2/0/25':{
                            'mode':'100G'
                        },
                        'Hu2/0/26':{
                            'mode':'100G'
                        },
                        'Fou2/0/27':{
                            'mode':'100G'
                        },
                        'Hu2/0/28':{
                            'mode':'100G'
                        }
                    }
                },
                2:{
                    'port':{
                        'Hu2/0/29':{
                            'mode':'100G'
                        },
                        'Hu2/0/30':{
                            'mode':'100G'
                        },
                        'Fou2/0/31':{
                            'mode':'100G'
                        },
                        'Hu2/0/32':{
                            'mode':'100G'
                        }
                    }
                }
            }
        }
    }
}