expected_output = {
    'queues': {
        'DHCP snooping': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'DOT1X authentication': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'EWLC control': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'EWLC data': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Exception': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Forus Resolution': {
            'retrieved': 516148,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Forus Traffic': {
            'retrieved': 26032,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'High rate app': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Inter FED': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'L2 LVX control': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'L2 LVX data': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'L2 Protocol': {
            'retrieved': 23362,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Multi End station': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Openflow': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Proto snooping': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Routing Protocol': {
            'retrieved': 327,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'System Critical': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Topology control': {
            'retrieved': 136276,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Transit Traffic': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'Webauth': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'broadcast': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'icmp gen': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'icmp redirect': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'logging': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'rpf-fail': {
            'retrieved': 0,
            'dropped': 0,
            'invalid': 0,
            'hol_block': 0,
        },
        'sw forwarding': {
            'retrieved': 433,
            'dropped': 425,
            'invalid': 0,
            'hol_block': 0,
        },
    }
}