expected_output = {
    'TwentyFiveGigE0/0/18': {
        'description': 'None',
        'signal_type': 'NA',
        'mode': 'Synchronous (Ql-enabled)',
        'esmc_tx': 'ENABLED',
        'esmc_rx': 'ENABLED',
        'ql_receive': 'QL-SEC',
        'ql_receive_configured': '-',
        'ql_receive_overrided': '-',
        'ql_transmit': 'QL-SEC',
        'ql_transmit_configured': '-',
        'hold_off_time': 600,
        'hold_off_configured': 'TRUE',
        'wait_to_restore': 40,
        'wtr_configured': 'FALSE',
        'lock_out': 'FALSE',
        'signal_fail': 'FALSE',
        'alarms': 'FALSE',
        'reason_for_alarm_flag': 0,
        'slot_disabled': 'FALSE',
        'hold_off_timer': 'STOPPED',
        'wait_to_restore_timer': 'STOPPED',
        'switchover_timer': 'STOPPED',
        'esmc_tx_timer': 'RUNNING',
        'esmc_rx_timer': 'RUNNING',
        'tsm_delay_timer': 'STOPPED'
    },
    't0': {
        'selected_source': 'FALSE',
        'priority': 4,
        'force_switch': 'FALSE',
        'manual_switch': 'FALSE',
        'manual_switch_in_progress': 'FALSE',
        'not_use': 'FALSE',
        'been_selected': 'TRUE',
        'snmp_input_source_index': 10,
        'snmp_parent_source_index': 0,
        'intf_sig_nv': '0'
    }
}
