expected_output = {
    "mac_address": {
        "0027.900a.ff68": {
            "interface": "Te6/1/2",
            "state": "offline",
            "role": "Aux",
            "ha": "Act",
            "auth": "N/A",
            "ipv6_address": "2002::7979:7943",
        },
        "0027.900b.0dc6": {
            "interface": "Te6/1/2",
            "state": "online",
            "role": "Aux",
            "ha": "Act",
            "auth": "N/A",
            "ipv6_address": "2002::C08C:28A3",
        },
        "0027.900b.0e26": {
            "interface": "Te6/1/2",
            "state": "!online",
            "role": "Aux",
            "ha": "Act",
            "auth": "N/A",
            "ipv6_address": "2002::C08C:28C4",
        },
        "7872.5d49.bdda": {
            "interface": "Te6/1/0",
            "state": "online",
            "role": "Pri",
            "ha": "Act",
            "auth": "N/A",
            "ipv6_address": "2002::C08C:2852",
        },
        "7872.5d49.bf7e": {
            "interface": "Te6/1/0",
            "state": "online",
            "role": "Pri",
            "ha": "Act",
            "auth": "N/A",
            "ipv6_address": "2002::7878:789E",
        },
        "7872.5d49.bfa2": {
            "interface": "Te6/1/0",
            "state": "online",
            "role": "Pri",
            "ha": "Act",
            "auth": "N/A",
            "ipv6_address": "2002::C08C:2820",
        },
        "f4db.e6b4.eaae": {
            "interface": "Te6/1/2",
            "state": "!online",
            "role": "Aux",
            "ha": "Act",
            "auth": "N/A",
            "ipv6_address": "2002::C0AF:AF74",
        },
    }
}
