expected_output = {
    "crypto_isakmp_performance_stats": {
        "ingress": {
            "ike_established": {
                "sample_size": 0,
                "tps_avg": 0,
                "tps_min": 0,
                "tps_max": 0,
                "cpu_avg": 0,
                "cpu_min": 0,
                "cpu_max": 0,
            },
            "ipsec_child_establishe": {
                "sample_size": 0,
                "tps_avg": 0,
                "tps_min": 0,
                "tps_max": 0,
                "cpu_avg": 0,
                "cpu_min": 0,
                "cpu_max": 0,
            },
            "ike_child_established": {
                "sample_size": 0,
                "tps_avg": 0,
                "tps_min": 0,
                "tps_max": 0,
                "cpu_avg": 0,
                "cpu_min": 0,
                "cpu_max": 0,
            },
        },
        "egress": {
            "ike_established": {
                "sample_size": 0,
                "tps_avg": 0,
                "tps_min": 0,
                "tps_max": 0,
                "cpu_avg": 0,
                "cpu_min": 0,
                "cpu_max": 0,
            },
            "ipsec_child_establishe": {
                "sample_size": 0,
                "tps_avg": 0,
                "tps_min": 0,
                "tps_max": 0,
                "cpu_avg": 0,
                "cpu_min": 0,
                "cpu_max": 0,
            },
            "ike_child_established": {
                "sample_size": 0,
                "tps_avg": 0,
                "tps_min": 0,
                "tps_max": 0,
                "cpu_avg": 0,
                "cpu_min": 0,
                "cpu_max": 0,
            },
        },
    },
    "crypto_isakmp_packet_stats": {
        "incoming_ike_packets": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "init": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "auth": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "no_name_0": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "no_name_1": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "child": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "info": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "default": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "egress_ike_attempted": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
    },
    "crypto_ikev2_packet_queue_stats": {
        "packet_queue0": {"sample_size": 108221, "avg": 0, "min": 0, "max": 1008},
        "packet_queue1": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "packet_queue2": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "packet_queue3": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "packet_queue4": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "packet_queue5": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "packet_queue6": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
    },
    "crypto_isakmp_protocol_stats": {
        "r_init_proc": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_init_proc": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_auth_proc": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_auth_proc": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_init_int": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_auth_int": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_auth_int": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_init_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_init_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_auth_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_auth_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_init_wire": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_auth_wire": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_auth_wire": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_cookie_int": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_cookie_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ke_int": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ke_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_ike_child_proc": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_ipsec_child_proc": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ike_child_proc": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ipsec_child_proc": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ike_child_wire": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ipsec_child_wire": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_ike_child_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_ipsec_child_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ike_child_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ipsec_child_send": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ike_child_int": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "r_ipsec_child_int": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_ike_child_int": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "i_ipsec_child_int": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
    },
    "crypto_engine_stats": {
        "dh_create": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "dh_share_secret": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "dh_delete": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "create_ike_sa": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "delete_ike_sa": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "ps_key_auth_generation": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "rsa_public_key_auth_ge": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "ike_encrypt": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "ike_decrypt": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "ike_hmac": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "ipsec_create_key": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "ipsec_delete_sa": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "public_key_sign": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "public_key_verify": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "public_key_encrypt": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "public_key_decrypt": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
    },
    "external_service_stats": {
        "get_ike_policy": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "get_preshared_key": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "get_config_mode_data": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "set_config_mode_data": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "received_eap": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "recieved_client_eap": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "verify_certificate": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "fetch_certificate": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "get_ipsec_policy": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "no_name_2": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "redirect_check": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "redirect_acceptance_ch": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "no_name_3": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
        "no_name_4": {"sample_size": 0, "avg": 0, "min": 0, "max": 0},
    },
    "summary": {
        "main": {
            "exchange_setup_value": 0,
            "main_processing": {"value": 0, "percentage": 0},
            "on_ipc_queue": {"value": 0, "percentage": 0},
            "transmission": {"value": 0, "percentage": 0},
        },
        "child": {
            "exchange_setup_value": 0,
            "child_processing": {"value": 0, "percentage": 0},
            "transmission": {"value": 0, "percentage": 0},
        },
    },
}

