expected_output = {
    'message_types': {
        'solicit': {'rx': 40, 'tx': 0, 'drops': 0},
        'advertise': {'rx': 0, 'tx': 40, 'drops': 0},
        'request': {'rx': 40, 'tx': 0, 'drops': 0},
        'confirm': {'rx': 0, 'tx': 0, 'drops': 0},
        'renew': {'rx': 20, 'tx': 0, 'drops': 0},
        'rebind': {'rx': 0, 'tx': 0, 'drops': 0},
        'reply': {'rx': 0, 'tx': 90, 'drops': 0},
        'release': {'rx': 30, 'tx': 0, 'drops': 0},
        'decline': {'rx': 0, 'tx': 0, 'drops': 0},
        'reconfigure': {'rx': 0, 'tx': 0, 'drops': 0},
        'information_request': {'rx': 0, 'tx': 0, 'drops': 0},
        'relay_fwd': {'rx': 0, 'tx': 130, 'drops': 0},
        'relay_reply': {'rx': 130, 'tx': 0, 'drops': 0},
        'unknown': {'rx': 0, 'tx': 0, 'drops': 0},
        'total': {'rx': 260, 'tx': 260, 'drops': 0},
    },
    'server_stats': {
        'relay_address': '192:0:2::42',
        'destination_interface': 'Ethernet1/2',
        'vrf_name': 'vxlan-1001',
        'request': 130,
        'response': 130,
    },
    'drops': {
        'dhcpv6_relay_is_disabled': 0,
        'max_hops_exceeded': 0,
        'packet_validation_fails': 0,
        'unknown_output_interface': 0,
        'invalid_vrf': 0,
        'option_insertion_failed': 0,
        'direct_replies': 0,
        'ipv6_addr_not_configured': 0,
        'interface_error': 0,
        'vpn_option_disabled': 0,
        'ipv6_extn_headers_present': 0,
        'dhcp_request_dropped_on_mct': 0,
    },
}