expected_output = {
    "cpu_utilization": {
        "cpu_util_five_secs": "0%",
        "cpu_util_one_min": "0%",
        "cpu_util_five_min": "0%",
        "core": {
            "Core 2": {
                "core_cpu_util_five_secs": "0%",
                "core_cpu_util_one_min": "0%",
                "core_cpu_util_five_min": "0%",
            },
            "Core 3": {
                "core_cpu_util_five_secs": "0%",
                "core_cpu_util_one_min": "0%",
                "core_cpu_util_five_min": "0%",
            },
            "Core 4": {
                "core_cpu_util_five_secs": "0%",
                "core_cpu_util_one_min": "0%",
                "core_cpu_util_five_min": "0%",
            },
            "Core 5": {
                "core_cpu_util_five_secs": "0%",
                "core_cpu_util_one_min": "0%",
                "core_cpu_util_five_min": "0%",
            },
            "Core 14": {
                "core_cpu_util_five_secs": "0%",
                "core_cpu_util_one_min": "0%",
                "core_cpu_util_five_min": "0%",
            },
            "Core 15": {
                "core_cpu_util_five_secs": "0%",
                "core_cpu_util_one_min": "0%",
                "core_cpu_util_five_min": "0%",
            },
            "Core 16": {
                "core_cpu_util_five_secs": "0%",
                "core_cpu_util_one_min": "0%",
                "core_cpu_util_five_min": "0%",
            },
            "Core 17": {
                "core_cpu_util_five_secs": "0%",
                "core_cpu_util_one_min": "0%",
                "core_cpu_util_five_min": "0%",
            },
        },
    },
    "plane_process_utilization": {
        "cpu_util_five_secs": "0%",
        "cpu_util_one_min": "0%",
        "cpu_util_five_min": "0%",
    },
    "pid": {
        "13168": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 9728,
            "name": "libvirt_lxc",
        },
        "13170": {
            "ppid": 13168,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 176,
            "name": "tini",
        },
        "13197": {
            "ppid": 13170,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 176,
            "name": "runsvdir",
        },
        "13857": {
            "ppid": 13197,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 176,
            "name": "runsv",
        },
        "13858": {
            "ppid": 13197,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 176,
            "name": "runsv",
        },
        "13859": {
            "ppid": 13857,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 1056,
            "name": "run",
        },
        "13860": {
            "ppid": 13858,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 14212,
            "name": "te-agent",
        },
        "13865": {
            "ppid": 13859,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 176,
            "name": "inotifywait",
        },
    },
}
