expected_output = {
    "cpu_utilization": {
        "cpu_util_five_secs": "5%",
        "cpu_util_one_min": "3%",
        "cpu_util_five_min": "3%",
        "core": {
            "Core 0": {
                "core_cpu_util_five_secs": "6%",
                "core_cpu_util_one_min": "3%",
                "core_cpu_util_five_min": "3%",
            },
            "Core 1": {
                "core_cpu_util_five_secs": "8%",
                "core_cpu_util_one_min": "4%",
                "core_cpu_util_five_min": "3%",
            },
            "Core 12": {
                "core_cpu_util_five_secs": "6%",
                "core_cpu_util_one_min": "3%",
                "core_cpu_util_five_min": "3%",
            },
            "Core 13": {
                "core_cpu_util_five_secs": "3%",
                "core_cpu_util_one_min": "3%",
                "core_cpu_util_five_min": "3%",
            },
        },
    },
    "plane_process_utilization": {
        "cpu_util_five_secs": "25%",
        "cpu_util_one_min": "15%",
        "cpu_util_five_min": "12%",
    },
    "pid": {
        "1": {
            "ppid": 0,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 19068,
            "name": "systemd",
        },
        "365": {
            "ppid": 13994,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 528,
            "name": "sleep",
        },
        "660": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 6460,
            "name": "systemd-journal",
        },
        "718": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2372,
            "name": "auditd",
        },
        "736": {
            "ppid": 718,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 1728,
            "name": "audisp-syslog",
        },
        "741": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2504,
            "name": "rpc.idmapd",
        },
        "781": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2880,
            "name": "nfsdcld",
        },
        "786": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 9096,
            "name": "systemd-udevd",
        },
        "2870": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 9156,
            "name": "droputil.sh",
        },
        "2873": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2908,
            "name": "oom.sh",
        },
        "2875": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 768,
            "name": "sntp",
        },
        "2887": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 17892,
            "name": "libvirtd",
        },
        "2893": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 6912,
            "name": "virtlogd",
        },
        "2924": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 768,
            "name": "xinetd",
        },
        "2965": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 596,
            "name": "rpcbind",
        },
        "2999": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2304,
            "name": "rotee",
        },
        "3003": {
            "ppid": 2873,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 576,
            "name": "sleep",
        },
        "3010": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 384,
            "name": "rpc.statd",
        },
        "3014": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 1420,
            "name": "rpc.mountd",
        },
        "3338": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2304,
            "name": "rotee",
        },
        "3440": {
            "ppid": 2870,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 576,
            "name": "inotifywait",
        },
        "3532": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 8832,
            "name": "reflector.sh",
        },
        "3655": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2304,
            "name": "rotee",
        },
        "3741": {
            "ppid": 3532,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 852,
            "name": "inotifywait",
        },
        "3759": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 5568,
            "name": "iptbl.sh",
        },
        "3902": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2304,
            "name": "rotee",
        },
        "4076": {
            "ppid": 3759,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 576,
            "name": "inotifywait",
        },
        "7383": {
            "ppid": 1,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 880,
            "name": "xinetd",
        },
        "9476": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "9482": {
            "ppid": 9476,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 29012,
            "name": "psd",
        },
        "9755": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2768,
            "name": "pman",
        },
        "9766": {
            "ppid": 9755,
            "five_sec": "1%",
            "one_min": "1%",
            "five_min": "1%",
            "status": "S",
            "size": 762772,
            "name": "linux_iosd-imag",
        },
        "9984": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "9990": {
            "ppid": 9984,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 20768,
            "name": "vman",
        },
        "10173": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "10186": {
            "ppid": 10173,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 73744,
            "name": "sessmgrd",
        },
        "10434": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "10447": {
            "ppid": 10434,
            "five_sec": "0%",
            "one_min": "2%",
            "five_min": "0%",
            "status": "R",
            "size": 121508,
            "name": "smand",
        },
        "10899": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "10906": {
            "ppid": 10899,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 23232,
            "name": "repm",
        },
        "11045": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "11052": {
            "ppid": 11045,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 11380,
            "name": "plogd",
        },
        "11690": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "11696": {
            "ppid": 11690,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "R",
            "size": 30312,
            "name": "hman",
        },
        "11823": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "11830": {
            "ppid": 11823,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 87472,
            "name": "fman_rp",
        },
        "12062": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "12069": {
            "ppid": 12062,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 4576,
            "name": "flash_check.sh",
        },
        "12287": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "12294": {
            "ppid": 12287,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 114752,
            "name": "dbm",
        },
        "12421": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "12427": {
            "ppid": 12421,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 76560,
            "name": "cmand",
        },
        "12660": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "12679": {
            "ppid": 12660,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 42944,
            "name": "cli_agent",
        },
        "13356": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "13370": {
            "ppid": 13356,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 31880,
            "name": "btman",
        },
        "13683": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "13696": {
            "ppid": 13683,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 9680,
            "name": "tams_proc",
        },
        "13869": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "13876": {
            "ppid": 13869,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 8800,
            "name": "tamd_proc",
        },
        "13987": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "13994": {
            "ppid": 13987,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 1760,
            "name": "sort_files_by_i",
        },
        "14843": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "14855": {
            "ppid": 14843,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 8096,
            "name": "tam_svcs_esg_cf",
        },
        "15721": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "15739": {
            "ppid": 15721,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 5632,
            "name": "autodns",
        },
        "16487": {
            "ppid": 16179,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "16494": {
            "ppid": 16487,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 21120,
            "name": "hman",
        },
        "16593": {
            "ppid": 16179,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2816,
            "name": "pman",
        },
        "16600": {
            "ppid": 16593,
            "five_sec": "1%",
            "one_min": "1%",
            "five_min": "1%",
            "status": "S",
            "size": 162860,
            "name": "fman_fp_image",
        },
        "16797": {
            "ppid": 16179,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "16804": {
            "ppid": 16797,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 70928,
            "name": "cpp_sp_svr",
        },
        "16899": {
            "ppid": 16179,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "16906": {
            "ppid": 16899,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 59136,
            "name": "cpp_ha_top_leve",
        },
        "17001": {
            "ppid": 16179,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "17008": {
            "ppid": 17001,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 54912,
            "name": "cpp_driver",
        },
        "17103": {
            "ppid": 16179,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "17110": {
            "ppid": 17103,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 182776,
            "name": "cpp_cp_svr",
        },
        "17205": {
            "ppid": 16179,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "17211": {
            "ppid": 17205,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 21296,
            "name": "cman_fp",
        },
        "17307": {
            "ppid": 16179,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "17313": {
            "ppid": 17307,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 15664,
            "name": "btman",
        },
        "17981": {
            "ppid": 17540,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "17988": {
            "ppid": 17981,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 20944,
            "name": "hman",
        },
        "18138": {
            "ppid": 17540,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "18145": {
            "ppid": 18138,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 22528,
            "name": "cmcc",
        },
        "18581": {
            "ppid": 17540,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "18594": {
            "ppid": 18581,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 16016,
            "name": "btman",
        },
        "18907": {
            "ppid": 17540,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "18914": {
            "ppid": 18907,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 46768,
            "name": "iomd",
        },
        "19127": {
            "ppid": 17540,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "19134": {
            "ppid": 19127,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 46604,
            "name": "iomd",
        },
        "19508": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "19514": {
            "ppid": 19508,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 87296,
            "name": "paed",
        },
        "19638": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2816,
            "name": "pman",
        },
        "19645": {
            "ppid": 19638,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 10384,
            "name": "autodns.py",
        },
        "19755": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2816,
            "name": "pman",
        },
        "19761": {
            "ppid": 19755,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 7744,
            "name": "run_ioxn_caf.sh",
        },
        "21173": {
            "ppid": 17540,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "21185": {
            "ppid": 21173,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 13552,
            "name": "ngiolite",
        },
        "21210": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "21221": {
            "ppid": 21210,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 33792,
            "name": "ioxman",
        },
        "21415": {
            "ppid": 17540,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "21422": {
            "ppid": 21415,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 13904,
            "name": "ngiolite",
        },
        "21507": {
            "ppid": 19761,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 72964,
            "name": "python3",
        },
        "21508": {
            "ppid": 21507,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 6940,
            "name": "run_ioxn_caf.sh",
        },
        "21509": {
            "ppid": 21508,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 704,
            "name": "sed",
        },
        "21510": {
            "ppid": 21508,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 528,
            "name": "logger",
        },
        "22181": {
            "ppid": 7383,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 1056,
            "name": "tftpd",
        },
        "22986": {
            "ppid": 9063,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 2640,
            "name": "pman",
        },
        "22993": {
            "ppid": 22986,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 15752,
            "name": "nginx",
        },
        "23050": {
            "ppid": 22993,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 8764,
            "name": "nginx",
        },
        "23051": {
            "ppid": 22993,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 8052,
            "name": "nginx",
        },
        "31783": {
            "ppid": 12069,
            "five_sec": "0%",
            "one_min": "0%",
            "five_min": "0%",
            "status": "S",
            "size": 528,
            "name": "sleep",
        },
    },
}
