

expected_output = {
    'vlans':
        {'1': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                  'mac_aging_time': '-',
                                                  'mac_type': 'static',
                                                  'ntfy': 'F',
                                                  'ports': 'sup-eth1(R)',
                                                  'secure': 'F'}}},
       '100': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'},
                                 'fa16.3eff.2a0c': {'entry': '*',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': '(0x47000001) '
                                                             'nve-peer1 '
                                                             '93.1.1.',
                                                    'secure': 'F'},
                                 'fa16.3eff.6b31': {'entry': '*',
                                                    'mac_aging_time': '00:01:43',
                                                    'mac_type': 'dynamic',
                                                    'ntfy': 'F',
                                                    'ports': 'Eth1/4',
                                                    'secure': 'F'}}},
       '1000': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                     'mac_aging_time': '-',
                                                     'mac_type': 'static',
                                                     'ntfy': 'F',
                                                     'ports': 'sup-eth1(R)',
                                                     'secure': 'F'}}},
       '1005': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                     'mac_aging_time': '-',
                                                     'mac_type': 'static',
                                                     'ntfy': 'F',
                                                     'ports': 'sup-eth1(R)',
                                                     'secure': 'F'}}},
       '1006': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                     'mac_aging_time': '-',
                                                     'mac_type': 'static',
                                                     'ntfy': 'F',
                                                     'ports': 'sup-eth1(R)',
                                                     'secure': 'F'}}},
       '1007': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                     'mac_aging_time': '-',
                                                     'mac_type': 'static',
                                                     'ntfy': 'F',
                                                     'ports': 'sup-eth1(R)',
                                                     'secure': 'F'}}},
       '1008': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                     'mac_aging_time': '-',
                                                     'mac_type': 'static',
                                                     'ntfy': 'F',
                                                     'ports': 'sup-eth1(R)',
                                                     'secure': 'F'}}},
       '1009': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                     'mac_aging_time': '-',
                                                     'mac_type': 'static',
                                                     'ntfy': 'F',
                                                     'ports': 'sup-eth1(R)',
                                                     'secure': 'F'}}},
       '101': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '102': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '103': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '105': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '106': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '107': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '108': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '109': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '110': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '111': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '112': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '113': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}},
       '114': {'mac_addresses': {'5e01.80ff.0007': {'entry': 'G',
                                                    'mac_aging_time': '-',
                                                    'mac_type': 'static',
                                                    'ntfy': 'F',
                                                    'ports': 'sup-eth1(R)',
                                                    'secure': 'F'}}}}}
