expected_output = {
    "watts": {
        "1": {"module": "1", "available": 1550.0, "used": 147.0, "remaining": 1403.0},
        "2": {"module": "2", "available": 1550.0, "used": 424.7, "remaining": 1125.3},
        "3": {"module": "3", "available": 1550.0, "used": 397.4, "remaining": 1152.6},
        "4": {"module": "4", "available": 1550.0, "used": 267.0, "remaining": 1283.0},
        "5": {"module": "5", "available": 1550.0, "used": 80.6, "remaining": 1469.4},
    },
    "interface": {
        "GigabitEthernet1/0/1": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet1/0/2": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet1/0/3": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet2/0/1": {
            "power": 7.1,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "on",
            "device": "IP Phone 8845",
            "class": "2",
        },
        "GigabitEthernet2/0/2": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet2/0/3": {
            "power": 26.1,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "on",
            "device": "AIR-AP2802I-E-K9",
            "class": "4",
        },
        "GigabitEthernet3/0/1": {
            "power": 26.1,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "on",
            "device": "AIR-AP2802I-E-K9",
            "class": "4",
        },
        "GigabitEthernet3/0/2": {
            "power": 26.1,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "on",
            "device": "AIR-AP2802I-E-K9",
            "class": "4",
        },
        "GigabitEthernet4/0/1": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet4/0/2": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet4/0/3": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet4/0/4": {
            "power": 14.8,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "on",
            "device": "IP Phone 8865",
            "class": "4",
        },
        "GigabitEthernet5/0/1": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/2": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/3": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/4": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/5": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/6": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/7": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/8": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/9": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/10": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/11": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/12": {
            "power": 0.0,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "off",
        },
        "GigabitEthernet5/0/13": {
            "power": 15.2,
            "max": 30.0,
            "admin_state": "auto",
            "oper_state": "on",
            "device": "IP Phone 8865",
            "class": "4",
        },
    },
}
