expected_output = {'ap_name': {'AP002a.106d.2e10': {'backup_image': '0.0.0.0',
                                                    'method': 'N/A',
                                                    'next_retry_time': 'N/A',
                                                    'predownload_status': 'None',
                                                    'predownload_version': '0.0.0.0',
                                                    'primary_image': '17.13.0.44',
                                                    'retry_count': 0},
                               'AP4001.7AB2.C1B6': {'backup_image': '17.13.0.30',
                                                    'method': 'N/A',
                                                    'next_retry_time': 'N/A',
                                                    'predownload_status': 'None',
                                                    'predownload_version': '0.0.0.0',
                                                    'primary_image': '17.13.0.44',
                                                    'retry_count': 0},
                               'AP501C.B0BC.1448': {'backup_image': '17.13.0.30',
                                                    'method': 'N/A',
                                                    'next_retry_time': 'N/A',
                                                    'predownload_status': 'None',
                                                    'predownload_version': '0.0.0.0',
                                                    'primary_image': '17.13.0.44',
                                                    'retry_count': 0},
                               'APF4DB.E651.2280': {'backup_image': '17.13.0.30',
                                                    'method': 'N/A',
                                                    'next_retry_time': 'N/A',
                                                    'predownload_status': 'None',
                                                    'predownload_version': '0.0.0.0',
                                                    'primary_image': '17.13.0.44',
                                                    'retry_count': 0},
                               'wsimap-0001': {'backup_image': '8.3.15.109',
                                               'method': 'N/A',
                                               'next_retry_time': 'N/A',
                                               'predownload_status': 'None',
                                               'predownload_version': '0.0.0.0',
                                               'primary_image': '17.13.0.44',
                                               'retry_count': 0}},
                   'number_of_aps': {'completed_downloading': 4,
                                     'completed_predownloading': 0,
                                     'downloading': 0,
                                     'failed_to_predownload': 0,
                                     'initiated': 0,
                                     'not_supported': 0,
                                     'predownload_in_progress': 'No',
                                     'predownloading': 0},
                   'total_number_of_aps': 5}
