expected_output = {
      "groups":{
         "bw-suiteB":{
            "group_members":{
               "46.46.46.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":2001,
                  "group_name":"bw-suiteB",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"15.15.15.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               },
               "56.56.56.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":2001,
                  "group_name":"bw-suiteB",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"16.16.16.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               }
            },
            "last_rekey_duration":1,
            "rekeys_sent":0,
            "retransmits_num":0
         },
         "bw-suiteB-v6":{
            "group_members":{
               "42.42.42.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":2002,
                  "group_name":"bw-suiteB-v6",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"15.15.15.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               },
               "52.52.52.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":2002,
                  "group_name":"bw-suiteB-v6",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"16.16.16.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               }
            },
            "last_rekey_duration":1,
            "rekeys_sent":0,
            "retransmits_num":0
         },
         "bw600-IPV6":{
            "group_members":{
               "41.41.41.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":6600,
                  "group_name":"bw600-IPV6",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"15.15.15.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               },
               "51.51.51.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":6600,
                  "group_name":"bw600-IPV6",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"16.16.16.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               }
            },
            "last_rekey_duration":10001,
            "rekeys_sent":0,
            "retransmits_num":0
         },
         "bw600-IPV6_eft":{
            "group_members":{
               "43.43.43.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":2233,
                  "group_name":"bw600-IPV6_eft",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"15.15.15.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               },
               "53.53.53.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":2233,
                  "group_name":"bw600-IPV6_eft",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"16.16.16.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               }
            },
            "last_rekey_duration":10001,
            "rekeys_sent":0,
            "retransmits_num":0
         },
         "bw6000":{
            "group_members":{
               "44.44.44.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":6000,
                  "group_name":"bw6000",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"15.15.15.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               },
               "54.54.54.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":6000,
                  "group_name":"bw6000",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"16.16.16.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               }
            },
            "last_rekey_duration":10000,
            "rekeys_sent":0,
            "retransmits_num":0
         },
         "bw6000_eft":{
            "group_members":{
               "45.45.45.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":1122,
                  "group_name":"bw6000_eft",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"15.15.15.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               },
               "55.55.55.1":{
                  "gm_state":"Registered",
                  "gm_version":"1.0.25",
                  "group_id":1122,
                  "group_name":"bw6000_eft",
                  "group_type":"GDOI (ISAKMP)",
                  "key_server_id":"16.16.16.1",
                  "rcvd_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  },
                  "rekey_acks_missed":0,
                  "rekey_acks_rcvd":0,
                  "rekeys_retries":0,
                  "rekeys_sent":0,
                  "sent_seq_num":{
                     "seq1":0,
                     "seq2":0,
                     "seq3":0,
                     "seq4":0
                  }
               }
            },
            "last_rekey_duration":10001,
            "rekeys_sent":0,
            "retransmits_num":0
         }
      }
   }