expected_output = {
   "Tunnel":{
      "Decap_Pass":{
         "0":{
            "RI":"0x1b2",
            "SI":"0x4d0",
            "SI_DI":"0x5012",
            "SI_RI":"0x1b2",
            "asic_instance":0,
            "rcpServiceID":"0",
            "replication_bitmap":"LD"
         },
         "1":{
            "RI":"0x1b2",
            "SI":"0x4d0",
            "SI_DI":"0x5012",
            "SI_RI":"0x1b2",
            "asic_instance":1,
            "rcpServiceID":"0",
            "replication_bitmap":"RD"
         },
         "DI":"0x5012"
      },
      "Decrypt_Pass":{
         "0":{
            "RI":"0x1b0",
            "SI":"0x4cf",
            "SI_DI":"0x5112",
            "SI_RI":"0x1b0",
            "asic_instance":0,
            "rcpServiceID":"0x33",
            "replication_bitmap":"LD"
         },
         "1":{
            "RI":"0x1b0",
            "SI":"0x4cf",
            "SI_DI":"0x5112",
            "SI_RI":"0x1b0",
            "asic_instance":1,
            "rcpServiceID":"0x33",
            "replication_bitmap":"RD"
         },
         "DI":"0x5112"
      },
      "Encrypt_Pass":{
         "0":{
            "RI":"0x1b4",
            "SI":"0xbc",
            "SI_DI":"0x5112",
            "SI_RI":"0x1b4",
            "asic_instance":0,
            "rcpServiceID":"0x30",
            "replication_bitmap":"LD"
         },
         "1":{
            "RI":"0x1b4",
            "SI":"0xbc",
            "SI_DI":"0x5112",
            "SI_RI":"0x1b4",
            "asic_instance":1,
            "rcpServiceID":"0x30",
            "replication_bitmap":"RD"
         },
         "DI":"0x5112"
      },
      "Total-asic-instance":2,
      "Tunnel-id":"Tunnel222",
      "fvrf_id":0,
      "if-id":"0x5c",
      "inbound_flow_id":838,
      "ivrf_id":0,
      "outbound_flow_id":837
   }
}


expected_output = {
   "if-id":"0x5c",
   "inbound_flow":{
      "anti_replay_fail":0,
      "asic_instance":"SA Stats",
      "auth_fail":0,
      "byte_count":81982020,
      "flow_id":54,
      "fvrf_id":0,
      "invalid_sa":0,
      "ivrf_id":0,
      "packet_count":683184,
      "packet_format_check_error":0,
      "sa_index":23,
      "sequence_number_overflows":0
   },
   "outbound_flow":{
      "anti_replay_fail":0,
      "asic_instance":"SA Stats",
      "auth_fail":0,
      "byte_count":974181368,
      "flow_id":53,
      "fvrf_id":0,
      "invalid_sa":0,
      "ivrf_id":0,
      "packet_count":6840571,
      "packet_format_check_error":0,
      "sa_index":1069,
      "sequence_number_overflows":0
   }
}