expected_output = {
    "certificate_not_valid_after": "Dec 15 18:06:59 2017 GMT",
    "certificate_not_valid_before": "Dec 15 18:06:59 2016 GMT",
    "certificate_status": "Installed",
    "certificate_validity": "Valid",
    "chassis_num_unique_id": "b5887dd3-3d70-4987-a3a4-6e06c1d64a8c",
    "wan_interfaces": {
        "ge0/0": {
            "color": "lte",
            "control": "yes",
            "last_connection": "0:00:00:16",
            "lb": "No",
            "lr": "No",
            "max_cntrl": "2",
            "nat_type": "E",
            "private_ipv4": "10.1.15.15",
            "private_ipv6": "::",
            "private_port": "12426",
            "public_ipv4": "10.1.15.15",
            "public_port": "12426",
            "restrict": "no",
            "spi_time_remaining": "0:11:26:41",
            "state": "up",
            "stun": "no",
            "vm_con_prf": "5",
            "vmanage": "0",
            "vsmart": "0",
        },
        "ge0/3": {
            "color": "3g",
            "control": "yes",
            "last_connection": "0:00:00:13",
            "lb": "No",
            "lr": "No",
            "max_cntrl": "2",
            "nat_type": "N",
            "private_ipv4": "10.0.20.15",
            "private_ipv6": "::",
            "private_port": "12406",
            "public_ipv4": "10.0.20.15",
            "public_port": "12406",
            "restrict": "no",
            "spi_time_remaining": "0:11:26:45",
            "state": "up",
            "stun": "no",
            "vm_con_prf": "5",
            "vmanage": "0",
            "vsmart": "0",
        },
    },
    "dns_cache_ttl": "0:00:02:00",
    "dns_name": "10.0.12.26",
    "domain_id": "1",
    "keygen_interval": "1:00:00:00",
    "no_activity_exp_interval": "0:00:00:12",
    "number_active_wan_interfaces": "1",
    "number_vbond_peers": "0",
    "organization_name": "Cisco, Inc.",
    "personality": "vedge",
    "port_hopped": "TRUE",
    "protocol": "dtls",
    "retry_interval": "0:00:00:19",
    "root_ca_chain_status": "Installed",
    "serial_num": "12345714",
    "site_id": "100",
    "system_ip": "172.16.255.11",
    "time_since_last_port_hop": "0:00:43:16",
    "tls_port": "0",
}
