expected_output = {
   "power_supplies":{
      "PS1":{
         "model":"C9600-PWR-3KWAC",
         "type":"ac",
         "capacity":3000,
         "status":"active",
         "fan_states":{
            "1":"good",
            "2":"good"
         }
      },
      "PS2":{
         "model":"C9600-PWR-3KWAC",
         "type":"ac",
         "capacity":3000,
         "status":"active",
         "fan_states":{
            "1":"good",
            "2":"good"
         }
      },
      "PS3":{
         "model":"C9600-PWR-3KWAC",
         "type":"ac",
         "capacity":3000,
         "status":"active",
         "fan_states":{
            "1":"good",
            "2":"good"
         }
      },
      "PS4":{
         "model":"C9600-PWR-3KWAC",
         "type":"ac",
         "capacity":3000,
         "status":"active",
         "fan_states":{
            "1":"good",
            "2":"good"
         }
      },
      "PS5":{
         "model":"C9600-PWR-3KWAC",
         "type":"ac",
         "capacity":3000,
         "status":"active",
         "fan_states":{
            "1":"good",
            "2":"good"
         }
      },
      "PS6":{
         "model":"C9600-PWR-3KWAC",
         "type":"ac",
         "capacity":3000,
         "status":"active",
         "fan_states":{
            "1":"good",
            "2":"good"
         }
      },
      "PS7":{
         "model":"C9600-PWR-3KWAC",
         "type":"ac",
         "capacity":3000,
         "status":"active",
         "fan_states":{
            "1":"good",
            "2":"good"
         }
      },
      "PS8":{
         "model":"C9600-PWR-3KWAC",
         "type":"ac",
         "capacity":3000,
         "status":"active",
         "fan_states":{
            "1":"good",
            "2":"good"
         }
      }
   },
   "current_configuration_mode":"Combined",
   "current_operating_state":"Normal",
   "redundant_power":0,
   "power_supplies_active":8,
   "power_supplies_available":8,
   "power_summary":{
      "used":8671,
      "available":23580
   },
   "power_budget_mode":"Dual Sup",
   "modules":{
      "3":{
         "model":"C9610-LC-32CD",
         "state":"accepted",
         "budget":450,
         "instantaneous":27,
         "peak":105,
         "out_of_reset":450,
         "in_reset":10
      },
      "4":{
         "model":"C9610-LC-40YL4CD",
         "state":"accepted",
         "budget":420,
         "instantaneous":22,
         "peak":58,
         "out_of_reset":420,
         "in_reset":10
      },
      "5":{
         "model":"C9610-SUP-3",
         "state":"accepted",
         "budget":1500,
         "instantaneous":406,
         "peak":455,
         "out_of_reset":1500,
         "in_reset":650
      },
      "6":{
         "model":"C9610-SUP-3",
         "state":"accepted",
         "budget":1500,
         "instantaneous":418,
         "peak":455,
         "out_of_reset":1500,
         "in_reset":650
      },
      "10":{
         "model":"C9600-LC-48TX",
         "state":"---",
         "budget":1,
         "instantaneous":0,
         "peak":0,
         "out_of_reset":0,
         "in_reset":1
      },
      "FT1":{
         "model":"C9610-FAN",
         "state":"accepted",
         "budget":1200,
         "instantaneous":47,
         "peak":69,
         "out_of_reset":1200,
         "in_reset":0
      },
      "FT2":{
         "model":"C9610-FAN",
         "state":"accepted",
         "budget":1200,
         "instantaneous":46,
         "peak":69,
         "out_of_reset":1200,
         "in_reset":0
      },
      "FT3":{
         "model":"C9610-FAN",
         "state":"accepted",
         "budget":1200,
         "instantaneous":47,
         "peak":69,
         "out_of_reset":1200,
         "in_reset":0
      },
      "FT4":{
         "model":"C9610-FAN",
         "state":"accepted",
         "budget":1200,
         "instantaneous":47,
         "peak":69,
         "out_of_reset":1200,
         "in_reset":0
      }
   },
   "total_allocated_power":8671,
   "total_required_power":8670
}