expected_output = {
    "ap_name": {
        "b25a-13-cap10": {
            "ap_mac": "3c41.0fee.5094",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25b-12-cap01": {
            "ap_mac": "3c41.0fee.5884",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25b-11-cap01": {
            "ap_mac": "3c41.0fee.5d90",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-12-cap07": {
            "ap_mac": "3c41.0fee.5de8",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-11-cap05": {
            "ap_mac": "3c41.0fee.5df0",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-11-cap04": {
            "ap_mac": "3c41.0fee.5e5c",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-12-cap08": {
            "ap_mac": "3c41.0fee.5e74",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-11-cap01": {
            "ap_mac": "3c41.0fee.5eac",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-11-cap08": {
            "ap_mac": "3c41.0fee.5ef8",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-11-cap02": {
            "ap_mac": "3c41.0fee.5f94",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-11-cap07": {
            "ap_mac": "3c41.0fee.5fbc",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-12-cap02": {
            "ap_mac": "2c57.4518.16ac",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25b-11-cap06": {
            "ap_mac": "2c57.4518.2df0",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25b-11-cap08": {
            "ap_mac": "2c57.4518.41b0",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25b-11-cap07": {
            "ap_mac": "2c57.4518.432c",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-12-cap11": {
            "ap_mac": "2c57.4518.4330",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25b-12-cap02": {
            "ap_mac": "3c41.0fee.4394",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-13-cap09": {
            "ap_mac": "2c57.4518.564c",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25b-12-cap03": {
            "ap_mac": "2c57.4518.5b40",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
        "b25a-12-cap10": {
            "ap_mac": "2c57.4518.5b48",
            "site_tag_name": "default-site-tag-fabric",
            "policy_tag_name": "PT_Fabri_B25_B25-1_fe778",
            "rf_tag_name": "Standard",
            "misconfigured": False,
            "tag_source": "Static",
        },
    },
    "number_of_aps": 20,
}
