expected_output = {
    'switch': {
        1: {
            'svl': {
                1: {
                    'local_port': {
                        'HundredGigE1/1/0/19': {
                            'remote_port': 'HundredGigE2/1/0/23'}, 
                        'HundredGigE1/5/0/17': {
                            'remote_port': 'HundredGigE2/1/0/24'}, 
                        'FiftyGigE1/6/0/33': {
                            'remote_port': 'None'}}}}}, 
        2: {
            'svl': {
                1: {
                    'local_port': {
                        'HundredGigE2/1/0/23': {
                            'remote_port': 'HundredGigE1/1/0/19'}, 
                        'HundredGigE2/1/0/24': {
                            'remote_port': 'HundredGigE1/5/0/17'}, 
                        'FiftyGigE2/6/0/29': {
                            'remote_port': 'None'}}}}}}}
