expected_output={'name': {'acl-v4': {'counter_name': {'count_seq_1': {'bytes': 0, 'packets': 0},
                                      'count_seq_10': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_100': {'bytes': 0,
                                                        'packets': 0},
                                      'count_seq_11': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_12': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_13': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_14': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_15': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_16': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_17': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_18': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_19': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_2': {'bytes': 0, 'packets': 0},
                                      'count_seq_20': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_21': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_22': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_23': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_24': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_25': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_26': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_27': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_28': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_29': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_3': {'bytes': 0, 'packets': 0},
                                      'count_seq_30': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_31': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_32': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_33': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_34': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_35': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_36': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_37': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_38': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_39': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_4': {'bytes': 0, 'packets': 0},
                                      'count_seq_40': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_41': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_42': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_43': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_44': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_45': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_46': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_47': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_48': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_49': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_5': {'bytes': 0, 'packets': 0},
                                      'count_seq_50': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_51': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_52': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_53': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_54': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_55': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_56': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_57': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_58': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_59': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_60': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_61': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_62': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_63': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_64': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_65': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_66': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_67': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_68': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_69': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_7': {'bytes': 0, 'packets': 0},
                                      'count_seq_70': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_71': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_72': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_73': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_74': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_75': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_76': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_77': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_78': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_79': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_8': {'bytes': 0, 'packets': 0},
                                      'count_seq_80': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_81': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_82': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_83': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_84': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_85': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_86': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_87': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_88': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_89': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_9': {'bytes': 0, 'packets': 0},
                                      'count_seq_90': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_91': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_92': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_93': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_94': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_95': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_96': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_97': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_98': {'bytes': 0,
                                                       'packets': 0},
                                      'count_seq_99': {'bytes': 0,
                                                       'packets': 0},
                                      'default_action_count': {'bytes': 0,
                                                               'packets': 0},
                                      'vpn1002-v4-traffic': {'bytes': 8520697223296,
                                                             'packets': 9788308290}}},
          'acl-v4-40gig': {'counter_name': {'acl_v4_40gig_counter': {'bytes': 0,
                                                                     'packets': 0},
                                            'default_action_count': {'bytes': 0,
                                                                     'packets': 0}}},
          'acl-v4-apple': {'counter_name': {'default_action_count': {'bytes': 239371283918,
                                                                     'packets': 246601717},
                                            'seq1': {'bytes': 7977499318508,
                                                     'packets': 8726713375}}}}}