expected_output = {
    'interfaces': {
        'GigabitEthernet0/0/2': {
            'status': 'up',
            'if_number': 10,
            'corr_hwidb_fast_if_number': 10,
            'corr_hwidb_firstsw_if_number': 10,
            'policy_accounting_status': 'BGP based Policy accounting on output is enabled',
            'direction': 'output',
            'policy_statistics': {
                '1': {'packets': 10, 'bytes': 1000},
                '2': {'packets': 10, 'bytes': 1000},
                '3': {'packets': 10, 'bytes': 1000},
                '4': {'packets': 10, 'bytes': 1000},
                '5': {'packets': 10, 'bytes': 1000},
                '6': {'packets': 10, 'bytes': 1000},
                '7': {'packets': 10, 'bytes': 1000},
                '8': {'packets': 10, 'bytes': 1000},
                '9': {'packets': 0, 'bytes': 0},
                '10': {'packets': 0, 'bytes': 0},
                '11': {'packets': 0, 'bytes': 0},
                '12': {'packets': 0, 'bytes': 0},
                '13': {'packets': 0, 'bytes': 0},
                '14': {'packets': 0, 'bytes': 0},
                '15': {'packets': 0, 'bytes': 0},
                '16': {'packets': 0, 'bytes': 0},
                '17': {'packets': 0, 'bytes': 0},
                '18': {'packets': 0, 'bytes': 0},
                '19': {'packets': 0, 'bytes': 0},
                '20': {'packets': 0, 'bytes': 0},
                '21': {'packets': 0, 'bytes': 0},
                '22': {'packets': 0, 'bytes': 0},
                '23': {'packets': 0, 'bytes': 0},
                '24': {'packets': 0, 'bytes': 0},
                '25': {'packets': 0, 'bytes': 0},
                '26': {'packets': 0, 'bytes': 0},
                '27': {'packets': 0, 'bytes': 0},
                '28': {'packets': 0, 'bytes': 0},
                '29': {'packets': 0, 'bytes': 0},
                '30': {'packets': 0, 'bytes': 0},
                '31': {'packets': 0, 'bytes': 0},
                '32': {'packets': 0, 'bytes': 0},
                '33': {'packets': 0, 'bytes': 0},
                '34': {'packets': 0, 'bytes': 0},
                '35': {'packets': 0, 'bytes': 0},
                '36': {'packets': 0, 'bytes': 0},
                '37': {'packets': 0, 'bytes': 0},
                '38': {'packets': 0, 'bytes': 0},
                '39': {'packets': 0, 'bytes': 0},
                '40': {'packets': 0, 'bytes': 0},
                '41': {'packets': 0, 'bytes': 0},
                '42': {'packets': 0, 'bytes': 0},
                '43': {'packets': 0, 'bytes': 0},
                '44': {'packets': 0, 'bytes': 0},
                '45': {'packets': 0, 'bytes': 0},
                '46': {'packets': 0, 'bytes': 0},
                '47': {'packets': 0, 'bytes': 0},
                '48': {'packets': 0, 'bytes': 0},
                '49': {'packets': 0, 'bytes': 0},
                '50': {'packets': 0, 'bytes': 0},
                '51': {'packets': 0, 'bytes': 0},
                '52': {'packets': 0, 'bytes': 0},
                '53': {'packets': 0, 'bytes': 0},
                '54': {'packets': 0, 'bytes': 0},
                '55': {'packets': 0, 'bytes': 0},
                '56': {'packets': 0, 'bytes': 0},
                '57': {'packets': 0, 'bytes': 0},
                '58': {'packets': 0, 'bytes': 0},
                '59': {'packets': 0, 'bytes': 0},
                '60': {'packets': 0, 'bytes': 0},
                '61': {'packets': 0, 'bytes': 0},
                '62': {'packets': 0, 'bytes': 0},
                '63': {'packets': 0, 'bytes': 0},
                '64': {'packets': 0, 'bytes': 0}
            }
        }
    }
}