expected_output = {
    'group_id': {
        '1': {'administrative_state': 'No Shutdown',
                        'aggregate_operational_state': 'Up',
                        'fault_states_group': {'1': {'rg_faults_rg_state': 'Up',
                                                    'runtime_priority': 150,
                                                    'total_down_or_up_state_changes_due_to_faults': 0,
                                                    'total_switchovers_due_to_faults': 8}},
                        'group_name': 'GREEN',
                        'my_role': 'STANDBY',
                        'peer_comm': 'Yes',
                        'peer_presence': 'Yes',
                        'peer_progression_started': 'Yes',
                        'peer_role': 'ACTIVE',
                        'rf_domain': {'btob-one': {'peer_rf_state': 'ACTIVE',
                                                'rf_state': 'STANDBY HOT'}},
                        'rg_media_context': {1: {'active_peer': {'bytes': 319227402,
                                                                'ha_seq': 0,
                                                                'hold_timer': 750,
                                                                'pkt_loss': 0,
                                                                'pkts': 4092659,
                                                                'seq_number': 54194689,
                                                                'status': 'Present'},
                                                'ctrl_interface': 'Port-channel60.2511',
                                                'ctx_state': 'Standby',
                                                'media_type': 'Default',
                                                'protocol_id': 1,
                                                'stats': {'authentication_failures': 0,
                                                        'bytes': 5744720032,
                                                        'ha_seq': 0,
                                                        'pkt_loss': 0,
                                                        'pkts': 54195472,
                                                        'reload_peer': {'rx': 0, 'tx': 0},
                                                        'resign': {'rx': 10, 'tx': 10},
                                                        'seq_number': 54195472},
                                                'timers': {'configured_hello_timer': 250,
                                                            'current_hello_timer': 250,
                                                            'hold_timer': 750,
                                                            'peer_hello_timer': 250,
                                                            'peer_hold_timer': 750}}},
                        'rg_protocol': {1: {'active_peer': {'address': '10.240.0.45',
                                                            'interface': 'Po60.2511',
                                                            'priority': 255},
                                            'ctrl_interfaces_state': 'Up',
                                            'log_counters': {'ctrl_interface_events': {'admin_down': 0,
                                                                                    'down': 1,
                                                                                    'up': 1},
                                                            'disable_events': {'rg_down_state': 0,
                                                                                'rg_shut': 0},
                                                            'reload_events': {'local_request': 8,
                                                                            'peer_request': 0},
                                                            'role_change_to_active': 10,
                                                            'role_change_to_standby': 11},
                                            'negotiation': 'Enabled',
                                            'priority': 150,
                                            'protocol_state': 'Standby-hot',
                                            'role': 'Standby',
                                            'standby_peer': {'address': 'Local'}}}}}
}
