expected_output = {
    "version": {
        "version_short": "15.2",
        "platform": "C3750E",
        "version": "15.2(2)E8",
        "image_id": "C3750E-UNIVERSALK9-M",
        "os": "IOS",
        "image_type": "production image",
        "label": "RELEASE SOFTWARE (fc1)",
        "compiled_date": "Mon 22-Jan-18 04:07",
        "compiled_by": "prod_rel_team",
        "copyright_years": "1986-2018",
        "rom": "Bootstrap program is C3750E boot loader",
        "bootldr": "C3750E Boot Loader (C3750X-HBOOT-M) Version 12.2(58r)SE, RELEASE SOFTWARE (fc1)",
        "hostname": "sample_switch",
        "uptime": "8 weeks, 3 days, 10 hours, 27 minutes",
        "returned_to_rom_by": "power-on",
        "system_restarted_at": "05:06:40 GMT Tue Sep 10 2019",
        "system_image": "flash:c3750e-universalk9-mz.152-2.E8.bin",
        "last_reload_reason": "power-on",
        "license_level": "ipservices",
        "license_type": "Permanent",
        "next_reload_license_level": "ipservices",
        "chassis": "WS-C3750X-24S",
        "main_mem": "524288",
        "processor_type": "PowerPC405",
        "rtr_type": "WS-C3750X-24S",
        'switch_num': {	
             '1': {
                'clei_code_num': 'CMMFF00ARC',
                'db_assembly_num': '800-32727-03',
                'db_sn': 'FDO172217ED',
                'hb_rev_num': '0x04',
                'mac_address': 'AC:F2:C5:FF:55:E7',
                'mb_assembly_num': '73-13061-04',
                'mb_rev_num': 'A0',
                'mb_sn': 'FDO1633Q14M',
                'model_num': 'WS-C3750X-24S-E',
                'model_rev_num': 'A0',
                'system_sn': 'FDO1633Q14S',
                'top_assembly_part_num': '800-33746-04',
                'top_assembly_rev_num': 'B0',
                'version_id': 'V03',
             },
         },
        "chassis_sn": "FDO1633Q14S",
        "number_of_intfs": {
            "Virtual Ethernet": "14",
            "FastEthernet": "1",
            "Gigabit Ethernet": "28",
            "Ten Gigabit Ethernet": "2",
        },
        "mem_size": {"flash-simulated non-volatile configuration": "512"},
        "curr_config_register": "0xF",
    }
}
