expected_output = {
    "slot": {
        9: {
            "sub_slot": "-",
            "lc_group": "0",
            "my_state": "Active",
            "peer_state": "Stdby Warm",
            "peer_slot": "0",
            "peer_sub_slot": "-",
            "role": "Active",
            "mode": "Primary",
        },
        0: {
            "sub_slot": "-",
            "lc_group": "0",
            "my_state": "-",
            "peer_state": "-",
            "peer_slot": "Multiple",
            "peer_sub_slot": "None",
            "role": "Standby",
            "mode": "Secondary",
        },
        1: {
            "sub_slot": "-",
            "lc_group": "None",
            "my_state": "Active",
            "peer_state": "-",
            "peer_slot": "None",
            "peer_sub_slot": "None",
            "role": "Active",
            "mode": "None",
        },
        2: {
            "sub_slot": "-",
            "lc_group": "None",
            "my_state": "Active",
            "peer_state": "-",
            "peer_slot": "None",
            "peer_sub_slot": "None",
            "role": "Active",
            "mode": "None",
        },
        3: {
            "sub_slot": "-",
            "lc_group": "None",
            "my_state": "Active",
            "peer_state": "-",
            "peer_slot": "None",
            "peer_sub_slot": "None",
            "role": "Active",
            "mode": "None",
        },
    }
}
