expected_output = {
    "asic_specific_section":[
        {
            "asic":0,
            "acl_oid":1438,
            "entries":[
                {
                    "position":0,
                    "protocol":"UDP",
                    "src_port":68,
                    "dst_port":67,
                    "action":"PUNT",
                    "counter_oid":1439
                },
                {
                    "position":1,
                    "protocol":"UDP",
                    "src_port":67,
                    "dst_port":68,
                    "action":"PUNT",
                    "counter_oid":1439
                },
                {
                    "position":2,
                    "protocol":"UDP",
                    "src_port":67,
                    "dst_port":67,
                    "action":"PUNT",
                    "counter_oid":1439
                }
            ]
        },
        {
            "asic":1,
            "acl_oid":1372,
            "entries":[
                {
                    "position":0,
                    "protocol":"UDP",
                    "src_port":68,
                    "dst_port":67,
                    "action":"PUNT",
                    "counter_oid":1373
                },
                {
                    "position":1,
                    "protocol":"UDP",
                    "src_port":67,
                    "dst_port":68,
                    "action":"PUNT",
                    "counter_oid":1373
                },
                {
                    "position":2,
                    "protocol":"UDP",
                    "src_port":67,
                    "dst_port":67,
                    "action":"PUNT",
                    "counter_oid":1373
                }
            ]
        }
    ],
    "multicast_group_id":[
        {
            "oid":3476,
            "asic":0
        },
        {
            "oid":3415,
            "asic":1
        }
    ],
    "no_trust_ports":True,
    "punject_switch_profile":"FALSE",
    "trusted_ports":[
        {
            "interface":"Multicast",
            "interface_id":"Group",
            "po_id":"ID:"
        }
    ],
    "trusted_ports_multicast_gid":"0x2043",
    "vlan":50
}