expected_output = {
    'isis1':{
        1:{
            'prefix_name':'4.4.4.4/32',
            'metric':40,
            'priority':'Medium',
            'route_type':'L1',
            'path_type':'Primary',
            'change_type':'Add',
            'spf_run_id':4,
            'paths':{
                'HundredGigE0/0/0/0':{
                    'next_hop':'10.1.1.2',
                    'metric':10,
                    'change_type':'Add'
                }
            },
            'trigger_time':'Oct 31 06:10:20.872',
            'summary':{
                'ip_time':{
                    'min_time':9,
                    'min_node_id':'0/1/CPU0',
                    'max_time':10,
                    'max_node_id':'0/0/CPU0'
                },
                'mpls_time':{
                    'min_time':10,
                    'min_node_id':'0/1/CPU0',
                    'max_time':11,
                    'max_node_id':'0/0/CPU0'
                }
            },
            'timeline':{
                'details':{
                    'isis':0,
                    'ribv4_enter':0,
                    'ribv4_exit':3,
                    'ribv4_redist':3,
                    'ldp_enter':5,
                    'ldp_exit':6,
                    'lsd_enter':6,
                    'lsd_exit':8,
                    'lc':{
                        'ip':{
                            '0/0/CPU0':{
                                'path':'S',
                                'time':10
                            },
                            '0/1/CPU0':{
                                'path':'F',
                                'time':9
                            }
                        },
                        'mpls':{
                            '0/0/CPU0':{
                                'path':'S',
                                'time':11
                            },
                            '0/1/CPU0':{
                                'path':'F',
                                'time':10
                            }
                        }
                    }
                }
            }
        },
        3:{
            'prefix_name':'4.4.4.4/32',
            'metric':30,
            'priority':'Medium',
            'route_type':'L1',
            'path_type':'Primary',
            'change_type':'Modify',
            'spf_run_id':5,
            'paths':{
                'HundredGigE0/0/0/1':{
                    'next_hop':'10.5.1.2',
                    'metric':10,
                    'change_type':'Add'
                },
                'HundredGigE0/0/0/0':{
                    'next_hop':'10.1.1.2',
                    'metric':10,
                    'change_type':'Delete'
                }
            },
            'trigger_time':'Oct 31 06:10:21.273',
            'summary':{
                'ip_time':{
                    'min_time':7,
                    'min_node_id':'0/0/CPU0',
                    'max_time':8,
                    'max_node_id':'0/1/CPU0'
                },
                'mpls_time':{
                    'min_time':7,
                    'min_node_id':'0/0/CPU0',
                    'max_time':8,
                    'max_node_id':'0/1/CPU0'
                }
            },
            'timeline':{
                'details':{
                    'isis':0,
                    'ribv4_enter':1,
                    'ribv4_exit':3,
                    'ribv4_redist':3,
                    'ldp_enter':3,
                    'ldp_exit':3,
                    'lsd_enter':4,
                    'lsd_exit':6,
                    'lc':{
                        'ip':{
                            '0/0/CPU0':{
                                'path':'F',
                                'time':7
                            },
                            '0/1/CPU0':{
                                'path':'S',
                                'time':8
                            }
                        },
                        'mpls':{
                            '0/0/CPU0':{
                                'path':'F',
                                'time':7
                            },
                            '0/1/CPU0':{
                                'path':'S',
                                'time':8
                            }
                        }
                    }
                }
            }
        },
        7:{
            'prefix_name':'4.4.4.4/32',
            'metric':30,
            'priority':'Low',
            'route_type':'L1',
            'path_type':'Backup',
            'change_type':'Modify',
            'ip_frr_event_id':2,
            'paths':{
                'HundredGigE0/0/0/1':{
                    'next_hop':'10.5.1.2',
                    'metric':10,
                    'change_type':'NoChange'
                },
                'HundredGigE0/0/0/0':{
                    'ip_frr_path':'*',
                    'next_hop':'10.1.1.2',
                    'metric':10,
                    'change_type':'Add'
                }
            },
            'trigger_time':'Oct 31 06:10:21.775',
            'summary':{
                'ip_time':{
                    'min_time':26,
                    'min_node_id':'0/1/CPU0',
                    'max_time':28,
                    'max_node_id':'0/0/CPU0'
                },
                'mpls_time':{
                    'min_time':29,
                    'min_node_id':'0/1/CPU0',
                    'max_time':31,
                    'max_node_id':'0/0/CPU0'
                }
            },
            'timeline':{
                'details':{
                    'isis':0,
                    'ribv4_enter':0,
                    'ribv4_exit':2,
                    'ribv4_redist':3,
                    'ldp_enter':3,
                    'ldp_exit':5,
                    'lsd_enter':5,
                    'lsd_exit':7,
                    'lc':{
                        'ip':{
                            '0/0/CPU0':{
                                'path':'S',
                                'time':28
                            },
                            '0/1/CPU0':{
                                'path':'F',
                                'time':26
                            }
                        },
                        'mpls':{
                            '0/0/CPU0':{
                                'path':'S',
                                'time':31
                            },
                            '0/1/CPU0':{
                                'path':'F',
                                'time':29
                            }
                        }
                    }
                }
            }
        }
    }
} 
