expected_output = {
    'isis1':{
        7:{
            'prefix_name':'4.4.4.4/32',
            'metric':30,
            'priority':'Low',
            'route_type':'L1',
            'path_type':'Backup',
            'change_type':'Modify',
            'ip_frr_event_id':2,
            'paths':{
                'HundredGigE0/0/0/1':{
                    'next_hop':'10.5.1.2',
                    'metric':10,
                    'change_type':'NoChange'
                },
                'HundredGigE0/0/0/0':{
                    'ip_frr_path':'*',
                    'next_hop':'10.1.1.2',
                    'metric':10,
                    'change_type':'Add'
                }
            },
            'trigger_time':'Oct 31 06:10:21.775',
            'summary':{
                'ip_time':{
                    'min_time':26,
                    'min_node_id':'0/1/CPU0',
                    'max_time':28,
                    'max_node_id':'0/0/CPU0'
                },
                'mpls_time':{
                    'min_time':29,
                    'min_node_id':'0/1/CPU0',
                    'max_time':31,
                    'max_node_id':'0/0/CPU0'
                }
            },
            'timeline':{
                'details':{
                    'isis':0,
                    'ribv4_enter':0,
                    'ribv4_exit':2,
                    'ribv4_redist':3,
                    'ldp_enter':3,
                    'ldp_exit':5,
                    'lsd_enter':5,
                    'lsd_exit':7,
                    'lc':{
                        'ip':{
                            '0/0/CPU0':{
                                'path':'S',
                                'time':28
                            },
                            '0/1/CPU0':{
                                'path':'F',
                                'time':26
                            }
                        },
                        'mpls':{
                            '0/0/CPU0':{
                                'path':'S',
                                'time':31
                            },
                            '0/1/CPU0':{
                                'path':'F',
                                'time':29
                            }
                        }
                    }
                }
            }
        }
    }
} 
