expected_output = {
    "index": {
        1: {
            "advertisement_ver": 2,
            "capabilities": "Router Switch",
            "device_id": "MXMERCN5.cosmos.es.ftgroup",
            "duplex_mode": "",
            "entry_addresses": {"10.2.3.41": {}},
            "hold_time": 160,
            "local_interface": "Serial0/0/0:1",
            "management_addresses": {},
            "native_vlan": "",
            "platform": "Cisco 3825",
            "port_id": "Serial1/4:1",
            "software_version": "Cisco IOS Software, 3800 Software (C3825-ENTSERVICESK9-M), Version 12.4(24)T8, RELEASE SOFTWARE (fc1)\nTechnical Support: http://www.cisco.com/techsupport\nCopyright (c) 1986-2012 by Cisco Systems, Inc.\nCompiled Sun 09-Sep-12 05:35 by prod_rel_team",
            "vtp_management_domain": "NotUsed",
        },
        2: {
            "advertisement_ver": 2,
            "capabilities": "Router Switch",
            "device_id": "BXPEDRCN2.cosmos.es.ftgroup",
            "duplex_mode": "full",
            "entry_addresses": {"10.32.0.2": {}},
            "hold_time": 164,
            "local_interface": "FastEthernet0/0.1",
            "management_addresses": {},
            "native_vlan": "1",
            "platform": "cisco WS-C6509-E",
            "port_id": "GigabitEthernet7/27",
            "software_version": "Cisco IOS Software, s3223_rp Software (s3223_rp-IPSERVICESK9_WAN-M), Version 12.2(33)SXI14, RELEASE SOFTWARE (fc2)\nTechnical Support: http://www.cisco.com/techsupport\nCopyright (c) 1986-2014 by Cisco Systems, Inc.\nCompiled Wed 03-Sep-14 23:45 by prod_rel_team",
            "vtp_management_domain": "alpi",
        },
    },
    "total_entries_displayed": 2,
}
