expected_output = {
    "total_entries_displayed": 2,
    "index": {
        1: {
            "device_id": "e0553d849f1a",
            "duplex_mode": "",
            "vtp_management_domain": "",
            "native_vlan": "",
            "management_addresses": {},
            "entry_addresses": {"10.0.0.7": {}},
            "platform": "Meraki MV21 Cloud Managed Indoor HD Dom",
            "port_id": "Port 0",
            "local_interface": "GigabitEthernet3/0/29",
            "hold_time": 145,
            "software_version": "1",
            "power_drawn":0.0,
            "power_request_id":31314,
            "power_mgmt_id_1":0,
            "power_req_level":"15400 0 0 0 0",
            "advertisement_ver": 2,
        },
        2: {
            "device_id": "System1",
            "duplex_mode": "full",
            "vtp_management_domain": " ",
            "native_vlan": "",
            "management_addresses": {"10.0.0.8": {}},
            "entry_addresses": {"10.0.0.8": {}},
            "capabilities": "Router Switch IGMP",
            "platform": "cisco ISR4351/K9",
            "port_id": "GigabitEthernet0/0/2",
            "local_interface": "GigabitEthernet1/0/47",
            "hold_time": 129,
            "software_version": "Cisco IOS Software [Fuji], ISR Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.9.4, RELEASE SOFTWARE (fc2)\nTechnical Support: http://www.cisco.com/techsupport\nCopyright (c) 1986-2019 by Cisco Systems, Inc.\nCompiled Thu 22-Aug-19 18:09 by mcpre",
            "advertisement_ver": 2,
        },
    },
}
