expected_output = {
    "interface":{
      "GigabitEthernet0/0/0/3.200":{
         "interface_status":"up",
         "line_protocol_status":"up",
         "ip_address":"90.11.1.1/30",
         "area":"0",
         "sid":"0",
         "strict_spf_sid":"0",
         "label_stack":{
            "primary_label":"0",
            "backup_label":"0",
            "srte_label":"0"
         },
         "process_id":1,
         "vrf_name":"VRF_1",
         "router_id":"90.11.1.1",
         "network_type":"POINT_TO_POINT",
         "cost":"1",
         "transmit_delay":"1 sec",
         "state":"POINT_TO_POINT",
         "mtu":"1500",
         "max_pkt_sz":"1500",
         "forward_reference":"No",
         "unnumbered":False,
         "bandwidth":1000000,
         "hello_interval":10,
         "dead_interval":40,
         "wait_interval":40,
         "retransmit_interval":5,
         "hello_timer":"00:00:02:685",
         "index":"1/1",
         "flood_queue_length":0,
         "next":"0(0)/0(0)",
         "last_flood_scan_length":1,
         "max_flood_scan_length":1,
         "last_flood_scan_time_msec":0,
         "max_flood_scan_time_msec":0,
         "ls_ack_list":"current",
         "ls_ack_list_length":0,
         "high_water_mark":1,
         "neighbor_count":1,
         "adjacnt_neighbor_count":1,
         "neighbors":{
            "neighbor_router_id":"90.11.1.2"
         }
      }
   }
}