expected_output={
   "message_summary":{
      "05/16/2015 21:39:57":[
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT :  >254 LAST  OBFL PS-FAN NOT PRESENT : FEP fan PS-2",
         "NYQ-2-PLATFORM_PSFAN_PRESENT :  >254 LAST  OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "04/25/2019 17:44:59":[
         "NYQ-2-PLATFORM_FAN_PRESENT :  >254 LAST  OBFL FAN PRESENT : operational fan 3"
      ],
      "05/09/2019 05:47:20":[
         "NYQ-3-PLATFORM_FEP_POWER_ON :  250  : LAST :  OBFL FEP POWER ON: A"
      ],
      "05/08/2019 18:47:12":[
         "NYQ-2-PLATFORM_PSFAN_CRITICAL :  1    : LAST :  OBFL PS-FAN CRITICAL: FEP fan PS-1"
      ],
      "04/08/2019 11:55:19":[
         "NYQ-2-PLATFORM_FAN_NOT_PRESENT :  >254 LAST  OBFL FAN NOT PRESENT : operational fan 3"
      ],
      "05/16/2015 15:57:21":[
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 16:16:47":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 16:22:52":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 16:28:37":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 16:31:51":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 16:55:27":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 17:02:30":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 17:31:52":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 17:38:03":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 17:47:21":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 17:50:26":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 19:58:39":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 20:03:58":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 20:19:03":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 20:24:22":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 20:29:23":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 20:32:58":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 20:36:10":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 20:39:39":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 20:54:35":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 20:59:53":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 21:04:52":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 21:08:26":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 21:11:38":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 21:24:16":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 21:30:40":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 21:43:02":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 21:47:41":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ],
      "05/16/2015 21:53:00":[
         "NYQ-2-PLATFORM_PSFAN_PRESENT : OBFL PS-FAN PRESENT : FEP fan PS-1",
         "NYQ-2-PLATFORM_PSFAN_NOT_PRESENT : OBFL PS-FAN NOT PRESENT : FEP fan PS-2"
      ]
   }
}