

expected_output = {
'vrf': {
    'VRF1': {
        'address_family': {
            'ipv6': {
                'routes': {
                    '2001:10:12:120::/64': {
                        'active': True,
                        'mbest': 0,
                        'metric': 3072,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 3072,
                                    'next_hop': 'fe80::f816:3eff:fef8:e824',
                                    'outgoing_interface': 'Ethernet1/2.390',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:25:35',
                                },
                            },
                        },
                        'process_id': 'test',
                        'route': '2001:10:12:120::/64',
                        'route_preference': 90,
                        'source_protocol': 'eigrp',
                        'source_protocol_status': 'internal',
                        'ubest': 1,
                    },
                    '2001:10:12:90::/64': {
                        'active': True,
                        'mbest': 0,
                        'metric': 3072,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 3072,
                                    'next_hop': 'fe80::f816:3eff:fe80:67f4',
                                    'outgoing_interface': 'Ethernet1/1.390',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:51:47',
                                },
                                2: {
                                    'best_ucast_nexthop': True,
                                    'index': 2,
                                    'metric': 3072,
                                    'next_hop': 'fe80::f816:3eff:fef8:e824',
                                    'outgoing_interface': 'Ethernet1/2.390',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:55:29',
                                },
                            },
                        },
                        'process_id': 'test',
                        'route': '2001:10:12:90::/64',
                        'route_preference': 90,
                        'source_protocol': 'eigrp',
                        'source_protocol_status': 'internal',
                        'ubest': 2,
                    },
                    '2001:10:13:110::3/128': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'metric': 0,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 0,
                                    'next_hop': '2001:10:13:110::3',
                                    'outgoing_interface': 'Ethernet1/2.410',
                                    'route_preference': 0,
                                    'source_protocol': 'local',
                                    'updated': '03:55:43',
                                },
                            },
                        },
                        'route': '2001:10:13:110::3/128',
                        'route_preference': 0,
                        'source_protocol': 'local',
                        'ubest': 1,
                    },
                    '2001:10:13:115::/64': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'metric': 0,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 0,
                                    'next_hop': '2001:10:13:115::3',
                                    'outgoing_interface': 'Ethernet1/2.415',
                                    'route_preference': 0,
                                    'source_protocol': 'direct',
                                    'updated': '03:55:43',
                                },
                            },
                        },
                        'route': '2001:10:13:115::/64',
                        'route_preference': 0,
                        'source_protocol': 'direct',
                        'ubest': 1,
                    },
                    '2001:10:13:120::3/128': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'route': '2001:10:13:120::3/128',
                        'ubest': 1,
                    },
                    '2001:10:13:90::/64': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'metric': 0,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 0,
                                    'next_hop': '2001:10:13:90::3',
                                    'outgoing_interface': 'Ethernet1/2.390',
                                    'route_preference': 0,
                                    'source_protocol': 'direct',
                                    'updated': '03:55:44',
                                },
                            },
                        },
                        'route': '2001:10:13:90::/64',
                        'route_preference': 0,
                        'source_protocol': 'direct',
                        'ubest': 1,
                    },
                    '2001:1:1:1::1/128': {
                        'active': True,
                        'mbest': 0,
                        'metric': 2848,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 2848,
                                    'next_hop': 'fe80::f816:3eff:fef8:e824',
                                    'outgoing_interface': 'Ethernet1/2.390',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:55:29',
                                },
                            },
                        },
                        'process_id': 'test',
                        'route': '2001:1:1:1::1/128',
                        'route_preference': 90,
                        'source_protocol': 'eigrp',
                        'source_protocol_status': 'internal',
                        'ubest': 1,
                    },
                    '2001:2:2:2::2/128': {
                        'active': True,
                        'mbest': 0,
                        'metric': 2842,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 2842,
                                    'next_hop': 'fe80::f816:3eff:fe80:67f4',
                                    'outgoing_interface': 'Ethernet1/1.390',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:51:47',
                                },
                            },
                        },
                        'process_id': 'test',
                        'route': '2001:2:2:2::2/128',
                        'route_preference': 90,
                        'source_protocol': 'eigrp',
                        'source_protocol_status': 'internal',
                        'ubest': 1,
                    },
                    '2001:3:3:3::3/128': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'metric': 0,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 0,
                                    'next_hop': '2001:3:3:3::3',
                                    'outgoing_interface': 'Loopback300',
                                    'route_preference': 0,
                                    'source_protocol': 'direct',
                                    'updated': '03:55:33',
                                },
                                2: {
                                    'best_ucast_nexthop': True,
                                    'index': 2,
                                    'metric': 0,
                                    'next_hop': '2001:3:3:3::3',
                                    'outgoing_interface': 'Loopback300',
                                    'route_preference': 0,
                                    'source_protocol': 'local',
                                    'updated': '03:55:33',
                                },
                            },
                        },
                        'route': '2001:3:3:3::3/128',
                        'route_preference': 0,
                        'source_protocol': 'local',
                        'ubest': 2,
                    },
                },
            },
        },
    },
    'default': {
        'address_family': {
            'ipv6': {
                'routes': {
                    '2001:10:12:120::/64': {
                        'active': True,
                        'mbest': 0,
                        'metric': 3072,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 3072,
                                    'next_hop': 'fe80::f816:3eff:fef8:e824',
                                    'outgoing_interface': 'Ethernet1/2.90',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:39:27',
                                },
                            },
                        },
                        'process_id': 'test',
                        'route': '2001:10:12:120::/64',
                        'route_preference': 90,
                        'source_protocol': 'eigrp',
                        'source_protocol_status': 'internal',
                        'ubest': 1,
                    },
                    '2001:10:12:90::/64': {
                        'active': True,
                        'mbest': 0,
                        'metric': 3072,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 3072,
                                    'next_hop': 'fe80::f816:3eff:fe80:67f4',
                                    'outgoing_interface': 'Ethernet1/1.90',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:51:46',
                                },
                                2: {
                                    'best_ucast_nexthop': True,
                                    'index': 2,
                                    'metric': 3072,
                                    'next_hop': 'fe80::f816:3eff:fef8:e824',
                                    'outgoing_interface': 'Ethernet1/2.90',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:55:29',
                                },
                            },
                        },
                        'process_id': 'test',
                        'route': '2001:10:12:90::/64',
                        'route_preference': 90,
                        'source_protocol': 'eigrp',
                        'source_protocol_status': 'internal',
                        'ubest': 2,
                    },
                    '2001:10:13:90::/64': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'metric': 0,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 0,
                                    'next_hop': '2001:10:13:90::3',
                                    'outgoing_interface': 'Ethernet1/2.90',
                                    'route_preference': 0,
                                    'source_protocol': 'direct',
                                    'updated': '03:55:45',
                                },
                            },
                        },
                        'route': '2001:10:13:90::/64',
                        'route_preference': 0,
                        'source_protocol': 'direct',
                        'ubest': 1,
                    },
                    '2001:10:13:90::3/128': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'metric': 0,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 0,
                                    'next_hop': '2001:10:13:90::3',
                                    'outgoing_interface': 'Ethernet1/2.90',
                                    'route_preference': 0,
                                    'source_protocol': 'local',
                                    'updated': '03:55:45',
                                },
                            },
                        },
                        'route': '2001:10:13:90::3/128',
                        'route_preference': 0,
                        'source_protocol': 'local',
                        'ubest': 1,
                    },
                    '2001:10:23:120::/64': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'metric': 0,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 0,
                                    'next_hop': '2001:10:23:120::3',
                                    'outgoing_interface': 'Ethernet1/1.120',
                                    'route_preference': 0,
                                    'source_protocol': 'direct',
                                    'updated': '02:50:42',
                                },
                            },
                        },
                        'route': '2001:10:23:120::/64',
                        'route_preference': 0,
                        'source_protocol': 'direct',
                        'ubest': 1,
                    },
                    '2001:10:23:120::3/128': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'metric': 0,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 0,
                                    'next_hop': '2001:10:23:120::3',
                                    'outgoing_interface': 'Ethernet1/1.120',
                                    'route_preference': 0,
                                    'source_protocol': 'local',
                                    'updated': '02:50:42',
                                },
                            },
                        },
                        'route': '2001:10:23:120::3/128',
                        'route_preference': 0,
                        'source_protocol': 'local',
                        'ubest': 1,
                    },
                    '2001:1:1:1::1/128': {
                        'active': True,
                        'mbest': 0,
                        'metric': 2848,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 2848,
                                    'next_hop': 'fe80::f816:3eff:fef8:e824',
                                    'outgoing_interface': 'Ethernet1/2.90',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:55:29',
                                },
                            },
                        },
                        'process_id': 'test',
                        'route': '2001:1:1:1::1/128',
                        'route_preference': 90,
                        'source_protocol': 'eigrp',
                        'source_protocol_status': 'internal',
                        'ubest': 1,
                    },
                    '2001:2:2:2::2/128': {
                        'active': True,
                        'mbest': 0,
                        'metric': 2842,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 2842,
                                    'next_hop': 'fe80::f816:3eff:fe80:67f4',
                                    'outgoing_interface': 'Ethernet1/1.90',
                                    'route_preference': 90,
                                    'source_protocol': 'eigrp',
                                    'source_protocol_status': 'internal',
                                    'updated': '03:51:46',
                                },
                            },
                        },
                        'process_id': 'test',
                        'route': '2001:2:2:2::2/128',
                        'route_preference': 90,
                        'source_protocol': 'eigrp',
                        'source_protocol_status': 'internal',
                        'ubest': 1,
                    },
                    '2001:3:3:3::3/128': {
                        'active': True,
                        'attached': True,
                        'mbest': 0,
                        'metric': 0,
                        'next_hop': {
                            'next_hop_list': {
                                1: {
                                    'best_ucast_nexthop': True,
                                    'index': 1,
                                    'metric': 0,
                                    'next_hop': '2001:3:3:3::3',
                                    'outgoing_interface': 'Loopback0',
                                    'route_preference': 0,
                                    'source_protocol': 'direct',
                                    'updated': '03:55:33',
                                },
                                2: {
                                    'best_ucast_nexthop': True,
                                    'index': 2,
                                    'metric': 0,
                                    'next_hop': '2001:3:3:3::3',
                                    'outgoing_interface': 'Loopback0',
                                    'route_preference': 0,
                                    'source_protocol': 'local',
                                    'updated': '03:55:33',
                                },
                            },
                        },
                        'route': '2001:3:3:3::3/128',
                        'route_preference': 0,
                        'source_protocol': 'local',
                        'ubest': 2,
                    },
                },
            },
        },
    },
},
}
