expected_output = {
    "ospf-database-information": {
        "ospf-area-header": {"ospf-area": "0.0.0.0"},
        "ospf-database": [
            {
                "advertising-router": "10.4.1.1",
                "age": "14",
                "checksum": "0x9f32",
                "lsa-id": "10.4.1.1",
                "lsa-length": "48",
                "lsa-type": "Router",
                "options": "0x22",
                "ospf-database-extensive": {
                    "aging-timer": {"#text": "00:59:46"},
                    "expiration-time": {"#text": "00:59:46"},
                    "installation-time": {"#text": "00:00:11"},
                    "lsa-change-count": "3",
                    "lsa-changed-time": {"#text": "00:00:11"},
                },
                "ospf-router-lsa": {
                    "bits": "0x2",
                    "link-count": "2",
                    "ospf-link": [
                        {
                            "link-data": "10.135.0.1",
                            "link-id": "10.135.0.2",
                            "link-type-name": "Transit",
                            "link-type-value": "2",
                            "metric": "1",
                            "ospf-topology-count": "0",
                        },
                        {
                            "link-data": "10.135.0.1",
                            "link-id": "10.135.0.2",
                            "link-type-name": "Transit",
                            "link-type-value": "2",
                            "metric": "1",
                            "ospf-topology-count": "0",
                        },
                        {
                            "link-data": "255.255.255.255",
                            "link-id": "10.4.1.1",
                            "link-type-name": "Stub",
                            "link-type-value": "3",
                            "metric": "0",
                            "ospf-topology-count": "0",
                        },
                        {
                            "link-data": "255.255.255.255",
                            "link-id": "10.4.1.1",
                            "link-type-name": "Stub",
                            "link-type-value": "3",
                            "metric": "0",
                            "ospf-topology-count": "0",
                        },
                    ],
                    "ospf-lsa-topology": {
                        "ospf-lsa-topology-link": [
                            {
                                "link-type-name": "Transit",
                                "ospf-lsa-topology-link-metric": "1",
                                "ospf-lsa-topology-link-node-id": "10.135.0.2",
                                "ospf-lsa-topology-link-state": "Bidirectional",
                            }
                        ],
                        "ospf-topology-id": "0",
                        "ospf-topology-name": "default",
                    },
                },
                "sequence-number": "0x80000005",
            },
            {
                "advertising-router": "10.36.3.3",
                "age": "99",
                "checksum": "0xb705",
                "lsa-id": "10.36.3.3",
                "lsa-length": "48",
                "lsa-type": "Router",
                "options": "0x22",
                "ospf-database-extensive": {
                    "aging-timer": {"#text": "00:58:21"},
                    "expiration-time": {"#text": "00:58:21"},
                    "generation-timer": {"#text": "00:48:21"},
                    "installation-time": {"#text": "00:01:39"},
                    "send-time": {"#text": "00:01:37"},
                },
                "ospf-router-lsa": {
                    "bits": "0x0",
                    "link-count": "2",
                    "ospf-link": [
                        {
                            "link-data": "10.135.0.2",
                            "link-id": "10.135.0.2",
                            "link-type-name": "Transit",
                            "link-type-value": "2",
                            "metric": "1",
                            "ospf-topology-count": "0",
                        },
                        {
                            "link-data": "10.135.0.2",
                            "link-id": "10.135.0.2",
                            "link-type-name": "Transit",
                            "link-type-value": "2",
                            "metric": "1",
                            "ospf-topology-count": "0",
                        },
                        {
                            "link-data": "255.255.255.255",
                            "link-id": "10.36.3.3",
                            "link-type-name": "Stub",
                            "link-type-value": "3",
                            "metric": "0",
                            "ospf-topology-count": "0",
                        },
                        {
                            "link-data": "255.255.255.255",
                            "link-id": "10.36.3.3",
                            "link-type-name": "Stub",
                            "link-type-value": "3",
                            "metric": "0",
                            "ospf-topology-count": "0",
                        },
                    ],
                    "ospf-lsa-topology": {
                        "ospf-lsa-topology-link": [
                            {
                                "link-type-name": "Transit",
                                "ospf-lsa-topology-link-metric": "1",
                                "ospf-lsa-topology-link-node-id": "10.135.0.2",
                                "ospf-lsa-topology-link-state": "Bidirectional",
                            }
                        ],
                        "ospf-topology-id": "0",
                        "ospf-topology-name": "default",
                    },
                },
                "our-entry": True,
                "sequence-number": "0x80000003",
            },
            {
                "advertising-router": "10.36.3.3",
                "age": "104",
                "checksum": "0x42bb",
                "lsa-id": "10.135.0.2",
                "lsa-length": "32",
                "lsa-type": "Network",
                "options": "0x22",
                "ospf-database-extensive": {
                    "aging-timer": {"#text": "00:58:16"},
                    "expiration-time": {"#text": "00:58:16"},
                    "generation-timer": {"#text": "00:48:16"},
                    "installation-time": {"#text": "00:01:44"},
                    "send-time": {"#text": "00:01:42"},
                },
                "ospf-network-lsa": {
                    "address-mask": "255.255.255.0",
                    "attached-router": ["10.36.3.3", "10.4.1.1"],
                    "ospf-lsa-topology": {
                        "ospf-lsa-topology-link": [
                            {
                                "link-type-name": "Transit",
                                "ospf-lsa-topology-link-metric": "0",
                                "ospf-lsa-topology-link-node-id": "10.4.1.1",
                                "ospf-lsa-topology-link-state": "Bidirectional",
                            },
                            {
                                "link-type-name": "Transit",
                                "ospf-lsa-topology-link-metric": "0",
                                "ospf-lsa-topology-link-node-id": "10.36.3.3",
                                "ospf-lsa-topology-link-state": "Bidirectional",
                            },
                        ],
                        "ospf-topology-id": "0",
                        "ospf-topology-name": "default",
                    },
                },
                "our-entry": True,
                "sequence-number": "0x80000001",
            },
            {
                "advertising-router": "10.4.1.1",
                "age": "14",
                "checksum": "0xe69b",
                "lsa-id": "10.229.11.11",
                "lsa-length": "36",
                "lsa-type": "Extern",
                "options": "0x22",
                "ospf-database-extensive": {
                    "aging-timer": {"#text": "00:59:46"},
                    "expiration-time": {"#text": "00:59:46"},
                    "installation-time": {"#text": "00:00:11"},
                    "lsa-change-count": "1",
                    "lsa-changed-time": {"#text": "00:00:11"},
                },
                "ospf-external-lsa": {
                    "address-mask": "255.255.255.255",
                    "ospf-external-lsa-topology": {
                        "forward-address": "0.0.0.0",
                        "ospf-topology-id": "0",
                        "ospf-topology-metric": "0",
                        "ospf-topology-name": "default",
                        "tag": "0.0.0.0",
                        "type-value": "2",
                    },
                },
                "sequence-number": "0x80000001",
            },
        ],
    }
}
