

expected_output = {
    'Ethernet2/2':
        {'access_vlan': 1,
         'access_vlan_mode': 'default',
         'admin_priv_vlan_primary_host_assoc': 'none',
         'admin_priv_vlan_primary_mapping': 'none',
         'admin_priv_vlan_secondary_host_assoc': 'none',
         'admin_priv_vlan_secondary_mapping': 'none',
         'admin_priv_vlan_trunk_encapsulation': 'dot1q',
         'admin_priv_vlan_trunk_native_vlan': 'none',
         'admin_priv_vlan_trunk_normal_vlans': 'none',
         'admin_priv_vlan_trunk_private_vlans': 'none',
         'native_vlan': 1,
         'native_vlan_mode': 'default',
         'operational_private_vlan': 'none',
         'switchport_mode': 'trunk',
         'switchport_monitor': 'Not enabled',
         'switchport_status': 'enabled',
         'switchport_enable': True,
         'trunk_vlans': '100,300'},
    'Ethernet2/3':
        {'access_vlan': 100,
         'access_vlan_mode': 'Vlan not created',
         'admin_priv_vlan_primary_host_assoc': 'none',
         'admin_priv_vlan_primary_mapping': 'none',
         'admin_priv_vlan_secondary_host_assoc': 'none',
         'admin_priv_vlan_secondary_mapping': 'none',
         'admin_priv_vlan_trunk_encapsulation': 'dot1q',
         'admin_priv_vlan_trunk_native_vlan': 'none',
         'admin_priv_vlan_trunk_normal_vlans': 'none',
         'admin_priv_vlan_trunk_private_vlans': 'none',
         'native_vlan': 1,
         'native_vlan_mode': 'default',
         'operational_private_vlan': 'none',
         'switchport_mode': 'access',
         'switchport_monitor': 'Not enabled',
         'switchport_status': 'enabled',
         'switchport_enable': True,
         'trunk_vlans': '1-4094'}}
