expected_output = {
    "index": {
        1: {
            "vid": "V02",
            "pid": "C9300-48UXM",
            "name": "c93xx Stack",
            "descr": "c93xx Stack",
            "sn": "FCW2242G0V3",
        },
        2: {
            "vid": "V02",
            "pid": "C9300-48UXM",
            "name": "Switch 1",
            "descr": "C9300-48UXM",
            "sn": "FCW2242G114",
        },
        3: {
            "vid": "V01",
            "pid": "STACK-T1-1M",
            "name": "StackPort1/1",
            "descr": "StackPort1/1",
            "sn": "MOC2236A6JM",
        },
        4: {
            "vid": "V01",
            "pid": "STACK-T1-1M",
            "name": "StackPort1/2",
            "descr": "StackPort1/2",
            "sn": "MOC2240A2JM",
        },
        5: {
            "vid": "V02",
            "pid": "PWR-C1-1100WAC",
            "name": "Switch 1 - Power Supply A",
            "descr": "Switch 1 - Power Supply A",
            "sn": "DTN2236V68C",
        },
        6: {
            "vid": "V02",
            "pid": "C9300-NM-8X",
            "name": "Switch 1 FRU Uplink Module 1",
            "descr": "8x10G Uplink Module",
            "sn": "FOC22423G0U",
        },
        7: {
            "vid": "V03",
            "pid": "SFP-10G-SR",
            "name": "Te1/1/1",
            "descr": "SFP-10GBase-SR",
            "sn": "AVD223594E6",
        },
        8: {
            "vid": "V02",
            "pid": "C9300-48UXM",
            "name": "Switch 2",
            "descr": "C9300-48UXM",
            "sn": "FCW2242G0V3",
        },
        9: {
            "vid": "V01",
            "pid": "STACK-T1-1M",
            "name": "StackPort2/1",
            "descr": "StackPort2/1",
            "sn": "MOC2240A2JM",
        },
        10: {
            "vid": "V01",
            "pid": "STACK-T1-1M",
            "name": "StackPort2/2",
            "descr": "StackPort2/2",
            "sn": "MOC2236A6JM",
        },
        11: {
            "vid": "V02",
            "pid": "PWR-C1-1100WAC",
            "name": "Switch 2 - Power Supply A",
            "descr": "Switch 2 - Power Supply A",
            "sn": "DTN2236V6DL",
        },
        12: {
            "vid": "V02",
            "pid": "C9300-NM-8X",
            "name": "Switch 2 FRU Uplink Module 1",
            "descr": "8x10G Uplink Module",
            "sn": "FOC22423FF4",
        },
    },
}
