expected_output = {
   "group_member_information":{
      "groups":{
         "bw-suiteB":{
            "group_id":2001,
            "group_members":2,
            "key_server_ids":{
               "15.15.15.1":{
                  "gmdb_state":"LOCAL",
                  "group_members":1,
                  "members":{
                     "46.46.46.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               },
               "16.16.16.1":{
                  "gmdb_state":"REDUNDANT",
                  "group_members":1,
                  "members":{
                     "56.56.56.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               }
            }
         },
         "bw-suiteB-v6":{
            "group_id":2002,
            "group_members":2,
            "key_server_ids":{
               "15.15.15.1":{
                  "gmdb_state":"LOCAL",
                  "group_members":1,
                  "members":{
                     "42.42.42.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               },
               "16.16.16.1":{
                  "gmdb_state":"REDUNDANT",
                  "group_members":1,
                  "members":{
                     "52.52.52.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               }
            }
         },
         "bw600-IPV6":{
            "group_id":6600,
            "group_members":2,
            "key_server_ids":{
               "15.15.15.1":{
                  "gmdb_state":"LOCAL",
                  "group_members":1,
                  "members":{
                     "41.41.41.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               },
               "16.16.16.1":{
                  "gmdb_state":"REDUNDANT",
                  "group_members":1,
                  "members":{
                     "51.51.51.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               }
            }
         },
         "bw600-IPV6_eft":{
            "group_id":2233,
            "group_members":2,
            "key_server_ids":{
               "15.15.15.1":{
                  "gmdb_state":"LOCAL",
                  "group_members":1,
                  "members":{
                     "43.43.43.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               },
               "16.16.16.1":{
                  "gmdb_state":"REDUNDANT",
                  "group_members":1,
                  "members":{
                     "53.53.53.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               }
            }
         },
         "bw6000":{
            "group_id":6000,
            "group_members":2,
            "key_server_ids":{
               "15.15.15.1":{
                  "gmdb_state":"LOCAL",
                  "group_members":1,
                  "members":{
                     "44.44.44.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               },
               "16.16.16.1":{
                  "gmdb_state":"REDUNDANT",
                  "group_members":1,
                  "members":{
                     "54.54.54.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               }
            }
         },
         "bw6000_eft":{
            "group_id":1122,
            "group_members":2,
            "key_server_ids":{
               "15.15.15.1":{
                  "gmdb_state":"LOCAL",
                  "group_members":1,
                  "members":{
                     "45.45.45.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               },
               "16.16.16.1":{
                  "gmdb_state":"REDUNDANT",
                  "group_members":1,
                  "members":{
                     "55.55.55.1":{
                        "rekey_ack_missed":0,
                        "rekey_sent":0,
                        "version":"1.0.25"
                     }
                  }
               }
            }
         }
      }
   }
}