expected_output = {
    'number_of_address': 4,
    'number_of_drop_address': 0,
    'number_of_local_lisp_address': 0,
    'number_of_remote_lisp_address': 0,
    'number_of_secure_address': 0,
    'vlan': {
        '0': {
            'mac': {
                '7061.7bb8.c3e8': {
                    'atime': 0,
                    'con': 'Yes',
                    'dihandle': '0x5ddf',
                    'ecbi': 0,
                    'etime': 0,
                    'flags': 64,
                    'machandle': '0x71450ca79f48',
                    'ports': 'GigabitEthernet1/4/0/26',
                    'rihandle': '0x0',
                    'seq': 0,
                    'sihandle': '0x71450c355218',
                    'type': '0x8002',
                },
            },
        },
        '1': {
            'mac': {
                '7061.7bb8.c3e7': {
                    'atime': 0,
                    'con': 'Yes',
                    'dihandle': '0x0',
                    'ecbi': 0,
                    'etime': 0,
                    'flags': 64,
                    'machandle': '0x71450ca90f78',
                    'ports': 'Vlan1',
                    'rihandle': '0x0',
                    'seq': 0,
                    'sihandle': '0x71450c355218',
                    'type': '0x8002',
                },
                '74ad.980f.e0a5': {
                    'atime': 300,
                    'con': 'Yes',
                    'dihandle': '0x71450c359498',
                    'ecbi': 0,
                    'etime': 3,
                    'flags': 0,
                    'machandle': '0x71450cac2c98',
                    'ports': 'GigabitEthernet1/4/0/25',
                    'rihandle': '0x0',
                    'seq': 995,
                    'sihandle': '0x71450c9a37a8',
                    'type': '0x1',
                },
            },
        },
        '9': {
            'mac': {
                '7061.7bb8.c3e8': {
                    'atime': 0,
                    'con': 'Yes',
                    'dihandle': '0x0',
                    'ecbi': 0,
                    'etime': 0,
                    'flags': 64,
                    'machandle': '0x71450ca556e8',
                    'ports': 'Vlan9',
                    'rihandle': '0x0',
                    'seq': 0,
                    'sihandle': '0x71450c355218',
                    'type': '0x8002',
                },
            },
        },
    },
}