expected_output = {'interface-information': {'physical-interface': [{'admin-status': {'@junos:format': 'Enabled'},
                                                   'bpdu-error': 'None',
                                                   'if-flow-control': 'Disabled',
                                                   'link-level-type': 'Ethernet',
                                                   'local-index': '192',
                                                   'loopback': 'Disabled',
                                                   'mac-rewrite-error': 'None',
                                                   'minimum-bandwidth-in-aggregate': '1bps',
                                                   'minimum-links-in-aggregate': '1',
                                                   'mtu': '1514',
                                                   'name': 'ae0',
                                                   'oper-status': 'Up',
                                                   'pad-to-minimum-frame-size': 'Disabled',
                                                   'snmp-index': '822',
                                                   'source-filtering': 'Disabled',
                                                   'speed': '30Gbps'}]}}