expected_output = {
    'cmd': 'port_diag unit 0 port 40 slot 0',
    'mac_port_details': {
        'am_lock': ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F'],
        'get_an_enabled': 'FALSE',
        'get_link_management_enabled': 'TRUE',
        'get_loopback_mode': 'NONE',
        'get_serdes_continuous_tuning_enabled': 'TRUE',
        'get_speed': '10G',
        'get_state': 'TUNING',
        'get_tune_status': 'FALSE',
        'high_ber': 0,
        'link_state': 0,
        'mac_pcs_lanes': [0],
        'pcs_status': 0,
        'state_transitions': [{'state': 'INACTIVE', 'count': 2}, {'state': 'garbage', 'count': 4}, {'state': 'ACTIVE', 'count': 8}, {'state': 'WAITING_FOR_PEER', 'count': 6}, {'state': 'TUNING', 'count': 6}, {'state': 'TUNED', 'count': 5}, {'state': 'PCS_LOCK', 'count': 3}, {'state': 'garbage', 'count': 85}, {'state': 'PCS_STABLE', 'count': 86}, {'state': 'LINK_UP', 'count': 1}],
    },
    'mib_counters': {
        'rx_legal_bytes': 68,
        'rx_legal_flow_control_packets': 0,
        'rx_legal_frames': 1,
        'rx_legal_frames_with_1024_1518_bytes': 0,
        'rx_legal_frames_with_128_255_bytes': 0,
        'rx_legal_frames_with_1519_2500_bytes': 0,
        'rx_legal_frames_with_2501_9000_bytes': 0,
        'rx_legal_frames_with_256_511_bytes': 0,
        'rx_legal_frames_with_511_1023_bytes': 0,
        'rx_legal_frames_with_64_bytes': 0,
        'rx_legal_frames_with_65_127_bytes': 1,
        'rx_out_of_band_packets_received': 0,
        'rx_out_of_band_packets_with_code_error': 0,
        'rx_out_of_band_packets_with_crc_error': 0,
        'rx_packet_received_larger_from_max_packet_size': 0,
        'rx_packet_received_smaller_from_min_packet_size': 0,
        'rx_packets_received_with_crc_errors': 0,
        'rx_packets_received_with_inverted_crc': 0,
        'rx_packets_with_code_error': 0,
        'rx_received_frames_with_inverted_crc': 0,
        'tx_frames_with_crc_error': 0,
        'tx_internal_error_out_of_band_packets_with_crc_error': 0,
        'tx_internal_error_packets_missing_the_end_of_packet': 0,
        'tx_internal_error_under_run_packets': 0,
        'tx_legal_bytes_counter': 68,
        'tx_legal_flow_control_packets': 0,
        'tx_legal_frames_counter': 1,
        'tx_legal_frames_with_1024_1518_bytes': 0,
        'tx_legal_frames_with_128_255_bytes': 0,
        'tx_legal_frames_with_1519_2500_bytes': 0,
        'tx_legal_frames_with_2501_9000_bytes': 0,
        'tx_legal_frames_with_256_511_bytes': 0,
        'tx_legal_frames_with_512_1023_bytes': 0,
        'tx_legal_frames_with_64_bytes': 0,
        'tx_legal_frames_with_65_127_bytes': 1,
        'tx_out_of_band_packets_transmitted': 0,
    },
    'port': 41,
    'rc': '0x0',
    'reason': 'success',
    'slot': 1,
}
