expected_output = {
    'cause': {
        'ACL MIRROR': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 1211,
            'rx_delta': 1211,
            'source': 'EGMIR',
        },
        'ARP MIRROR': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 1092039,
            'rx_delta': 1092039,
            'source': 'INMIR',
        },
        'ARP Snooping': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 1616,
            'rx_delta': 1616,
            'source': 'ITRAP',
        },
        'CISCO Protocols': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 525860,
            'rx_delta': 525860,
            'source': 'ITRAP',
        },
        'DHCP Client(v4)': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 264,
            'rx_delta': 264,
            'source': 'ITRAP',
        },
        'DHCP MIRROR': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 1493428,
            'rx_delta': 1493428,
            'source': 'INMIR',
        },
        'DHCP Server(v4)': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 3645,
            'rx_delta': 3645,
            'source': 'ITRAP',
        },
        'DHCP Server(v6)': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 42,
            'rx_delta': 42,
            'source': 'ITRAP',
        },
        'DHCP Snooping': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 4855,
            'rx_delta': 4855,
            'source': 'ITRAP',
        },
        'DHCPv4 C to S': {
            'drop_cur': 12,
            'drop_delta': 12,
            'rx_cur': 12,
            'rx_delta': 12,
            'source': 'LPTS',
        },
        'DHCPv6 C to S': {
            'drop_cur': 5622,
            'drop_delta': 5622,
            'rx_cur': 5622,
            'rx_delta': 5622,
            'source': 'LPTS',
        },
        'EPC': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 14,
            'rx_delta': 14,
            'source': 'EGMIR',
        },
        'Egres DHCP Snooping': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 13,
            'rx_delta': 13,
            'source': 'ETRAP',
        },
        'GLEAN-SUBNET': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 217,
            'rx_delta': 217,
            'source': 'ITRAP',
        },
        'ICMP IPv4': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 409,
            'rx_delta': 409,
            'source': 'LPTS',
        },
        'ICMP IPv6 MC': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 16408,
            'rx_delta': 16408,
            'source': 'LPTS',
        },
        'IGMP l2 lpts': {
            'drop_cur': 1,
            'drop_delta': 1,
            'rx_cur': 92,
            'rx_delta': 92,
            'source': 'ITRAP',
        },
        'IPv4 MC': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 341,
            'rx_delta': 341,
            'source': 'LPTS',
        },
        'IPv6 MC': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 40,
            'rx_delta': 40,
            'source': 'LPTS',
        },
        'IPv6 Options': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 19260,
            'rx_delta': 19260,
            'source': 'LPTS',
        },
        'LACP': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 10971,
            'rx_delta': 10971,
            'source': 'ITRAP',
        },
        'LLDP': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 53864,
            'rx_delta': 53864,
            'source': 'ITRAP',
        },
        'MDNS': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 1824,
            'rx_delta': 1824,
            'source': 'ITRAP',
        },
        'OSPF v2 MC': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 334089,
            'rx_delta': 334089,
            'source': 'LPTS',
        },
        'OSPF v2 UC': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 441,
            'rx_delta': 441,
            'source': 'LPTS',
        },
        'OSPF v3 MC': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 862,
            'rx_delta': 862,
            'source': 'LPTS',
        },
        'SISF': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 341,
            'rx_delta': 341,
            'source': 'ITRAP',
        },
        'STP(IEEE)': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 799679,
            'rx_delta': 799679,
            'source': 'ITRAP',
        },
        'UDP default IPv4': {
            'drop_cur': 0,
            'drop_delta': 0,
            'rx_cur': 432,
            'rx_delta': 432,
            'source': 'LPTS',
        },
        'UNKNOWN': {
            'drop_cur': 47,
            'drop_delta': 47,
            'rx_cur': 47,
            'rx_delta': 47,
            'source': 'UKNWN',
        },
    },
}
