expected_output = {'instance': {'65100': {'vrf': {'osatm': {'interfaces': {
    'loopback105': {'name': 'loopback105', 'status': 'protocol-up/link-up/admin-up',
                    'ipv4': '10.101.68.54', 'ipv4_subnet': '10.101.68.54/32',
                    'ipv6': {'3620:82:e000:50::4/128': {'state': 'VALID'}},
                    'ipv6_subnet': '3620:82:e000:50::4/128',
                    'ipv6_link_local_address': 'fe80::f6db:e6ff:fe4a:6333',
                    'authentication': {'level_1': {}, 'level_2': {'auth_check': 'set'}},
                    'index': '0x0002', 'local_circuit_id': '0x01', 'circuit_type': 'L2',
                    'bfd_ipv4': 'locally disabled', 'bfd_ipv6': 'locally disabled',
                    'mtr': 'disabled', 'passive': 'level-1-2',
                    'levels': {'1': {'metric': '1'}, '2': {'metric': '1'}},
                    'topologies': {'0': {'level': {
                        '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                              'ipv4_mt': 'DN', 'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                              'ipv6_cfg': 'no'},
                        '2': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                              'ipv4_mt': 'DN', 'ipv4_cfg': 'yes', 'ipv6_mt': 'DN',
                              'ipv6_cfg': 'yes'}}}}},
    'port-channel1.105': {'name': 'port-channel1.105',
                          'status': 'protocol-up/link-up/admin-up',
                          'ipv4': '10.101.68.154', 'ipv4_subnet': '10.101.68.154/31',
                          'ipv6': {'3620:82:e000:52::4/127': {'state': 'VALID'}},
                          'ipv6_subnet': '3620:82:e000:52::4/127',
                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                          'index': '0x0001', 'local_circuit_id': '0x01',
                          'circuit_type': 'L2', 'bfd_ipv4': 'locally enabled',
                          'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                          'passive': 'level-1', 'mtu': 9216, 'lsp_interval_ms': 33,
                          'topologies': {'0': {'level': {
                              '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                    'ipv4_mt': 'DN', 'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                    'ipv6_cfg': 'no'},
                              '2': {'metric': '5', 'metric_cfg': 'yes', 'fwdng': 'UP',
                                    'ipv4_mt': 'UP', 'ipv4_cfg': 'yes', 'ipv6_mt': 'UP',
                                    'ipv6_cfg': 'yes'}}}}},
    'Ethernet1/2.105': {'name': 'Ethernet1/2.105',
                        'status': 'protocol-up/link-up/admin-up',
                        'ipv4': '10.101.69.108', 'ipv4_subnet': '10.101.69.108/31',
                        'ipv6': {'3620:82:e000:52::1e/127': {'state': 'VALID'}},
                        'ipv6_subnet': '3620:82:e000:52::1e/127',
                        'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                        'index': '0x0003', 'local_circuit_id': '0x01',
                        'circuit_type': 'L2', 'bfd_ipv4': 'locally enabled',
                        'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                        'passive': 'level-1', 'mtu': 9216, 'lsp_interval_ms': 33,
                        'topologies': {'0': {'level': {
                            '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                  'ipv4_mt': 'DN', 'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                  'ipv6_cfg': 'no'},
                            '2': {'metric': '140', 'metric_cfg': 'yes', 'fwdng': 'UP',
                                  'ipv4_mt': 'UP', 'ipv4_cfg': 'yes', 'ipv6_mt': 'UP',
                                  'ipv6_cfg': 'yes'}}}}},
    'Ethernet2/2.105': {'name': 'Ethernet2/2.105',
                        'status': 'protocol-up/link-up/admin-up',
                        'ipv4': '10.101.69.53', 'ipv4_subnet': '10.101.69.52/31',
                        'ipv6': {'3620:82:e000:52::17/127': {'state': 'VALID'}},
                        'ipv6_subnet': '3620:82:e000:52::16/127',
                        'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                        'index': '0x0004', 'local_circuit_id': '0x01',
                        'circuit_type': 'L2', 'bfd_ipv4': 'locally enabled',
                        'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                        'passive': 'level-1', 'mtu': 9216, 'lsp_interval_ms': 33,
                        'topologies': {'0': {'level': {
                            '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                  'ipv4_mt': 'DN', 'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                  'ipv6_cfg': 'no'},
                            '2': {'metric': '700', 'metric_cfg': 'yes', 'fwdng': 'UP',
                                  'ipv4_mt': 'UP', 'ipv4_cfg': 'yes', 'ipv6_mt': 'UP',
                                  'ipv6_cfg': 'yes'}}}}}}}, 'odeprod': {'interfaces': {
    'loopback104': {'name': 'loopback104', 'status': 'protocol-up/link-up/admin-up',
                    'ipv4': '10.101.68.44', 'ipv4_subnet': '10.101.68.44/32',
                    'ipv6': {'3620:82:e000:40::4/128': {'state': 'VALID'}},
                    'ipv6_subnet': '3620:82:e000:40::4/128',
                    'ipv6_link_local_address': 'fe80::f6db:e6ff:fe4a:6333',
                    'authentication': {'level_1': {}, 'level_2': {'auth_check': 'set'}},
                    'index': '0x0002', 'local_circuit_id': '0x01', 'circuit_type': 'L2',
                    'bfd_ipv4': 'locally disabled', 'bfd_ipv6': 'locally disabled',
                    'mtr': 'disabled', 'passive': 'level-1-2',
                    'levels': {'1': {'metric': '1'}, '2': {'metric': '1'}},
                    'topologies': {'0': {'level': {
                        '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                              'ipv4_mt': 'DN', 'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                              'ipv6_cfg': 'no'},
                        '2': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                              'ipv4_mt': 'DN', 'ipv4_cfg': 'yes', 'ipv6_mt': 'DN',
                              'ipv6_cfg': 'yes'}}}}},
    'port-channel1.104': {'name': 'port-channel1.104',
                          'status': 'protocol-up/link-up/admin-up',
                          'ipv4': '10.101.68.144', 'ipv4_subnet': '10.101.68.144/31',
                          'ipv6': {'3620:82:e000:42::4/127': {'state': 'VALID'}},
                          'ipv6_subnet': '3620:82:e000:42::4/127',
                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                          'index': '0x0001', 'local_circuit_id': '0x01',
                          'circuit_type': 'L2', 'bfd_ipv4': 'locally enabled',
                          'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                          'passive': 'level-1', 'mtu': 9216, 'lsp_interval_ms': 33,
                          'topologies': {'0': {'level': {
                              '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                    'ipv4_mt': 'DN', 'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                    'ipv6_cfg': 'no'},
                              '2': {'metric': '5', 'metric_cfg': 'yes', 'fwdng': 'UP',
                                    'ipv4_mt': 'UP', 'ipv4_cfg': 'yes', 'ipv6_mt': 'UP',
                                    'ipv6_cfg': 'yes'}}}}},
    'Ethernet1/2.104': {'name': 'Ethernet1/2.104',
                        'status': 'protocol-up/link-up/admin-up',
                        'ipv4': '10.101.69.106', 'ipv4_subnet': '10.101.69.106/31',
                        'ipv6': {'3620:82:e000:42::1e/127': {'state': 'VALID'}},
                        'ipv6_subnet': '3620:82:e000:42::1e/127',
                        'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                        'index': '0x0003', 'local_circuit_id': '0x01',
                        'circuit_type': 'L2', 'bfd_ipv4': 'locally enabled',
                        'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                        'passive': 'level-1', 'mtu': 9216, 'lsp_interval_ms': 33,
                        'topologies': {'0': {'level': {
                            '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                  'ipv4_mt': 'DN', 'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                  'ipv6_cfg': 'no'},
                            '2': {'metric': '140', 'metric_cfg': 'yes', 'fwdng': 'UP',
                                  'ipv4_mt': 'UP', 'ipv4_cfg': 'yes', 'ipv6_mt': 'UP',
                                  'ipv6_cfg': 'yes'}}}}},
    'Ethernet2/2.104': {'name': 'Ethernet2/2.104',
                        'status': 'protocol-up/link-up/admin-up',
                        'ipv4': '10.101.69.51', 'ipv4_subnet': '10.101.69.50/31',
                        'ipv6': {'3620:82:e000:42::17/127': {'state': 'VALID'}},
                        'ipv6_subnet': '3620:82:e000:42::16/127',
                        'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                        'index': '0x0004', 'local_circuit_id': '0x01',
                        'circuit_type': 'L2', 'bfd_ipv4': 'locally enabled',
                        'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                        'passive': 'level-1', 'mtu': 9216, 'lsp_interval_ms': 33,
                        'topologies': {'0': {'level': {
                            '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                  'ipv4_mt': 'DN', 'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                  'ipv6_cfg': 'no'},
                            '2': {'metric': '700', 'metric_cfg': 'yes', 'fwdng': 'UP',
                                  'ipv4_mt': 'UP', 'ipv4_cfg': 'yes', 'ipv6_mt': 'UP',
                                  'ipv6_cfg': 'yes'}}}}}}}, 'excontrol': {
    'interfaces': {
        'loopback102': {'name': 'loopback102', 'status': 'protocol-up/link-up/admin-up',
                        'ipv4': '10.101.68.24', 'ipv4_subnet': '10.101.68.24/32',
                        'ipv6': {'3620:82:e000:20::4/128': {'state': 'VALID'}},
                        'ipv6_subnet': '3620:82:e000:20::4/128',
                        'ipv6_link_local_address': 'fe80::f6db:e6ff:fe4a:6333',
                        'authentication': {'level_1': {},
                                           'level_2': {'auth_check': 'set'}},
                        'index': '0x0002', 'local_circuit_id': '0x01',
                        'circuit_type': 'L2', 'bfd_ipv4': 'locally disabled',
                        'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                        'passive': 'level-1-2',
                        'levels': {'1': {'metric': '1'}, '2': {'metric': '1'}},
                        'topologies': {'0': {'level': {
                            '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                  'ipv4_mt': 'DN', 'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                  'ipv6_cfg': 'no'},
                            '2': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                  'ipv4_mt': 'DN', 'ipv4_cfg': 'yes', 'ipv6_mt': 'DN',
                                  'ipv6_cfg': 'yes'}}}}},
        'port-channel1.102': {'name': 'port-channel1.102',
                              'status': 'protocol-up/link-up/admin-up',
                              'ipv4': '10.101.68.124',
                              'ipv4_subnet': '10.101.68.124/31',
                              'ipv6': {'3620:82:e000:22::4/127': {'state': 'VALID'}},
                              'ipv6_subnet': '3620:82:e000:22::4/127',
                              'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                              'index': '0x0001', 'local_circuit_id': '0x01',
                              'circuit_type': 'L2', 'bfd_ipv4': 'locally enabled',
                              'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                              'passive': 'level-1', 'mtu': 9216, 'lsp_interval_ms': 33,
                              'topologies': {'0': {'level': {
                                  '1': {'metric': '1', 'metric_cfg': 'no',
                                        'fwdng': 'UP', 'ipv4_mt': 'DN',
                                        'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                        'ipv6_cfg': 'no'},
                                  '2': {'metric': '5', 'metric_cfg': 'yes',
                                        'fwdng': 'UP', 'ipv4_mt': 'UP',
                                        'ipv4_cfg': 'yes', 'ipv6_mt': 'UP',
                                        'ipv6_cfg': 'yes'}}}}},
        'Ethernet1/2.102': {'name': 'Ethernet1/2.102',
                            'status': 'protocol-up/link-up/admin-up',
                            'ipv4': '10.101.69.102', 'ipv4_subnet': '10.101.69.102/31',
                            'ipv6': {'3620:82:e000:22::1e/127': {'state': 'VALID'}},
                            'ipv6_subnet': '3620:82:e000:22::1e/127',
                            'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                            'index': '0x0003', 'local_circuit_id': '0x01',
                            'circuit_type': 'L2', 'bfd_ipv4': 'locally enabled',
                            'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                            'passive': 'level-1', 'mtu': 9216, 'lsp_interval_ms': 33,
                            'topologies': {'0': {'level': {
                                '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                      'ipv4_mt': 'DN', 'ipv4_cfg': 'no',
                                      'ipv6_mt': 'DN', 'ipv6_cfg': 'no'},
                                '2': {'metric': '140', 'metric_cfg': 'yes',
                                      'fwdng': 'UP', 'ipv4_mt': 'UP', 'ipv4_cfg': 'yes',
                                      'ipv6_mt': 'UP', 'ipv6_cfg': 'yes'}}}}},
        'Ethernet2/2.102': {'name': 'Ethernet2/2.102',
                            'status': 'protocol-up/link-up/admin-up',
                            'ipv4': '10.101.69.47', 'ipv4_subnet': '10.101.69.46/31',
                            'ipv6': {'3620:82:e000:22::17/127': {'state': 'VALID'}},
                            'ipv6_subnet': '3620:82:e000:22::16/127',
                            'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                            'index': '0x0004', 'local_circuit_id': '0x01',
                            'circuit_type': 'L2', 'bfd_ipv4': 'locally enabled',
                            'bfd_ipv6': 'locally disabled', 'mtr': 'disabled',
                            'passive': 'level-1', 'mtu': 9216, 'lsp_interval_ms': 33,
                            'topologies': {'0': {'level': {
                                '1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                      'ipv4_mt': 'DN', 'ipv4_cfg': 'no',
                                      'ipv6_mt': 'DN', 'ipv6_cfg': 'no'},
                                '2': {'metric': '700', 'metric_cfg': 'yes',
                                      'fwdng': 'UP', 'ipv4_mt': 'UP', 'ipv4_cfg': 'yes',
                                      'ipv6_mt': 'UP', 'ipv6_cfg': 'yes'}}}}}}},
                                                  'default': {}, 'oos-be': {
        'interfaces': {'loopback108': {'name': 'loopback108',
                                       'status': 'protocol-up/link-up/admin-up',
                                       'ipv4': '10.101.68.84',
                                       'ipv4_subnet': '10.101.68.84/32', 'ipv6': {
                '3620:82:e000:80::4/128': {'state': 'VALID'}},
                                       'ipv6_subnet': '3620:82:e000:80::4/128',
                                       'ipv6_link_local_address': 'fe80::f6db:e6ff:fe4a:6333',
                                       'authentication': {'level_1': {}, 'level_2': {
                                           'auth_check': 'set'}}, 'index': '0x0002',
                                       'local_circuit_id': '0x01', 'circuit_type': 'L2',
                                       'bfd_ipv4': 'locally disabled',
                                       'bfd_ipv6': 'locally disabled',
                                       'mtr': 'disabled', 'passive': 'level-1-2',
                                       'levels': {'1': {'metric': '1'},
                                                  '2': {'metric': '1'}}, 'topologies': {
                '0': {'level': {'1': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                      'ipv4_mt': 'DN', 'ipv4_cfg': 'no',
                                      'ipv6_mt': 'DN', 'ipv6_cfg': 'no'},
                                '2': {'metric': '1', 'metric_cfg': 'no', 'fwdng': 'UP',
                                      'ipv4_mt': 'DN', 'ipv4_cfg': 'yes',
                                      'ipv6_mt': 'DN', 'ipv6_cfg': 'yes'}}}}},
                       'port-channel1.108': {'name': 'port-channel1.108',
                                             'status': 'protocol-up/link-up/admin-up',
                                             'ipv4': '10.101.68.184',
                                             'ipv4_subnet': '10.101.68.184/31',
                                             'ipv6': {'3620:82:e000:82::4/127': {
                                                 'state': 'VALID'}},
                                             'ipv6_subnet': '3620:82:e000:82::4/127',
                                             'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                             'index': '0x0001',
                                             'local_circuit_id': '0x01',
                                             'circuit_type': 'L2',
                                             'bfd_ipv4': 'locally enabled',
                                             'bfd_ipv6': 'locally disabled',
                                             'mtr': 'disabled', 'passive': 'level-1',
                                             'mtu': 9216, 'lsp_interval_ms': 33,
                                             'topologies': {'0': {'level': {
                                                 '1': {'metric': '1',
                                                       'metric_cfg': 'no',
                                                       'fwdng': 'UP', 'ipv4_mt': 'DN',
                                                       'ipv4_cfg': 'no',
                                                       'ipv6_mt': 'DN',
                                                       'ipv6_cfg': 'no'},
                                                 '2': {'metric': '5',
                                                       'metric_cfg': 'yes',
                                                       'fwdng': 'UP', 'ipv4_mt': 'UP',
                                                       'ipv4_cfg': 'yes',
                                                       'ipv6_mt': 'UP',
                                                       'ipv6_cfg': 'yes'}}}}},
                       'Ethernet1/2.108': {'name': 'Ethernet1/2.108',
                                           'status': 'protocol-up/link-up/admin-up',
                                           'ipv4': '10.101.69.170',
                                           'ipv4_subnet': '10.101.69.170/31', 'ipv6': {
                               '3620:82:e000:82::1e/127': {'state': 'VALID'}},
                                           'ipv6_subnet': '3620:82:e000:82::1e/127',
                                           'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                           'index': '0x0003',
                                           'local_circuit_id': '0x01',
                                           'circuit_type': 'L2',
                                           'bfd_ipv4': 'locally enabled',
                                           'bfd_ipv6': 'locally disabled',
                                           'mtr': 'disabled', 'passive': 'level-1',
                                           'mtu': 9216, 'lsp_interval_ms': 33,
                                           'topologies': {'0': {'level': {
                                               '1': {'metric': '1', 'metric_cfg': 'no',
                                                     'fwdng': 'UP', 'ipv4_mt': 'DN',
                                                     'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                                     'ipv6_cfg': 'no'},
                                               '2': {'metric': '140',
                                                     'metric_cfg': 'yes', 'fwdng': 'UP',
                                                     'ipv4_mt': 'UP', 'ipv4_cfg': 'yes',
                                                     'ipv6_mt': 'UP',
                                                     'ipv6_cfg': 'yes'}}}}},
                       'Ethernet2/2.108': {'name': 'Ethernet2/2.108',
                                           'status': 'protocol-up/link-up/admin-up',
                                           'ipv4': '10.101.69.155',
                                           'ipv4_subnet': '10.101.69.154/31', 'ipv6': {
                               '3620:82:e000:82::17/127': {'state': 'VALID'}},
                                           'ipv6_subnet': '3620:82:e000:82::16/127',
                                           'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                           'index': '0x0004',
                                           'local_circuit_id': '0x01',
                                           'circuit_type': 'L2',
                                           'bfd_ipv4': 'locally enabled',
                                           'bfd_ipv6': 'locally disabled',
                                           'mtr': 'disabled', 'passive': 'level-1',
                                           'mtu': 9216, 'lsp_interval_ms': 33,
                                           'topologies': {'0': {'level': {
                                               '1': {'metric': '1', 'metric_cfg': 'no',
                                                     'fwdng': 'UP', 'ipv4_mt': 'DN',
                                                     'ipv4_cfg': 'no', 'ipv6_mt': 'DN',
                                                     'ipv6_cfg': 'no'},
                                               '2': {'metric': '700',
                                                     'metric_cfg': 'yes', 'fwdng': 'UP',
                                                     'ipv4_mt': 'UP', 'ipv4_cfg': 'yes',
                                                     'ipv6_mt': 'UP',
                                                     'ipv6_cfg': 'yes'}}}}}}},
                                                  'oon-hybrid': {'interfaces': {
                                                      'loopback106': {
                                                          'name': 'loopback106',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.64',
                                                          'ipv4_subnet': '10.101.68.64/32',
                                                          'ipv6': {
                                                              '3620:82:e000:60::4/128': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:60::4/128',
                                                          'ipv6_link_local_address': 'fe80::f6db:e6ff:fe4a:6333',
                                                          'authentication': {
                                                              'level_1': {},
                                                              'level_2': {
                                                                  'auth_check': 'set'}},
                                                          'index': '0x0002',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally disabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1-2',
                                                          'levels': {
                                                              '1': {'metric': '1'},
                                                              '2': {'metric': '1'}},
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'port-channel1.106': {
                                                          'name': 'port-channel1.106',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.164',
                                                          'ipv4_subnet': '10.101.68.164/31',
                                                          'ipv6': {
                                                              '3620:82:e000:62::4/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:62::4/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0001',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '5',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet1/2.106': {
                                                          'name': 'Ethernet1/2.106',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.110',
                                                          'ipv4_subnet': '10.101.69.110/31',
                                                          'ipv6': {
                                                              '3620:82:e000:62::1e/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:62::1e/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0003',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '140',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet2/2.106': {
                                                          'name': 'Ethernet2/2.106',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.55',
                                                          'ipv4_subnet': '10.101.69.54/31',
                                                          'ipv6': {
                                                              '3620:82:e000:62::17/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:62::16/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0004',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '700',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}}}},
                                                  'exnotprod': {'interfaces': {
                                                      'loopback103': {
                                                          'name': 'loopback103',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.34',
                                                          'ipv4_subnet': '10.101.68.34/32',
                                                          'ipv6': {
                                                              '3620:82:e000:30::4/128': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:30::4/128',
                                                          'ipv6_link_local_address': 'fe80::f6db:e6ff:fe4a:6333',
                                                          'authentication': {
                                                              'level_1': {},
                                                              'level_2': {
                                                                  'auth_check': 'set'}},
                                                          'index': '0x0002',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally disabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1-2',
                                                          'levels': {
                                                              '1': {'metric': '1'},
                                                              '2': {'metric': '1'}},
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'port-channel1.103': {
                                                          'name': 'port-channel1.103',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.134',
                                                          'ipv4_subnet': '10.101.68.134/31',
                                                          'ipv6': {
                                                              '3620:82:e000:32::4/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:32::4/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0001',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '5',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet1/2.103': {
                                                          'name': 'Ethernet1/2.103',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.104',
                                                          'ipv4_subnet': '10.101.69.104/31',
                                                          'ipv6': {
                                                              '3620:82:e000:32::1e/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:32::1e/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0003',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '140',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet2/2.103': {
                                                          'name': 'Ethernet2/2.103',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.49',
                                                          'ipv4_subnet': '10.101.69.48/31',
                                                          'ipv6': {
                                                              '3620:82:e000:32::17/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:32::16/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0004',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '700',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}}}},
                                                  'exrestrict': {'interfaces': {
                                                      'loopback100': {
                                                          'name': 'loopback100',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.4',
                                                          'ipv4_subnet': '10.101.68.4/32',
                                                          'ipv6': {
                                                              '3620:82:e000::4/128': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000::4/128',
                                                          'ipv6_link_local_address': 'fe80::f6db:e6ff:fe4a:6333',
                                                          'authentication': {
                                                              'level_1': {},
                                                              'level_2': {
                                                                  'auth_check': 'set'}},
                                                          'index': '0x0002',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally disabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1-2',
                                                          'levels': {
                                                              '1': {'metric': '1'},
                                                              '2': {'metric': '1'}},
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'port-channel1.100': {
                                                          'name': 'port-channel1.100',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.104',
                                                          'ipv4_subnet': '10.101.68.104/31',
                                                          'ipv6': {
                                                              '3620:82:e000:2::4/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:2::4/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0001',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '5',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet1/2.100': {
                                                          'name': 'Ethernet1/2.100',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.98',
                                                          'ipv4_subnet': '10.101.69.98/31',
                                                          'ipv6': {
                                                              '3620:82:e000:2::1e/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:2::1e/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0003',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '140',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet2/2.100': {
                                                          'name': 'Ethernet2/2.100',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.43',
                                                          'ipv4_subnet': '10.101.69.42/31',
                                                          'ipv6': {
                                                              '3620:82:e000:2::17/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:2::16/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0004',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '700',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}}}},
                                                  'exwan-netconf': {'interfaces': {
                                                      'loopback107': {
                                                          'name': 'loopback107',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.74',
                                                          'ipv4_subnet': '10.101.68.74/32',
                                                          'ipv6': {
                                                              '3620:82:e000:70::4/128': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:70::4/128',
                                                          'ipv6_link_local_address': 'fe80::f6db:e6ff:fe4a:6333',
                                                          'authentication': {
                                                              'level_1': {},
                                                              'level_2': {
                                                                  'auth_check': 'set'}},
                                                          'index': '0x0002',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally disabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1-2',
                                                          'levels': {
                                                              '1': {'metric': '1'},
                                                              '2': {'metric': '1'}},
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'port-channel1.107': {
                                                          'name': 'port-channel1.107',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.174',
                                                          'ipv4_subnet': '10.101.68.174/31',
                                                          'ipv6': {
                                                              '3620:82:e000:72::4/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:72::4/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0001',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '5',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet1/2.107': {
                                                          'name': 'Ethernet1/2.107',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.168',
                                                          'ipv4_subnet': '10.101.69.168/31',
                                                          'ipv6': {
                                                              '3620:82:e000:72::1e/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:72::1e/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0003',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '140',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet2/2.107': {
                                                          'name': 'Ethernet2/2.107',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.153',
                                                          'ipv4_subnet': '10.101.69.152/31',
                                                          'ipv6': {
                                                              '3620:82:e000:72::17/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:72::16/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0004',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '700',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}}}},
                                                  'exuuser': {'interfaces': {
                                                      'loopback101': {
                                                          'name': 'loopback101',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.14',
                                                          'ipv4_subnet': '10.101.68.14/32',
                                                          'ipv6': {
                                                              '3620:82:e000:10::4/128': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:10::4/128',
                                                          'ipv6_link_local_address': 'fe80::f6db:e6ff:fe4a:6333',
                                                          'authentication': {
                                                              'level_1': {},
                                                              'level_2': {
                                                                  'auth_check': 'set'}},
                                                          'index': '0x0002',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally disabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1-2',
                                                          'levels': {
                                                              '1': {'metric': '1'},
                                                              '2': {'metric': '1'}},
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'port-channel1.101': {
                                                          'name': 'port-channel1.101',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.68.114',
                                                          'ipv4_subnet': '10.101.68.114/31',
                                                          'ipv6': {
                                                              '3620:82:e000:12::4/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:12::4/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0001',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '5',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet1/2.101': {
                                                          'name': 'Ethernet1/2.101',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.100',
                                                          'ipv4_subnet': '10.101.69.100/31',
                                                          'ipv6': {
                                                              '3620:82:e000:12::1e/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:12::1e/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0003',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '140',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}},
                                                      'Ethernet2/2.101': {
                                                          'name': 'Ethernet2/2.101',
                                                          'status': 'protocol-up/link-up/admin-up',
                                                          'ipv4': '10.101.69.45',
                                                          'ipv4_subnet': '10.101.69.44/31',
                                                          'ipv6': {
                                                              '3620:82:e000:12::17/127': {
                                                                  'state': 'VALID'}},
                                                          'ipv6_subnet': '3620:82:e000:12::16/127',
                                                          'ipv6_link_local_address': 'fe80::2de:fbff:fef2:ee41',
                                                          'index': '0x0004',
                                                          'local_circuit_id': '0x01',
                                                          'circuit_type': 'L2',
                                                          'bfd_ipv4': 'locally enabled',
                                                          'bfd_ipv6': 'locally disabled',
                                                          'mtr': 'disabled',
                                                          'passive': 'level-1',
                                                          'mtu': 9216,
                                                          'lsp_interval_ms': 33,
                                                          'topologies': {'0': {
                                                              'level': {
                                                                  '1': {'metric': '1',
                                                                        'metric_cfg': 'no',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'DN',
                                                                        'ipv4_cfg': 'no',
                                                                        'ipv6_mt': 'DN',
                                                                        'ipv6_cfg': 'no'},
                                                                  '2': {'metric': '700',
                                                                        'metric_cfg': 'yes',
                                                                        'fwdng': 'UP',
                                                                        'ipv4_mt': 'UP',
                                                                        'ipv4_cfg': 'yes',
                                                                        'ipv6_mt': 'UP',
                                                                        'ipv6_cfg': 'yes'}}}}}}}}}}}
