expected_output = {
    'lsmi_io_pool': {
        'free': 832,
        'total': 6295128,
        'used': 6294296,
    },
    'per_process_memory': {
        "SERIAL A'detect": {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45128,
            'pid': 58,
            'retbufs': 0,
            'tty': 0,
        },
        '*Dead*': {
            'allocated': 5393488,
            'freed': 3511208,
            'getbufs': 17486679,
            'holding': 1567944,
            'pid': 0,
            'retbufs': 0,
            'tty': 0,
        },
        '*Init*': {
            'allocated': 384659632,
            'freed': 63644408,
            'getbufs': 0,
            'holding': 296924520,
            'pid': 0,
            'retbufs': 0,
            'tty': 0,
        },
        '*MallocLite*': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 3348768,
            'pid': 0,
            'retbufs': 0,
            'tty': 0,
        },
        '*Sched*': {
            'allocated': 1008,
            'freed': 1142232,
            'getbufs': 0,
            'holding': 1008,
            'pid': 0,
            'retbufs': 0,
            'tty': 0,
        },
        '100ms check': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 110,
            'retbufs': 0,
            'tty': 0,
        },
        '802.1x switch': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 181,
            'retbufs': 0,
            'tty': 0,
        },
        'AAA ACCT Proc': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 194,
            'retbufs': 0,
            'tty': 0,
        },
        'AAA Cached Serve': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 328,
            'retbufs': 0,
            'tty': 0,
        },
        'AAA Dictionary R': {
            'allocated': 560,
            'freed': 560,
            'getbufs': 0,
            'holding': 45000,
            'pid': 201,
            'retbufs': 0,
            'tty': 0,
        },
        'AAA EPD HANDLER': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 214,
            'retbufs': 0,
            'tty': 0,
        },
        'AAA Proxy': {
            'allocated': 7944,
            'freed': 848,
            'getbufs': 0,
            'holding': 76760,
            'pid': 342,
            'retbufs': 0,
            'tty': 0,
        },
        'AAA SEND STOP EV': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 384,
            'retbufs': 0,
            'tty': 0,
        },
        'AAA Server': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 193,
            'retbufs': 0,
            'tty': 0,
        },
        'AAA System Acct': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 307,
            'retbufs': 0,
            'tty': 0,
        },
        'AAA_SERVER_DEADT': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 40,
            'retbufs': 0,
            'tty': 0,
        },
        'ACCT Periodic Pr': {
            'allocated': 98736,
            'freed': 0,
            'getbufs': 0,
            'holding': 143736,
            'pid': 195,
            'retbufs': 0,
            'tty': 0,
        },
        'ACL Log Punt Ser': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 119,
            'retbufs': 0,
            'tty': 0,
        },
        'ACL Logging Proc': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 33000,
            'pid': 145,
            'retbufs': 0,
            'tty': 0,
        },
        'ACL deny punt se': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 120,
            'retbufs': 0,
            'tty': 0,
        },
        'ADJ NSF process': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 33408,
            'pid': 200,
            'retbufs': 0,
            'tty': 0,
        },
        'ADJ background': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 69408,
            'pid': 293,
            'retbufs': 0,
            'tty': 0,
        },
        'ADJ resolve proc': {
            'allocated': 456,
            'freed': 0,
            'getbufs': 0,
            'holding': 69456,
            'pid': 308,
            'retbufs': 0,
            'tty': 0,
        },
        'AN CONFIG DOWNLO': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 117000,
            'pid': 272,
            'retbufs': 0,
            'tty': 0,
        },
        'AN HELPER': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 117000,
            'pid': 271,
            'retbufs': 0,
            'tty': 0,
        },
        'AN': {
            'allocated': 71280,
            'freed': 1672,
            'getbufs': 0,
            'holding': 186728,
            'pid': 270,
            'retbufs': 0,
            'tty': 0,
        },
        'ARP Background': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 36,
            'retbufs': 0,
            'tty': 0,
        },
        'ARP HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 106,
            'retbufs': 0,
            'tty': 0,
        },
        'ARP Input': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 35,
            'retbufs': 0,
            'tty': 0,
        },
        'ARP Snoop': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 53,
            'retbufs': 0,
            'tty': 0,
        },
        'ASP Process Crea': {
            'allocated': 448,
            'freed': 880,
            'getbufs': 0,
            'holding': 117000,
            'pid': 373,
            'retbufs': 0,
            'tty': 0,
        },
        'ATM ASYNC PROC': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 38,
            'retbufs': 0,
            'tty': 0,
        },
        'ATM Idle Timer': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 37,
            'retbufs': 0,
            'tty': 0,
        },
        'AUTO LAG Protoco': {
            'allocated': 896,
            'freed': 448,
            'getbufs': 0,
            'holding': 57448,
            'pid': 256,
            'retbufs': 0,
            'tty': 0,
        },
        'AggMgr Process': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 128,
            'retbufs': 0,
            'tty': 0,
        },
        'App Route Proces': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 57000,
            'pid': 316,
            'retbufs': 0,
            'tty': 0,
        },
        'BACK CHECK': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 73,
            'retbufs': 0,
            'tty': 0,
        },
        'BFD HA': {
            'allocated': 16680,
            'freed': 0,
            'getbufs': 0,
            'holding': 61680,
            'pid': 305,
            'retbufs': 0,
            'tty': 0,
        },
        'BSO task': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 117000,
            'pid': 245,
            'retbufs': 0,
            'tty': 0,
        },
        'Bulkstat-Client': {
            'allocated': 17264,
            'freed': 21400,
            'getbufs': 0,
            'holding': 56576,
            'pid': 403,
            'retbufs': 0,
            'tty': 0,
        },
        'CDP Forward Proc': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 185,
            'retbufs': 0,
            'tty': 0,
        },
        'CDP Protocol': {
            'allocated': 401112,
            'freed': 124360,
            'getbufs': 0,
            'holding': 86688,
            'pid': 196,
            'retbufs': 0,
            'tty': 0,
        },
        'CEF MIB API': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 39,
            'retbufs': 0,
            'tty': 0,
        },
        'CEF RP Backgroun': {
            'allocated': 456,
            'freed': 0,
            'getbufs': 0,
            'holding': 45456,
            'pid': 239,
            'retbufs': 0,
            'tty': 0,
        },
        'CEF RRP RF waite': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 33000,
            'pid': 108,
            'retbufs': 0,
            'tty': 0,
        },
        'CEF background p': {
            'allocated': 231536,
            'freed': 8168,
            'getbufs': 0,
            'holding': 292184,
            'pid': 230,
            'retbufs': 0,
            'tty': 0,
        },
        'CEF switching ba': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 69408,
            'pid': 199,
            'retbufs': 0,
            'tty': 0,
        },
        'CEF: IPv4 proces': {
            'allocated': 56704,
            'freed': 22752,
            'getbufs': 0,
            'holding': 99800,
            'pid': 292,
            'retbufs': 0,
            'tty': 0,
        },
        'CEF: IPv6 proces': {
            'allocated': 10552,
            'freed': 3088,
            'getbufs': 0,
            'holding': 76824,
            'pid': 257,
            'retbufs': 0,
            'tty': 0,
        },
        'CFM HA IPC messa': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 252,
            'retbufs': 0,
            'tty': 0,
        },
        'CMM IPC Msg Proc': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 285,
            'retbufs': 0,
            'tty': 0,
        },
        'CMM event proces': {
            'allocated': 10096,
            'freed': 0,
            'getbufs': 0,
            'holding': 55096,
            'pid': 286,
            'retbufs': 0,
            'tty': 0,
        },
        'COND_DEBUG HA IP': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 341,
            'retbufs': 0,
            'tty': 0,
        },
        'CONSOLE helper p': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 92,
            'retbufs': 0,
            'tty': 0,
        },
        'COPS': {
            'allocated': 1944,
            'freed': 0,
            'getbufs': 0,
            'holding': 262944,
            'pid': 309,
            'retbufs': 0,
            'tty': 0,
        },
        'CRYPTO MAP FREE': {
            'allocated': 448,
            'freed': 896,
            'getbufs': 0,
            'holding': 45000,
            'pid': 355,
            'retbufs': 0,
            'tty': 0,
        },
        'CTS CORE': {
            'allocated': 2336,
            'freed': 0,
            'getbufs': 0,
            'holding': 71336,
            'pid': 71,
            'retbufs': 0,
            'tty': 0,
        },
        'CTS HA IPC flow': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 82,
            'retbufs': 0,
            'tty': 0,
        },
        'CTS HA': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 81,
            'retbufs': 0,
            'tty': 0,
        },
        'CWAN OIR Handler': {
            'allocated': 3808456,
            'freed': 10600,
            'getbufs': 0,
            'holding': 1031720,
            'pid': 155,
            'retbufs': 0,
            'tty': 0,
        },
        'Call Home DS': {
            'allocated': 50072,
            'freed': 144,
            'getbufs': 0,
            'holding': 48864,
            'pid': 406,
            'retbufs': 0,
            'tty': 0,
        },
        'Call Home DSfile': {
            'allocated': 3720,
            'freed': 328,
            'getbufs': 0,
            'holding': 48720,
            'pid': 407,
            'retbufs': 0,
            'tty': 0,
        },
        'Call Home Timer': {
            'allocated': 26576,
            'freed': 0,
            'getbufs': 0,
            'holding': 48328,
            'pid': 198,
            'retbufs': 0,
            'tty': 0,
        },
        'Call Home proces': {
            'allocated': 244032,
            'freed': 83448,
            'getbufs': 0,
            'holding': 137832,
            'pid': 405,
            'retbufs': 0,
            'tty': 0,
        },
        'Check heaps': {
            'allocated': 6240,
            'freed': 448,
            'getbufs': 0,
            'holding': 50792,
            'pid': 9,
            'retbufs': 0,
            'tty': 0,
        },
        'Chunk Manager': {
            'allocated': 1533936,
            'freed': 0,
            'getbufs': 0,
            'holding': 1578936,
            'pid': 1,
            'retbufs': 0,
            'tty': 0,
        },
        'Collection proce': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 69408,
            'pid': 294,
            'retbufs': 0,
            'tty': 0,
        },
        'Compute load avg': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 125,
            'retbufs': 0,
            'tty': 0,
        },
        'Connection Mgr': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57128,
            'pid': 501,
            'retbufs': 0,
            'tty': 0,
        },
        'Critical Bkgnd': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 66,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto ACL': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 117000,
            'pid': 361,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto CA': {
            'allocated': 1288432,
            'freed': 1112144,
            'getbufs': 0,
            'holding': 176320,
            'pid': 346,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto IKE Dispa': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 357,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto IKEv2': {
            'allocated': 312096,
            'freed': 2112,
            'getbufs': 0,
            'holding': 378984,
            'pid': 364,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto IKMP': {
            'allocated': 41456,
            'freed': 448,
            'getbufs': 0,
            'holding': 110008,
            'pid': 358,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto INT': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 356,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto PAS Proc': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 362,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto PKI-CRL': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 347,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto PKI-HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 107,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto PKI-Rev-P': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 348,
            'retbufs': 0,
            'tty': 0,
        },
        'Crypto Support': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 326,
            'retbufs': 0,
            'tty': 0,
        },
        'DAI Packet Proce': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 33000,
            'pid': 282,
            'retbufs': 0,
            'tty': 0,
        },
        'DB Lock Manager': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 15,
            'retbufs': 0,
            'tty': 0,
        },
        'DBAL EVENTS': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 117000,
            'pid': 95,
            'retbufs': 0,
            'tty': 0,
        },
        'DCM Core Thread': {
            'allocated': 30880,
            'freed': 5984,
            'getbufs': 0,
            'holding': 69800,
            'pid': 383,
            'retbufs': 0,
            'tty': 0,
        },
        'DCM snmp dp Thre': {
            'allocated': 31144,
            'freed': 1136,
            'getbufs': 0,
            'holding': 59768,
            'pid': 401,
            'retbufs': 0,
            'tty': 0,
        },
        'DDR Timers': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45120,
            'pid': 42,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCP Client': {
            'allocated': 0,
            'freed': 1824,
            'getbufs': 0,
            'holding': 69000,
            'pid': 300,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCP Security He': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 376,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCP Snooping HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 103,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCP Snooping cl': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 100,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCP Snooping db': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 102,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCP Snooping': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 101,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCPC HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 111,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCPD HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 105,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCPv6 LQ client': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 320,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCPv6 Relay HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 112,
            'retbufs': 0,
            'tty': 0,
        },
        'DHCPv6 Server HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 113,
            'retbufs': 0,
            'tty': 0,
        },
        'DNS Service': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 312,
            'retbufs': 0,
            'tty': 0,
        },
        'DTP Protocol': {
            'allocated': 1792,
            'freed': 448,
            'getbufs': 0,
            'holding': 70344,
            'pid': 180,
            'retbufs': 0,
            'tty': 0,
        },
        'DiagCard1/-1': {
            'allocated': 17952,
            'freed': 18312,
            'getbufs': 0,
            'holding': 45000,
            'pid': 368,
            'retbufs': 0,
            'tty': 0,
        },
        'DiscardQ Backgro': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 11,
            'retbufs': 0,
            'tty': 0,
        },
        'DynCmd Package P': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 323,
            'retbufs': 0,
            'tty': 0,
        },
        'Dynamic ARP Insp': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 51,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED CLI': {
            'allocated': 14056,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65376,
            'pid': 410,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED CRASH': {
            'allocated': 20352,
            'freed': 5680,
            'getbufs': 0,
            'holding': 71672,
            'pid': 425,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Config': {
            'allocated': 14056,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65376,
            'pid': 422,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Counter': {
            'allocated': 14056,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65376,
            'pid': 411,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED DS': {
            'allocated': 20352,
            'freed': 5680,
            'getbufs': 0,
            'holding': 71672,
            'pid': 424,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Env': {
            'allocated': 14056,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65376,
            'pid': 423,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Generic': {
            'allocated': 385264,
            'freed': 5680,
            'getbufs': 72316,
            'holding': 436584,
            'pid': 387,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED IOSWD': {
            'allocated': 14184,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65504,
            'pid': 413,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Identity': {
            'allocated': 14208,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65528,
            'pid': 143,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Interface': {
            'allocated': 15456,
            'freed': 5680,
            'getbufs': 0,
            'holding': 66776,
            'pid': 412,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED MAT': {
            'allocated': 14104,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65424,
            'pid': 150,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED ND': {
            'allocated': 53608,
            'freed': 353744,
            'getbufs': 0,
            'holding': 104360,
            'pid': 151,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED None': {
            'allocated': 15008,
            'freed': 6248,
            'getbufs': 0,
            'holding': 66328,
            'pid': 414,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED OIR': {
            'allocated': 14056,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65376,
            'pid': 415,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED RF': {
            'allocated': 15280,
            'freed': 5912,
            'getbufs': 0,
            'holding': 65872,
            'pid': 416,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED RPC': {
            'allocated': 14056,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65376,
            'pid': 400,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Routing': {
            'allocated': 14248,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65568,
            'pid': 388,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED SNMP Noti': {
            'allocated': 14248,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65568,
            'pid': 419,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED SNMP Obje': {
            'allocated': 14056,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65376,
            'pid': 418,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED SNMP': {
            'allocated': 14056,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65376,
            'pid': 417,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Syslog': {
            'allocated': 3938440,
            'freed': 5680,
            'getbufs': 849828,
            'holding': 3989760,
            'pid': 386,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Test': {
            'allocated': 14056,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65376,
            'pid': 421,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM ED Timer': {
            'allocated': 14360,
            'freed': 5680,
            'getbufs': 0,
            'holding': 65680,
            'pid': 420,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM GED BINOS PR': {
            'allocated': 20160,
            'freed': 5680,
            'getbufs': 0,
            'holding': 71480,
            'pid': 375,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM Helper Threa': {
            'allocated': 9000,
            'freed': 528,
            'getbufs': 0,
            'holding': 53472,
            'pid': 495,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM Policy Direc': {
            'allocated': 19240,
            'freed': 1784,
            'getbufs': 0,
            'holding': 74456,
            'pid': 408,
            'retbufs': 0,
            'tty': 0,
        },
        'EEM Server': {
            'allocated': 1485272,
            'freed': 28496,
            'getbufs': 0,
            'holding': 1501776,
            'pid': 399,
            'retbufs': 0,
            'tty': 0,
        },
        'EFP Errd': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 246,
            'retbufs': 0,
            'tty': 0,
        },
        'EM Background Pr': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 330,
            'retbufs': 0,
            'tty': 0,
        },
        'EM ED GOLD': {
            'allocated': 40832,
            'freed': 5680,
            'getbufs': 0,
            'holding': 92152,
            'pid': 426,
            'retbufs': 0,
            'tty': 0,
        },
        'EM_SHIM_NOTIFY_T': {
            'allocated': 448,
            'freed': 17328,
            'getbufs': 0,
            'holding': 45000,
            'pid': 94,
            'retbufs': 0,
            'tty': 0,
        },
        'EM_SHIM_TASK': {
            'allocated': 17328,
            'freed': 84840,
            'getbufs': 0,
            'holding': 45000,
            'pid': 93,
            'retbufs': 0,
            'tty': 0,
        },
        'ENABLE AAA': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 329,
            'retbufs': 0,
            'tty': 0,
        },
        'EPC WS PD suppor': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 393,
            'retbufs': 0,
            'tty': 0,
        },
        'EPC WS PI suppor': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 392,
            'retbufs': 0,
            'tty': 0,
        },
        'Entity MIB API': {
            'allocated': 30656,
            'freed': 0,
            'getbufs': 0,
            'holding': 75656,
            'pid': 43,
            'retbufs': 0,
            'tty': 0,
        },
        'Ethchnl': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 161,
            'retbufs': 0,
            'tty': 0,
        },
        'Ether EFP Proces': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 247,
            'retbufs': 0,
            'tty': 0,
        },
        'Ethernet CFM': {
            'allocated': 2600,
            'freed': 448,
            'getbufs': 0,
            'holding': 119152,
            'pid': 160,
            'retbufs': 0,
            'tty': 0,
        },
        'Ethernet OAM Pro': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 57000,
            'pid': 159,
            'retbufs': 0,
            'tty': 0,
        },
        'Ethernet PM Moni': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69128,
            'pid': 255,
            'retbufs': 0,
            'tty': 0,
        },
        'Ethernet PM Proc': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 253,
            'retbufs': 0,
            'tty': 0,
        },
        'Ethernet PM Soft': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 57000,
            'pid': 254,
            'retbufs': 0,
            'tty': 0,
        },
        'Exec': {
            'allocated': 28890432,
            'freed': 28683432,
            'getbufs': 0,
            'holding': 278216,
            'pid': 153,
            'retbufs': 0,
            'tty': 0,
        },
        'FEC_Link_event_h': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 132,
            'retbufs': 0,
            'tty': 0,
        },
        'FEP background p': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 136,
            'retbufs': 0,
            'tty': 0,
        },
        'FHRP Main thread': {
            'allocated': 3344,
            'freed': 0,
            'getbufs': 0,
            'holding': 48344,
            'pid': 186,
            'retbufs': 0,
            'tty': 0,
        },
        'FMANRP REP Helpe': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 173,
            'retbufs': 0,
            'tty': 0,
        },
        'FNF background p': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 396,
            'retbufs': 0,
            'tty': 0,
        },
        'FNF_WIRELESS_PRO': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 288,
            'retbufs': 0,
            'tty': 0,
        },
        'FPD Action Proce': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 149,
            'retbufs': 0,
            'tty': 0,
        },
        'FPD Management P': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45112,
            'pid': 148,
            'retbufs': 0,
            'tty': 0,
        },
        'FRR Background P': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 229,
            'retbufs': 0,
            'tty': 0,
        },
        'File Copy Handle': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 339,
            'retbufs': 0,
            'tty': 0,
        },
        'Flow Exporter Pa': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 284,
            'retbufs': 0,
            'tty': 0,
        },
        'Flow Exporter Ti': {
            'allocated': 448,
            'freed': 2056,
            'getbufs': 0,
            'holding': 69000,
            'pid': 283,
            'retbufs': 0,
            'tty': 0,
        },
        'GLBP HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 297,
            'retbufs': 0,
            'tty': 0,
        },
        'GraphIt': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 49,
            'retbufs': 0,
            'tty': 0,
        },
        'HQF TARGET DYNAM': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 202,
            'retbufs': 0,
            'tty': 0,
        },
        'HSRP HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 298,
            'retbufs': 0,
            'tty': 0,
        },
        'HTTP CORE': {
            'allocated': 34968,
            'freed': 34696,
            'getbufs': 0,
            'holding': 119456,
            'pid': 275,
            'retbufs': 0,
            'tty': 0,
        },
        'ICMP event handl': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 209,
            'retbufs': 0,
            'tty': 0,
        },
        'IDB Work': {
            'allocated': 1472,
            'freed': 1472,
            'getbufs': 0,
            'holding': 69000,
            'pid': 68,
            'retbufs': 0,
            'tty': 0,
        },
        'IDMGR CORE': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 331,
            'retbufs': 0,
            'tty': 0,
        },
        'IF-MGR control p': {
            'allocated': 6600,
            'freed': 0,
            'getbufs': 0,
            'holding': 51600,
            'pid': 86,
            'retbufs': 0,
            'tty': 0,
        },
        'IF-MGR event pro': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 87,
            'retbufs': 0,
            'tty': 0,
        },
        'IFS Agent Manage': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 44,
            'retbufs': 0,
            'tty': 0,
        },
        'IGMPQR': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 279,
            'retbufs': 0,
            'tty': 0,
        },
        'IGMPSN L2MCM': {
            'allocated': 11544,
            'freed': 53352,
            'getbufs': 0,
            'holding': 47608,
            'pid': 259,
            'retbufs': 0,
            'tty': 0,
        },
        'IGMPSN MRD': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 260,
            'retbufs': 0,
            'tty': 0,
        },
        'IGMPSN': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 261,
            'retbufs': 0,
            'tty': 0,
        },
        'IGMPSN-HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 280,
            'retbufs': 0,
            'tty': 0,
        },
        'IKEv2 AAA handle': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 365,
            'retbufs': 0,
            'tty': 0,
        },
        'IKEv2 Cluster Lo': {
            'allocated': 1824,
            'freed': 0,
            'getbufs': 0,
            'holding': 46824,
            'pid': 378,
            'retbufs': 0,
            'tty': 0,
        },
        'IKEv2 FlexVPN Pr': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 377,
            'retbufs': 0,
            'tty': 0,
        },
        'IOSD chasfs task': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 117000,
            'pid': 75,
            'retbufs': 0,
            'tty': 0,
        },
        'IOSD ipc task': {
            'allocated': 35078768,
            'freed': 3199408,
            'getbufs': 0,
            'holding': 31261592,
            'pid': 74,
            'retbufs': 36456,
            'tty': 0,
        },
        'IOSXE heartbeat': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 14,
            'retbufs': 0,
            'tty': 0,
        },
        'IOSXE signals IO': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 48,
            'retbufs': 0,
            'tty': 0,
        },
        'IOSXE-RP FastPat': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 131,
            'retbufs': 0,
            'tty': 0,
        },
        'IOSXE-RP Punt IP': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 118,
            'retbufs': 0,
            'tty': 0,
        },
        'IOSXE-RP Punt Se': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 117,
            'retbufs': 0,
            'tty': 0,
        },
        'IOSXE-RP SPA TSM': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 121,
            'retbufs': 0,
            'tty': 0,
        },
        'IP ARP Adjacency': {
            'allocated': 2296,
            'freed': 0,
            'getbufs': 0,
            'holding': 71296,
            'pid': 206,
            'retbufs': 0,
            'tty': 0,
        },
        'IP ARP Retry Age': {
            'allocated': 66064,
            'freed': 0,
            'getbufs': 0,
            'holding': 111064,
            'pid': 207,
            'retbufs': 0,
            'tty': 0,
        },
        'IP Background': {
            'allocated': 76792,
            'freed': 44216,
            'getbufs': 0,
            'holding': 90856,
            'pid': 242,
            'retbufs': 0,
            'tty': 0,
        },
        'IP Connected Rou': {
            'allocated': 90104,
            'freed': 0,
            'getbufs': 0,
            'holding': 147104,
            'pid': 243,
            'retbufs': 0,
            'tty': 0,
        },
        'IP IRDP': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 232,
            'retbufs': 0,
            'tty': 0,
        },
        'IP Input': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 208,
            'retbufs': 0,
            'tty': 0,
        },
        'IP RIB Update': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 69408,
            'pid': 241,
            'retbufs': 0,
            'tty': 0,
        },
        'IP Traceroute': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 304,
            'retbufs': 0,
            'tty': 0,
        },
        'IPAM Events': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 205,
            'retbufs': 0,
            'tty': 0,
        },
        'IPAM Manager': {
            'allocated': 98736,
            'freed': 0,
            'getbufs': 0,
            'holding': 167872,
            'pid': 204,
            'retbufs': 0,
            'tty': 0,
        },
        'IPAM/ODAP Events': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 203,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Apps Task': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 17,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Check Queue': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 28,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Deferred Por': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 25,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Dynamic Cach': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 21,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Event Notifi': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 18,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC ISSU Dispatc': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 6,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC ISSU Version': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 488,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Keep Alive M': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 31,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC LC Message H': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 237,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Loadometer': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 32,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Mcast Pendin': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 19,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Periodic Tim': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 24,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Process leve': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 26,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Seat Manager': {
            'allocated': 2192,
            'freed': 0,
            'getbufs': 0,
            'holding': 47192,
            'pid': 27,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Seat RX Cont': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 29,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Seat TX Cont': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 30,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Service NonC': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 22,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Session Deta': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 33,
            'retbufs': 0,
            'tty': 0,
        },
        'IPC Zone Manager': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 23,
            'retbufs': 0,
            'tty': 0,
        },
        'IPSEC key engine': {
            'allocated': 6936,
            'freed': 5616,
            'getbufs': 0,
            'holding': 69872,
            'pid': 360,
            'retbufs': 0,
            'tty': 0,
        },
        'IPSEC manual key': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 359,
            'retbufs': 0,
            'tty': 0,
        },
        'IPSECv6 PS Proc': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 327,
            'retbufs': 0,
            'tty': 0,
        },
        'IPSec background': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 363,
            'retbufs': 0,
            'tty': 0,
        },
        'IPv6 Access Cont': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 124,
            'retbufs': 0,
            'tty': 0,
        },
        'IPv6 RIB Cleanup': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 317,
            'retbufs': 0,
            'tty': 0,
        },
        'IPv6 RIB Event H': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 318,
            'retbufs': 0,
            'tty': 0,
        },
        'IPv6 Static Hand': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 319,
            'retbufs': 0,
            'tty': 0,
        },
        'IPv6 ping proces': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 212,
            'retbufs': 0,
            'tty': 0,
        },
        'ISSU Utility Pro': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 391,
            'retbufs': 0,
            'tty': 0,
        },
        'Image License br': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 62,
            'retbufs': 0,
            'tty': 0,
        },
        'Inline Power': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 183,
            'retbufs': 0,
            'tty': 0,
        },
        'Key chain liveke': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 333,
            'retbufs': 0,
            'tty': 0,
        },
        'L2MCAST Wireless': {
            'allocated': 0,
            'freed': 944,
            'getbufs': 0,
            'holding': 45000,
            'pid': 287,
            'retbufs': 0,
            'tty': 0,
        },
        'L2TRACE SERVER': {
            'allocated': 63744,
            'freed': 448,
            'getbufs': 0,
            'holding': 51168,
            'pid': 289,
            'retbufs': 0,
            'tty': 0,
        },
        'LDAP process': {
            'allocated': 2288,
            'freed': 448,
            'getbufs': 0,
            'holding': 70840,
            'pid': 332,
            'retbufs': 0,
            'tty': 0,
        },
        'LICENSE AGENT': {
            'allocated': 47792,
            'freed': 1632,
            'getbufs': 0,
            'holding': 164904,
            'pid': 502,
            'retbufs': 0,
            'tty': 0,
        },
        'LIM Process': {
            'allocated': 1008,
            'freed': 1008,
            'getbufs': 0,
            'holding': 45000,
            'pid': 258,
            'retbufs': 0,
            'tty': 0,
        },
        'LINE AAA': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 334,
            'retbufs': 0,
            'tty': 0,
        },
        'LOCAL AAA': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 335,
            'retbufs': 0,
            'tty': 0,
        },
        'License Client N': {
            'allocated': 336,
            'freed': 1328,
            'getbufs': 0,
            'holding': 45000,
            'pid': 61,
            'retbufs': 0,
            'tty': 0,
        },
        'License HA Consi': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 64,
            'retbufs': 0,
            'tty': 0,
        },
        'License IPC serv': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 55,
            'retbufs': 0,
            'tty': 0,
        },
        'License IPC stat': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 54,
            'retbufs': 0,
            'tty': 0,
        },
        'Licensing Auto U': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 63,
            'retbufs': 0,
            'tty': 0,
        },
        'Licensing MIB pr': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 374,
            'retbufs': 0,
            'tty': 0,
        },
        'Load Meter': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 33000,
            'pid': 2,
            'retbufs': 0,
            'tty': 0,
        },
        'Logger': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 69,
            'retbufs': 0,
            'tty': 0,
        },
        'MATM CF Flow Con': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 97,
            'retbufs': 0,
            'tty': 0,
        },
        'MATM RP Shim Pro': {
            'allocated': 640,
            'freed': 640,
            'getbufs': 0,
            'holding': 45000,
            'pid': 154,
            'retbufs': 0,
            'tty': 0,
        },
        'MATM SPI client': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 79,
            'retbufs': 0,
            'tty': 0,
        },
        'MFIB Master back': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 69408,
            'pid': 299,
            'retbufs': 0,
            'tty': 0,
        },
        'MGMTE stats Proc': {
            'allocated': 45600,
            'freed': 45600,
            'getbufs': 0,
            'holding': 45000,
            'pid': 152,
            'retbufs': 0,
            'tty': 0,
        },
        'MKA': {
            'allocated': 37816,
            'freed': 1096,
            'getbufs': 0,
            'holding': 81720,
            'pid': 191,
            'retbufs': 0,
            'tty': 0,
        },
        'MLDSN L2MCM': {
            'allocated': 11496,
            'freed': 50064,
            'getbufs': 0,
            'holding': 50040,
            'pid': 276,
            'retbufs': 0,
            'tty': 0,
        },
        'MLDSN-HA': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 281,
            'retbufs': 0,
            'tty': 0,
        },
        'MLD_SNOOP': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 278,
            'retbufs': 0,
            'tty': 0,
        },
        'MMN bkgrd proces': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 141,
            'retbufs': 0,
            'tty': 0,
        },
        'MRD': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 277,
            'retbufs': 0,
            'tty': 0,
        },
        'MRIB Process': {
            'allocated': 167728,
            'freed': 448,
            'getbufs': 0,
            'holding': 236280,
            'pid': 494,
            'retbufs': 0,
            'tty': 0,
        },
        'MRIB RP Proxy': {
            'allocated': 784,
            'freed': 0,
            'getbufs': 0,
            'holding': 69784,
            'pid': 302,
            'retbufs': 0,
            'tty': 0,
        },
        'MVPN Mgr Process': {
            'allocated': 2152,
            'freed': 448,
            'getbufs': 0,
            'holding': 58704,
            'pid': 313,
            'retbufs': 0,
            'tty': 0,
        },
        'MVRP Process': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 57000,
            'pid': 162,
            'retbufs': 0,
            'tty': 0,
        },
        'MVRP SWITCH Proc': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 57000,
            'pid': 340,
            'retbufs': 0,
            'tty': 0,
        },
        'Multicast Offloa': {
            'allocated': 896,
            'freed': 448,
            'getbufs': 0,
            'holding': 57448,
            'pid': 314,
            'retbufs': 0,
            'tty': 0,
        },
        'NCD Process': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 369,
            'retbufs': 0,
            'tty': 0,
        },
        'NG Backup Interf': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 133,
            'retbufs': 0,
            'tty': 0,
        },
        'NGCP SCHEDULER P': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 248,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC Configurati': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 96,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC DOT1X Proce': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 142,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC ILP CF Proc': {
            'allocated': 10096,
            'freed': 0,
            'getbufs': 0,
            'holding': 55096,
            'pid': 104,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC L2M': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 139,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC Learning Pr': {
            'allocated': 26392,
            'freed': 26392,
            'getbufs': 0,
            'holding': 45000,
            'pid': 98,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC OIR CC Proc': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 77,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC diag proces': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 138,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC led process': {
            'allocated': 0,
            'freed': 4312,
            'getbufs': 0,
            'holding': 45000,
            'pid': 176,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC stack power': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 273,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC_MACSEC_IOSD': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 146,
            'retbufs': 0,
            'tty': 0,
        },
        'NGWC_OIRSHIM_TAS': {
            'allocated': 45632,
            'freed': 2880,
            'getbufs': 0,
            'holding': 45000,
            'pid': 76,
            'retbufs': 0,
            'tty': 0,
        },
        'NIST rng proc': {
            'allocated': 36576,
            'freed': 34960,
            'getbufs': 0,
            'holding': 46616,
            'pid': 338,
            'retbufs': 0,
            'tty': 0,
        },
        'Net Background': {
            'allocated': 350968,
            'freed': 11864,
            'getbufs': 0,
            'holding': 96416,
            'pid': 67,
            'retbufs': 0,
            'tty': 0,
        },
        'Net Input': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 56,
            'retbufs': 0,
            'tty': 0,
        },
        'Network-rf Notif': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 115,
            'retbufs': 0,
            'tty': 0,
        },
        'Ng3k envvar sync': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 78,
            'retbufs': 0,
            'tty': 0,
        },
        'Online Diag EEM': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 45408,
            'pid': 379,
            'retbufs': 0,
            'tty': 0,
        },
        'Opaque Database': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 324,
            'retbufs': 0,
            'tty': 0,
        },
        'PI MATM Aging Pr': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 177,
            'retbufs': 0,
            'tty': 0,
        },
        'PIM HA': {
            'allocated': 896,
            'freed': 448,
            'getbufs': 0,
            'holding': 45448,
            'pid': 366,
            'retbufs': 0,
            'tty': 0,
        },
        'PIM register asy': {
            'allocated': 576,
            'freed': 576,
            'getbufs': 0,
            'holding': 45136,
            'pid': 211,
            'retbufs': 0,
            'tty': 0,
        },
        'PKI OCSP': {
            'allocated': 1936,
            'freed': 0,
            'getbufs': 0,
            'holding': 70936,
            'pid': 349,
            'retbufs': 0,
            'tty': 0,
        },
        'PKI Revocation': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 350,
            'retbufs': 0,
            'tty': 0,
        },
        'PKI Trustpool': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69112,
            'pid': 197,
            'retbufs': 0,
            'tty': 0,
        },
        'PKI/SSL IPC proc': {
            'allocated': 9408,
            'freed': 2416,
            'getbufs': 0,
            'holding': 125704,
            'pid': 175,
            'retbufs': 0,
            'tty': 0,
        },
        'PLFM-MGR IPC pro': {
            'allocated': 4456,
            'freed': 397872,
            'getbufs': 0,
            'holding': 45000,
            'pid': 135,
            'retbufs': 0,
            'tty': 0,
        },
        'PM Callback': {
            'allocated': 37792,
            'freed': 115000,
            'getbufs': 0,
            'holding': 45000,
            'pid': 371,
            'retbufs': 0,
            'tty': 0,
        },
        'PM EPD API': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 215,
            'retbufs': 0,
            'tty': 0,
        },
        'PPP Bind': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 217,
            'retbufs': 0,
            'tty': 0,
        },
        'PPP IP Route': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 218,
            'retbufs': 0,
            'tty': 0,
        },
        'PPP SIP': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 216,
            'retbufs': 0,
            'tty': 0,
        },
        'PTP protocol eng': {
            'allocated': 5528,
            'freed': 448,
            'getbufs': 0,
            'holding': 50080,
            'pid': 182,
            'retbufs': 0,
            'tty': 0,
        },
        'Per-Second Jobs': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 127,
            'retbufs': 0,
            'tty': 0,
        },
        'Per-minute Jobs': {
            'allocated': 2816,
            'freed': 0,
            'getbufs': 0,
            'holding': 47816,
            'pid': 126,
            'retbufs': 0,
            'tty': 0,
        },
        'Platform appsess': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 20,
            'retbufs': 0,
            'tty': 0,
        },
        'Policy Manager': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 41,
            'retbufs': 0,
            'tty': 0,
        },
        'Policy bind Proc': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 370,
            'retbufs': 0,
            'tty': 0,
        },
        'Pool Manager': {
            'allocated': 1095576,
            'freed': 823776,
            'getbufs': 993784,
            'holding': 343176,
            'pid': 10,
            'retbufs': 788868,
            'tty': 0,
        },
        'Port-Security': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 45408,
            'pid': 179,
            'retbufs': 0,
            'tty': 0,
        },
        'PrstVbl': {
            'allocated': 4032,
            'freed': 4032,
            'getbufs': 0,
            'holding': 45000,
            'pid': 45,
            'retbufs': 0,
            'tty': 0,
        },
        'Punt FP Stats Du': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 33000,
            'pid': 84,
            'retbufs': 0,
            'tty': 0,
        },
        'PuntInject Keepa': {
            'allocated': 560,
            'freed': 560,
            'getbufs': 0,
            'holding': 33000,
            'pid': 85,
            'retbufs': 0,
            'tty': 0,
        },
        'QoS stats proces': {
            'allocated': 11808,
            'freed': 11808,
            'getbufs': 0,
            'holding': 57000,
            'pid': 321,
            'retbufs': 0,
            'tty': 0,
        },
        'RBM CORE': {
            'allocated': 29776,
            'freed': 896,
            'getbufs': 0,
            'holding': 97880,
            'pid': 398,
            'retbufs': 0,
            'tty': 0,
        },
        'REDUNDANCY FSM': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 83,
            'retbufs': 0,
            'tty': 0,
        },
        'REDUNDANCY peer': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 109,
            'retbufs': 0,
            'tty': 0,
        },
        'REP BPA/EPA Proc': {
            'allocated': 7504,
            'freed': 448,
            'getbufs': 0,
            'holding': 52056,
            'pid': 269,
            'retbufs': 0,
            'tty': 0,
        },
        'REP LSL Hello Pr': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 174,
            'retbufs': 0,
            'tty': 0,
        },
        'REP LSL Proc': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 268,
            'retbufs': 0,
            'tty': 0,
        },
        'REP Switch Helpe': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 343,
            'retbufs': 0,
            'tty': 0,
        },
        'REP Topology cha': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 172,
            'retbufs': 0,
            'tty': 0,
        },
        'RF Master Main T': {
            'allocated': 33416,
            'freed': 46808,
            'getbufs': 0,
            'holding': 61808,
            'pid': 122,
            'retbufs': 0,
            'tty': 0,
        },
        'RF Master Status': {
            'allocated': 3384,
            'freed': 0,
            'getbufs': 0,
            'holding': 48384,
            'pid': 123,
            'retbufs': 0,
            'tty': 0,
        },
        'RF Slave Main Th': {
            'allocated': 560832,
            'freed': 23144,
            'getbufs': 0,
            'holding': 477832,
            'pid': 4,
            'retbufs': 0,
            'tty': 0,
        },
        'RIB LM VALIDATE': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 220,
            'retbufs': 0,
            'tty': 0,
        },
        'RMI RM Notify Wa': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 33000,
            'pid': 47,
            'retbufs': 0,
            'tty': 0,
        },
        'RO Notify Timers': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 7,
            'retbufs': 0,
            'tty': 0,
        },
        'RP HA Periodic': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 91,
            'retbufs': 0,
            'tty': 0,
        },
        'RSA background p': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 345,
            'retbufs': 0,
            'tty': 0,
        },
        'RSVP SYNC': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 267,
            'retbufs': 0,
            'tty': 0,
        },
        'RTTYS Process': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 157,
            'retbufs': 0,
            'tty': 0,
        },
        'Remote Console P': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 144,
            'retbufs': 0,
            'tty': 0,
        },
        'Retransmission o': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 5,
            'retbufs': 0,
            'tty': 0,
        },
        'Routing Topology': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 240,
            'retbufs': 0,
            'tty': 0,
        },
        'SCTP Main Proces': {
            'allocated': 38912,
            'freed': 448,
            'getbufs': 0,
            'holding': 83464,
            'pid': 322,
            'retbufs': 0,
            'tty': 0,
        },
        'SENSOR-MGR event': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 34,
            'retbufs': 0,
            'tty': 0,
        },
        'SEP_webui_wsma_h': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 118248,
            'pid': 336,
            'retbufs': 0,
            'tty': 0,
        },
        'SFF8472': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 130,
            'retbufs': 0,
            'tty': 0,
        },
        'SISF HA Process': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 57000,
            'pid': 114,
            'retbufs': 0,
            'tty': 0,
        },
        'SMART': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 50,
            'retbufs': 0,
            'tty': 0,
        },
        'SNMP DBAL Cache': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 170,
            'retbufs': 0,
            'tty': 0,
        },
        'SNMP DBAL WRAPPE': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 117000,
            'pid': 169,
            'retbufs': 0,
            'tty': 0,
        },
        'SNMP LA Cache In': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 496,
            'retbufs': 0,
            'tty': 0,
        },
        'SNMP LA Cache pr': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 499,
            'retbufs': 0,
            'tty': 0,
        },
        'SNMP MA SA': {
            'allocated': 8457552,
            'freed': 133928,
            'getbufs': 0,
            'holding': 5682240,
            'pid': 168,
            'retbufs': 0,
            'tty': 0,
        },
        'SNMP Timers': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 303,
            'retbufs': 0,
            'tty': 0,
        },
        'SPA ENTITY Proce': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 380,
            'retbufs': 0,
            'tty': 0,
        },
        'SPAN switch': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 394,
            'retbufs': 0,
            'tty': 0,
        },
        'SR CapMan Proces': {
            'allocated': 11384,
            'freed': 448,
            'getbufs': 0,
            'holding': 55936,
            'pid': 311,
            'retbufs': 0,
            'tty': 0,
        },
        'SSH Event handle': {
            'allocated': 8728,
            'freed': 0,
            'getbufs': 0,
            'holding': 53472,
            'pid': 219,
            'retbufs': 0,
            'tty': 0,
        },
        'SSM connection m': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 221,
            'retbufs': 0,
            'tty': 0,
        },
        'SSS Feature Mana': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 224,
            'retbufs': 0,
            'tty': 0,
        },
        'SSS Feature Time': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 225,
            'retbufs': 0,
            'tty': 0,
        },
        'SSS Manager': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 222,
            'retbufs': 0,
            'tty': 0,
        },
        'SSS Policy Manag': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 223,
            'retbufs': 0,
            'tty': 0,
        },
        'STACK MGR Proces': {
            'allocated': 0,
            'freed': 1296,
            'getbufs': 0,
            'holding': 45000,
            'pid': 80,
            'retbufs': 0,
            'tty': 0,
        },
        'STP HA IPC flow': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 306,
            'retbufs': 0,
            'tty': 0,
        },
        'SXP CORE': {
            'allocated': 2376,
            'freed': 2968,
            'getbufs': 0,
            'holding': 70928,
            'pid': 72,
            'retbufs': 0,
            'tty': 0,
        },
        'Serial Backgroun': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 46,
            'retbufs': 0,
            'tty': 0,
        },
        'Service Routing': {
            'allocated': 152,
            'freed': 0,
            'getbufs': 0,
            'holding': 45152,
            'pid': 310,
            'retbufs': 0,
            'tty': 0,
        },
        'Socket Timers': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 274,
            'retbufs': 0,
            'tty': 0,
        },
        'SpanTree Flush': {
            'allocated': 0,
            'freed': 142528,
            'getbufs': 0,
            'holding': 45000,
            'pid': 244,
            'retbufs': 0,
            'tty': 0,
        },
        'SpanTree Helper': {
            'allocated': 69752,
            'freed': 29728,
            'getbufs': 0,
            'holding': 45112,
            'pid': 3,
            'retbufs': 0,
            'tty': 0,
        },
        'Spanning Tree St': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 192,
            'retbufs': 0,
            'tty': 0,
        },
        'Spanning Tree': {
            'allocated': 162736,
            'freed': 448,
            'getbufs': 0,
            'holding': 46008,
            'pid': 226,
            'retbufs': 0,
            'tty': 0,
        },
        'Src Fltr backgro': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 45408,
            'pid': 147,
            'retbufs': 0,
            'tty': 0,
        },
        'Switch Backup In': {
            'allocated': 73984,
            'freed': 0,
            'getbufs': 0,
            'holding': 118984,
            'pid': 164,
            'retbufs': 0,
            'tty': 0,
        },
        'Syslog Traps': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 389,
            'retbufs': 0,
            'tty': 0,
        },
        'Syslog': {
            'allocated': 47200,
            'freed': 47200,
            'getbufs': 0,
            'holding': 69000,
            'pid': 427,
            'retbufs': 0,
            'tty': 0,
        },
        'TCP HA PROC': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 264,
            'retbufs': 0,
            'tty': 0,
        },
        'TCP Protocols': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 263,
            'retbufs': 0,
            'tty': 0,
        },
        'TCP Timer': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 262,
            'retbufs': 0,
            'tty': 0,
        },
        'TP CUTOVER EVENT': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 156,
            'retbufs': 0,
            'tty': 0,
        },
        'TPLUS': {
            'allocated': 2432,
            'freed': 448,
            'getbufs': 0,
            'holding': 70984,
            'pid': 337,
            'retbufs': 0,
            'tty': 0,
        },
        'TPS IPC Process': {
            'allocated': 792,
            'freed': 5896,
            'getbufs': 0,
            'holding': 117792,
            'pid': 352,
            'retbufs': 0,
            'tty': 0,
        },
        'TRACK Client thr': {
            'allocated': 3344,
            'freed': 0,
            'getbufs': 0,
            'holding': 48344,
            'pid': 188,
            'retbufs': 0,
            'tty': 0,
        },
        'TRACK Main threa': {
            'allocated': 13440,
            'freed': 0,
            'getbufs': 0,
            'holding': 58440,
            'pid': 187,
            'retbufs': 0,
            'tty': 0,
        },
        'TTY Background': {
            'allocated': 70144,
            'freed': 448,
            'getbufs': 0,
            'holding': 45568,
            'pid': 70,
            'retbufs': 0,
            'tty': 0,
        },
        'Test AAA Client': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 385,
            'retbufs': 0,
            'tty': 0,
        },
        'Thermal backgrou': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 140,
            'retbufs': 0,
            'tty': 0,
        },
        'Timer Library': {
            'allocated': 99192,
            'freed': 448,
            'getbufs': 0,
            'holding': 143744,
            'pid': 325,
            'retbufs': 0,
            'tty': 0,
        },
        'Timers': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 12,
            'retbufs': 0,
            'tty': 0,
        },
        'Token Daemon': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45128,
            'pid': 65,
            'retbufs': 0,
            'tty': 0,
        },
        'Transport Port A': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 129,
            'retbufs': 0,
            'tty': 0,
        },
        'Tunnel FIB': {
            'allocated': 456,
            'freed': 0,
            'getbufs': 0,
            'holding': 57456,
            'pid': 290,
            'retbufs': 0,
            'tty': 0,
        },
        'Tunnel': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 291,
            'retbufs': 0,
            'tty': 0,
        },
        'UDLD': {
            'allocated': 17704,
            'freed': 448,
            'getbufs': 0,
            'holding': 62256,
            'pid': 227,
            'retbufs': 0,
            'tty': 0,
        },
        'VIDB BACKGD MGR': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 8,
            'retbufs': 0,
            'tty': 0,
        },
        'VLAN Manager': {
            'allocated': 515168,
            'freed': 463664,
            'getbufs': 0,
            'holding': 119032,
            'pid': 429,
            'retbufs': 0,
            'tty': 0,
        },
        'VMATM Callback': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 178,
            'retbufs': 0,
            'tty': 0,
        },
        'VRRP Main thread': {
            'allocated': 3344,
            'freed': 0,
            'getbufs': 0,
            'holding': 48344,
            'pid': 189,
            'retbufs': 0,
            'tty': 0,
        },
        'VRRS Main thread': {
            'allocated': 36976,
            'freed': 0,
            'getbufs': 0,
            'holding': 81976,
            'pid': 190,
            'retbufs': 0,
            'tty': 0,
        },
        'VRRS': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 228,
            'retbufs': 0,
            'tty': 0,
        },
        'VTP Trap Process': {
            'allocated': 7504,
            'freed': 448,
            'getbufs': 0,
            'holding': 52056,
            'pid': 367,
            'retbufs': 0,
            'tty': 0,
        },
        'WATCH_AFS': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 33000,
            'pid': 13,
            'retbufs': 0,
            'tty': 0,
        },
        'WCDB ARP Process': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 52,
            'retbufs': 0,
            'tty': 0,
        },
        'WCM CONFIG SHARE': {
            'allocated': 560,
            'freed': 1152,
            'getbufs': 0,
            'holding': 69560,
            'pid': 266,
            'retbufs': 0,
            'tty': 0,
        },
        'WCM/AAA IPC proc': {
            'allocated': 296,
            'freed': 592,
            'getbufs': 0,
            'holding': 117000,
            'pid': 353,
            'retbufs': 0,
            'tty': 0,
        },
        'WDB Process': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 184,
            'retbufs': 0,
            'tty': 0,
        },
        'WLM HA IPC flow': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 167,
            'retbufs': 0,
            'tty': 0,
        },
        'WLM HA': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 166,
            'retbufs': 0,
            'tty': 0,
        },
        'WPM HA Reconcile': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 99,
            'retbufs': 0,
            'tty': 0,
        },
        'WSMAN Process': {
            'allocated': 15952,
            'freed': 14136,
            'getbufs': 0,
            'holding': 118944,
            'pid': 395,
            'retbufs': 0,
            'tty': 0,
        },
        'WSMA_NOTIFY': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 117304,
            'pid': 213,
            'retbufs': 0,
            'tty': 0,
        },
        'Wireless Manager': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 165,
            'retbufs': 0,
            'tty': 0,
        },
        'XDR FOF process': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 45408,
            'pid': 296,
            'retbufs': 0,
            'tty': 0,
        },
        'XDR RP Ping Back': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 235,
            'retbufs': 0,
            'tty': 0,
        },
        'XDR RP Test Back': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 238,
            'retbufs': 0,
            'tty': 0,
        },
        'XDR RRP RF waite': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 33000,
            'pid': 116,
            'retbufs': 0,
            'tty': 0,
        },
        'XDR background p': {
            'allocated': 408,
            'freed': 0,
            'getbufs': 0,
            'holding': 45528,
            'pid': 233,
            'retbufs': 0,
            'tty': 0,
        },
        'XDR mcast': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 234,
            'retbufs': 0,
            'tty': 0,
        },
        'XDR receive': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 236,
            'retbufs': 0,
            'tty': 0,
        },
        'XML Proxy Client': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 60,
            'retbufs': 0,
            'tty': 0,
        },
        'XPS background p': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 137,
            'retbufs': 0,
            'tty': 0,
        },
        'client_entity_se': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 57,
            'retbufs': 0,
            'tty': 0,
        },
        'cpf_msg_holdq_pr': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 88,
            'retbufs': 0,
            'tty': 0,
        },
        'cpf_msg_rcvq_pro': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 89,
            'retbufs': 0,
            'tty': 0,
        },
        'cpf_process_tpQ': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 90,
            'retbufs': 0,
            'tty': 0,
        },
        'crypto engine pr': {
            'allocated': 268672,
            'freed': 267472,
            'getbufs': 0,
            'holding': 46056,
            'pid': 344,
            'retbufs': 0,
            'tty': 0,
        },
        'crypto sw pk pro': {
            'allocated': 7375736,
            'freed': 7341992,
            'getbufs': 0,
            'holding': 56936,
            'pid': 59,
            'retbufs': 0,
            'tty': 0,
        },
        'dcm_cli_engine': {
            'allocated': 14920,
            'freed': 200,
            'getbufs': 0,
            'holding': 59592,
            'pid': 381,
            'retbufs': 0,
            'tty': 0,
        },
        'dcm_cli_provider': {
            'allocated': 9712,
            'freed': 464,
            'getbufs': 0,
            'holding': 54384,
            'pid': 382,
            'retbufs': 0,
            'tty': 0,
        },
        'dcm_expression_p': {
            'allocated': 6752,
            'freed': 464,
            'getbufs': 0,
            'holding': 51128,
            'pid': 404,
            'retbufs': 0,
            'tty': 0,
        },
        'dhcp snooping sw': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 45000,
            'pid': 372,
            'retbufs': 0,
            'tty': 0,
        },
        'encrypt proc': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 69000,
            'pid': 354,
            'retbufs': 0,
            'tty': 0,
        },
        'fib_fib_bfd_sb e': {
            'allocated': 536,
            'freed': 0,
            'getbufs': 0,
            'holding': 69536,
            'pid': 231,
            'retbufs': 0,
            'tty': 0,
        },
        'ifIndex Receive': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 45000,
            'pid': 16,
            'retbufs': 0,
            'tty': 0,
        },
        'mDNS': {
            'allocated': 631152,
            'freed': 340616,
            'getbufs': 0,
            'holding': 265952,
            'pid': 210,
            'retbufs': 0,
            'tty': 0,
        },
        'mdns Timer Proce': {
            'allocated': 553160,
            'freed': 553016,
            'getbufs': 0,
            'holding': 69144,
            'pid': 493,
            'retbufs': 0,
            'tty': 0,
        },
        'nbar-auto-custom': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 251,
            'retbufs': 0,
            'tty': 0,
        },
        'nbar-custom-prot': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 250,
            'retbufs': 0,
            'tty': 0,
        },
        'nbar-graph-sende': {
            'allocated': 448,
            'freed': 448,
            'getbufs': 0,
            'holding': 69000,
            'pid': 249,
            'retbufs': 0,
            'tty': 0,
        },
        'ngpm main proces': {
            'allocated': 0,
            'freed': 0,
            'getbufs': 0,
            'holding': 57000,
            'pid': 134,
            'retbufs': 0,
            'tty': 0,
        },
        'ngwc callhome pe': {
            'allocated': 7616,
            'freed': 7616,
            'getbufs': 0,
            'holding': 45000,
            'pid': 163,
            'retbufs': 0,
            'tty': 0,
        },
        'pki_app': {
            'allocated': 1704,
            'freed': 0,
            'getbufs': 0,
            'holding': 70704,
            'pid': 351,
            'retbufs': 0,
            'tty': 0,
        },
        'radius dtls clie': {
            'allocated': 100560,
            'freed': 0,
            'getbufs': 0,
            'holding': 145560,
            'pid': 158,
            'retbufs': 0,
            'tty': 0,
        },
        'snmp dcm ma shim': {
            'allocated': 6288,
            'freed': 464,
            'getbufs': 0,
            'holding': 50808,
            'pid': 402,
            'retbufs': 0,
            'tty': 0,
        },
        'static': {
            'allocated': 448,
            'freed': 3632,
            'getbufs': 0,
            'holding': 57000,
            'pid': 315,
            'retbufs': 0,
            'tty': 0,
        },
    },
    'processor_pool': {
        'free': 514879552,
        'total': 886321088,
        'used': 371441536,
    },
}