expected_output = {
    "pce_peer_database":{
      "192.168.0.3":{
         "state":"Idle",
         "maximum_sid_depth":0,
         "statistics":{
            "rx":{
               "keepalive_messages":0,
               "request_messages":0,
               "reply_messages":0,
               "error_messages":0,
               "open_messages":0,
               "report_messages":0,
               "update_messages":0,
               "initiate_messages":0
            },
            "tx":{
               "keepalive_messages":0,
               "request_messages":0,
               "reply_messages":0,
               "error_messages":0,
               "open_messages":0,
               "report_messages":0,
               "update_messages":0,
               "initiate_messages":0
            }
         },
         "last_pcerror":{
            "received":"None",
            "sent":"None"
         }
      }
   }
}