expected_output = {
    "autoconfig_status": "Enable",
    "vlans": {
        "1": {
            "created": "No",
            "ip_assign": (0, 0),
            "ip_state": (0, 0),
            "l2": "Up",
            "route": (0, 0),
            "score": (0, 0),
            "state": 3,
            "static": (0, 0),
            "svi": "Yes",
        },
        "100": {
            "created": "Yes",
            "ip_assign": (0, 0),
            "ip_state": (0, 0),
            "l2": "Up",
            "route": (0, 0),
            "score": (0, 0),
            "state": 0,
            "static": (0, 0),
            "svi": "No",
        },
        "20": {
            "created": "Yes",
            "ip_assign": (0, 0),
            "ip_state": (0, 0),
            "l2": "Up",
            "route": (0, 0),
            "score": (0, 0),
            "state": 0,
            "static": (0, 0),
            "svi": "No",
        },
        "77": {
            "created": "Yes",
            "ip_assign": (0, 0),
            "ip_state": (0, 0),
            "l2": "Up",
            "route": (0, 0),
            "score": (0, 0),
            "state": 0,
            "static": (0, 0),
            "svi": "No",
        },
        "90": {
            "created": "Yes",
            "ip_assign": (0, 0),
            "ip_state": (0, 0),
            "l2": "Up",
            "route": (0, 0),
            "score": (0, 0),
            "state": 0,
            "static": (0, 0),
            "svi": "No",
        },
        "91": {
            "created": "No",
            "ip_assign": (1, 1),
            "ip_state": (11, 7),
            "l2": "Up",
            "route": (1, 0),
            "score": (3, 1),
            "state": 3,
            "static": (0, 0),
            "svi": "Yes",
        },
        "92": {
            "created": "No",
            "ip_assign": (1, 1),
            "ip_state": (9, 7),
            "l2": "Up",
            "route": (0, 0),
            "score": (3, 1),
            "state": 3,
            "static": (0, 0),
            "svi": "Yes",
        },
    },
}
