expected_output = {
        'system': 'GREEN', 
        'express_setup': 'BLACK',
        'dc_a': 'GREEN',
        'dc_b': 'BLACK', 
        'alarm-out': 'GREEN', 
        'alarm-in1': 'GREEN',
        'alarm-in2': 'GREEN',
        'number_of_ports_in_status': '20',
        'status': {
            'Gi1/1': 'BLINK_GREEN-BLACK', 
            'Gi1/2': 'BLACK-BLINK_GREEN',
            'Gi1/3': 'BLACK', 
            'Gi1/4': 'BLINK_GREEN',
            'Gi1/5': 'BLINK_GREEN',
            'Gi1/6': 'BLINK_GREEN', 
            'Gi1/7': 'BLINK_GREEN',
            'Gi1/8': 'BLINK_GREEN', 
            'Gi1/9': 'BLINK_GREEN', 
            'Gi1/10': 'BLACK',
            'Gi1/11': 'BLACK',
            'Gi1/12': 'BLACK',
            'Gi1/13': 'BLACK', 
            'Gi1/14': 'BLACK', 
            'Gi1/15': 'BLACK',
            'Gi1/16': 'BLACK',
            'Gi1/17': 'BLACK',
            'Gi1/18': 'BLACK',
            'Gi1/19': 'BLACK', 
            'Gi1/20': 'BLINK_GREEN'
            }
        }
