expected_output = {
    "process_and_memory": {
        "memory_stats": {
            "mem_used_kb": 46468,
            "mem_free_kb": 14468,
            "mem_shrd_kb": 0,
            "mem_buff_kb": 0,
            "mem_cached_kb": 32764,
        },
        "cpu_stats": {
            "cpu_usr_percent": 0,
            "cpu_sys_percent": 0,
            "cpu_nic_percent": 0,
            "cpu_idle_percent": 100,
            "cpu_io_percent": 0,
            "cpu_irq_percent": 0,
            "cpu_sirq_percent": 0,
        },
        "load_average": "0.06 0.03 0.00 3/20 10258",
        "processes": {
            158: {
                "pid": 158,
                "ppid": 157,
                "user": "0",
                "stat": "R",
                "vsz": "146m",
                "mem_percent": "246%",
                "cpu_percent": "0%",
                "command": "[cisco_fortitude]",
            },
            156: {
                "pid": 156,
                "ppid": 155,
                "user": "0",
                "stat": "S",
                "vsz": "35060",
                "mem_percent": "58%",
                "cpu_percent": "0%",
                "command": "[save_cisco_fort]",
            },
            1: {
                "pid": 1,
                "ppid": 0,
                "user": "0",
                "stat": "S",
                "vsz": "3452",
                "mem_percent": "6%",
                "cpu_percent": "0%",
                "command": "sh",
            },
            10251: {
                "pid": 10251,
                "ppid": 10250,
                "user": "0",
                "stat": "S",
                "vsz": "3080",
                "mem_percent": "5%",
                "cpu_percent": "0%",
                "command": "/bin/sh ./fortitude_moduleinfo.sh Proc",
            },
            10250: {
                "pid": 10250,
                "ppid": 158,
                "user": "0",
                "stat": "S",
                "vsz": "3016",
                "mem_percent": "5%",
                "cpu_percent": "0%",
                "command": 'sh -c ./fortitude_moduleinfo.sh "Proce',
            },
            10252: {
                "pid": 10252,
                "ppid": 10251,
                "user": "0",
                "stat": "R",
                "vsz": "3016",
                "mem_percent": "5%",
                "cpu_percent": "0%",
                "command": "/usr/bin/top -b -n 1 -d 30",
            },
            157: {
                "pid": 157,
                "ppid": 155,
                "user": "0",
                "stat": "S",
                "vsz": "1852",
                "mem_percent": "3%",
                "cpu_percent": "0%",
                "command": "./Supervisory",
            },
            155: {
                "pid": 155,
                "ppid": 1,
                "user": "0",
                "stat": "S",
                "vsz": "1788",
                "mem_percent": "3%",
                "cpu_percent": "0%",
                "command": "./Supervisory",
            },
            2: {
                "pid": 2,
                "ppid": 0,
                "user": "0",
                "stat": "SW<",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[kthreadd]",
            },
            3: {
                "pid": 3,
                "ppid": 2,
                "user": "0",
                "stat": "SW<",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[ksoftirqd/0]",
            },
            4: {
                "pid": 4,
                "ppid": 2,
                "user": "0",
                "stat": "SW<",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[events/0]",
            },
            5: {
                "pid": 5,
                "ppid": 2,
                "user": "0",
                "stat": "SW<",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[khelper]",
            },
            6: {
                "pid": 6,
                "ppid": 2,
                "user": "0",
                "stat": "SW<",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[kblockd/0]",
            },
            7: {
                "pid": 7,
                "ppid": 2,
                "user": "0",
                "stat": "SW",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[pdflush]",
            },
            8: {
                "pid": 8,
                "ppid": 2,
                "user": "0",
                "stat": "SW",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[pdflush]",
            },
            9: {
                "pid": 9,
                "ppid": 2,
                "user": "0",
                "stat": "SW<",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[kswapd0]",
            },
            10: {
                "pid": 10,
                "ppid": 2,
                "user": "0",
                "stat": "SW<",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[aio/0]",
            },
            19: {
                "pid": 19,
                "ppid": 2,
                "user": "0",
                "stat": "SW<",
                "vsz": "0",
                "mem_percent": "0%",
                "cpu_percent": "0%",
                "command": "[mtdblockd]",
            },
        },
    },
    "interrupts": {
        2: {
            "cpu0": 0,
            "controller": "MIPS",
            "description": "WinPath interrupt controller",
        },
        7: {
            "cpu0": 55317,
            "controller": "MIPS",
            "description": "timer",
        },
        8: {
            "cpu0": 0,
            "controller": "WinPath-PIC",
            "description": "sys_err_handler",
        },
        9: {
            "cpu0": 0,
            "controller": "WinPath-PIC",
            "description": "sys_err_handler",
        },
        10: {
            "cpu0": 0,
            "controller": "WinPath-PIC",
            "description": "sys_err_handler",
        },
        11: {
            "cpu0": 0,
            "controller": "WinPath-PIC",
            "description": "sys_err_handler",
        },
        12: {
            "cpu0": 0,
            "controller": "WinPath-PIC",
            "description": "sys_err_handler",
        },
        36: {
            "cpu0": 0,
            "controller": "WinPath-PIC",
            "description": "FPGAInt",
        },
        37: {
            "cpu0": 0,
            "controller": "WinPath-PIC",
            "description": "FramerInt",
        },
        50: {
            "cpu0": 544,
            "controller": "WinPath-PIC",
            "description": "serial",
        },
        63: {
            "cpu0": 30189,
            "controller": "WinPath-PIC",
            "description": "ser_qs_handler",
        },
        "err": 0,
    },
    "system_status": {
        "cpu": "115 0 611 21404 0 0 0 0 0",
        "intr": "86063 0 0 0 0 0 0 0 55326 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 544 0 0 0 0 0 0 0 0 0 0 0 0 30193 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0",
        "ctxt": 205235,
        "btime": 0,
        "processes": 10236,
        "procs_running": 2,
        "procs_blocked": 0,
    },
    "klm_module_status": {
        "modules": {
            "klm_mmap": {
                "size": 5917008,
                "used": 4,
                "flags": "-",
                "address": "0xc05ff000",
                "state": "Live",
            },
            "klm_ds0dump": {
                "size": 2848,
                "used": 0,
                "flags": "-",
                "address": "0xc0bb2000",
                "state": "Live",
            },
            "dmesg": {
                "size": 544,
                "used": 0,
                "flags": "-",
                "address": "0xc0bbb000",
                "state": "Live",
            },
            "pmc_adapter": {
                "size": 1856,
                "used": 0,
                "flags": "-",
                "address": "0xc0bc5000",
                "state": "Live",
            },
            "max4422": {
                "size": 2112,
                "used": 0,
                "flags": "-",
                "address": "0xc0bd0000",
                "state": "Live",
            },
        },
        "wddi_memory": 8732064,
        "qnode_status": 65276,
    },
}