expected_output={
    'active_tenants_num': '20',
    'max_tenants': '24',
    'tenant_name': {
            'Tenanttest12': {
                'tenant_id': '2',
                'tenant_name': 'Tenanttest12',
                'tenant_vpnid': '1004'},
            'Tenanttest13': {
                'tenant_id': '3',
                'tenant_name': 'Tenanttest13',
                'tenant_vpnid': '1005'},
            'apple': {
                'tenant_id': '4',
                'tenant_name': 'apple',
                'tenant_vpnid': '1006'},
            'ciscov-DEEP1': {
                'tenant_id': '22',
                'tenant_name': 'ciscov-DEEP1',
                'tenant_vpnid': '1024'},
            'ciscov-DEEP1234': {
                'tenant_id': '10',
                'tenant_name': 'ciscov-DEEP1234',
                'tenant_vpnid': '1029'},
            'ciscov-DEEP2': {
                'tenant_id': '23',
                'tenant_name': 'ciscov-DEEP2',
                'tenant_vpnid': '1025'},
            'ciscov-DEEP3': {
                'tenant_id': '24',
                'tenant_name': 'ciscov-DEEP3',
                'tenant_vpnid': '1026'},
            'ciscov-DEEP4': {
                'tenant_id': '1',
                'tenant_name': 'ciscov-DEEP4',
                'tenant_vpnid': '1027'},
            'ciscov-bgl-new1': {
                'tenant_id': '13',
                'tenant_name': 'ciscov-bgl-new1',
                'tenant_vpnid': '1032'},
            'ciscov-bgl-new10': {
                'tenant_id': '14',
                'tenant_name': 'ciscov-bgl-new10',
                'tenant_vpnid': '1033'},
            'ciscov-bgl-new6': {
                'tenant_id': '11',
                'tenant_name': 'ciscov-bgl-new6',
                'tenant_vpnid': '1030'},
            'ciscov-test': {
                'tenant_id': '16',
                'tenant_name': 'ciscov-test',
                'tenant_vpnid': '1035'},
            'ciscov-testdeep1': {
                'tenant_id': '17',
                'tenant_name': 'ciscov-testdeep1',
                'tenant_vpnid': '1036'},
            'ciscov-testdeep2': {
                'tenant_id': '20',
                'tenant_name': 'ciscov-testdeep2',
                'tenant_vpnid': '1037'},
            'grapes': {
                'tenant_id': '5',
                'tenant_name': 'grapes',
                'tenant_vpnid': '1007'},
            'orange': {
                'tenant_id': '6',
                'tenant_name': 'orange',
                'tenant_vpnid': '1008'},
            'pineapple': {
                'tenant_id': '7',
                'tenant_name': 'pineapple',
                'tenant_vpnid': '1009'},
            'temp1': {
                'tenant_id': '8',
                'tenant_name': 'temp1',
                'tenant_vpnid': '1010'},
            'tenanttemp4': {
                'tenant_id': '18',
                'tenant_name': 'tenanttemp4',
                'tenant_vpnid': '1020'},
            'tenanttemp8': {
                'tenant_id': '19',
                'tenant_name': 'tenanttemp8',
                'tenant_vpnid': '1021'}
            }
    }