expected_output = {
    'interface': {
        'GigabitEthernet2/0/1': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet2/0/15': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet2/0/2': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet2/0/20': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet2/0/21': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet2/0/23': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet2/0/24': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet2/0/36': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet2/0/4': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet4/0/1': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet4/0/13': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet4/0/15': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet4/0/20': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet4/0/23': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'GigabitEthernet4/0/4': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'HundredGigE1/1/1': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'manual',
            'protocol': 'up',
            'status': 'up',
        },
        'HundredGigE1/1/3': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'HundredGigE3/1/1': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'manual',
            'protocol': 'up',
            'status': 'up',
        },
        'HundredGigE3/1/3': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'Port-channel126': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'Port-channel16': {
            'interface_is_ok': 'YES',
            'ip_address': '12.15.10.1',
            'method': 'manual',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/1': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/15': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/2': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/20': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/21': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/22': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/23': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/24': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/3': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/30': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/36': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet1/0/4': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet3/0/1': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet3/0/15': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet3/0/20': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet3/0/23': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet3/0/36': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'TenGigabitEthernet3/0/4': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'unset',
            'protocol': 'up',
            'status': 'up',
        },
        'Vlan1': {
            'interface_is_ok': 'YES',
            'ip_address': 'unassigned',
            'method': 'DHCP',
            'protocol': 'up',
            'status': 'up',
        },
        'Vlan1025': {
            'interface_is_ok': 'YES',
            'ip_address': '100.25.10.3',
            'method': 'manual',
            'protocol': 'up',
            'status': 'up',
        },
    },
}
