expected_output = {'address_family':
                    {'ipv4': {
                        'instance': {
                            '94': {
                                'areas': {
                                    '0.0.0.0': {
                                        'interfaces': {
                                            'GigabitEthernet0/5/6': {
                                                'attached': 'network '
                                                    'statement',
                                                    'bfd': {'enable': False},
                                                    'cost': 50,
                                                    'dead_interval': 40,
                                                    'demand_circuit': False,
                                                    'enable': True,
                                                    'flood_queue_length': 0,
                                                    'graceful_restart': {'cisco': {'helper': True,
                                                                                    'type': 'cisco'},
                                                                        'ietf': {'helper': True,
                                                                                    'type': 'ietf'}},
                                                    'hello_interval': 10,
                                                    'hello_timer': '00:00:05',
                                                    'index': '1/8/8',
                                                    'interface_id': 45,
                                                    'interface_type': 'point-to-point',
                                                    'ip_address': '172.30.79.17/30',
                                                    'ipfrr_candidate': True,
                                                    'ipfrr_protected': True,
                                                    'last_flood_scan_length': 1,
                                                    'last_flood_scan_time_msec': 0,
                                                    'line_protocol': True,
                                                    'lls': True,
                                                    'max_flood_scan_length': 9,
                                                    'max_flood_scan_time_msec': 12,
                                                    'name': 'GigabitEthernet0/5/6',
                                                    'next': '0x0(0)/0x0(0)/0x0(0)',
                                                    'oob_resync_timeout': 40,
                                                    'passive': False,
                                                    'retransmit_interval': 5,
                                                    'router_id': '246.132.205.143',
                                                    'state': 'point-to-point',
                                                    'statistics': {'adj_nbr_count': 0,
                                                                    'nbr_count': 0,
                                                                    'num_nbrs_suppress_hello': 0},
                                                    'ti_lfa_protected': False,
                                                    'topology': {0: {'cost': 50,
                                                                    'disabled': False,
                                                                    'name': 'Base',
                                                                    'shutdown': False}},
                                                    'transmit_delay': 1,
                                                    'wait_interval': 40},
                            'Loopback0': {'attached': 'network '
                                        'statement',
                                        'bfd': {'enable': False},
                                        'cost': 1,
                                        'dead_interval': 40,
                                        'demand_circuit': False,
                                        'enable': True,
                                        'flood_queue_length': 0,
                                        'graceful_restart': {'cisco': {'helper': True,
                                                                        'type': 'cisco'},
                                                                'ietf': {'helper': True,
                                                                        'type': 'ietf'}},
                                        'hello_interval': 10,
                                        'index': '1/5/5',
                                        'interface_id': 49,
                                        'interface_type': 'point-to-point',
                                        'ip_address': '245.132.205.143/32',
                                        'ipfrr_candidate': True,
                                        'ipfrr_protected': True,
                                        'last_flood_scan_length': 0,
                                        'last_flood_scan_time_msec': 0,
                                        'line_protocol': True,
                                        'lls': True,
                                        'max_flood_scan_length': 0,
                                        'max_flood_scan_time_msec': 0,
                                        'name': 'Loopback0',
                                        'next': '0x0(0)/0x0(0)/0x0(0)',
                                        'oob_resync_timeout': 40,
                                        'retransmit_interval': 5,
                                        'router_id': '246.132.205.143',
                                        'state': 'point-to-point',
                                        'statistics': {'adj_nbr_count': 0,
                                                        'nbr_count': 0,
                                                        'num_nbrs_suppress_hello': 0},
                                        'ti_lfa_protected': False,
                                        'topology': {0: {'cost': 1,
                                                            'disabled': False,
                                                            'name': 'Base',
                                                            'shutdown': False}},
                                        'transmit_delay': 1,
                                        'wait_interval': 40},
                            'Loopback99': {'attached': 'network '
                                            'statement',
                                            'bfd': {'enable': False},
                                            'cost': 1,
                                            'demand_circuit': False,
                                            'enable': True,
                                            'interface_id': 48,
                                            'interface_type': 'loopback',
                                            'ip_address': '174.20.72.26/32',
                                            'line_protocol': True,
                                            'name': 'Loopback99',
                                            'router_id': '246.132.205.143',
                                            'stub_host': True,
                                            'topology': {0: {'cost': 1,
                                                            'disabled': False,
                                                            'name': 'Base',
                                                            'shutdown': False}}},
                            'Port-channel1': {'attached': 'network '
                                                        'statement',
                                            'bfd': {'enable': False},
                                            'cost': 20,
                                            'dead_interval': 40,
                                            'demand_circuit': False,
                                            'enable': True,
                                            'flood_queue_length': 0,
                                            'graceful_restart': {'cisco': {'helper': True,
                                                                            'type': 'cisco'},
                                                                    'ietf': {'helper': True,
                                                                            'type': 'ietf'}},
                                            'hello_interval': 10,
                                            'hello_timer': '00:00:05',
                                            'index': '1/4/4',
                                            'interface_id': 50,
                                            'interface_type': 'point-to-point',
                                            'ip_address': '175.30.79.42/30',
                                            'ipfrr_candidate': True,
                                            'ipfrr_protected': True,
                                            'last_flood_scan_length': 1,
                                            'last_flood_scan_time_msec': 0,
                                            'line_protocol': True,
                                            'lls': True,
                                            'max_flood_scan_length': 64,
                                            'max_flood_scan_time_msec': 12,
                                            'name': 'Port-channel1',
                                            'next': '0x0(0)/0x0(0)/0x0(0)',
                                            'oob_resync_timeout': 40,
                                            'passive': False,
                                            'retransmit_interval': 5,
                                            'router_id': '246.132.205.143',
                                            'state': 'point-to-point',
                                            'statistics': {'adj_nbr_count': 1,
                                                            'nbr_count': 1,
                                                            'num_nbrs_suppress_hello': 0},
                                            'ti_lfa_protected': False,
                                            'topology': {0: {'cost': 20,
                                                                'disabled': False,
                                                                'name': 'Base',
                                                                'shutdown': False}},
                                            'transmit_delay': 1,
                                            'wait_interval': 40},
                            'Port-channel3': {'attached': 'network '
                                                        'statement',
                                            'bfd': {'enable': False},
                                            'cost': 7,
                                            'dead_interval': 40,
                                            'demand_circuit': False,
                                            'enable': True,
                                            'flood_queue_length': 0,
                                            'graceful_restart': {'cisco': {'helper': True,
                                                                            'type': 'cisco'},
                                                                    'ietf': {'helper': True,
                                                                            'type': 'ietf'}},
                                            'hello_interval': 10,
                                            'hello_timer': '00:00:04',
                                            'index': '1/3/3',
                                            'interface_id': 51,
                                            'interface_type': 'point-to-point',
                                            'ip_address': '175.30.75.158/30',
                                            'ipfrr_candidate': True,
                                            'ipfrr_protected': True,
                                            'last_flood_scan_length': 4,
                                            'last_flood_scan_time_msec': 0,
                                            'line_protocol': True,
                                            'lls': True,
                                            'max_flood_scan_length': 8,
                                            'max_flood_scan_time_msec': 12,
                                            'name': 'Port-channel3',
                                            'next': '0x0(0)/0x0(0)/0x0(0)',
                                            'oob_resync_timeout': 40,
                                            'passive': False,
                                            'retransmit_interval': 5,
                                            'router_id': '245.132.205.143',
                                            'state': 'point-to-point',
                                            'statistics': {'adj_nbr_count': 1,
                                                            'nbr_count': 1,
                                                            'num_nbrs_suppress_hello': 0},
                                            'ti_lfa_protected': False,
                                            'topology': {0: {'cost': 7,
                                                                'disabled': False,
                                                                'name': 'Base',
                                                                'shutdown': False}},
                                            'transmit_delay': 1,
                                            'wait_interval': 40},
                            'Port-channel7': {'attached': 'network '
                                                        'statement',
                                            'bfd': {'enable': False},
                                            'cost': 7,
                                            'dead_interval': 40,
                                            'demand_circuit': False,
                                            'enable': True,
                                            'flood_queue_length': 0,
                                            'graceful_restart': {'cisco': {'helper': True,
                                                                            'type': 'cisco'},
                                                                    'ietf': {'helper': True,
                                                                            'type': 'ietf'}},
                                            'hello_interval': 10,
                                            'hello_timer': '00:00:00',
                                            'index': '1/2/2',
                                            'interface_id': 53,
                                            'interface_type': 'point-to-point',
                                            'ip_address': '172.30.73.158/30',
                                            'ipfrr_candidate': True,
                                            'ipfrr_protected': True,
                                            'last_flood_scan_length': 4,
                                            'last_flood_scan_time_msec': 0,
                                            'line_protocol': True,
                                            'lls': True,
                                            'max_flood_scan_length': 8,
                                            'max_flood_scan_time_msec': 8,
                                            'name': 'Port-channel7',
                                            'next': '0x0(0)/0x0(0)/0x0(0)',
                                            'oob_resync_timeout': 40,
                                            'passive': False,
                                            'retransmit_interval': 5,
                                            'router_id': '245.133.205.143',
                                            'state': 'point-to-point',
                                            'statistics': {'adj_nbr_count': 1,
                                                            'nbr_count': 1,
                                                            'num_nbrs_suppress_hello': 0},
                                            'ti_lfa_protected': False,
                                            'topology': {0: {'cost': 7,
                                                                'disabled': False,
                                                                'name': 'Base',
                                                                'shutdown': False}},
                                            'transmit_delay': 1,
                                            'wait_interval': 40},
                            'TenGigabitEthernet0/4/0': {'attached': 'network '
                                                                    'statement',
                                                        'authentication': {'auth_trailer_key': {'crypto_algorithm': 'md5',
                                                                                                'youngest_key_id': 1}},
                                                        'bfd': {'enable': False},
                                                        'cost': 181,
                                                        'dead_interval': 40,
                                                        'demand_circuit': False,
                                                        'enable': True,
                                                        'flood_queue_length': 0,
                                                        'graceful_restart': {'cisco': {'helper': True,
                                                                                        'type': 'cisco'},
                                                                            'ietf': {'helper': True,
                                                                                    'type': 'ietf'}},
                                                        'hello_interval': 10,
                                                        'hello_timer': '00:00:08',
                                                        'index': '1/9/9',
                                                        'interface_id': 31,
                                                        'interface_type': 'point-to-point',
                                                        'ip_address': '175.20.248.226/30',
                                                        'ipfrr_candidate': True,
                                                        'ipfrr_protected': True,
                                                        'last_flood_scan_length': 1,
                                                        'last_flood_scan_time_msec': 0,
                                                        'line_protocol': True,
                                                        'lls': True,
                                                        'max_flood_scan_length': 24,
                                                        'max_flood_scan_time_msec': 16,
                                                        'name': 'TenGigabitEthernet0/4/0',
                                                        'next': '0x0(0)/0x0(0)/0x0(0)',
                                                        'oob_resync_timeout': 40,
                                                        'passive': False,
                                                        'retransmit_interval': 5,
                                                        'router_id': '245.132.205.143',
                                                        'state': 'point-to-point',
                                                        'statistics': {'adj_nbr_count': 1,
                                                                        'nbr_count': 1,
                                                                        'num_nbrs_suppress_hello': 0},
                                                        'ti_lfa_protected': False,
                                                        'topology': {0: {'cost': 181,
                                                                        'disabled': False,
                                                                        'name': 'Base',
                                                                        'shutdown': False}},
                                                        'transmit_delay': 1,
                                                        'wait_interval': 40},
                            'Tunnel100': {'attached': 'network '
                                                    'statement',
                                        'bfd': {'enable': False},
                                        'cost': 65535,
                                        'dead_interval': 40,
                                        'demand_circuit': False,
                                        'enable': False,
                                        'hello_interval': 10,
                                        'interface_id': 54,
                                        'interface_type': 'point-to-point',
                                        'ip_address': 'unnumbered',
                                        'line_protocol': False,
                                        'name': 'Tunnel100',
                                        'oob_resync_timeout': 40,
                                        'retransmit_interval': 5,
                                        'router_id': '246.132.205.143',
                                        'state': 'down',
                                        'topology': {0: {'cost': 65535,
                                                            'disabled': False,
                                                            'name': 'Base',
                                                            'shutdown': False}},
                                        'transmit_delay': 1,
                                        'wait_interval': 40},
                            'Tunnel101': {'attached': 'network '
                                                    'statement',
                                        'bfd': {'enable': False},
                                        'cost': 65535,
                                        'dead_interval': 40,
                                        'demand_circuit': False,
                                        'enable': False,
                                        'hello_interval': 10,
                                        'interface_id': 55,
                                        'interface_type': 'point-to-point',
                                        'ip_address': 'unnumbered',
                                        'line_protocol': False,
                                        'name': 'Tunnel101',
                                        'oob_resync_timeout': 40,
                                        'retransmit_interval': 5,
                                        'router_id': '245.132.205.143',
                                        'state': 'down',
                                        'topology': {0: {'cost': 65535,
                                                            'disabled': False,
                                                            'name': 'Base',
                                                            'shutdown': False}},
                                        'transmit_delay': 1,
                                        'wait_interval': 40}}}}}}}}}
