expected_output =  {
    'name': {
        'ACL Drop': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-default',
            'priority': 1,
            'source': 'TRAP',
            'tc': 2,
        },
        'ACL LOG': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-default',
            'priority': 0,
            'source': 'TRAP',
            'tc': 2,
        },
        'ARP': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-arp',
            'priority': 4,
            'source': 'MIRROR',
            'tc': 0,
        },
        'ARP Snooping': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-proto-snoop-v4',
            'priority': 3,
            'source': 'TRAP',
            'tc': 3,
        },
        'BFD ECHO IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bfd-v4',
            'priority': 19,
            'source': 'LPTSv4',
            'tc': 6,
        },
        'BFD ECHO IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bfd-v6',
            'priority': 20,
            'source': 'LPTSv6',
            'tc': 6,
        },
        'BFD IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bfd-v4',
            'priority': 18,
            'source': 'LPTSv4',
            'tc': 6,
        },
        'BFD IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bfd-v6',
            'priority': 19,
            'source': 'LPTSv6',
            'tc': 6,
        },
        'BFD MHOP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bfd-v4',
            'priority': 20,
            'source': 'LPTSv4',
            'tc': 6,
        },
        'BFD MHOP IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bfd-v6',
            'priority': 21,
            'source': 'LPTSv6',
            'tc': 6,
        },
        'BGP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bgp-v4',
            'priority': 8,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'BGP IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bgp-v6',
            'priority': 9,
            'source': 'LPTSv6',
            'tc': 5,
        },
        'BGP established IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bgp-v4',
            'priority': 9,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'BGP established IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-bgp-v6',
            'priority': 10,
            'source': 'LPTSv6',
            'tc': 5,
        },
        'CISCO Protocols': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 15449,
            'cir_sw': 16000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-l2-control',
            'priority': 3,
            'source': 'TRAP',
            'tc': 5,
        },
        'DHCP Client(v4)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-dhcp-v4',
            'priority': 3,
            'source': 'TRAP',
            'tc': 4,
        },
        'DHCP Client(v6)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-dhcp-v6',
            'priority': 3,
            'source': 'TRAP',
            'tc': 4,
        },
        'DHCP Server(v4)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-dhcp-v4',
            'priority': 3,
            'source': 'TRAP',
            'tc': 4,
        },
        'DHCP Server(v6)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-dhcp-v6',
            'priority': 3,
            'source': 'TRAP',
            'tc': 4,
        },
        'DHCP Snooping': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-dhcp-snooping',
            'priority': 3,
            'source': 'TRAP',
            'tc': 3,
        },
        'DHCP(mirror)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 5793,
            'cir_sw': 6000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-dhcp-v4',
            'priority': 3,
            'source': 'MIRROR',
            'tc': 0,
        },
        'DHCPv4 C to S': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-udp-v4',
            'priority': 24,
            'source': 'LPTSv4',
            'tc': 0,
        },
        'DHCPv4 S to C': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-udp-v4',
            'priority': 25,
            'source': 'LPTSv4',
            'tc': 0,
        },
        'DHCPv4 S to S': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-udp-v4',
            'priority': 23,
            'source': 'LPTSv4',
            'tc': 4,
        },
        'DHCPv4 Server TCP Bulk Query': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-tcp-v4',
            'priority': 22,
            'source': 'LPTSv4',
            'tc': 4,
        },
        'DHCPv6 C to S': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-udp-v6',
            'priority': 24,
            'source': 'LPTSv6',
            'tc': 0,
        },
        'DHCPv6 S to C': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-udp-v6',
            'priority': 25,
            'source': 'LPTSv6',
            'tc': 0,
        },
        'DHCPv6 S to S': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-udp-v6',
            'priority': 23,
            'source': 'LPTSv6',
            'tc': 4,
        },
        'DHCPv6 Server TCP Bulk Query': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-tcp-v6',
            'priority': 22,
            'source': 'LPTSv6',
            'tc': 4,
        },
        'EIGRP IPV6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-igrp-v6',
            'priority': 12,
            'source': 'LPTSv6',
            'tc': 5,
        },
        'EIGRP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-igrp-v4',
            'priority': 11,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'Egres DHCP Snooping': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-dhcp-snooping',
            'priority': 3,
            'source': 'TRAP',
            'tc': 3,
        },
        'GLBP IPV6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-fhrp-v6',
            'priority': 16,
            'source': 'LPTSv6',
            'tc': 4,
        },
        'GLBP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-fhrp-v4',
            'priority': 15,
            'source': 'LPTSv4',
            'tc': 4,
        },
        'GLEAN': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-sw-forward',
            'priority': 5,
            'source': 'TRAP',
            'tc': 2,
        },
        'GLEAN-SUBNET': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-default',
            'priority': 5,
            'source': 'TRAP',
            'tc': 2,
        },
        'GOLD': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-default',
            'priority': 0,
            'source': 'TRAP',
            'tc': 3,
        },
        'HSRP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-fhrp-v4',
            'priority': 14,
            'source': 'LPTSv4',
            'tc': 4,
        },
        'HSRP IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-fhrp-v6',
            'priority': 15,
            'source': 'LPTSv6',
            'tc': 4,
        },
        'ICMP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 2494,
            'cir_sw': 2500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-icmp-v4',
            'priority': 1,
            'source': 'LPTSv4',
            'tc': 3,
        },
        'ICMP IPv6 MC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 2494,
            'cir_sw': 2500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-icmp-v6',
            'priority': 1,
            'source': 'LPTSv6',
            'tc': 3,
        },
        'ICMP IPv6 UC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 2494,
            'cir_sw': 2500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-icmp-v6',
            'priority': 2,
            'source': 'LPTSv6',
            'tc': 3,
        },
        'IGMP ENABLE': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-proto-snoop-v4',
            'priority': 8,
            'source': 'TRAP',
            'tc': 4,
        },
        'IP Options(v4)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-sw-forward',
            'priority': 5,
            'source': 'TRAP',
            'tc': 3,
        },
        'IP Options(v6)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-sw-forward',
            'priority': 1,
            'source': 'TRAP',
            'tc': 3,
        },
        'IPV4 FRAGMENTATION': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 2494,
            'cir_sw': 2500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-fragment-v4',
            'priority': 33,
            'source': 'LPTSv4',
            'tc': 3,
        },
        'IPV4 UNKNOWN': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-default',
            'priority': 4,
            'source': 'TRAP',
            'tc': 3,
        },
        'IPv4 Checksum': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-default',
            'priority': 3,
            'source': 'TRAP',
            'tc': 2,
        },
        'IPv4 IGMP': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-proto-snoop-v4',
            'priority': 31,
            'source': 'LPTSv4',
            'tc': 4,
        },
        'IPv4 MC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-ctrl-v4',
            'priority': 32,
            'source': 'LPTSv4',
            'tc': 0,
        },
        'IPv4 PIM Reg Mcast': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-register-v4',
            'priority': 30,
            'source': 'LPTSv4',
            'tc': 1,
        },
        'IPv6 Fragment': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 2494,
            'cir_sw': 2500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-fragment-v6',
            'priority': 28,
            'source': 'LPTSv6',
            'tc': 3,
        },
        'IPv6 MC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-ctrl-v6',
            'priority': 27,
            'source': 'LPTSv6',
            'tc': 0,
        },
        'IPv6 MLD': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-proto-snoop-v6',
            'priority': 26,
            'source': 'LPTSv6',
            'tc': 4,
        },
        'IPv6 UC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-alt-sw-forward',
            'priority': 32,
            'source': 'LPTSv6',
            'tc': 2,
        },
        'ISIS(L2)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-isis',
            'priority': 3,
            'source': 'TRAP',
            'tc': 5,
        },
        'ISIS(L3)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-isis',
            'priority': 3,
            'source': 'TRAP',
            'tc': 5,
        },
        'LACP': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-lacp',
            'priority': 4,
            'source': 'TRAP',
            'tc': 5,
        },
        'LDP TCP DST IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ldp-v4',
            'priority': 7,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'LDP TCP SRC IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ldp-v4',
            'priority': 6,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'LDP TCP SRC IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ldp-v6',
            'priority': 7,
            'source': 'LPTSv6',
            'tc': 5,
        },
        'LDP UDP DST IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ldp-v4',
            'priority': 5,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'LDP UDP DST IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ldp-v6',
            'priority': 8,
            'source': 'LPTSv6',
            'tc': 5,
        },
        'LDP UDP SRC IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ldp-v4',
            'priority': 4,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'LDP UDP SRC IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ldp-v6',
            'priority': 5,
            'source': 'LPTSv6',
            'tc': 5,
        },
        'LLDP': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 15449,
            'cir_sw': 16000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-l2-control',
            'priority': 4,
            'source': 'TRAP',
            'tc': 5,
        },
        'LPM Drop': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-alt-sw-forward',
            'priority': 80,
            'source': 'TRAP',
            'tc': 2,
        },
        'MACSEC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 15449,
            'cir_sw': 16000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-l2-control',
            'priority': 3,
            'source': 'TRAP',
            'tc': 4,
        },
        'MC DIRECT CONNECT': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-data',
            'priority': 5,
            'source': 'TRAP',
            'tc': 1,
        },
        'MC FWD DISABLED(v4)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-data',
            'priority': 6,
            'source': 'TRAP',
            'tc': 1,
        },
        'MC FWD DISABLED(v6)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-data',
            'priority': 6,
            'source': 'TRAP',
            'tc': 1,
        },
        'MC G PIM PUNT': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-data',
            'priority': 6,
            'source': 'MIRROR',
            'tc': 0,
        },
        'MC NOT FOUND': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-data',
            'priority': 5,
            'source': 'TRAP',
            'tc': 1,
        },
        'MC PIM RPF': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-rpf-fail',
            'priority': 5,
            'source': 'TRAP',
            'tc': 1,
        },
        'MC PIM RPF FAIL': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-rpf-fail',
            'priority': 5,
            'source': 'TRAP',
            'tc': 1,
        },
        'MC SG PIM PUNT': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-data',
            'priority': 6,
            'source': 'MIRROR',
            'tc': 0,
        },
        'MC SNOOP RPF FAIL': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-rpf-fail',
            'priority': 5,
            'source': 'MIRROR',
            'tc': 0,
        },
        'MC SNOOP and DIRECT CONNECT': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-data',
            'priority': 5,
            'source': 'TRAP',
            'tc': 1,
        },
        'MDNS': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-proto-snoop-v6',
            'priority': 8,
            'source': 'TRAP',
            'tc': 4,
        },
        'MLD ENABLE': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-proto-snoop-v6',
            'priority': 8,
            'source': 'TRAP',
            'tc': 4,
        },
        'MPLS OAM IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mpls-oam',
            'priority': 21,
            'source': 'LPTSv4',
            'tc': 4,
        },
        'MPLS-VPN-TTL1': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mtu-ttl-fail',
            'priority': 8,
            'source': 'TRAP',
            'tc': 3,
        },
        'MTU(L3)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mtu-ttl-fail',
            'priority': 8,
            'source': 'TRAP',
            'tc': 3,
        },
        'OSPF v2 MC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ospf-v4',
            'priority': 2,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'OSPF v2 UC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ospf-v4',
            'priority': 3,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'OSPF v3 MC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ospf-v6',
            'priority': 3,
            'source': 'LPTSv6',
            'tc': 5,
        },
        'OSPF v3 UC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-ospf-v6',
            'priority': 4,
            'source': 'LPTSv6',
            'tc': 5,
        },
        'PIM IPV6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-ctrl-v6',
            'priority': 17,
            'source': 'LPTSv6',
            'tc': 4,
        },
        'PIM IPV6 Reg Mcast': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-register-v6',
            'priority': 18,
            'source': 'LPTSv6',
            'tc': 1,
        },
        'PIM IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mcast-ctrl-v4',
            'priority': 17,
            'source': 'LPTSv4',
            'tc': 4,
        },
        'RIP': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-rip-bc',
            'priority': 3,
            'source': 'TRAP',
            'tc': 5,
        },
        'RIP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-rip-v4',
            'priority': 12,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'RIP IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-rip-v6',
            'priority': 14,
            'source': 'LPTSv6',
            'tc': 5,
        },
        'RPF(unicast)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 0,
            'cir_sw': 0,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-default',
            'priority': 2,
            'source': 'TRAP',
            'tc': 0,
        },
        'RSVP IPV4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-default-v4',
            'priority': 34,
            'source': 'LPTSv4',
            'tc': 5,
        },
        'SISF': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-proto-snoop-v6',
            'priority': 3,
            'source': 'TRAP',
            'tc': 3,
        },
        'STP(IEEE)': {
            'bytes_a': 330,
            'bytes_d': 0,
            'cir_hw': 4988,
            'cir_sw': 5000,
            'packets_a': 3,
            'packets_d': 0,
            'policy': 'system-cpp-police-topology-control',
            'priority': 4,
            'source': 'TRAP',
            'tc': 5,
        },
        'TCP DST PORT LISP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-lisp-ctrl',
            'priority': 29,
            'source': 'LPTSv4',
            'tc': 2,
        },
        'TCP SRC PORT LISP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-lisp-ctrl',
            'priority': 28,
            'source': 'LPTSv4',
            'tc': 2,
        },
        'TCP default IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-tcp-v4',
            'priority': 35,
            'source': 'LPTSv4',
            'tc': 2,
        },
        'TCP default IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-tcp-v6',
            'priority': 30,
            'source': 'LPTSv6',
            'tc': 2,
        },
        'TTL0(MPLS)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mtu-ttl-fail',
            'priority': 8,
            'source': 'TRAP',
            'tc': 3,
        },
        'TTL1(L3)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mtu-ttl-fail',
            'priority': 8,
            'source': 'TRAP',
            'tc': 3,
        },
        'TTL1(MPLS)': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-mtu-ttl-fail',
            'priority': 8,
            'source': 'TRAP',
            'tc': 3,
        },
        'UDP DST PORT LISP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-lisp-ctrl',
            'priority': 27,
            'source': 'LPTSv4',
            'tc': 2,
        },
        'UDP SRC PORT LISP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-lisp-ctrl',
            'priority': 26,
            'source': 'LPTSv4',
            'tc': 2,
        },
        'UDP default IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-udp-v4',
            'priority': 36,
            'source': 'LPTSv4',
            'tc': 2,
        },
        'UDP default IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 583,
            'cir_sw': 600,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-udp-v6',
            'priority': 31,
            'source': 'LPTSv6',
            'tc': 2,
        },
        'Unknown UC': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 965,
            'cir_sw': 1000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-unknown-uc',
            'priority': 3,
            'source': 'TRAP',
            'tc': 3,
        },
        'VRRP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-fhrp-v4',
            'priority': 13,
            'source': 'LPTSv4',
            'tc': 4,
        },
        'VRRP IPv6': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 4345,
            'cir_sw': 4500,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-police-fhrp-v6',
            'priority': 13,
            'source': 'LPTSv6',
            'tc': 4,
        },
        'WCCP IPv4': {
            'bytes_a': 0,
            'bytes_d': 0,
            'cir_hw': 1931,
            'cir_sw': 2000,
            'packets_a': 0,
            'packets_d': 0,
            'policy': 'system-cpp-default-v4',
            'priority': 16,
            'source': 'LPTSv4',
            'tc': 4,
        },
    },
}