expected_output = {
   "interface":{
     "if_id":"29",
     "clock_mode":"BOUNDARY CLOCK",
     "delay_mechanism":"End-to-End",
     "delay_req_seq_num":0,
     "domain_value":0,
     "log_mean_delay_interval":0,
     "log_mean_sync_interval":0,
     "num_info":{
        "num_delay_requests_received":0,
        "num_delay_requests_transmitted":0,
        "num_delay_responses_received":0,
        "num_delay_responses_transmitted":0,
        "num_followup_messages_received":0,
        "num_followup_messages_transmitted":1710,
        "num_sync_messages_received":0,
        "num_sync_messages_transmitted":1710
     },
     "port_info":{
        "clock_identity":"34:ED:1B:FF:FE:7D:F2:80",
        "mac_address":"34:ED:1B:7D:F2:A1",
        "number":33,
        "port_enabled":"TRUE",
        "state":"MASTER"
     },
     "profile_type":"DEFAULT",
     "ptp_info":{
        "version":2
     },
     "ptt_port_enabled":"TRUE",
     "sync_seq_num":44364,
    }
}
