expected_output = {
    "lisp_router_instances": {
        0: {
            "service": {
                "ipv4": {
                    "statistics": {
                        "EID": {
                            "control": {
                                "authoritative_records_in": "1",
                                "authoritative_records_out": "1",
                                "ddt_referral_deferred": "0",
                                "ddt_referral_dropped": "0",
                                "ddt_request_deferred": "0",
                                "ddt_request_dropped": "0",
                                "deferred_packet_transmission": "0/0",
                                "dropped_control_packets_in_input_queue": "0",
                                "encapsulated_map_requests_in": "0",
                                "encapsulated_map_requests_out": "3",
                                "etr_info_request_deferred": "0",
                                "etr_info_request_dropped": "0",
                                "map_notify_records_in": "4",
                                "map_notify_records_out": "0",
                                "map_notify_auth_failures": "0",
                                "map_register_records_in": "0",
                                "map_register_records_out": "2857",
                                "map_reply_deferred": "0",
                                "map_reply_dropped": "0",
                                "map_reply_records_in": "2",
                                "map_reply_records_out": "1",
                                "map_requests_expired_no-reply": "0",
                                "map_requests_expired_on-queue": "0",
                                "map_requests_in": "0",
                                "map_requests_out": "4",
                                "map_resolver_map_requests_forwarded": "0",
                                "map_server_af_disabled": "0",
                                "map_registers_in_auth_failed": "0",
                                "map_server_map_requests_forwarded": "0",
                                "map_server_proxy_reply_records_out": "0",
                                "map_subscribe_failures_in": "0",
                                "map_subscribe_failures_out": "0",
                                "map_unsubscribe_failures_in": "0",
                                "map_unsubscribe_failures_out": "0",
                                "mr_map_request_fwd_deferred": "0",
                                "mr_map_request_fwd_dropped": "0",
                                "mr_negative_map_reply_deferred": "0",
                                "mr_negative_map_reply_dropped": "0",
                                "ms_info_reply_deferred": "0",
                                "ms_info_reply_dropped": "0",
                                "ms_map_request_fwd_deferred": "0",
                                "ms_map_request_fwd_dropped": "0",
                                "ms_proxy_map_reply_deferred": "0",
                                "ms_proxy_map_reply_dropped": "0",
                                "negative_records_in": "0",
                                "negative_records_out": "0",
                                "non_authoritative_records_in": "1",
                                "non_authoritative_records_out": "0",
                                "rloc_probe_map_requests_in": "0",
                                "rloc_probe_map_requests_out": "1",
                                "rloc_probe_records_in": "1",
                                "rloc_probe_records_out": "1",
                                "rtr_map_notify_fwd_deferred": "0",
                                "rtr_map_notify_fwd_dropped": "0",
                                "rtr_map_register_fwd_deferred": "0",
                                "rtr_map_register_fwd_dropped": "0",
                                "smr_based_map_requests_in": "0",
                                "smr_based_map_requests_out": "0",
                                "wlc_ap_map_notify_in": "0",
                                "wlc_ap_map_notify_out": "0",
                                "wlc_ap_map_register_in": "0",
                                "wlc_ap_map_register_out": "0",
                                "wlc_client_map_notify_in": "0",
                                "wlc_client_map_notify_out": "0",
                                "wlc_client_map_register_in": "0",
                                "wlc_client_map_register_out": "0",
                                "wlc_map_notify_failures_in": "0",
                                "wlc_map_notify_failures_out": "0",
                                "wlc_map_notify_records_in": "0",
                                "wlc_map_notify_records_out": "0",
                                "wlc_map_register_failures_in": "0",
                                "wlc_map_register_failures_out": "0",
                                "wlc_map_register_records_in": "0",
                                "wlc_map_register_records_out": "0",
                                "wlc_map_subscribe_records_in": "0",
                                "wlc_map_subscribe_records_out": "1",
                                "wlc_map_unsubscribe_records_in": "0",
                                "wlc_map_unsubscribe_records_out": "0",
                                "xtr_mcast_map_notify_deferred": "0",
                                "xtr_mcast_map_notify_dropped": "0",
                            },
                            "errors": {
                                "average_rlocs_per_eid_prefix": "1",
                                "cache_entries_created": "3",
                                "cache_entries_deleted": "1",
                                "ddt_itr_map_requests_dropped": "0 (nonce-collision: 0, bad-xTR-nonce: 0)",
                                "map_register_invalid_source_rloc_drops": "0",
                                "map_request_invalid_source_rloc_drops": "0",
                                "map_rseolvers": {
                                    "10.166.13.13": {
                                        "last_reply": "03:13:58",
                                        "metric": "26",
                                        "negative": 0,
                                        "no_reply": 1,
                                        "positive": 0,
                                        "reqs_sent": 2,
                                    },
                                    "10.64.4.4": {
                                        "last_reply": "03:13:58",
                                        "metric": "4",
                                        "negative": 0,
                                        "no_reply": 0,
                                        "positive": 1,
                                        "reqs_sent": 1,
                                    },
                                },
                                "number_of_data_signals_processed": "1 (+ dropped 0)",
                                "number_of_eid_prefixes_in_map_cache": "2",
                                "number_of_negative_entries_in_map_cache": "1",
                                "number_of_reachability_reports": "0 (+ dropped 0)",
                                "total_number_of_rlocs_in_map_cache": "1",
                            },
                            "last_cleared": "never",
                        },
                        "Miscellaneous": {
                            "errors": {
                                "invalid_ip_header_drops": "0",
                                "invalid_ip_proto_field_drops": "0",
                                "invalid_ip_version_drops": "0",
                                "invalid_lisp_checksum_drops": "0",
                                "invalid_lisp_control_port_drops": "0",
                                "invalid_packet_size_dropss": "0",
                                "unknown_packet_drops": "0",
                                "unsupported_lisp_packet_type_drops": "0",
                            },
                            "last_cleared": "never",
                        },
                        "RLOC": {
                            "control": {
                                "ddt_map_referrals_in": "0",
                                "ddt_map_referrals_out": "0",
                                "ddt_map_requests_in": "0",
                                "ddt_map_requests_out": "0",
                                "rtr_map_notifies_forwarded": "0",
                                "rtr_map_requests_forwarded": "0",
                            },
                            "errors": {
                                "ddt_requests_failed": "0",
                                "map_referral_format_errors": "0",
                                "map_reply_format_errors": "0",
                                "map_request_format_errors": "0",
                                "mapping_record_ttl_alerts": "0",
                            },
                            "last_cleared": "never",
                        },
                    }
                }
            }
        }
    }
}
