expected_output = {
    "version": {
        "chassis": "WS-C4507R+E",
        "chassis_sn": "FXS1729E2TD",
        "compiled_by": "prod_rel_team",
        "compiled_date": "Tue 23-Oct-12 23:51",
        "copyright_years": "1986-2012",
        "curr_config_register": "0x2101",
        "hostname": "switchname",
        "image_id": "cat4500e-UNIVERSALK9-M",
        "image_type": "production image",
        "jawa_revision": "7",
        "last_reload_reason": "Reload",
        "license_level": "entservices",
        "license_type": "Permanent",
        "main_mem": "2097152",
        "mem_size": {"non-volatile configuration": "511"},
        "next_config_register": "0x2102",
        "next_reload_license_level": "entservices",
        "number_of_intfs": {
            "Gigabit Ethernet": "240",
            "Ten Gigabit Ethernet": "4",
            "Virtual Ethernet": "9",
        },
        "os": "IOS-XE",
        "platform": "Catalyst 4500 L3 Switch",
        "processor": {"cpu_type": "MPC8572", "speed": "1.5GHz", "supervisor": "7"},
        "processor_type": "MPC8572",
        "returned_to_rom_by": "reload",
        "rom": "15.0(1r)SG5",
        "rtr_type": "WS-C4507R+E",
        "running_default_software": True,
        "snowtrooper_revision": "0x0.0x1C",
        "system_restarted_at": "09:57:20 GMT Tue Oct 15 2013",
        "uptime": "6 years, 2 weeks, 13 hours, 31 minutes",
        "uptime_this_cp": "6 years, 2 weeks, 13 hours, 33 minutes",
        "version": "03.03.02.SG",
        "version_short": "03.03",
    }
}
