expected_output = {
    "version": {
        "version_short": "03.04",
        "platform": "Catalyst 4500 L3 Switch",
        "version": "03.04.06.SG",
        "image_id": "cat4500e-UNIVERSALK9-M",
        "os": "IOS-XE",
        "image_type": "production image",
        "compiled_date": "Mon 04-May-15 02:44",
        "compiled_by": "prod_rel_team",
        "copyright_years": "1986-2015",
        "rom": "15.0(1r)SG10",
        "hostname": "sample_4510r_e",
        "uptime": "2 years, 11 weeks, 3 days, 3 hours, 3 minutes",
        "uptime_this_cp": "2 years, 11 weeks, 1 day, 22 hours, 18 minutes",
        "returned_to_rom_by": "SSO Switchover",
        "system_restarted_at": "19:11:28 GMT Tue Aug 22 2017",
        "system_image": "bootflash:cat4500e-universalk9.SPA.03.04.06.SG.151-2.SG6.bin",
        "jawa_revision": "7",
        "snowtrooper_revision": "0x0.0x1C",
        "last_reload_reason": "PowerUp",
        "license_type": "Permanent",
        "license_level": "entservices",
        "next_reload_license_level": "entservices",
        "chassis": "WS-C4510R+E",
        "main_mem": "2097152",
        "processor_type": "MPC8572",
        "rtr_type": "WS-C4510R+E",
        "chassis_sn": "JAD213101PP",
        "processor": {"cpu_type": "MPC8572", "speed": "1.5GHz", "supervisor": "7"},
        "number_of_intfs": {
            "Virtual Ethernet": "8",
            "Gigabit Ethernet": "384",
            "Ten Gigabit Ethernet": "8",
        },
        "mem_size": {"non-volatile configuration": "511"},
        "curr_config_register": "0x2102",
    }
}
