expected_output = {
    "version": {
        "version_short": "15.2",
        "platform": "C2960X",
        "version": "15.2(2)E7",
        "image_id": "C2960X-UNIVERSALK9-M",
        "os": "IOS",
        "image_type": "production image",
        "compiled_date": "Wed 12-Jul-17 13:06",
        "compiled_by": "prod_rel_team",
        "copyright_years": "1986-2017",
        "rom": "Bootstrap program is C2960X boot loader",
        "bootldr": "C2960X Boot Loader (C2960X-HBOOT-M) Version 15.2(2r)E1, RELEASE SOFTWARE (fc1)",
        "hostname": "testname",
        "uptime": "25 weeks, 5 days, 15 hours, 45 minutes",
        "returned_to_rom_by": "power-on",
        "system_restarted_at": "19:24:47 UTC+2 Wed Oct 9 2019",
        "system_image": "flash:c2960x-universalk9-mz.152-2.E7/c2960x-universalk9-mz.152-2.E7.bin",
        "last_reload_reason": "power-on",
        "chassis": "WS-C2960X-48FPD-L",
        "main_mem": "524288",
        "processor_type": "APM86XXX",
        "rtr_type": "WS-C2960X-48FPD-L",
        "chassis_sn": "FOC1913S46M",
        "number_of_intfs": {
            "Virtual Ethernet": "4",
            "FastEthernet": "1",
            "Gigabit Ethernet": "100",
            "Ten Gigabit Ethernet": "4",
        },
        "mem_size": {"flash-simulated non-volatile configuration": "512"},
        "switch_num": {
            "1": {
                "uptime": "9 weeks, 5 days, 16 hours, 1 minute",
                "mac_address": "00:11:22:ff:77:88",
                "mb_assembly_num": "77-99999-00",
                "power_supply_part_nr": "111-0111-03",
                "mb_sn": "FOC666777G4",
                "power_supply_sn": "LIT122334DD",
                "model_rev_num": "V0",
                "mb_rev_num": "D0",
                "model_num": "WS-C2960X-48FPD-L",
                "db_assembly_num": "73-12230-13",
                "db_sn": "FOC33144FDG",
                "system_sn": "FOC3333S00A",
                "top_assembly_part_num": "00-100000-00",
                "top_assembly_rev_num": "D0",
                "version_id": "V07",
                "clei_code_num": "CDFER00DFG",
                "db_rev_num": "B0",
                "ports": "52",
                "model": "WS-C2960X-48FPD-L",
                "sw_ver": "15.2(2)E7",
                "sw_image": "C2960X-UNIVERSALK9-M",
                "active": False,
            },
            "2": {
                "ports": "52",
                "model": "WS-C2960X-48FPD-L",
                "sw_ver": "15.2(2)E7",
                "sw_image": "C2960X-UNIVERSALK9-M",
                "active": True,
                "mac_address": "CC:44:33:FF:99:22",
                "mb_assembly_num": "71-123456-02",
                "power_supply_part_nr": "311-4567-11",
                "mb_sn": "FOC123456U12",
                "power_supply_sn": "DCB324354RH",
                "model_rev_num": "F0",
                "mb_rev_num": "C0",
                "model_num": "WS-C2960X-48FPD-L",
                "db_assembly_num": "73-11111-00",
                "db_sn": "FOC87654CWW",
                "system_sn": "FOC4444S23V",
                "top_assembly_part_num": "800-55555-11",
                "top_assembly_rev_num": "C0",
                "version_id": "V02",
                "clei_code_num": "AAALJ00ERT",
                "db_rev_num": "A0",
                "hb_rev_num": "0x12",
            },
        },
        "curr_config_register": "0xF",
        "label": "RELEASE SOFTWARE (fc3)",
    }
}
