expected_output = {
        'mrp_rings':
        {
            '1':{'ring': 'not configured'},
            '10': {'ring': 'not configured'},
            '11': {'ring': 'not configured'},
            '12': {
                'best_manager': 
                {
                    'mac_address': '04:A7:41:4D:20:17',
                    'priority': '40960'
                    },
                'default_test_frame_interval': '20',
                'domain_id': 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF3',
                'domain_name': 'RING12',
                'from': 'CLI',
                'gateway':
                {
                    'status': 'Disabled'
                    },
                'license': 'Not Applicable',
                'mode': 'Auto-Manager',
                'network_status': 'CLOSED',
                'network_topology': 'Ring',
                'operation_mode': 'Manager',
                'operational_test_frame_interval': '20',
                'port1': {
                    'interface': 'GigabitEthernet1/0/23',
                    'mac_address': '04:A7:41:4D:20:17',
                    'status': 'Forwarding'
                    },
                'port2':
                {
                    'interface': 'GigabitEthernet1/0/24',
                    'mac_address': '04:A7:41:4D:20:18',
                    'status': 'Blocked'
                    },
               'priority': '40960',
               'profile': '200',
               'short_test_frame_interval': '10',
               'test_monitoring_extended_interval_count': 'N/A',
               'test_monitoring_interval_count': '3',
               'topology_change_repeat_count': '3',
               'topology_change_request_interval': '10',
               'vlan_id': '221'
               },
            '13': {'ring': 'not configured'},
            '14': {'ring': 'not configured'},
            '15': {'ring': 'not configured'},
            '16': {'ring': 'not configured'},
            '17': {'ring': 'not configured'},
            '18': {'ring': 'not configured'},
            '19': {'ring': 'not configured'},
            '2': {'ring': 'not configured'},
            '20': {'ring': 'not configured'},
            '21': {'ring': 'not configured'},
            '22': {'ring': 'not configured'},
            '3': {'best_manager': {'mac_address': '04:A7:41:4D:20:05',
                                      'priority': '36864'},
                     'default_test_frame_interval': '20',
                     'domain_id': 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFC',
                     'domain_name': 'RING3',
                     'from': 'CLI',
                     'gateway': {'status': 'Disabled'},
                     'license': 'Not Applicable',
                     'mode': 'Auto-Manager',
                     'network_status': 'CLOSED',
                     'network_topology': 'Ring',
                     'operation_mode': 'Manager',
                     'operational_test_frame_interval': '20',
                     'port1': {'interface': 'GigabitEthernet1/0/5',
                               'mac_address': '04:A7:41:4D:20:05',
                               'status': 'Forwarding'},
                     'port2': {'interface': 'GigabitEthernet1/0/6',
                               'mac_address': '04:A7:41:4D:20:06',
                               'status': 'Blocked'},
                     'priority': '36864',
                     'profile': '200',
                     'short_test_frame_interval': '10',
                     'test_monitoring_extended_interval_count': 'N/A',
                     'test_monitoring_interval_count': '3',
                     'topology_change_repeat_count': '3',
                     'topology_change_request_interval': '10',
                     'vlan_id': '131'},
               '4': {'best_manager': {'mac_address': '04:A7:41:4D:20:07',
                                      'priority': '40960'},
                     'default_test_frame_interval': '20',
                     'domain_id': 'FFFFFFFF-FFFF-FFFF-FFFF-AAAAAAAAAAAE',
                     'domain_name': 'RING4',
                     'from': 'CLI',
                     'gateway': {'status': 'Disabled'},
                     'license': 'Not Applicable',
                     'mode': 'Auto-Manager',
                     'network_status': 'OPEN',
                     'network_topology': 'Ring',
                     'operation_mode': 'Manager',
                     'operational_test_frame_interval': '20',
                     'port1': {'interface': 'GigabitEthernet1/0/7',
                               'mac_address': '04:A7:41:4D:20:07',
                               'status': 'Forwarding'},
                     'port2': {'interface': 'GigabitEthernet1/0/8',
                               'mac_address': '04:A7:41:4D:20:08',
                               'status': 'Forwarding'},
                     'priority': '40960',
                     'profile': '200',
                     'short_test_frame_interval': '10',
                     'test_monitoring_extended_interval_count': 'N/A',
                     'test_monitoring_interval_count': '3',
                     'topology_change_repeat_count': '3',
                     'topology_change_request_interval': '10',
                     'vlan_id': '141'},
               '5': {'best_manager': {'mac_address': '04:A7:41:4D:20:09',
                                      'priority': '40960'},
                     'default_test_frame_interval': '20',
                     'domain_id': 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFA',
                     'domain_name': 'RING5',
                     'from': 'CLI',
                     'gateway': {'status': 'Disabled'},
                     'license': 'Not Applicable',
                     'mode': 'Auto-Manager',
                     'network_status': 'CLOSED',
                     'network_topology': 'Ring',
                     'operation_mode': 'Manager',
                     'operational_test_frame_interval': '20',
                     'port1': {'interface': 'GigabitEthernet1/0/9',
                               'mac_address': '04:A7:41:4D:20:09',
                               'status': 'Forwarding'},
                     'port2': {'interface': 'GigabitEthernet1/0/10',
                               'mac_address': '04:A7:41:4D:20:0A',
                               'status': 'Blocked'},
                     'priority': '40960',
                     'profile': '200',
                     'short_test_frame_interval': '10',
                     'test_monitoring_extended_interval_count': 'N/A',
                     'test_monitoring_interval_count': '3',
                     'topology_change_repeat_count': '3',
                     'topology_change_request_interval': '10',
                     'vlan_id': '151'},
               '6': {'best_manager': {'mac_address': '04:A7:41:4D:20:0B',
                                      'priority': '40960'},
                     'default_test_frame_interval': '20',
                     'domain_id': 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF9',
                     'domain_name': 'RING6',
                     'from': 'CLI',
                     'gateway': {'status': 'Disabled'},
                     'license': 'Not Applicable',
                     'mode': 'Auto-Manager',
                     'network_status': 'CLOSED',
                     'network_topology': 'Ring',
                     'operation_mode': 'Manager',
                     'operational_test_frame_interval': '20',
                     'port1': {'interface': 'GigabitEthernet1/0/11',
                               'mac_address': '04:A7:41:4D:20:0B',
                               'status': 'Forwarding'},
                     'port2': {'interface': 'GigabitEthernet1/0/12',
                               'mac_address': '04:A7:41:4D:20:0C',
                               'status': 'Blocked'},
                     'priority': '40960',
                     'profile': '200',
                     'short_test_frame_interval': '10',
                     'test_monitoring_extended_interval_count': 'N/A',
                     'test_monitoring_interval_count': '3',
                     'topology_change_repeat_count': '3',
                     'topology_change_request_interval': '10',
                     'vlan_id': '161'},
               '7': {'best_manager': {'mac_address': '04:A7:41:4D:20:0D',
                                      'priority': '40960'},
                     'default_test_frame_interval': '20',
                     'domain_id': 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF8',
                     'domain_name': 'RING7',
                     'from': 'CLI',
                     'gateway': {'status': 'Disabled'},
                     'license': 'Not Applicable',
                     'mode': 'Auto-Manager',
                     'network_status': 'CLOSED',
                     'network_topology': 'Ring',
                     'operation_mode': 'Manager',
                     'operational_test_frame_interval': '20',
                     'port1': {'interface': 'GigabitEthernet1/0/13',
                               'mac_address': '04:A7:41:4D:20:0D',
                               'status': 'Forwarding'},
                     'port2': {'interface': 'GigabitEthernet1/0/14',
                               'mac_address': '04:A7:41:4D:20:0E',
                               'status': 'Blocked'},
                     'priority': '40960',
                     'profile': '200',
                     'short_test_frame_interval': '10',
                     'test_monitoring_extended_interval_count': 'N/A',
                     'test_monitoring_interval_count': '3',
                     'topology_change_repeat_count': '3',
                     'topology_change_request_interval': '10',
                     'vlan_id': '171'},
               '8': {'best_manager': {'mac_address': '04:A7:41:4D:20:0F',
                                      'priority': '40960'},
                     'default_test_frame_interval': '20',
                     'domain_id': 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF7',
                     'domain_name': 'RING8',
                     'from': 'CLI',
                     'gateway': {'status': 'Disabled'},
                     'license': 'Not Applicable',
                     'mode': 'Auto-Manager',
                     'network_status': 'CLOSED',
                     'network_topology': 'Ring',
                     'operation_mode': 'Manager',
                     'operational_test_frame_interval': '20',
                     'port1': {'interface': 'GigabitEthernet1/0/15',
                               'mac_address': '04:A7:41:4D:20:0F',
                               'status': 'Forwarding'},
                     'port2': {'interface': 'GigabitEthernet1/0/16',
                               'mac_address': '04:A7:41:4D:20:10',
                               'status': 'Blocked'},
                     'priority': '40960',
                     'profile': '200',
                     'short_test_frame_interval': '10',
                     'test_monitoring_extended_interval_count': 'N/A',
                     'test_monitoring_interval_count': '3',
                     'topology_change_repeat_count': '3',
                     'topology_change_request_interval': '10',
                     'vlan_id': '181'},
               '9': {'best_manager': {'mac_address': '04:A7:41:4D:20:11',
                                      'priority': '40960'},
                     'default_test_frame_interval': '20',
                     'domain_id': 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF6',
                     'domain_name': 'RING9',
                     'from': 'CLI',
                     'gateway': {'status': 'Disabled'},
                     'license': 'Not Applicable',
                     'mode': 'Auto-Manager',
                     'network_status': 'CLOSED',
                     'network_topology': 'Ring',
                     'operation_mode': 'Manager',
                     'operational_test_frame_interval': '20',
                     'port1': {'interface': 'GigabitEthernet1/0/18',
                               'mac_address': '04:A7:41:4D:20:12',
                               'status': 'Forwarding'},
                     'port2': {'interface': 'GigabitEthernet1/0/17',
                               'mac_address': '04:A7:41:4D:20:11',
                               'status': 'Blocked'},
                     'priority': '40960',
                     'profile': '200',
                     'short_test_frame_interval': '10',
                     'test_monitoring_extended_interval_count': 'N/A',
                     'test_monitoring_interval_count': '3',
                     'topology_change_repeat_count': '3',
                     'topology_change_request_interval': '10',
                     'vlan_id': '191'}}}

