expected_output = {'mrp_rings': {'1': {'domain_id': 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFE',
                     'domain_name': 'Cisco MRP Ring 1',
                     'from': 'CLI',
                     'gateway': {'status': 'Disabled'},
                     'license': 'Not Applicable',
                     'link_change_up_or_down_count': '4',
                     'link_down_timer_interval': '20',
                     'link_up_timer_interval': '20',
                     'mode': 'Client',
                     'vlan_id': '1'},
               '10': {'ring': 'not configured'},
               '11': {'ring': 'not configured'},
               '12': {'ring': 'not configured'},
               '13': {'ring': 'not configured'},
               '14': {'ring': 'not configured'},
               '15': {'ring': 'not configured'},
               '16': {'ring': 'not configured'},
               '17': {'ring': 'not configured'},
               '18': {'ring': 'not configured'},
               '19': {'ring': 'not configured'},
               '2': {'ring': 'not configured'},
               '20': {'ring': 'not configured'},
               '21': {'ring': 'not configured'},
               '22': {'ring': 'not configured'},
               '3': {'ring': 'not configured'},
               '4': {'ring': 'not configured'},
               '5': {'ring': 'not configured'},
               '6': {'ring': 'not configured'},
               '7': {'ring': 'not configured'},
               '8': {'ring': 'not configured'},
               '9': {'ring': 'not configured'}}}
