expected_output = {
    "eigrp_instance":{
        "10":{
            "vrf":{
                "red":{
                    "address_family":{
                        "IPv4":{
                            "eigrp_id":{
                                "10.169.0.2":{
                                    "eigrp_routes":{
                                        "10.169.0.0/16":{
                                            "route_code":"P",
                                            "successor_count":1,
                                            "FD":2816,
                                            "route_type":"Passive",
                                            "route":"10.169.0.0/16",
                                            "known_via":"Connected",
                                            "outgoing_interface":"GigabitEthernet0/0/0"
                                        },
                                        "10.36.3.3/32":{
                                            "route_code":"P",
                                            "successor_count":1,
                                            "FD":130816,
                                            "route_type":"Passive",
                                            "route":"10.36.3.3/32",
                                            "known_via":"10.169.0.1",
                                            "outgoing_interface":"GigabitEthernet0/0/0"
                                        },
                                        "10.4.1.1/32":{
                                            "route_code":"P",
                                            "successor_count":1,
                                            "FD":2816,
                                            "route_type":"Passive",
                                            "route":"10.4.1.1/32",
                                            "known_via":"Redistributed",
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}