expected_output = {
    "instance": {
        1: {
            "mtid": 0,
            "network": {
                "1.1.1.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.10.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.11.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.2.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.3.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.4.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.5.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.6.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.7.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.8.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
                "1.1.9.0/24": {
                    "interface": "Null0",
                    "metric": 16777214,
                    "origin": "static",
                    "tag": 0,
                    "type": 1,
                    "via_network": "None",
                },
            },
            "router_id": "2.2.2.2",
        },
        100: {
            "mtid": 0,
            "network": {
                "10.20.0.0/24": {
                    "interface": "GigabitEthernet0/0/1",
                    "metric": 20,
                    "origin": "connected",
                    "tag": 0,
                    "type": 2,
                    "via_network": "None",
                },
            },
            "router_id": "192.168.3.2",
        },
    },
}
