expected_output = {
    "rsvp-neighbor-information": {
        "rsvp-neighbor": [
            {
                "hello-interval": "9",
                "hellos-received": "0",
                "hellos-sent": "187",
                "last-changed-time": "27:54",
                "messages-received": "0",
                "neighbor-down-count": "0",
                "neighbor-idle": "27:55",
                "neighbor-up-count": "0",
                "rsvp-nbr-enh-local-protection": {"rsvp-nbr-enh-lp-status": "Disabled"},
                "rsvp-neighbor-address": "10.34.3.252",
                "rsvp-neighbor-local-instance": "0xf81317e",
                "rsvp-neighbor-node": True,
                "rsvp-neighbor-remote-instance": "0x0",
                "rsvp-neighbor-status": "Down",
                "rsvp-refresh-reduct-ack-status": "disabled",
                "rsvp-refresh-reduct-remote-status": "disabled",
                "rsvp-refresh-reduct-status": "not operational",
            },
            {
                "hello-interval": "9",
                "hellos-received": "0",
                "hellos-sent": "309",
                "last-changed-time": "46:15",
                "messages-received": "0",
                "neighbor-down-count": "0",
                "neighbor-idle": "46:15",
                "neighbor-up-count": "0",
                "rsvp-nbr-enh-local-protection": {"rsvp-nbr-enh-lp-status": "Disabled"},
                "rsvp-neighbor-address": "10.169.14.240",
                "rsvp-neighbor-local-instance": "0x1a61c152",
                "rsvp-neighbor-node": True,
                "rsvp-neighbor-remote-instance": "0x0",
                "rsvp-neighbor-status": "Down",
                "rsvp-refresh-reduct-ack-status": "disabled",
                "rsvp-refresh-reduct-remote-status": "disabled",
                "rsvp-refresh-reduct-status": "not operational",
            },
            {
                "hello-interval": "9",
                "hellos-received": "309",
                "hellos-sent": "310",
                "last-changed-time": "46:15",
                "messages-received": "695",
                "neighbor-down-count": "0",
                "neighbor-idle": "0",
                "neighbor-up-count": "1",
                "rsvp-nbr-enh-local-protection": {
                    "rsvp-nbr-enh-lp-nhop-lsp-count": "0",
                    "rsvp-nbr-enh-lp-nnhop-lsp-count": "0",
                    "rsvp-nbr-enh-lp-phop-lsp-count": "30",
                    "rsvp-nbr-enh-lp-pphop-lsp-count": "0",
                    "rsvp-nbr-enh-lp-status": "Enabled",
                    "rsvp-nbr-enh-lp-total-lsp-count": "30",
                },
                "rsvp-neighbor-address": "10.169.14.157",
                "rsvp-neighbor-interface": "ge-0/0/0.0",
                "rsvp-neighbor-local-instance": "0xb6ab962a",
                "rsvp-neighbor-node": True,
                "rsvp-neighbor-remote-instance": "0xe6740271",
                "rsvp-neighbor-status": "Up",
                "rsvp-refresh-reduct-ack-status": "enabled",
                "rsvp-refresh-reduct-remote-status": "enabled",
                "rsvp-refresh-reduct-status": "operational",
            },
            {
                "hello-interval": "9",
                "hellos-received": "183",
                "hellos-sent": "183",
                "last-changed-time": "27:57",
                "messages-received": "557",
                "neighbor-down-count": "0",
                "neighbor-idle": "0",
                "neighbor-up-count": "1",
                "rsvp-nbr-enh-local-protection": {
                    "rsvp-nbr-enh-lp-nhop-lsp-count": "30",
                    "rsvp-nbr-enh-lp-nnhop-lsp-count": "0",
                    "rsvp-nbr-enh-lp-phop-lsp-count": "0",
                    "rsvp-nbr-enh-lp-pphop-lsp-count": "0",
                    "rsvp-nbr-enh-lp-status": "Enabled",
                    "rsvp-nbr-enh-lp-total-lsp-count": "30",
                },
                "rsvp-neighbor-address": "192.168.145.218",
                "rsvp-neighbor-interface": "ge-0/0/1.1",
                "rsvp-neighbor-local-instance": "0x41ad0a42",
                "rsvp-neighbor-node": True,
                "rsvp-neighbor-remote-instance": "0xa1a75540",
                "rsvp-neighbor-status": "Up",
                "rsvp-refresh-reduct-ack-status": "enabled",
                "rsvp-refresh-reduct-remote-status": "enabled",
                "rsvp-refresh-reduct-status": "operational",
            },
        ],
        "rsvp-neighbor-count": "4",
    }
}
