expected_output = {
   "interface":{
      "HundredGigE1/1/1":{
         "domain":0,
         "state":"FAULTY"
      },
      "HundredGigE1/1/2":{
         "domain":0,
         "state":"FAULTY"
      },
      "HundredGigE1/1/3":{
         "domain":0,
         "state":"FAULTY"
      },
      "HundredGigE1/1/4":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/1":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/10":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/11":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/12":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/13":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/14":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/15":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/16":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/17":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/18":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/19":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/2":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/20":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/21":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/22":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/23":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/24":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/25":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/26":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/27":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/28":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/29":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/3":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/30":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/31":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/32":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/33":{
         "domain":0,
         "state":"MASTER"
      },
      "TenGigabitEthernet1/0/34":{
         "domain":0,
         "state":"MASTER"
      },
      "TenGigabitEthernet1/0/35":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/36":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/37":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/38":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/39":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/4":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/40":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/41":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/42":{
         "domain":0,
         "state":"MASTER"
      },
      "TenGigabitEthernet1/0/43":{
         "domain":0,
         "state":"MASTER"
      },
      "TenGigabitEthernet1/0/44":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/45":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/46":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/47":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/48":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/5":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/6":{
         "domain":0,
         "state":"MASTER"
      },
      "TenGigabitEthernet1/0/7":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/8":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/0/9":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/1/1":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/1/2":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/1/3":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/1/4":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/1/5":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/1/6":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/1/7":{
         "domain":0,
         "state":"FAULTY"
      },
      "TenGigabitEthernet1/1/8":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/1":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/10":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/11":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/12":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/13":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/14":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/15":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/16":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/2":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/3":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/4":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/5":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/6":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/7":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/8":{
         "domain":0,
         "state":"FAULTY"
      },
      "TwentyFiveGigE1/1/9":{
         "domain":0,
         "state":"FAULTY"
      }
   }
}
