expected_output = {
    "interface": {
        "TenGigabitEthernet2/0/1": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/2": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/3": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/4": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/5": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/6": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/7": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/8": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/9": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/10": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/11": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/12": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/13": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/14": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/15": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/16": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/17": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/18": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/19": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/20": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/21": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/22": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/23": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/24": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/25": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/26": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/27": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/28": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/29": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/30": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/31": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/32": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/33": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/34": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/35": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/36": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/37": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/38": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/39": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/40": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/41": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/42": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/43": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/44": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/45": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/46": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/47": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet2/0/48": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/1": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/2": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/3": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/4": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/5": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/6": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/7": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/8": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/9": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/10": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/11": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/12": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/13": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/14": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/15": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/16": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/17": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/18": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/19": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/20": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/21": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/22": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/23": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "GigabitEthernet3/0/24": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/25": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "static",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/26": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "static",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/27": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/28": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/29": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/30": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/31": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/32": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/33": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/34": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/35": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/36": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/37": {
            "cutoff_power": "n/a",
            "oper_power": "11.5",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/38": {
            "cutoff_power": "n/a",
            "oper_power": "20.2",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/39": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/40": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/41": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/42": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/43": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/44": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/45": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/46": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/47": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet3/0/48": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/1": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/2": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/3": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/4": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/5": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/6": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/7": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/8": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/9": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/10": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/11": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/12": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/13": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/14": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/15": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/16": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/17": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/18": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/19": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/20": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/21": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/22": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/23": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/24": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/25": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/26": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/27": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/28": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/29": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/30": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/31": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/32": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/33": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/34": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/35": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/36": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/37": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/38": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/39": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/40": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/41": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/42": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/43": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/44": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/45": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/46": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/47": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet4/0/48": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/1": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/2": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/3": {
            "cutoff_power": "n/a",
            "oper_power": "2.8",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/4": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/5": {
            "cutoff_power": "n/a",
            "oper_power": "2.8",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/6": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/7": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/8": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/9": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/10": {
            "cutoff_power": "n/a",
            "oper_power": "2.5",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/11": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/12": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/13": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/14": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/15": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/16": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/17": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/18": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/19": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/20": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/21": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/22": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/23": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/24": {
            "cutoff_power": "n/a",
            "oper_power": "2.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/25": {
            "cutoff_power": "n/a",
            "oper_power": "3.6",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/26": {
            "cutoff_power": "n/a",
            "oper_power": "6.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/27": {
            "cutoff_power": "n/a",
            "oper_power": "14.5",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/28": {
            "cutoff_power": "15.4",
            "oper_power": "16.2",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "log",
            "oper_police": "overdrawn",
        },
        "TenGigabitEthernet7/0/29": {
            "cutoff_power": "n/a",
            "oper_power": "3.8",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/30": {
            "cutoff_power": "n/a",
            "oper_power": "6.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/31": {
            "cutoff_power": "n/a",
            "oper_power": "14.7",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/32": {
            "cutoff_power": "n/a",
            "oper_power": "29.2",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/33": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/34": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/35": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/36": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/37": {
            "cutoff_power": "n/a",
            "oper_power": "20.2",
            "admin_state": "auto",
            "oper_state": "on",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/38": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/39": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/40": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/41": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/42": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/43": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/44": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/45": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/46": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/47": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet7/0/48": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/1": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/2": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/3": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/4": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/5": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/6": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/7": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/8": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/9": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/10": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/11": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/12": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/13": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/14": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/15": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/16": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/17": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/18": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/19": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/20": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/21": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/22": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/23": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/24": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/25": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/26": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/27": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/28": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/29": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/30": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/31": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/32": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/33": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/34": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/35": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/36": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/37": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/38": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/39": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/40": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/41": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/42": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/43": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/44": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/45": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/46": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/47": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
        "TenGigabitEthernet9/0/48": {
            "cutoff_power": "n/a",
            "oper_power": "n/a",
            "admin_state": "auto",
            "oper_state": "off",
            "admin_police": "none",
            "oper_police": "n/a",
        },
    },
    'totals': 212.7,
}
