

expected_output = {
    'pvst': {
        'a': {
            'pvst_id': 'a',
            'vlans': {
                2: {
                    'vlan_id': 2,
                    'designated_root_priority': 32768,
                    'designated_root_address': '0021.1bff.d973',
                    'designated_root_max_age': 20,
                    'designated_root_forward_delay': 15,
                    'bridge_priority': 32768,
                    'sys_id_ext': 0,
                    'bridge_address': '8cb6.4fff.6588',
                    'bridge_max_age': 20,
                    'bridge_forward_delay': 15,
                    'bridge_transmit_hold_count': 6,
                    'interface': {
                        'GigabitEthernet0/7/0/0': {
                            'name': 'GigabitEthernet0/7/0/0',
                            'cost': 20000,
                            'role': 'DSGN',
                            'port_priority': 128,
                            'port_num': 1,
                            'port_state': 'FWD',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '8cb6.4fff.6588',
                            'designated_port_priority': 128,
                            'designated_port_num': 1,
                            },
                        'GigabitEthernet0/7/0/1': {
                            'name': 'GigabitEthernet0/7/0/1',
                            'cost': 20000,
                            'role': 'DSGN',
                            'port_priority': 128,
                            'port_num': 2,
                            'port_state': 'FWD',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '8cb6.4fff.6588',
                            'designated_port_priority': 128,
                            'designated_port_num': 2,
                            },
                        'GigabitEthernet0/7/0/10': {
                            'name': 'GigabitEthernet0/7/0/10',
                            'cost': 20000,
                            'role': 'ROOT',
                            'port_priority': 128,
                            'port_num': 3,
                            'port_state': 'FWD',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '0021.1bff.d973',
                            'designated_port_priority': 128,
                            'designated_port_num': 3,
                            },
                        'GigabitEthernet0/7/0/11': {
                            'name': 'GigabitEthernet0/7/0/11',
                            'cost': 20000,
                            'role': 'ALT',
                            'port_priority': 128,
                            'port_num': 4,
                            'port_state': 'BLK',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '0021.1bff.d973',
                            'designated_port_priority': 128,
                            'designated_port_num': 4,
                            },
                        },
                    },
                3: {
                    'vlan_id': 3,
                    'designated_root_priority': 32768,
                    'designated_root_address': '0021.1bff.d973',
                    'designated_root_max_age': 20,
                    'designated_root_forward_delay': 15,
                    'bridge_priority': 32768,
                    'sys_id_ext': 0,
                    'bridge_address': '8cb6.4fff.6588',
                    'bridge_max_age': 20,
                    'bridge_forward_delay': 15,
                    'bridge_transmit_hold_count': 6,
                    'interface': {
                        'GigabitEthernet0/7/0/0': {
                            'name': 'GigabitEthernet0/7/0/0',
                            'cost': 20000,
                            'role': 'DSGN',
                            'port_priority': 128,
                            'port_num': 1,
                            'port_state': 'FWD',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '8cb6.4fff.6588',
                            'designated_port_priority': 128,
                            'designated_port_num': 1,
                            },
                        'GigabitEthernet0/7/0/1': {
                            'name': 'GigabitEthernet0/7/0/1',
                            'cost': 20000,
                            'role': 'DSGN',
                            'port_priority': 128,
                            'port_num': 2,
                            'port_state': 'FWD',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '8cb6.4fff.6588',
                            'designated_port_priority': 128,
                            'designated_port_num': 2,
                            },
                        'GigabitEthernet0/7/0/10': {
                            'name': 'GigabitEthernet0/7/0/10',
                            'cost': 20000,
                            'role': 'ROOT',
                            'port_priority': 128,
                            'port_num': 3,
                            'port_state': 'FWD',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '0021.1bff.d973',
                            'designated_port_priority': 128,
                            'designated_port_num': 3,
                            },
                        'GigabitEthernet0/7/0/11': {
                            'name': 'GigabitEthernet0/7/0/11',
                            'cost': 20000,
                            'role': 'ALT',
                            'port_priority': 128,
                            'port_num': 4,
                            'port_state': 'BLK',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '0021.1bff.d973',
                            'designated_port_priority': 128,
                            'designated_port_num': 4,
                            },
                        },
                    },
                4: {
                    'vlan_id': 4,
                    'designated_root_priority': 32768,
                    'designated_root_address': '0021.1bff.d973',
                    'designated_root_max_age': 20,
                    'designated_root_forward_delay': 15,
                    'bridge_priority': 32768,
                    'sys_id_ext': 0,
                    'bridge_address': '8cb6.4fff.6588',
                    'bridge_max_age': 20,
                    'bridge_forward_delay': 15,
                    'bridge_transmit_hold_count': 6,
                    'interface': {
                        'GigabitEthernet0/7/0/0': {
                            'name': 'GigabitEthernet0/7/0/0',
                            'cost': 20000,
                            'role': 'DSGN',
                            'port_priority': 128,
                            'port_num': 1,
                            'port_state': 'FWD',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '8cb6.4fff.6588',
                            'designated_port_priority': 128,
                            'designated_port_num': 1,
                            },
                        'GigabitEthernet0/7/0/1': {
                            'name': 'GigabitEthernet0/7/0/1',
                            'cost': 20000,
                            'role': 'DSGN',
                            'port_priority': 128,
                            'port_num': 2,
                            'port_state': 'FWD',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '8cb6.4fff.6588',
                            'designated_port_priority': 128,
                            'designated_port_num': 2,
                            },
                        'GigabitEthernet0/7/0/10': {
                            'name': 'GigabitEthernet0/7/0/10',
                            'cost': 20000,
                            'role': 'ROOT',
                            'port_priority': 128,
                            'port_num': 3,
                            'port_state': 'FWD',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '0021.1bff.d973',
                            'designated_port_priority': 128,
                            'designated_port_num': 3,
                            },
                        'GigabitEthernet0/7/0/11': {
                            'name': 'GigabitEthernet0/7/0/11',
                            'cost': 20000,
                            'role': 'ALT',
                            'port_priority': 128,
                            'port_num': 4,
                            'port_state': 'BLK',
                            'designated_bridge_priority': 32768,
                            'designated_bridge_address': '0021.1bff.d973',
                            'designated_port_priority': 128,
                            'designated_port_num': 4,
                            },
                        },
                    },
                },
            },
        },
    }
