expected_output = {
    'fantray': {
        'FT1': {
            'air_flow_direction': 'Port-Side-Intake',
            'auto_poll_interval': '2.0 Seconds',
            'auto_poll_status': 'true',
            'beacon_led': 'OFF',
            'control_mode': 'Manual',
            'input_current': '5.3333 A',
            'input_power': '63.8889 W',
            'input_voltage': '11.9792 V',
            'rows': {
                '1': {
                    'inlet_rpm': 5375,
                    'outlet_rpm': 5341,
                    'pwm': '35%',
                },
                '2': {
                    'inlet_rpm': 5355,
                    'outlet_rpm': 5326,
                    'pwm': '35%',
                },
                '3': {
                    'inlet_rpm': 5333,
                    'outlet_rpm': 5345,
                    'pwm': '35%',
                },
                '4': {
                    'inlet_rpm': 5416,
                    'outlet_rpm': 5370,
                    'pwm': '35%',
                },
                '5': {
                    'inlet_rpm': 5437,
                    'outlet_rpm': 5432,
                    'pwm': '35%',
                },
                '6': {
                    'inlet_rpm': 5426,
                    'outlet_rpm': 5357,
                    'pwm': '35%',
                },
            },
            'status_led': 'GREEN',
            'temperature_local_a': '32 C',
            'temperature_local_b': '31 C',
            'temperature_slot_5': '25 C',
            'temperature_slot_6': '23 C',
        },
        'FT2': {
            'air_flow_direction': 'Port-Side-Intake',
            'auto_poll_interval': '2.0 Seconds',
            'auto_poll_status': 'true',
            'beacon_led': 'OFF',
            'control_mode': 'Manual',
            'input_current': '5.5000 A',
            'input_power': '66.1806 W',
            'input_voltage': '12.0328 V',
            'rows': {
                '1': {
                    'inlet_rpm': 5306,
                    'outlet_rpm': 5303,
                    'pwm': '35%',
                },
                '2': {
                    'inlet_rpm': 5407,
                    'outlet_rpm': 5389,
                    'pwm': '35%',
                },
                '3': {
                    'inlet_rpm': 5386,
                    'outlet_rpm': 5432,
                    'pwm': '35%',
                },
                '4': {
                    'inlet_rpm': 5381,
                    'outlet_rpm': 5401,
                    'pwm': '35%',
                },
                '5': {
                    'inlet_rpm': 5462,
                    'outlet_rpm': 5437,
                    'pwm': '35%',
                },
                '6': {
                    'inlet_rpm': 5419,
                    'outlet_rpm': 5420,
                    'pwm': '35%',
                },
            },
            'status_led': 'GREEN',
            'temperature_local_a': '32 C',
            'temperature_local_b': '32 C',
            'temperature_slot_5': '25 C',
            'temperature_slot_6': '24 C',
        },
        'FT3': {
            'air_flow_direction': 'Port-Side-Intake',
            'auto_poll_interval': '2.0 Seconds',
            'auto_poll_status': 'true',
            'beacon_led': 'OFF',
            'control_mode': 'Manual',
            'input_current': '5.4167 A',
            'input_power': '64.9910 W',
            'input_voltage': '11.9983 V',
            'rows': {
                '1': {
                    'inlet_rpm': 5437,
                    'outlet_rpm': 5340,
                    'pwm': '35%',
                },
                '2': {
                    'inlet_rpm': 5290,
                    'outlet_rpm': 5404,
                    'pwm': '35%',
                },
                '3': {
                    'inlet_rpm': 5330,
                    'outlet_rpm': 5370,
                    'pwm': '35%',
                },
                '4': {
                    'inlet_rpm': 5429,
                    'outlet_rpm': 5409,
                    'pwm': '35%',
                },
                '5': {
                    'inlet_rpm': 5352,
                    'outlet_rpm': 5456,
                    'pwm': '35%',
                },
                '6': {
                    'inlet_rpm': 5400,
                    'outlet_rpm': 5420,
                    'pwm': '35%',
                },
            },
            'status_led': 'GREEN',
            'temperature_local_a': '30 C',
            'temperature_local_b': '31 C',
            'temperature_slot_5': '27 C',
            'temperature_slot_6': '25 C',
        },
        'FT4': {
            'air_flow_direction': 'Port-Side-Intake',
            'auto_poll_interval': '2.0 Seconds',
            'auto_poll_status': 'true',
            'beacon_led': 'OFF',
            'control_mode': 'Manual',
            'input_current': '5.2500 A',
            'input_power': '63.1522 W',
            'input_voltage': '12.0290 V',
            'rows': {
                '1': {
                    'inlet_rpm': 5415,
                    'outlet_rpm': 5359,
                    'pwm': '35%',
                },
                '2': {
                    'inlet_rpm': 5391,
                    'outlet_rpm': 5440,
                    'pwm': '35%',
                },
                '3': {
                    'inlet_rpm': 5393,
                    'outlet_rpm': 5400,
                    'pwm': '35%',
                },
                '4': {
                    'inlet_rpm': 5413,
                    'outlet_rpm': 5470,
                    'pwm': '35%',
                },
                '5': {
                    'inlet_rpm': 5418,
                    'outlet_rpm': 5491,
                    'pwm': '35%',
                },
                '6': {
                    'inlet_rpm': 5389,
                    'outlet_rpm': 5440,
                    'pwm': '35%',
                },
            },
            'status_led': 'GREEN',
            'temperature_local_a': '28 C',
            'temperature_local_b': '28 C',
            'temperature_slot_5': '25 C',
            'temperature_slot_6': '24 C',
        },
    },
}