expected_output = {
        'local': {'device_number': '2103',
                  'device_id': '21030000000000000000000000000000',
                  'role': 'Hub',
                  'local_wan': {'wan_1': {'interface': 'gi2',
                                          'nat_type': 'Friendly',
                                          'private_port': '4500',
                                          'private_ip': '10.10.10.3'},
                                'wan_2': {'interface': 'gi4',
                                          'nat_type': 'Friendly',
                                          'private_port': '4500',
                                          'private_ip': '11.11.11.3'}},
                  
                  'registry_1': {'ip': '10.124.22.98',
                                 'port': '9350',
                                 'wan_1': {'ip': '10.74.9.190',
                                           'port': '5062',
                                           'status': 'Connected'},
                                 'wan_2': {'ip': '10.74.9.190',
                                           'port': '5063',
                                         'status': 'Connected'}},
                  'registry_2': {'ip': '10.124.22.98',
                                 'port': '9351',
                                 'wan_1': {'ip': '10.74.9.190',
                                           'port': '5062',
                                           'status': 'Connected'},
                                 'wan_2': {'ip': '10.74.9.190',
                                           'port': '5063',
                                           'status': 'Connected'}}},
        'session': {}}
