expected_output = {
    "list_of_neighbors": ["192.168.10.253"],
    "vrf": {
        "CE1test": {
            "neighbor": {
                "192.168.10.253": {
                    "remote_as": 65555,
                    "link": "external",
                    "shutdown": False,
                    "bgp_version": 4,
                    "router_id": "192.168.10.253",
                    "session_state": "Closing",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 90,
                        "keepalive_interval": 30,
                        "min_holdtime": 15,
                    },
                    "bgp_neighbor_session": {
                        "sessions": 0,
                        "stateful_switchover": "NO for session 0, 0",
                    },
                    "bgp_neighbor_counters": {
                        "multisession_messages": {
                            "192.168.10.253 active": {
                                "sent": {
                                    "opens": 1,
                                    "notifications": 1,
                                    "updates": 0,
                                    "keepalives": 0,
                                    "route_refresh": 0,
                                    "total": 2,
                                },
                                "received": {
                                    "opens": 1,
                                    "notifications": 0,
                                    "updates": 0,
                                    "keepalives": 0,
                                    "route_refresh": 0,
                                    "total": 2,
                                },
                                "in_queue_depth": 0,
                                "out_queue_depth": 0,
                            },
                            "192.168.10.253 passive": {
                                "sent": {
                                    "opens": 0,
                                    "notifications": 1,
                                    "updates": 0,
                                    "keepalives": 0,
                                    "route_refresh": 0,
                                    "total": 1,
                                },
                                "received": {
                                    "opens": 1,
                                    "notifications": 0,
                                    "updates": 0,
                                    "keepalives": 0,
                                    "route_refresh": 0,
                                    "total": 1,
                                },
                                "in_queue_depth": 0,
                                "out_queue_depth": 0,
                            },
                        }
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 0,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "192.168.10.253",
                        "connection": {
                            "established": 0,
                            "dropped": 0,
                            "last_reset": "never",
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "enabled",
                        "gr_restart_time": 120,
                        "gr_stalepath_time": 360,
                        "sso": False,
                        "connection_state": "closewait",
                        "io_status": 1,
                        "unread_input_bytes": 0,
                        "ecn_connection": "disabled",
                        "minimum_incoming_ttl": 0,
                        "outgoing_ttl": 1,
                        "transport": {
                            "local_host": "192.168.10.254",
                            "local_port": "26883",
                            "foreign_host": "192.168.10.253",
                            "foreign_port": "179",
                            "mss": 1460,
                        },
                        "connection_tableid": 1,
                        "maximum_output_segment_queue_size": 50,
                        "enqueued_packets": {
                            "retransmit_packet": 0,
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                        },
                        "iss": 168450936,
                        "snduna": 168451027,
                        "sndnxt": 168451027,
                        "irs": 3682975333,
                        "rcvnxt": 3682975411,
                        "sndwnd": 16294,
                        "snd_scale": 0,
                        "maxrcvwnd": 16384,
                        "rcvwnd": 16308,
                        "rcv_scale": 0,
                        "delrcvwnd": 76,
                        "srtt": 330,
                        "rtto": 3159,
                        "rtv": 2829,
                        "krtt": 0,
                        "min_rtt": 3,
                        "max_rtt": 1000,
                        "ack_hold": 200,
                        "uptime": 3222,
                        "sent_idletime": 3177,
                        "receive_idletime": 3178,
                        "status_flags": "active open",
                        "option_flags": "VRF id set, nagle, path mtu capable",
                        "ip_precedence_value": 6,
                        "datagram": {
                            "datagram_received": {
                                "value": 5,
                                "out_of_order": 0,
                                "with_data": 2,
                                "total_data": 76,
                            },
                            "datagram_sent": {
                                "value": 6,
                                "retransmit": 0,
                                "fastretransmit": 0,
                                "partialack": 0,
                                "second_congestion": 0,
                                "with_data": 2,
                                "total_data": 90,
                            },
                        },
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "fast_lock_acquisition_failures": 0,
                        "lock_slow_path": 0,
                        "tcp_semaphore": "0x7F2C7331EBC8",
                        "tcp_semaphore_status": "FREE",
                    },
                    "address_family": {
                        "vpnv4 unicast": {
                            "bgp_table_version": 239,
                            "neighbor_version": "1/239",
                            "output_queue_size": 0,
                            "index": 0,
                            "advertise_bit": 0,
                            "slow_peer_detection": False,
                            "slow_peer_split_update_group_dynamic": False,
                            "prefix_activity_counters": {
                                "sent": {
                                    "prefixes_current": 0,
                                    "prefixes_total": 0,
                                    "implicit_withdraw": 0,
                                    "explicit_withdraw": 0,
                                    "used_as_bestpath": "n/a",
                                    "used_as_multipath": "n/a",
                                    "used_as_secondary": "n/a",
                                },
                                "received": {
                                    "prefixes_current": 0,
                                    "prefixes_total": 0,
                                    "implicit_withdraw": 0,
                                    "explicit_withdraw": 0,
                                    "used_as_bestpath": 0,
                                    "used_as_multipath": 0,
                                    "used_as_secondary": 0,
                                },
                            },
                            "local_policy_denied_prefixes_counters": {
                                "outbound": {"total": 0},
                                "inbound": {"total": 0},
                            },
                            "max_nlri": 0,
                            "min_nlri": 0,
                            "last_detected_dynamic_slow_peer": "never",
                            "dynamic_slow_peer_recovered": "never",
                            "refresh_epoch": 1,
                            "last_sent_refresh_start_of_rib": "never",
                            "last_sent_refresh_end_of_rib": "never",
                            "last_received_refresh_start_of_rib": "never",
                            "last_received_refresh_end_of_rib": "never",
                            "refresh_activity_counters": {
                                "sent": {
                                    "refresh_start_of_rib": 0,
                                    "refresh_end_of_rib": 0,
                                },
                                "received": {
                                    "refresh_start_of_rib": 0,
                                    "refresh_end_of_rib": 0,
                                },
                            },
                            "current_time": "0x65B4C8",
                        }
                    },
                    "bgp_event_timer": {
                        "starts": {
                            "retrans": 3,
                            "timewait": 0,
                            "ackhold": 2,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "wakeups": {
                            "retrans": 0,
                            "timewait": 0,
                            "ackhold": 0,
                            "sendwnd": 0,
                            "keepalive": 0,
                            "giveup": 0,
                            "deadwait": 0,
                            "linger": 0,
                            "processq": 0,
                        },
                        "next": {
                            "retrans": "0x0",
                            "timewait": "0x0",
                            "ackhold": "0x0",
                            "sendwnd": "0x0",
                            "keepalive": "0x0",
                            "giveup": "0x0",
                            "deadwait": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                        },
                    },
                }
            }
        }
    },
}
