expected_output = {'ca-statistics': {'group-caks-generated': 0,
                   'group-caks-received': 0,
                   'pairwaise-cak-rekeys': 0,
                   'pairwise-caks-derived': 0},
 'deleted-secured': 1,
 'keepalive-timeouts': 0,
 'mka-error-counters': {'ca-failures': {'ckn-derivation': 0,
                                        'group-cak-decryption-unwrap': 0,
                                        'group-cak-encryption-wrap': 0,
                                        'group-sak-generation': 0,
                                        'ick-derivation': 0,
                                        'invalid-peer-macsec-capability': 0,
                                        'kek-derivation': 0,
                                        'pairwise-cak-derivation': 0},
                        'macsec-failures': {'rx-sa-installation': 0,
                                            'rx-sc-creation': 0,
                                            'tx-sa-installation': 1,
                                            'tx-sc-creation': 0},
                        'mkpdu-failures': {'mkpdu-rx-bad-peer-mn': 0,
                                           'mkpdu-rx-icv-verification': 0,
                                           'mkpdu-rx-nonrecent-peerlist-mn': 0,
                                           'mkpdu-rx-validation': 0,
                                           'mkpdu_tx': 0},
                        'sak-failures': {'hash-key-generation': 0,
                                         'sak-cipher-mismatch': 0,
                                         'sak-decryption-unwrap': 0,
                                         'sak-encryption-wrap': 0,
                                         'sak-generation': 0},
                        'session-failures': {'bringup-failures': 0,
                                             'duplicate-auth-mgr-handle': 0,
                                             'reauthentication-failures': 0}},
 'mkpdu-statistics': {'mkpdu-received': {'distributed-cak': 0,
                                         'distributed-sak': 4},
                      'mkpdu-transmitted': {'distributed-cak': 0,
                                            'distributed-sak': 1},
                      'mkpdus-transmitted': 337219,
                      'mkpdus-validated-received': 674402},
 'reauthentication-attempts': 0,
 'sa-statistics': {'sak-responses-received': 1,
                   'saks-generated': 1,
                   'saks-received': 4,
                   'saks-rekeyed': 1},
 'secured': 2,
 'sessions': {1: {'ckn': '1000000000000000000000000000000000000000000000000000000000000000',
                  'inherited': 'NO',
                  'interface': 'Hu1/0/25.25',
                  'key-server': 'NO',
                  'local-txsci': 'ecce.1346.f902/0494',
                  'macsec-peers': '2',
                  'peer-rxsci': 'a80c.0dee.d400/001a',
                  'policy-name': '*DEFAULT POLICY*',
                  'port-id': '1172',
                  'status': 'Secured'},
              'pending-mka-sessions': 0,
              'secured-mka-sessions': 1,
              'total-mka-sessions': 1}}
