expected_output = {
    "rapid_pvst": {
        "forwarding_delay": 15,
        "hello_time": 2,
        "hold_count": 6,
        "max_age": 20,
        "vlans": {
            1: {
                "aging_timer": 480,
                "bridge_address": "000e.39ff.71a2",
                "bridge_priority": 24576,
                "bridge_sysid": 1,
                "forwarding_delay": 15,
                "hello_time": 2,
                "hello_timer": 0,
                "hold_count": 6,
                "hold_time": 1,
                "interfaces": {
                    "Port-channel220": {
                        "cost": 1,
                        "counters": {"bpdu_received": 0, "bpdu_sent": 20120147},
                        "designated_bridge_address": "000e.39ff.71a2",
                        "designated_bridge_priority": 24577,
                        "designated_path_cost": 0,
                        "designated_port_id": "128.1671",
                        "designated_root_address": "000e.39ff.71a2",
                        "designated_root_priority": 24577,
                        "forward_delay": 0,
                        "hold": 0,
                        "link_type": "point-to-point",
                        "message_age": 0,
                        "name": "Port-channel220",
                        "number_of_forward_transitions": 1,
                        "port_identifier": "128.1671.",
                        "port_num": 1671,
                        "port_priority": 128,
                        "status": "designated forwarding",
                    },
                    "Port-channel265": {
                        "cost": 3,
                        "counters": {"bpdu_received": 0, "bpdu_sent": 21320048},
                        "designated_bridge_address": "000e.39ff.71a2",
                        "designated_bridge_priority": 24577,
                        "designated_path_cost": 0,
                        "designated_port_id": "128.1673",
                        "designated_root_address": "000e.39ff.71a2",
                        "designated_root_priority": 24577,
                        "forward_delay": 0,
                        "hold": 0,
                        "link_type": "point-to-point",
                        "message_age": 0,
                        "name": "Port-channel265",
                        "number_of_forward_transitions": 1,
                        "port_identifier": "128.1673.",
                        "port_num": 1673,
                        "port_priority": 128,
                        "status": "designated forwarding",
                    },
                },
                "max_age": 20,
                "notification_timer": 0,
                "notification_times": 2,
                "root_of_spanning_tree": True,
                "time_since_topology_change": "38w1d",
                "topology_change_flag": False,
                "topology_change_timer": 0,
                "topology_change_times": 35,
                "topology_changes": 10,
                "topology_detected_flag": False,
                "topology_from_port": "GigabitEthernet8/10",
                "vlan_id": 1,
            },
            115: {
                "aging_timer": 480,
                "bridge_address": "000e.39ff.71a2",
                "bridge_priority": 24576,
                "bridge_sysid": 115,
                "forwarding_delay": 15,
                "hello_time": 2,
                "hello_timer": 0,
                "hold_count": 6,
                "hold_time": 1,
                "interfaces": {
                    "Port-channel210": {
                        "cost": 2,
                        "counters": {"bpdu_received": 4, "bpdu_sent": 10172865},
                        "designated_bridge_address": "000e.39ff.71a2",
                        "designated_bridge_priority": 24691,
                        "designated_path_cost": 0,
                        "designated_port_id": "128.1670",
                        "designated_root_address": "000e.39ff.71a2",
                        "designated_root_priority": 24691,
                        "forward_delay": 0,
                        "hold": 0,
                        "link_type": "point-to-point",
                        "message_age": 0,
                        "name": "Port-channel210",
                        "number_of_forward_transitions": 1,
                        "port_identifier": "128.1670.",
                        "port_num": 1670,
                        "port_priority": 128,
                        "status": "designated forwarding",
                    }
                },
                "max_age": 20,
                "notification_timer": 0,
                "notification_times": 2,
                "root_of_spanning_tree": True,
                "time_since_topology_change": "33w6d",
                "topology_change_flag": False,
                "topology_change_timer": 0,
                "topology_change_times": 35,
                "topology_changes": 2,
                "topology_detected_flag": False,
                "topology_from_port": "Port-channel210",
                "vlan_id": 115,
            },
            116: {
                "aging_timer": 480,
                "bridge_address": "000e.39ff.71a2",
                "bridge_priority": 24576,
                "bridge_sysid": 116,
                "forwarding_delay": 15,
                "hello_time": 2,
                "hello_timer": 0,
                "hold_count": 6,
                "hold_time": 1,
                "interfaces": {
                    "Port-channel210": {
                        "cost": 2,
                        "counters": {"bpdu_received": 4, "bpdu_sent": 10172829},
                        "designated_bridge_address": "000e.39ff.71a2",
                        "designated_bridge_priority": 24692,
                        "designated_path_cost": 0,
                        "designated_port_id": "128.1670",
                        "designated_root_address": "000e.39ff.71a2",
                        "designated_root_priority": 24692,
                        "forward_delay": 0,
                        "hold": 0,
                        "link_type": "point-to-point",
                        "message_age": 0,
                        "name": "Port-channel210",
                        "number_of_forward_transitions": 1,
                        "port_identifier": "128.1670.",
                        "port_num": 1670,
                        "port_priority": 128,
                        "status": "designated forwarding",
                    }
                },
                "max_age": 20,
                "notification_timer": 0,
                "notification_times": 2,
                "root_of_spanning_tree": True,
                "time_since_topology_change": "33w6d",
                "topology_change_flag": False,
                "topology_change_timer": 0,
                "topology_change_times": 35,
                "topology_changes": 2,
                "topology_detected_flag": False,
                "topology_from_port": "Port-channel210",
                "vlan_id": 116,
            },
            118: {
                "aging_timer": 480,
                "bridge_address": "000e.39ff.71a2",
                "bridge_priority": 24576,
                "bridge_sysid": 118,
                "forwarding_delay": 15,
                "hello_time": 2,
                "hello_timer": 0,
                "hold_count": 6,
                "hold_time": 1,
                "interfaces": {
                    "Port-channel210": {
                        "cost": 2,
                        "counters": {"bpdu_received": 4, "bpdu_sent": 10172791},
                        "designated_bridge_address": "000e.39ff.71a2",
                        "designated_bridge_priority": 24694,
                        "designated_path_cost": 0,
                        "designated_port_id": "128.1670",
                        "designated_root_address": "000e.39ff.71a2",
                        "designated_root_priority": 24694,
                        "forward_delay": 0,
                        "hold": 0,
                        "link_type": "point-to-point",
                        "message_age": 0,
                        "name": "Port-channel210",
                        "number_of_forward_transitions": 1,
                        "port_identifier": "128.1670.",
                        "port_num": 1670,
                        "port_priority": 128,
                        "status": "designated forwarding",
                    }
                },
                "max_age": 20,
                "notification_timer": 0,
                "notification_times": 2,
                "root_of_spanning_tree": True,
                "time_since_topology_change": "33w6d",
                "topology_change_flag": False,
                "topology_change_timer": 0,
                "topology_change_times": 35,
                "topology_changes": 2,
                "topology_detected_flag": False,
                "topology_from_port": "Port-channel210",
                "vlan_id": 118,
            },
        },
    }
}
