expected_output = {
    "rapid_pvst": {
        "forwarding_delay": 15,
        "vlans": {
            201: {
                "forwarding_delay": 15,
                "hello_timer": 0,
                "bridge_sysid": 201,
                "hold_time": 1,
                "time_since_topology_change": "00:00:14",
                "notification_timer": 0,
                "topology_change_flag": True,
                "topology_changes": 1,
                "topology_change_times": 35,
                "aging_timer": 300,
                "topology_from_port": "Port-channel14",
                "topology_change_timer": 21,
                "bridge_address": "ecbd.1dff.5f89",
                "notification_times": 2,
                "bridge_priority": 28672,
                "topology_detected_flag": False,
                "hello_time": 2,
                "interfaces": {
                    "GigabitEthernet1/0/5": {
                        "designated_bridge_address": "ecbd.1dff.5f89",
                        "number_of_forward_transitions": 1,
                        "port_identifier": "128.5.",
                        "counters": {"bpdu_received": 4, "bpdu_sent": 20},
                        "cost": 4,
                        "designated_port_id": "128.5",
                        "designated_root_priority": 24777,
                        "designated_root_address": "58bf.eaff.e5b6",
                        "port_num": 5,
                        "status": "designated forwarding",
                        "port_priority": 128,
                        "forward_delay": 0,
                        "hold": 0,
                        "message_age": 0,
                        "peer": "STP",
                        "link_type": "point-to-point",
                        "designated_bridge_priority": 28873,
                        "designated_path_cost": 3,
                        "name": "GigabitEthernet1/0/5",
                    }
                },
                "max_age": 20,
                "hold_count": 6,
                "vlan_id": 201,
            },
            100: {
                "forwarding_delay": 15,
                "hello_timer": 0,
                "bridge_sysid": 100,
                "hold_time": 1,
                "time_since_topology_change": "00:00:34",
                "notification_timer": 0,
                "hello_time": 2,
                "topology_change_flag": True,
                "topology_changes": 1,
                "notification_times": 2,
                "aging_timer": 300,
                "topology_from_port": "Port-channel12",
                "topology_change_timer": 0,
                "bridge_address": "3820.56ff.76db",
                "topology_change_times": 35,
                "bridge_priority": 24576,
                "topology_detected_flag": False,
                "root_of_spanning_tree": True,
                "interfaces": {
                    "Port-channel12": {
                        "designated_bridge_address": "3820.56ff.76db",
                        "number_of_forward_transitions": 1,
                        "port_identifier": "128.2388.",
                        "counters": {"bpdu_received": 0, "bpdu_sent": 34},
                        "cost": 3,
                        "designated_port_id": "128.2388",
                        "designated_root_priority": 24676,
                        "designated_root_address": "3820.56ff.76db",
                        "port_num": 2388,
                        "status": "designated forwarding",
                        "port_priority": 128,
                        "forward_delay": 0,
                        "hold": 0,
                        "message_age": 0,
                        "link_type": "point-to-point",
                        "designated_bridge_priority": 24676,
                        "designated_path_cost": 0,
                        "name": "Port-channel12",
                    }
                },
                "max_age": 20,
                "hold_count": 6,
                "vlan_id": 100,
            },
        },
        "max_age": 20,
        "hold_count": 6,
        "hello_time": 2,
    }
}
