expected_output = {
    "switch": {
        "1": {
            "fantray_idprom": {
                "0": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NNF",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "1": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NNZ",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "2": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NUD",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "3": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NP1",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "4": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NSL",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "5": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NND",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
            },
            "module_idprom": {
                "1": {
                    "base_mac_address": "28 AF FD BE 94 00",
                    "board_revision": "14",
                    "clei_code": "TBD",
                    "controller_type": "4371",
                    "deviation_number": 0,
                    "environment_monitor_data": "06 00 00 00 0C 30 C3 00",
                    "hardware_revision": "0.2",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "max_power_requirement_watts": 195,
                    "pcb_part_number": "73-19902-02",
                    "pcb_serial_number": "FDO25130VES",
                    "pid": "C9500X-28C8D",
                    "rma_history": "00",
                    "rma_number": "0-0-0-0",
                    "rma_test_history": "00",
                    "top_assy_part_number": "68-103001-01",
                    "top_assy_revision": "10",
                    "typical_power_requirement_watts": 195,
                    "vid": "V00",
                }
            },
            "power_supply_idprom": {
                "0": {
                    "clei_code": "TBD",
                    "controller_type": "4376",
                    "deviation_number": 0,
                    "environment_monitor_data": "02 00 5D C5 DC 00 00",
                    "field_diagnostics_data": "00 00 00 00 00 00 00 00",
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "max_power_output_watts": 1500,
                    "pcb_serial_number": "QCS25146109",
                    "pid": "C9K-PWR-1500WAC-R",
                    "rma_history": "00",
                    "rma_number": "0-0-0-0",
                    "rma_test_history": "00",
                    "top_assy_part_number": "341-101195-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "1": {
                    "clei_code": "TBD",
                    "controller_type": "4376",
                    "deviation_number": 0,
                    "environment_monitor_data": "02 00 5D C5 DC 00 00",
                    "field_diagnostics_data": "00 00 00 00 00 00 00 00",
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "max_power_output_watts": 1500,
                    "pcb_serial_number": "QCS25146111",
                    "pid": "C9K-PWR-1500WAC-R",
                    "rma_history": "00",
                    "rma_number": "0-0-0-0",
                    "rma_test_history": "00",
                    "top_assy_part_number": "341-101195-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
            },
        },
        "2": {
            "fantray_idprom": {
                "0": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NSW",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "1": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NU1",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "2": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NVM",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "3": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NTB",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "4": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NSP",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "5": {
                    "clei_code": "TBD",
                    "controller_type": "4421",
                    "deviation_number": 0,
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "pcb_serial_number": "ACI25140NRM",
                    "pid": "C9K-FAN-1U-R",
                    "top_assy_part_number": "800-107500-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
            },
            "module_idprom": {
                "1": {
                    "base_mac_address": "F8 7A 41 37 C8 00",
                    "board_revision": "14",
                    "clei_code": "TBD",
                    "controller_type": "4371",
                    "deviation_number": 0,
                    "environment_monitor_data": "06 00 00 00 0C 30 C3 00",
                    "hardware_revision": "0.2",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "max_power_requirement_watts": 195,
                    "pcb_part_number": "73-19902-02",
                    "pcb_serial_number": "FDO25130VEP",
                    "pid": "C9500X-28C8D",
                    "rma_history": "00",
                    "rma_number": "0-0-0-0",
                    "rma_test_history": "00",
                    "top_assy_part_number": "68-103001-01",
                    "top_assy_revision": "10",
                    "typical_power_requirement_watts": 195,
                    "vid": "V00",
                }
            },
            "power_supply_idprom": {
                "0": {
                    "clei_code": "TBD",
                    "controller_type": "4376",
                    "deviation_number": 0,
                    "environment_monitor_data": "02 00 5D C5 DC 00 00",
                    "field_diagnostics_data": "00 00 00 00 00 00 00 00",
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "max_power_output_watts": 1500,
                    "pcb_serial_number": "QCS2514611W",
                    "pid": "C9K-PWR-1500WAC-R",
                    "rma_history": "00",
                    "rma_number": "0-0-0-0",
                    "rma_test_history": "00",
                    "top_assy_part_number": "341-101195-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
                "1": {
                    "clei_code": "TBD",
                    "controller_type": "4376",
                    "deviation_number": 0,
                    "environment_monitor_data": "02 00 5D C5 DC 00 00",
                    "field_diagnostics_data": "00 00 00 00 00 00 00 00",
                    "hardware_revision": "0.1",
                    "manufacturing_test_data": "00 00 00 00 00 00 00 00",
                    "max_power_output_watts": 1500,
                    "pcb_serial_number": "QCS25146173",
                    "pid": "C9K-PWR-1500WAC-R",
                    "rma_history": "00",
                    "rma_number": "0-0-0-0",
                    "rma_test_history": "00",
                    "top_assy_part_number": "341-101195-01",
                    "top_assy_revision": "01",
                    "vid": "V00",
                },
            },
        },
    }
}
