expected_output ={
   'lisp_id':{
      0:{
         'instance_id':{
            5000:{
               'eid_table':{
                  'vrf internet':{
                     'eid_prefix':{
                        '51.51.0.0/16':{
                           'eid':'51.51.0.0',
                           'mask':'16',
                           'first_published':'10:24:38',
                           'last_published':'10:24:36',
                           'exported_to':[
                              'local-eid'
                           ],
                           'publishers':{
                              '100.78.78.78':{
                                 'port':4342,
                                 'last_published':'10:24:36',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified'
                              },
                              '100.77.77.77':{
                                 'port':4342,
                                 'last_published':'10:24:38',
                                 'ttl':'never,',
                                 'expires':'never',
                                 'epoch':{
                                    'publisher':0,
                                    'entry':0
                                 },
                                 'entry_state':'unknown',
                                 'xtr_id':'unspecified',
                                 'domain_id':'extranet',
                                 'multihoming_id':'unspecified'
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}