expected_output = {
    "list_of_neighbors": ["10.1.1.1", "10.2.2.2", "172.17.111.2", "172.17.211.2"],
    "vrf": {
        "VRF100": {
            "neighbor": {
                "172.17.111.2": {
                    "address_family": {
                        "vpnv4 unicast": {
                            "advertise_bit": 0,
                            "bgp_table_version": 21,
                            "current_time": "0x197E192D",
                            "dynamic_slow_peer_recovered": "never",
                            "index": 1,
                            "last_detected_dynamic_slow_peer": "never",
                            "last_read": "00:00:18",
                            "last_received_refresh_end_of_rib": "never",
                            "last_received_refresh_start_of_rib": "never",
                            "last_sent_refresh_end_of_rib": "never",
                            "last_sent_refresh_start_of_rib": "never",
                            "last_write": "00:00:46",
                            "local_policy_denied_prefixes_counters": {
                                "inbound": {
                                    "bestpath_from_this_peer": "n/a",
                                    "total": 0,
                                },
                                "outbound": {"bestpath_from_this_peer": 2, "total": 2},
                            },
                            "max_nlri": 1,
                            "min_nlri": 0,
                            "neighbor_version": "21/0",
                            "output_queue_size": 0,
                            "prefix_activity_counters": {
                                "received": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 0,
                                    "prefixes_current": 1,
                                    "prefixes_total": 1,
                                    "used_as_bestpath": 1,
                                    "used_as_multipath": 0,
                                    "used_as_secondary": 0,
                                },
                                "sent": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 3,
                                    "prefixes_current": 3,
                                    "prefixes_total": 6,
                                    "used_as_bestpath": "n/a",
                                    "used_as_multipath": "n/a",
                                    "used_as_secondary": "n/a",
                                },
                            },
                            "refresh_activity_counters": {
                                "received": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                                "sent": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                            },
                            "refresh_epoch": 1,
                            "session_state": "Established",
                            "slow_peer_detection": False,
                            "slow_peer_split_update_group_dynamic": False,
                            "up_time": "4d22h",
                            "update_group_member": 1,
                        }
                    },
                    "bgp_event_timer": {
                        "next": {
                            "ackhold": "0x0",
                            "deadwait": "0x0",
                            "giveup": "0x0",
                            "keepalive": "0x0",
                            "linger": "0x0",
                            "pmtuager": "0x0",
                            "processq": "0x0",
                            "retrans": "0x0",
                            "sendwnd": "0x0",
                            "timewait": "0x0",
                        },
                        "starts": {
                            "ackhold": 7837,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 0,
                            "processq": 0,
                            "retrans": 7842,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                        "wakeups": {
                            "ackhold": 7720,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 0,
                            "processq": 0,
                            "retrans": 1,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "enhanced_refresh": "advertised and received",
                        "four_octets_asn": "advertised and received",
                        "ipv4_unicast": "advertised and received",
                        "route_refresh": "advertised and received(new)",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                            "received": {
                                "keepalives": 7835,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7838,
                                "updates": 2,
                            },
                            "sent": {
                                "keepalives": 7835,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7843,
                                "updates": 7,
                            },
                        }
                    },
                    "bgp_session_transport": {
                        "ack_hold": 200,
                        "address_tracking_status": "enabled",
                        "connection": {
                            "dropped": 0,
                            "established": 1,
                            "last_reset": "never",
                        },
                        "connection_state": "estab",
                        "connection_tableid": 1,
                        "datagram": {
                            "datagram_received": {
                                "out_of_order": 0,
                                "total_data": 148999,
                                "value": 15638,
                                "with_data": 7837,
                            },
                            "datagram_sent": {
                                "fastretransmit": 0,
                                "partialack": 0,
                                "retransmit": 1,
                                "second_congestion": 0,
                                "total_data": 149249,
                                "value": 15664,
                                "with_data": 7841,
                            },
                        },
                        "delrcvwnd": 1235,
                        "ecn_connection": "disabled",
                        "enqueued_packets": {
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                            "retransmit_packet": 0,
                        },
                        "fast_lock_acquisition_failures": 0,
                        "graceful_restart": "disabled",
                        "io_status": 1,
                        "ip_precedence_value": 6,
                        "irs": 3629657489,
                        "iss": 3636194669,
                        "krtt": 0,
                        "lock_slow_path": 0,
                        "max_rtt": 1000,
                        "maximum_output_segment_queue_size": 50,
                        "maxrcvwnd": 16384,
                        "min_rtt": 1,
                        "min_time_between_advertisement_runs": 0,
                        "minimum_incoming_ttl": 0,
                        "option_flags": "VRF id set, nagle, path mtu capable",
                        "outgoing_ttl": 1,
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "rcv_scale": 0,
                        "rcvnxt": 3629806489,
                        "rcvwnd": 15149,
                        "receive_idletime": 18940,
                        "rib_route_ip": "172.17.111.2",
                        "rtto": 1003,
                        "rtv": 3,
                        "sent_idletime": 18740,
                        "snd_scale": 0,
                        "sndnxt": 3636343919,
                        "snduna": 3636343919,
                        "sndwnd": 16365,
                        "srtt": 1000,
                        "sso": False,
                        "status_flags": "passive open, gen tcbs",
                        "tcp_path_mtu_discovery": "enabled",
                        "tcp_semaphore": "0x7F59978AAF50",
                        "tcp_semaphore_status": "FREE",
                        "transport": {
                            "foreign_host": "172.17.111.2",
                            "foreign_port": "14223",
                            "local_host": "172.17.111.1",
                            "local_port": "179",
                            "mss": 1460,
                        },
                        "unread_input_bytes": 0,
                        "uptime": 427542926,
                    },
                    "bgp_version": 4,
                    "link": "external",
                    "remote_as": 65001,
                    "router_id": "172.16.1.156",
                    "session_state": "Established",
                    "shutdown": False,
                }
            }
        },
        "VRF200": {
            "neighbor": {
                "172.17.211.2": {
                    "address_family": {
                        "vpnv4 unicast": {
                            "advertise_bit": 0,
                            "bgp_table_version": 21,
                            "current_time": "0x197E19C1",
                            "dynamic_slow_peer_recovered": "never",
                            "index": 2,
                            "last_detected_dynamic_slow_peer": "never",
                            "last_read": "00:00:00",
                            "last_received_refresh_end_of_rib": "never",
                            "last_received_refresh_start_of_rib": "never",
                            "last_sent_refresh_end_of_rib": "never",
                            "last_sent_refresh_start_of_rib": "never",
                            "last_write": "00:00:45",
                            "local_policy_denied_prefixes_counters": {
                                "inbound": {
                                    "bestpath_from_this_peer": "n/a",
                                    "total": 0,
                                },
                                "outbound": {"bestpath_from_this_peer": 2, "total": 2},
                            },
                            "max_nlri": 1,
                            "min_nlri": 0,
                            "neighbor_version": "21/0",
                            "output_queue_size": 0,
                            "prefix_activity_counters": {
                                "received": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 0,
                                    "prefixes_current": 1,
                                    "prefixes_total": 1,
                                    "used_as_bestpath": 1,
                                    "used_as_multipath": 0,
                                    "used_as_secondary": 0,
                                },
                                "sent": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 3,
                                    "prefixes_current": 3,
                                    "prefixes_total": 6,
                                    "used_as_bestpath": "n/a",
                                    "used_as_multipath": "n/a",
                                    "used_as_secondary": "n/a",
                                },
                            },
                            "refresh_activity_counters": {
                                "received": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                                "sent": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                            },
                            "refresh_epoch": 1,
                            "session_state": "Established",
                            "slow_peer_detection": False,
                            "slow_peer_split_update_group_dynamic": False,
                            "up_time": "4d22h",
                            "update_group_member": 2,
                        }
                    },
                    "bgp_event_timer": {
                        "next": {
                            "ackhold": "0x0",
                            "deadwait": "0x0",
                            "giveup": "0x0",
                            "keepalive": "0x0",
                            "linger": "0x0",
                            "processq": "0x0",
                            "retrans": "0x0",
                            "sendwnd": "0x0",
                            "timewait": "0x0",
                        },
                        "starts": {
                            "ackhold": 7835,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "processq": 0,
                            "retrans": 7847,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                        "wakeups": {
                            "ackhold": 7721,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "processq": 0,
                            "retrans": 1,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "enhanced_refresh": "advertised and received",
                        "four_octets_asn": "advertised and received",
                        "ipv4_unicast": "advertised and received",
                        "route_refresh": "advertised and received(new)",
                        "stateful_switchover": "NO for session 1",
                    },
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                            "received": {
                                "keepalives": 7834,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7837,
                                "updates": 2,
                            },
                            "sent": {
                                "keepalives": 7839,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7847,
                                "updates": 7,
                            },
                        }
                    },
                    "bgp_session_transport": {
                        "ack_hold": 200,
                        "address_tracking_status": "enabled",
                        "connection": {
                            "dropped": 0,
                            "established": 1,
                            "last_reset": "never",
                        },
                        "connection_state": "estab",
                        "connection_tableid": 2,
                        "datagram": {
                            "datagram_received": {
                                "out_of_order": 0,
                                "total_data": 148980,
                                "value": 15637,
                                "with_data": 7836,
                            },
                            "datagram_sent": {
                                "fastretransmit": 0,
                                "partialack": 0,
                                "retransmit": 1,
                                "second_congestion": 0,
                                "total_data": 149325,
                                "value": 15671,
                                "with_data": 7845,
                            },
                        },
                        "delrcvwnd": 1216,
                        "ecn_connection": "disabled",
                        "enqueued_packets": {
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                            "retransmit_packet": 0,
                        },
                        "fast_lock_acquisition_failures": 0,
                        "graceful_restart": "disabled",
                        "io_status": 1,
                        "ip_precedence_value": 6,
                        "irs": 950953285,
                        "iss": 3848368441,
                        "krtt": 0,
                        "lock_slow_path": 0,
                        "max_rtt": 1000,
                        "maximum_output_segment_queue_size": 50,
                        "maxrcvwnd": 16384,
                        "min_rtt": 1,
                        "min_time_between_advertisement_runs": 0,
                        "minimum_incoming_ttl": 0,
                        "option_flags": "VRF id set, nagle, path mtu capable",
                        "outgoing_ttl": 1,
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "rcv_scale": 0,
                        "rcvnxt": 951102266,
                        "rcvwnd": 15168,
                        "receive_idletime": 580,
                        "rib_route_ip": "172.17.211.2",
                        "rtto": 1003,
                        "rtv": 3,
                        "sent_idletime": 321,
                        "snd_scale": 0,
                        "sndnxt": 3848517767,
                        "snduna": 3848517767,
                        "sndwnd": 16289,
                        "srtt": 1000,
                        "sso": False,
                        "status_flags": "active open",
                        "tcp_path_mtu_discovery": "enabled",
                        "tcp_semaphore": "0x7F59978AAE80",
                        "tcp_semaphore_status": "FREE",
                        "transport": {
                            "foreign_host": "172.17.211.2",
                            "foreign_port": "179",
                            "local_host": "172.17.211.1",
                            "local_port": "48585",
                            "mss": 1460,
                        },
                        "unread_input_bytes": 0,
                        "uptime": 427538469,
                    },
                    "bgp_version": 4,
                    "link": "external",
                    "remote_as": 65001,
                    "router_id": "172.16.1.156",
                    "session_state": "Established",
                    "shutdown": False,
                }
            }
        },
        "default": {
            "neighbor": {
                "10.1.1.1": {
                    "address_family": {
                        "ipv4 unicast": {
                            "advertise_bit": 0,
                            "bgp_table_version": 1,
                            "dynamic_slow_peer_recovered": "never",
                            "index": 1,
                            "last_detected_dynamic_slow_peer": "never",
                            "last_received_refresh_end_of_rib": "never",
                            "last_received_refresh_start_of_rib": "never",
                            "last_sent_refresh_end_of_rib": "never",
                            "last_sent_refresh_start_of_rib": "never",
                            "local_policy_denied_prefixes_counters": {
                                "inbound": {"total": 0},
                                "outbound": {"total": 0},
                            },
                            "max_nlri": 0,
                            "min_nlri": 0,
                            "neighbor_version": "1/0",
                            "output_queue_size": 0,
                            "prefix_activity_counters": {
                                "received": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 0,
                                    "prefixes_current": 0,
                                    "prefixes_total": 0,
                                    "used_as_bestpath": 0,
                                    "used_as_multipath": 0,
                                    "used_as_secondary": 0,
                                },
                                "sent": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 0,
                                    "prefixes_current": 0,
                                    "prefixes_total": 0,
                                    "used_as_bestpath": "n/a",
                                    "used_as_multipath": "n/a",
                                    "used_as_secondary": "n/a",
                                },
                            },
                            "refresh_activity_counters": {
                                "received": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                                "sent": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                            },
                            "refresh_epoch": 1,
                            "slow_peer_detection": False,
                            "slow_peer_split_update_group_dynamic": False,
                            "update_group_member": 1,
                        },
                        "vpnv4 unicast": {
                            "advertise_bit": 1,
                            "bgp_table_version": 21,
                            "current_time": "0x197E167D",
                            "dynamic_slow_peer_recovered": "never",
                            "extended_community_attribute_sent": True,
                            "index": 3,
                            "last_detected_dynamic_slow_peer": "never",
                            "last_received_refresh_end_of_rib": "never",
                            "last_received_refresh_start_of_rib": "never",
                            "last_sent_refresh_end_of_rib": "never",
                            "last_sent_refresh_start_of_rib": "never",
                            "local_policy_denied_prefixes_counters": {
                                "inbound": {
                                    "af_permit_check": "n/a",
                                    "bestpath_from_ibgp_peer": "n/a",
                                    "bestpath_from_this_peer": "n/a",
                                    "originator_loop": 8,
                                    "total": 8,
                                },
                                "outbound": {
                                    "af_permit_check": 4,
                                    "bestpath_from_ibgp_peer": 4,
                                    "bestpath_from_this_peer": 4,
                                    "originator_loop": "n/a",
                                    "total": 12,
                                },
                            },
                            "max_nlri": 1,
                            "min_nlri": 0,
                            "neighbor_version": "21/0",
                            "output_queue_size": 0,
                            "prefix_activity_counters": {
                                "received": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 0,
                                    "prefixes_current": 4,
                                    "prefixes_total": 4,
                                    "used_as_bestpath": 4,
                                    "used_as_multipath": 0,
                                    "used_as_secondary": 0,
                                },
                                "sent": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 4,
                                    "prefixes_current": 4,
                                    "prefixes_total": 8,
                                    "used_as_bestpath": "n/a",
                                    "used_as_multipath": "n/a",
                                    "used_as_secondary": "n/a",
                                },
                            },
                            "refresh_activity_counters": {
                                "received": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                                "sent": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                            },
                            "refresh_epoch": 1,
                            "slow_peer_detection": False,
                            "slow_peer_split_update_group_dynamic": False,
                            "update_group_member": 3,
                        },
                    },
                    "bgp_event_timer": {
                        "next": {
                            "ackhold": "0x0",
                            "deadwait": "0x0",
                            "giveup": "0x0",
                            "keepalive": "0x0",
                            "linger": "0x0",
                            "pmtuager": "0x0",
                            "processq": "0x0",
                            "retrans": "0x0",
                            "sendwnd": "0x0",
                            "timewait": "0x0",
                        },
                        "starts": {
                            "ackhold": 7852,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 0,
                            "processq": 0,
                            "retrans": 7851,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                        "wakeups": {
                            "ackhold": 7671,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 0,
                            "processq": 0,
                            "retrans": 0,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "enhanced_refresh": "advertised and received",
                        "four_octets_asn": "advertised and received",
                        "ipv4_unicast": "advertised and received",
                        "route_refresh": "advertised and received(new)",
                        "stateful_switchover": "NO for session 1",
                        "vpnv4_unicast": "advertised and received",
                    },
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                            "received": {
                                "keepalives": 7849,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7864,
                                "updates": 14,
                            },
                            "sent": {
                                "keepalives": 7847,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7858,
                                "updates": 10,
                            },
                        }
                    },
                    "bgp_session_transport": {
                        "ack_hold": 200,
                        "address_tracking_status": "enabled",
                        "connection": {
                            "dropped": 0,
                            "established": 1,
                            "last_reset": "never",
                        },
                        "connection_state": "estab",
                        "connection_tableid": 0,
                        "datagram": {
                            "datagram_received": {
                                "out_of_order": 0,
                                "total_data": 150532,
                                "value": 15669,
                                "with_data": 7853,
                            },
                            "datagram_sent": {
                                "fastretransmit": 0,
                                "partialack": 0,
                                "retransmit": 0,
                                "second_congestion": 0,
                                "total_data": 149954,
                                "value": 15633,
                                "with_data": 7852,
                            },
                        },
                        "delrcvwnd": 19,
                        "ecn_connection": "disabled",
                        "enqueued_packets": {
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                            "retransmit_packet": 0,
                        },
                        "fast_lock_acquisition_failures": 0,
                        "graceful_restart": "disabled",
                        "io_status": 1,
                        "ip_precedence_value": 6,
                        "irs": 547332975,
                        "iss": 3484933877,
                        "krtt": 0,
                        "lock_slow_path": 0,
                        "max_rtt": 1000,
                        "maximum_output_segment_queue_size": 50,
                        "maxrcvwnd": 16384,
                        "min_rtt": 1,
                        "min_time_between_advertisement_runs": 0,
                        "minimum_incoming_ttl": 0,
                        "option_flags": "nagle, path mtu capable",
                        "outgoing_ttl": 255,
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "rcv_scale": 0,
                        "rcvnxt": 547483508,
                        "rcvwnd": 16365,
                        "receive_idletime": 20991,
                        "rib_route_ip": "10.1.1.1",
                        "rtto": 1003,
                        "rtv": 3,
                        "sent_idletime": 21193,
                        "snd_scale": 0,
                        "sndnxt": 3485083832,
                        "snduna": 3485083832,
                        "sndwnd": 15472,
                        "srtt": 1000,
                        "sso": False,
                        "status_flags": "passive open, gen tcbs",
                        "tcp_path_mtu_discovery": "enabled",
                        "tcp_semaphore": "0x7F59978AAB40",
                        "tcp_semaphore_status": "FREE",
                        "transport": {
                            "foreign_host": "10.1.1.1",
                            "foreign_port": "44730",
                            "local_host": "10.5.5.5",
                            "local_port": "179",
                            "mss": 1396,
                        },
                        "unread_input_bytes": 0,
                        "uptime": 427481259,
                    },
                    "bgp_version": 4,
                    "link": "internal",
                    "remote_as": 65000,
                    "router_id": "10.1.1.1",
                    "session_state": "Established",
                    "shutdown": False,
                },
                "10.2.2.2": {
                    "address_family": {
                        "ipv4 unicast": {
                            "advertise_bit": 0,
                            "bgp_table_version": 1,
                            "dynamic_slow_peer_recovered": "never",
                            "index": 1,
                            "last_detected_dynamic_slow_peer": "never",
                            "last_received_refresh_end_of_rib": "never",
                            "last_received_refresh_start_of_rib": "never",
                            "last_sent_refresh_end_of_rib": "never",
                            "last_sent_refresh_start_of_rib": "never",
                            "local_policy_denied_prefixes_counters": {
                                "inbound": {"total": 0},
                                "outbound": {"total": 0},
                            },
                            "max_nlri": 0,
                            "min_nlri": 0,
                            "neighbor_version": "1/0",
                            "output_queue_size": 0,
                            "prefix_activity_counters": {
                                "received": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 0,
                                    "prefixes_current": 0,
                                    "prefixes_total": 0,
                                    "used_as_bestpath": 0,
                                    "used_as_multipath": 0,
                                    "used_as_secondary": 0,
                                },
                                "sent": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 0,
                                    "prefixes_current": 0,
                                    "prefixes_total": 0,
                                    "used_as_bestpath": "n/a",
                                    "used_as_multipath": "n/a",
                                    "used_as_secondary": "n/a",
                                },
                            },
                            "refresh_activity_counters": {
                                "received": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                                "sent": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                            },
                            "refresh_epoch": 1,
                            "slow_peer_detection": False,
                            "slow_peer_split_update_group_dynamic": False,
                            "update_group_member": 1,
                        },
                        "vpnv4 unicast": {
                            "advertise_bit": 1,
                            "bgp_table_version": 21,
                            "current_time": "0x197E1784",
                            "dynamic_slow_peer_recovered": "never",
                            "extended_community_attribute_sent": True,
                            "index": 3,
                            "last_detected_dynamic_slow_peer": "never",
                            "last_read": "00:00:16",
                            "last_received_refresh_end_of_rib": "never",
                            "last_received_refresh_start_of_rib": "never",
                            "last_sent_refresh_end_of_rib": "never",
                            "last_sent_refresh_start_of_rib": "never",
                            "last_write": "00:00:28",
                            "local_policy_denied_prefixes_counters": {
                                "inbound": {
                                    "af_permit_check": "n/a",
                                    "bestpath_from_ibgp_peer": "n/a",
                                    "bestpath_from_this_peer": "n/a",
                                    "originator_loop": 8,
                                    "total": 8,
                                },
                                "outbound": {
                                    "af_permit_check": 4,
                                    "bestpath_from_ibgp_peer": 4,
                                    "bestpath_from_this_peer": 4,
                                    "originator_loop": "n/a",
                                    "total": 12,
                                },
                            },
                            "max_nlri": 1,
                            "min_nlri": 0,
                            "neighbor_version": "21/0",
                            "output_queue_size": 0,
                            "prefix_activity_counters": {
                                "received": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 0,
                                    "prefixes_current": 4,
                                    "prefixes_total": 4,
                                    "used_as_bestpath": 0,
                                    "used_as_multipath": 0,
                                    "used_as_secondary": 0,
                                },
                                "sent": {
                                    "explicit_withdraw": 0,
                                    "implicit_withdraw": 4,
                                    "prefixes_current": 4,
                                    "prefixes_total": 8,
                                    "used_as_bestpath": "n/a",
                                    "used_as_multipath": "n/a",
                                    "used_as_secondary": "n/a",
                                },
                            },
                            "refresh_activity_counters": {
                                "received": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                                "sent": {
                                    "refresh_end_of_rib": 0,
                                    "refresh_start_of_rib": 0,
                                },
                            },
                            "refresh_epoch": 1,
                            "session_state": "Established",
                            "slow_peer_detection": False,
                            "slow_peer_split_update_group_dynamic": False,
                            "up_time": "4d22h",
                            "update_group_member": 3,
                        },
                    },
                    "bgp_event_timer": {
                        "next": {
                            "ackhold": "0x0",
                            "deadwait": "0x0",
                            "giveup": "0x0",
                            "keepalive": "0x0",
                            "linger": "0x0",
                            "pmtuager": "0x0",
                            "processq": "0x0",
                            "retrans": "0x0",
                            "sendwnd": "0x0",
                            "timewait": "0x0",
                        },
                        "starts": {
                            "ackhold": 7840,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 0,
                            "processq": 0,
                            "retrans": 7839,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                        "wakeups": {
                            "ackhold": 7688,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 0,
                            "processq": 0,
                            "retrans": 0,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_negotiated_capabilities": {
                        "enhanced_refresh": "advertised and received",
                        "four_octets_asn": "advertised and received",
                        "ipv4_unicast": "advertised and received",
                        "route_refresh": "advertised and received(new)",
                        "stateful_switchover": "NO for session 1",
                        "vpnv4_unicast": "advertised and received",
                    },
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                            "received": {
                                "keepalives": 7837,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7852,
                                "updates": 14,
                            },
                            "sent": {
                                "keepalives": 7834,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 7845,
                                "updates": 10,
                            },
                        }
                    },
                    "bgp_session_transport": {
                        "ack_hold": 200,
                        "address_tracking_status": "enabled",
                        "connection": {
                            "dropped": 0,
                            "established": 1,
                            "last_reset": "never",
                        },
                        "connection_state": "estab",
                        "connection_tableid": 0,
                        "datagram": {
                            "datagram_received": {
                                "out_of_order": 0,
                                "total_data": 150304,
                                "value": 15651,
                                "with_data": 7841,
                            },
                            "datagram_sent": {
                                "fastretransmit": 0,
                                "partialack": 0,
                                "retransmit": 0,
                                "second_congestion": 0,
                                "total_data": 149707,
                                "value": 15636,
                                "with_data": 7839,
                            },
                        },
                        "delrcvwnd": 1197,
                        "ecn_connection": "disabled",
                        "enqueued_packets": {
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                            "retransmit_packet": 0,
                        },
                        "fast_lock_acquisition_failures": 0,
                        "graceful_restart": "disabled",
                        "io_status": 1,
                        "ip_precedence_value": 6,
                        "irs": 2814267610,
                        "iss": 84959429,
                        "krtt": 0,
                        "lock_slow_path": 0,
                        "max_rtt": 1000,
                        "maximum_output_segment_queue_size": 50,
                        "maxrcvwnd": 16384,
                        "min_rtt": 1,
                        "min_time_between_advertisement_runs": 0,
                        "minimum_incoming_ttl": 0,
                        "option_flags": "nagle, path mtu capable",
                        "outgoing_ttl": 255,
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "rcv_scale": 0,
                        "rcvnxt": 2814417915,
                        "rcvwnd": 15187,
                        "receive_idletime": 17149,
                        "rib_route_ip": "10.2.2.2",
                        "rtto": 1003,
                        "rtv": 3,
                        "sent_idletime": 16949,
                        "snd_scale": 0,
                        "sndnxt": 85109137,
                        "snduna": 85109137,
                        "sndwnd": 15719,
                        "srtt": 1000,
                        "sso": False,
                        "status_flags": "passive open, gen tcbs",
                        "tcp_path_mtu_discovery": "enabled",
                        "tcp_semaphore": "0x7F59978AAC10",
                        "tcp_semaphore_status": "FREE",
                        "transport": {
                            "foreign_host": "10.2.2.2",
                            "foreign_port": "43047",
                            "local_host": "10.5.5.5",
                            "local_port": "179",
                            "mss": 1396,
                        },
                        "unread_input_bytes": 0,
                        "uptime": 427486738,
                    },
                    "bgp_version": 4,
                    "link": "internal",
                    "remote_as": 65000,
                    "router_id": "10.2.2.2",
                    "session_state": "Established",
                    "shutdown": False,
                },
            }
        },
    },
}
