expected_output = {
    "list_of_neighbors": ["10.10.10.1", "10.10.11.1", "10.10.21.6"],
    "vrf": {
        "Admin": {
            "neighbor": {
                "10.10.10.1": {
                    "address_family": {
                        "vpnv4 unicast": {
                            "current_time": "0x1D210E7",
                            "last_read": "00:00:07",
                            "last_write": "00:00:00",
                            "session_state": "Established",
                            "up_time": "00:21:10",
                        }
                    },
                    "bgp_event_timer": {
                        "next": {
                            "ackhold": "0x0",
                            "deadwait": "0x0",
                            "giveup": "0x0",
                            "keepalive": "0x0",
                            "linger": "0x0",
                            "pmtuager": "0x0",
                            "processq": "0x0",
                            "retrans": "0x0",
                            "sendwnd": "0x0",
                            "timewait": "0x0",
                        },
                        "starts": {
                            "ackhold": 47,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 1,
                            "processq": 0,
                            "retrans": 51,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                        "wakeups": {
                            "ackhold": 44,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 1,
                            "processq": 0,
                            "retrans": 0,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                    },
                    "bgp_negotiated_capabilities": {
                        "enhanced_refresh": "advertised",
                        "four_octets_asn": "advertised " "and " "received",
                        "ipv4_unicast": "advertised " "and " "received",
                        "route_refresh": "advertised " "and " "received(new)",
                        "stateful_switchover": "NO " "for " "session " "1",
                    },
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 90,
                        "keepalive_interval": 30,
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                            "received": {
                                "keepalives": 44,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 47,
                                "updates": 2,
                            },
                            "sent": {
                                "keepalives": 49,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 52,
                                "updates": 2,
                            },
                        }
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_session_transport": {
                        "ack_hold": 200,
                        "address_tracking_status": "enabled",
                        "connection": {
                            "dropped": 16,
                            "established": 17,
                            "last_reset": "00:23:58",
                            "reset_reason": "Active " "open " "failed",
                        },
                        "connection_state": "estab",
                        "connection_tableid": 1,
                        "datagram": {
                            "datagram_received": {
                                "out_of_order": 0,
                                "total_data": 1012,
                                "value": 97,
                                "with_data": 46,
                            },
                            "datagram_sent": {
                                "fastretransmit": 0,
                                "partialack": 0,
                                "retransmit": 0,
                                "second_congestion": 0,
                                "total_data": 1066,
                                "value": 97,
                                "with_data": 51,
                            },
                        },
                        "delrcvwnd": 1012,
                        "ecn_connection": "disabled",
                        "enqueued_packets": {
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                            "retransmit_packet": 0,
                        },
                        "fast_lock_acquisition_failures": 0,
                        "graceful_restart": "disabled",
                        "io_status": 1,
                        "ip_precedence_value": 6,
                        "irs": 2154790871,
                        "iss": 1176688694,
                        "krtt": 0,
                        "lock_slow_path": 0,
                        "max_rtt": 1000,
                        "maximum_output_segment_queue_size": 50,
                        "maxrcvwnd": 16384,
                        "min_rtt": 3,
                        "min_time_between_advertisement_runs": 0,
                        "minimum_incoming_ttl": 0,
                        "option_flags": "VRF id set, nagle, path mtu capable",
                        "outgoing_ttl": 1,
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "rcv_scale": 0,
                        "rcvnxt": 2154791884,
                        "rcvwnd": 15372,
                        "receive_idletime": 68,
                        "rib_route_ip": "10.10.10.1",
                        "rtto": 1009,
                        "rtv": 10,
                        "sent_idletime": 73,
                        "snd_scale": 0,
                        "sndnxt": 1176689761,
                        "snduna": 1176689761,
                        "sndwnd": 32768,
                        "srtt": 999,
                        "sso": False,
                        "status_flags": "active " "open",
                        "tcp_path_mtu_discovery": "enabled",
                        "tcp_semaphore": "0x7F3C800B64D8",
                        "tcp_semaphore_status": "FREE",
                        "transport": {
                            "foreign_host": "10.10.10.1",
                            "foreign_port": "179",
                            "local_host": "10.10.10.2",
                            "local_port": "34272",
                            "mss": 1024,
                        },
                        "unread_input_bytes": 0,
                        "uptime": 1270382,
                    },
                    "bgp_version": 4,
                    "link": "external",
                    "remote_as": 4200000001,
                    "router_id": "10.0.1.1",
                    "session_state": "Established",
                    "shutdown": False,
                }
            }
        },
        "CustA-VPN1": {
            "neighbor": {
                "10.10.11.1": {
                    "address_family": {
                        "vpnv4 unicast": {
                            "current_time": "0x1D21195",
                            "last_read": "00:00:19",
                            "last_write": "00:00:23",
                            "session_state": "Established",
                            "up_time": "00:21:21",
                        }
                    },
                    "bgp_event_timer": {
                        "next": {
                            "ackhold": "0x0",
                            "deadwait": "0x0",
                            "giveup": "0x0",
                            "keepalive": "0x0",
                            "linger": "0x0",
                            "pmtuager": "0x0",
                            "processq": "0x0",
                            "retrans": "0x0",
                            "sendwnd": "0x0",
                            "timewait": "0x0",
                        },
                        "starts": {
                            "ackhold": 46,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 1,
                            "processq": 0,
                            "retrans": 51,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                        "wakeups": {
                            "ackhold": 42,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 1,
                            "processq": 0,
                            "retrans": 0,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                    },
                    "bgp_negotiated_capabilities": {
                        "enhanced_refresh": "advertised",
                        "four_octets_asn": "advertised " "and " "received",
                        "ipv4_unicast": "advertised " "and " "received",
                        "route_refresh": "advertised " "and " "received(new)",
                        "stateful_switchover": "NO " "for " "session " "1",
                    },
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 90,
                        "keepalive_interval": 30,
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                            "received": {
                                "keepalives": 44,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 48,
                                "updates": 3,
                            },
                            "sent": {
                                "keepalives": 48,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 52,
                                "updates": 3,
                            },
                        }
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_session_transport": {
                        "ack_hold": 200,
                        "address_tracking_status": "enabled",
                        "connection": {
                            "dropped": 16,
                            "established": 17,
                            "last_reset": "00:24:12",
                            "reset_reason": "Active " "open " "failed",
                        },
                        "connection_state": "estab",
                        "connection_tableid": 2,
                        "datagram": {
                            "datagram_received": {
                                "out_of_order": 0,
                                "total_data": 1078,
                                "value": 96,
                                "with_data": 46,
                            },
                            "datagram_sent": {
                                "fastretransmit": 0,
                                "partialack": 0,
                                "retransmit": 0,
                                "second_congestion": 0,
                                "total_data": 1103,
                                "value": 96,
                                "with_data": 50,
                            },
                        },
                        "delrcvwnd": 38,
                        "ecn_connection": "disabled",
                        "enqueued_packets": {
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                            "retransmit_packet": 0,
                        },
                        "fast_lock_acquisition_failures": 0,
                        "graceful_restart": "disabled",
                        "io_status": 1,
                        "ip_precedence_value": 6,
                        "irs": 1970766160,
                        "iss": 3531560020,
                        "krtt": 0,
                        "lock_slow_path": 0,
                        "max_rtt": 1000,
                        "maximum_output_segment_queue_size": 50,
                        "maxrcvwnd": 16384,
                        "min_rtt": 3,
                        "min_time_between_advertisement_runs": 0,
                        "minimum_incoming_ttl": 0,
                        "option_flags": "VRF "
                        "id "
                        "set, "
                        "nagle, "
                        "path "
                        "mtu "
                        "capable",
                        "outgoing_ttl": 1,
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "rcv_scale": 0,
                        "rcvnxt": 1970767239,
                        "rcvwnd": 16346,
                        "receive_idletime": 19547,
                        "rib_route_ip": "10.10.11.1",
                        "rtto": 1009,
                        "rtv": 10,
                        "sent_idletime": 19347,
                        "snd_scale": 0,
                        "sndnxt": 3531561124,
                        "snduna": 3531561124,
                        "sndwnd": 32768,
                        "srtt": 999,
                        "sso": False,
                        "status_flags": "active " "open",
                        "tcp_path_mtu_discovery": "enabled",
                        "tcp_semaphore": "0x7F3C800B6268",
                        "tcp_semaphore_status": "FREE",
                        "transport": {
                            "foreign_host": "10.10.11.1",
                            "foreign_port": "179",
                            "local_host": "10.10.11.2",
                            "local_port": "39949",
                            "mss": 1024,
                        },
                        "unread_input_bytes": 0,
                        "uptime": 1281819,
                    },
                    "bgp_version": 4,
                    "link": "external",
                    "local_as": 4200000101,
                    "no_prepend": True,
                    "remote_as": 4200000001,
                    "replace_as": True,
                    "router_id": "10.0.1.1",
                    "session_state": "Established",
                    "shutdown": False,
                },
                "10.10.21.6": {
                    "address_family": {
                        "ipv4 multicast": {},
                        "l2vpn evpn": {},
                        "mvpnv4 unicast": {},
                        "mvpnv6 unicast": {},
                        "vpnv4 flowspec": {},
                        "vpnv4 multicast": {},
                        "vpnv4 unicast": {
                            "current_time": "0x1D21234",
                            "last_read": "00:00:51",
                            "last_write": "00:00:05",
                            "session_state": "Established",
                            "up_time": "08:07:20",
                        },
                    },
                    "bgp_event_timer": {
                        "next": {
                            "ackhold": "0x0",
                            "deadwait": "0x0",
                            "giveup": "0x0",
                            "keepalive": "0x0",
                            "linger": "0x0",
                            "pmtuager": "0x0",
                            "processq": "0x0",
                            "retrans": "0x0",
                            "sendwnd": "0x0",
                            "timewait": "0x0",
                        },
                        "starts": {
                            "ackhold": 538,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 0,
                            "processq": 0,
                            "retrans": 553,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                        "wakeups": {
                            "ackhold": 525,
                            "deadwait": 0,
                            "giveup": 0,
                            "keepalive": 0,
                            "linger": 0,
                            "pmtuager": 0,
                            "processq": 0,
                            "retrans": 0,
                            "sendwnd": 0,
                            "timewait": 0,
                        },
                    },
                    "bgp_negotiated_capabilities": {
                        "enhanced_refresh": "advertised " "and " "received",
                        "four_octets_asn": "advertised " "and " "received",
                        "ipv4_unicast": "advertised " "and " "received",
                        "route_refresh": "advertised " "and " "received(new)",
                        "stateful_switchover": "NO " "for " "session " "1",
                    },
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 180,
                        "keepalive_interval": 60,
                    },
                    "bgp_neighbor_counters": {
                        "messages": {
                            "in_queue_depth": 0,
                            "out_queue_depth": 0,
                            "received": {
                                "keepalives": 536,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 539,
                                "updates": 2,
                            },
                            "sent": {
                                "keepalives": 519,
                                "notifications": 0,
                                "opens": 1,
                                "route_refresh": 0,
                                "total": 558,
                                "updates": 38,
                            },
                        }
                    },
                    "bgp_neighbor_session": {"sessions": 1},
                    "bgp_session_transport": {
                        "ack_hold": 200,
                        "address_tracking_status": "enabled",
                        "connection": {
                            "dropped": 1,
                            "established": 2,
                            "last_reset": "08:07:21",
                            "reset_reason": "Peer "
                            "closed "
                            "the "
                            "session "
                            "of "
                            "session "
                            "1",
                        },
                        "connection_state": "estab",
                        "connection_tableid": 2,
                        "datagram": {
                            "datagram_received": {
                                "out_of_order": 0,
                                "total_data": 10319,
                                "value": 1090,
                                "with_data": 539,
                            },
                            "datagram_sent": {
                                "fastretransmit": 0,
                                "partialack": 0,
                                "retransmit": 0,
                                "second_congestion": 0,
                                "total_data": 11612,
                                "value": 1089,
                                "with_data": 554,
                            },
                        },
                        "delrcvwnd": 76,
                        "ecn_connection": "disabled",
                        "enqueued_packets": {
                            "input_packet": 0,
                            "mis_ordered_packet": 0,
                            "retransmit_packet": 0,
                        },
                        "fast_lock_acquisition_failures": 0,
                        "graceful_restart": "disabled",
                        "io_status": 1,
                        "ip_precedence_value": 6,
                        "irs": 1467114123,
                        "iss": 925402839,
                        "krtt": 0,
                        "lock_slow_path": 0,
                        "max_rtt": 1000,
                        "maximum_output_segment_queue_size": 50,
                        "maxrcvwnd": 16384,
                        "min_rtt": 0,
                        "min_time_between_advertisement_runs": 0,
                        "minimum_incoming_ttl": 0,
                        "option_flags": "VRF "
                        "id "
                        "set, "
                        "nagle, "
                        "path "
                        "mtu "
                        "capable",
                        "outgoing_ttl": 1,
                        "packet_fast_path": 0,
                        "packet_fast_processed": 0,
                        "packet_slow_path": 0,
                        "rcv_scale": 0,
                        "rcvnxt": 1467124443,
                        "rcvwnd": 16308,
                        "receive_idletime": 5322,
                        "rib_route_ip": "10.10.21.6",
                        "rtto": 1003,
                        "rtv": 3,
                        "sent_idletime": 5527,
                        "snd_scale": 0,
                        "sndnxt": 925414452,
                        "snduna": 925414452,
                        "sndwnd": 15049,
                        "srtt": 1000,
                        "sso": False,
                        "status_flags": "passive " "open, " "gen " "tcbs",
                        "tcp_path_mtu_discovery": "enabled",
                        "tcp_semaphore": "0x7F3C800B6338",
                        "tcp_semaphore_status": "FREE",
                        "transport": {
                            "foreign_host": "10.10.21.6",
                            "foreign_port": "16600",
                            "local_host": "10.10.21.5",
                            "local_port": "179",
                            "mss": 1460,
                        },
                        "unread_input_bytes": 0,
                        "uptime": 29240881,
                    },
                    "bgp_version": 4,
                    "link": "external",
                    "local_as": 4200000101,
                    "no_prepend": False,
                    "remote_as": 65111,
                    "replace_as": False,
                    "router_id": "10.10.21.6",
                    "session_state": "Established",
                    "shutdown": False,
                },
            }
        },
    },
}