expected_output = {
    'punt_policer': {
        2: {
            'description': 'IPv4 Options',
            'config_rate_normal_pps': 4000,
            'config_rate_high_pps': 3000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 4000,
            'config_burst_high_pkts': 3000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        3: {
            'description': 'Layer2 control and legacy',
            'config_rate_normal_pps': 40000,
            'config_rate_high_pps': 10000,
            'conform_pkts_normal': 298852,
            'conform_pkts_high': 3586680,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 40000,
            'config_burst_high_pkts': 10000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        4: {
            'description': 'PPP Control',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        5: {
            'description': 'CLNS IS-IS Control',
            'config_rate_normal_pps': 40000,
            'config_rate_high_pps': 10000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 40000,
            'config_burst_high_pkts': 10000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        6: {
            'description': 'HDLC keepalives',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        7: {
            'description': 'ARP request or response',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 123723,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        8: {
            'description': 'Reverse ARP request or repso',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        9: {
            'description': 'Frame-relay LMI Control',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        10: {
            'description': 'Incomplete adjacency',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 15371,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        11: {
            'description': 'For-us data',
            'config_rate_normal_pps': 40000,
            'config_rate_high_pps': 5000,
            'conform_pkts_normal': 14762,
            'conform_pkts_high': 24837888,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 40000,
            'config_burst_high_pkts': 5000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        12: {
            'description': 'Mcast Directly Connected Sou',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        13: {
            'description': 'Mcast IPv4 Options data pack',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        15: {
            'description': 'MPLS TTL expired',
            'config_rate_normal_pps': 5120,
            'config_rate_high_pps': 2000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 5120,
            'config_burst_high_pkts': 2000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        16: {
            'description': 'MPLS Reserved label (ie: 0-1',
            'config_rate_normal_pps': 5120,
            'config_rate_high_pps': 2000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 5120,
            'config_burst_high_pkts': 2000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        18: {
            'description': 'IPV6 Hop-by-hop Options',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        19: {
            'description': 'Mcast Internal Copy',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        23: {
            'description': 'Mcast IGMP Unroutable',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        24: {
            'description': 'Glean adjacency',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 5000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 46158,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 5000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        25: {
            'description': 'Mcast PIM signaling',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        27: {
            'description': 'Subscriber session control',
            'config_rate_normal_pps': 10000,
            'config_rate_high_pps': 40000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 102452,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 10000,
            'config_burst_high_pkts': 40000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        29: {
            'description': 'RP handled ICMP',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        30: {
            'description': 'RP injected For-us data',
            'config_rate_normal_pps': 20000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 20000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        32: {
            'description': 'SBC RTP DTMF',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        33: {
            'description': 'Pseudowire VCCV control chan',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        35: {
            'description': 'Ethernet slow protocol (ie:',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        44: {
            'description': 'L2TP session',
            'config_rate_normal_pps': 1048,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 1048,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        45: {
            'description': 'BFD control',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 5000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 18,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 5000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        51: {
            'description': 'DMVPN NHRP redirect',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        52: {
            'description': 'PFR monitored prefix logging',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        53: {
            'description': 'PFR top talkers logging',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        54: {
            'description': 'PFR top talkers application',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        55: {
            'description': 'For-us control',
            'config_rate_normal_pps': 20000,
            'config_rate_high_pps': 20000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 443111,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 20000,
            'config_burst_high_pkts': 20000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        56: {
            'description': 'RP injected for-us control',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 2000,
            'conform_pkts_normal': 512,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 2000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        58: {
            'description': 'Layer2 bridge domain data pa',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        60: {
            'description': 'IP subnet or broadcast packe',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 2304,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        61: {
            'description': 'Ethernet CFM packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        62: {
            'description': 'Ethernet CFM notify packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        63: {
            'description': 'LISP LSB NOTIFICATION',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        64: {
            'description': 'Service Engine packet',
            'config_rate_normal_pps': 5000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 5000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        65: {
            'description': 'L2BD Control packet from FIA',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        66: {
            'description': 'L2BD Control Message from CP',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        67: {
            'description': 'MFR_LIP_CONTROL',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        69: {
            'description': 'OTV Control packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        70: {
            'description': 'OTV ARP packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        73: {
            'description': "STP BPDU's",
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 4000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 4000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        74: {
            'description': 'ACL log',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        75: {
            'description': 'EPC',
            'config_rate_normal_pps': 40000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 40000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        76: {
            'description': 'Lisp Dynamic eid',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        77: {
            'description': 'L2 Control packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        79: {
            'description': 'dhcp snoop',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        80: {
            'description': 'Metric Mediation Agent recor',
            'config_rate_normal_pps': 2400,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 24000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        81: {
            'description': 'IPv6 DMVPN NHRP redirect',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        82: {
            'description': 'Ethernet CFM packet from cor',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        83: {
            'description': 'Ethernet CFM punt fwd packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        84: {
            'description': 'PTP punt fwd packet',
            'config_rate_normal_pps': 8192,
            'config_rate_high_pps': 8192,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 8192,
            'config_burst_high_pkts': 8192,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        85: {
            'description': 'ISDN D-Channel raw packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        87: {
            'description': 'IPv6 FHS SG dropped packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 2000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 2000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        88: {
            'description': 'IPv6 FHS Data glean packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        89: {
            'description': 'SBC DSP pkts',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        90: {
            'description': 'Raw Socket Data packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        91: {
            'description': 'SSLVPN session control',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 5000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 5000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        92: {
            'description': 'ICMP unreachables for ACL de',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        93: {
            'description': 'CENT Smart Probe packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        95: {
            'description': 'Autonomic Network Channel Di',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        97: {
            'description': 'Packets to LFTS',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 30424,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        98: {
            'description': 'VLAN Auto Sense FSOL',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        102: {
            'description': 'Source Verify inconclusive',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        104: {
            'description': 'mpls receive adj',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 2000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 2000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        105: {
            'description': 'MKA EAPoL packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        106: {
            'description': 'ICMP Unreachable',
            'config_rate_normal_pps': 1048,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 1048,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        112: {
            'description': 'QoS CAC Flow Report',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        113: {
            'description': 'Active identity',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        114: {
            'description': 'BGP Overlay Tunnel packet',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        115: {
            'description': 'Lisp gsmr enabled',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        120: {
            'description': 'SBC RTP FWD DTMF',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        121: {
            'description': 'Path Manager',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        127: {
            'description': 'Path Manager TTL expired',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        128: {
            'description': 'L3 PTP message',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        140: {
            'description': 'EFP dot1x Packets',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        141: {
            'description': 'DMVPN GAL label check',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        143: {
            'description': 'epbr packets',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        144: {
            'description': 'PMIPv6 control packets',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 5000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 5000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        147: {
            'description': 'Mcast UDLR',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        148: {
            'description': 'L2BD SISF ctrl',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 4000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 4000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        150: {
            'description': 'SR TWAMP PROBE',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 1000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 1000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        },
        156: {
            'description': 'BFD L2 control',
            'config_rate_normal_pps': 2000,
            'config_rate_high_pps': 5000,
            'conform_pkts_normal': 0,
            'conform_pkts_high': 0,
            'dropped_pkts_normal': 0,
            'dropped_pkts_high': 0,
            'config_burst_normal_pkts': 2000,
            'config_burst_high_pkts': 5000,
            'config_alert_normal': 'Off',
            'config_alert_high': 'Off'
        }
    }
}
