expected_output={'tenant_name': {'apple': {'peer': {'169.254.10.10': {'domain_id': 1,
                                                      'overlay_id': 1,
                                                      'routes_installed': 0,
                                                      'routes_received': 11,
                                                      'routes_sent': 108,
                                                      'site_id': 501,
                                                      'state': 'up',
                                                      'type': 'vedge',
                                                      'uptime': '0:06:53:57'},
                                    '169.254.10.11': {'domain_id': 1,
                                                      'overlay_id': 1,
                                                      'routes_installed': 0,
                                                      'routes_received': 84,
                                                      'routes_sent': 33,
                                                      'site_id': 503,
                                                      'state': 'up',
                                                      'type': 'vedge',
                                                      'uptime': '0:21:39:37'},
                                    '169.254.10.12': {'domain_id': 1,
                                                      'overlay_id': 1,
                                                      'routes_installed': 0,
                                                      'routes_received': 16,
                                                      'routes_sent': 30,
                                                      'site_id': 504,
                                                      'state': 'up',
                                                      'type': 'vedge',
                                                      'uptime': '0:21:39:38'},
                                    '169.254.10.26': {'domain_id': 1,
                                                      'overlay_id': 1,
                                                      'routes_installed': 0,
                                                      'routes_received': 8,
                                                      'routes_sent': 70,
                                                      'site_id': 506,
                                                      'state': 'up',
                                                      'type': 'vedge',
                                                      'uptime': '0:21:39:37'},
                                    '169.254.10.7': {'domain_id': 1,
                                                     'overlay_id': 1,
                                                     'routes_installed': 0,
                                                     'routes_received': 114,
                                                     'routes_sent': 114,
                                                     'site_id': 26,
                                                     'state': 'up',
                                                     'type': 'vsmart',
                                                     'uptime': '0:21:24:40'}}}}}
