expected_output = {
    "GigabitEthernet0/1.1": {
        "mtu": 1500,
        "joined_group_addresses": [
            "FF02::1",
            "FF02::1:FF01:1",
            "FF02::1:FF05:2",
            "FF02::1:FF4B:55FD",
            "FF02::2",
            "FF02::5",
            "FF02::6",
        ],
        "enabled": True,
        "addresses_config_method": "stateless autoconfig",
        "ipv6": {
            "enabled": True,
            "2001:db8:405::1:1/112": {
                "status": "valid",
                "ip": "2001:db8:405::1:1",
                "prefix_length": "112",
            },
            "FE80::F816:3EFF:FEFF:A049": {
                "status": "valid",
                "ip": "FE80::F816:3EFF:FEFF:A049",
                "origin": "link_layer",
            },
            "2001:db8:405::5:2/112": {
                "status": "valid",
                "ip": "2001:db8:405::5:2",
                "prefix_length": "112",
            },
            "nd": {
                "suppress": False,
                "dad_enabled": True,
                "advertised_default_router_preference": "Medium",
                "advertised_retransmit_interval": 0,
                "router_advertisements_interval": 200,
                "advertised_retransmit_interval_unspecified": True,
                "router_advertisements_live": 1800,
                "using_time": 30000,
                "dad_attempts": 1,
                "advertised_reachable_time_unspecified": True,
                "reachable_time": 30000,
                "advertised_reachable_time": 0,
            },
            "icmp": {
                "redirects": True,
                "error_messages_limited": 100,
                "unreachables": "sent",
            },
        },
        "oper_status": "up",
    },
    "Loopback0": {
        "mtu": 1514,
        "joined_group_addresses": [
            "FF02::1",
            "FF02::1:FF00:0",
            "FF02::1:FF01:1",
            "FF02::2",
            "FF02::5",
        ],
        "enabled": True,
        "addresses_config_method": "stateless autoconfig",
        "ipv6": {
            "2001:db8:1:1::1:1/112": {
                "status": "valid",
                "ip": "2001:db8:1:1::1:1",
                "prefix_length": "112",
            },
            "enabled": True,
            "nd": {
                "suppress": True,
                "advertised_default_router_preference": "Medium",
                "advertised_retransmit_interval": 0,
                "advertised_retransmit_interval_unspecified": True,
                "router_advertisements_live": 1800,
                "reachable_time": 30000,
                "using_time": 30000,
                "advertised_reachable_time": 0,
                "advertised_reachable_time_unspecified": True,
            },
            "FE80::5C00:C0FF:FE00:0": {
                "status": "valid",
                "ip": "FE80::5C00:C0FF:FE00:0",
                "origin": "link_layer",
            },
            "icmp": {
                "redirects": True,
                "error_messages_limited": 100,
                "unreachables": "sent",
            },
        },
        "oper_status": "up",
    },
}
