expected_output = {
    "job_id": {
        "380": {
            "pid": 8930,
            "process_name": "optics_driver",
            "executable_path": "/opt/cisco/install-iosxr/base/bin/optics_driver",
            "instance": 1,
            "version_id": "00.00.0000",
            "respawn": "ON",
            "respawn_count": 1,
            "last_started": "Thu May  1 08:51:34 2025",
            "process_state": "Run",
            "package_state": "Normal",
            "core": "MAINMEM",
            "max_core": 0,
            "level": 99,
            "placement": "None",
            "startup_path": "/opt/cisco/install-iosxr/base/startup/optics_driver.startup",
            "ready": "2.650s",
            "process_cpu_time": {"user": 273.37, "kernel": 77.12, "total": 350.49},
            "tid": {
                8930: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "optics_driver",
                    "rt_pri": 0,
                },
                9121: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "libsani_backing",
                    "rt_pri": 0,
                },
                9127: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "lwm_service_thr",
                    "rt_pri": 0,
                },
                9137: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "qsm_service_thr",
                    "rt_pri": 0,
                },
                9187: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "chkpt_evm",
                    "rt_pri": 0,
                },
                9188: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "evm_signal_thre",
                    "rt_pri": 0,
                },
                9190: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "insight__event",
                    "rt_pri": 0,
                },
                9289: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "BSP_Port_Timer",
                    "rt_pri": 0,
                },
                9330: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "col_dom_thread",
                    "rt_pri": 0,
                },
                9331: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "aipc-lrd_thread",
                    "rt_pri": 0,
                },
                9333: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "xros_mmap_peer",
                    "rt_pri": 0,
                },
                9336: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "parser_ctrc_th",
                    "rt_pri": 0,
                },
                9345: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "opt chkpt thd",
                    "rt_pri": 0,
                },
                9415: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "Optics PTAH",
                    "rt_pri": 0,
                },
                9416: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "ptah_common_eve",
                    "rt_pri": 0,
                },
                9427: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "async",
                    "rt_pri": 0,
                },
                9437: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "optics_driver",
                    "rt_pri": 0,
                },
                9438: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "pm_ui thread",
                    "rt_pri": 0,
                },
                9449: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "telemetry_event",
                    "rt_pri": 0,
                },
                9461: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "dying gasp",
                    "rt_pri": 0,
                },
                9821: {
                    "stack": "0K",
                    "pri": 20,
                    "state": "Sleeping",
                    "name": "opt_invcpm_init",
                    "rt_pri": 0,
                },
            },
        }
    }
}