expected_output = {
    "GigabitEthernet3/8/0/48": {
        "auto_negotiate": True,
        "counters": {
            "normal": {
                "in_broadcast_pkts": 0,
                "in_mac_pause_frames": 0,
                "in_multicast_pkts": 3832415,
                "in_octets": 0,
                "in_pkts": 3184372634,
                "in_unicast_pkts": 3180540219,
                "out_broadcast_pkts": 2279737294,
                "out_mac_pause_frames": 0,
                "out_multicast_pkts": 25375569217,
                "out_octets": 0,
                "out_pkts": 189514390228,
                "out_unicast_pkts": 161859083717
            },
            "in_abort": 0,
            "in_broadcast_pkts": 0,
            "in_crc_errors": 0,
            "in_errors": 0,
            "in_frame": 0,
            "in_giants": 0,
            "in_ignored": 0,
            "in_mac_pause_frames": 0,
            "in_multicast_pkts": 3832415,
            "in_octets": 4508060351380,
            "in_overrun": 0,
            "in_parity_errors": 0,
            "in_pkts": 3184372634,
            "in_runts": 0,
            "in_throttles": 0,
            "in_unicast_pkts": 3180540219,
            "last_clear": "Never",
            "out_abort": 0,
            "out_broadcast_pkts": 2279737294,
            "out_buffer_failure": 0,
            "out_collision": 0,
            "out_deferred": 0,
            "out_errors": 0,
            "out_late_collision": 0,
            "out_lost_carrier": 0,
            "out_mac_pause_frames": 0,
            "out_multicast_pkts": 25375569217,
            "out_no_carrier": 0,
            "out_octets": 183658868807300,
            "out_pkts": 189514390228,
            "out_underruns": 0,
            "out_unicast_pkts": 161859083717,
            "rate": {
                "in_rate_bytes": 1145,
                "in_rate_pkts": 2,
                "load_interval": 300,
                "out_rate_bytes": 542086,
                "out_rate_pkts": 514
            }
        },
        "description": "## TRUNK INTERFACE ##",
        "duplex_mode": "full",
        "enabled": True,
        "frame_type": "PKTFMT_ETHNT_2",
        "mac_address": "cc3e-5f69-abcd",
        "max_frame_length": 9216,
        "media_type": "twisted pair",
        "oper_status": "UP",
        "port_speed": "1000mbps",
        "port_type": "1000_BASE_T",
        "priority": 0,
        "pvid": 1,
        "switchport": {
            "encapsulation": "IEEE 802.1q",
            "mode": "trunk",
            "vlan_passing": [
                1,
                3,
                9,
                17,
                20,
                28,
                203,
                207,
                550
            ],
            "vlan_permitted": [
                1,
                3,
                9,
                17,
                20,
                28,
                203,
                207,
                550
            ]
        },
        "type": "GigabitEthernet"
    }
}


