expected_output = {
   "vrf":{
      "default":{
         "maximum_paths":32,
         "route_source":{
            "application":{
               "memory_bytes":0,
               "networks":0,
               "overhead":0,
               "replicates":0,
               "subnets":0
            },
            "bgp":{
               "13979":{
                  "external":0,
                  "internal":0,
                  "local":0,
                  "memory_bytes":0,
                  "networks":0,
                  "overhead":0,
                  "replicates":0,
                  "subnets":0
               }
            },
            "connected":{
               "memory_bytes":3952,
               "networks":0,
               "overhead":1248,
               "replicates":0,
               "subnets":13
            },
            "internal":{
               "memory_bytes":7000,
               "networks":15
            },
            "isis":{
               "Test":{
                  "inter_area":0,
                  "level_1":0,
                  "level_2":0,
                  "memory_bytes":0,
                  "networks":0,
                  "overhead":0,
                  "replicates":0,
                  "subnets":0
               },
               "inter_area":0,
               "level_1":0,
               "level_2":0,
               "memory_bytes":0,
               "networks":0,
               "overhead":0,
               "replicates":0,
               "subnets":0
            },
            "nhrp":{
               "memory_bytes":0,
               "networks":0,
               "overhead":0,
               "replicates":0,
               "subnets":0
            },
            "ospf":{
               "100":{
                  "external_1":0,
                  "external_2":0,
                  "inter_area":0,
                  "intra_area":0,
                  "memory_bytes":0,
                  "networks":0,
                  "nssa_external_1":0,
                  "nssa_external_2":0,
                  "overhead":0,
                  "replicates":0,
                  "subnets":0
               }
            },
            "static":{
               "memory_bytes":4256,
               "networks":0,
               "overhead":1344,
               "replicates":0,
               "subnets":14
            }
         },
         "total_route_source":{
            "memory_bytes":15208,
            "networks":15,
            "overhead":2592,
            "replicates":0,
            "subnets":27
         },
         "vrf_id":"0x0"
      }
   }
}