expected_output = {
    "configured_system_action": "Flood",
    "configured_system_limit": 111,
    "current_system_count": 3,
    "currently_system_is": "Flooding Unknown SA",
    "mac_table": {
        "vlans": {
            "1": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "1",
            },
            "10": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 1,
                "currently": "Flooding Unknown SA",
                "vlan": "10",
            },
            "100": {
                "cfg_action": "Flood",
                "conf_limit": 200,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "100",
            },
            "1000": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "1000",
            },
            "1005": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "1005",
            },
            "1006": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "1006",
            },
            "1007": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "1007",
            },
            "1008": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "1008",
            },
            "1009": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "1009",
            },
            "101": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "101",
            },
            "102": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "102",
            },
            "103": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "103",
            },
            "104": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "104",
            },
            "105": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "105",
            },
            "106": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "106",
            },
            "107": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "107",
            },
            "108": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "108",
            },
            "109": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "109",
            },
            "110": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "110",
            },
            "111": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "111",
            },
            "112": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "112",
            },
            "113": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "113",
            },
            "114": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "114",
            },
            "115": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "115",
            },
            "185": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "185",
            },
            "20": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 1,
                "currently": "Flooding Unknown SA",
                "vlan": "20",
            },
            "285": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "285",
            },
            "30": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 1,
                "currently": "Flooding Unknown SA",
                "vlan": "30",
            },
            "910": {
                "cfg_action": "Flood",
                "conf_limit": 196000,
                "curr_count": 0,
                "currently": "Flooding Unknown SA",
                "vlan": "910",
            },
        }
    },
}
