expected_output = {
     'entity_state': {
         'card_status': 'full',
         'card_status_code': 2,
         'last_spa_env_get_ok': False,
         'last_spa_env_read_time': 145245938,
         'last_spa_env_read_time_str': '(0) 145245938 msecs ago',
         'last_spa_type': 'EPA-18X1GE',
         'last_spa_type_hex': '0xC55',
         'last_trap_oper_status': 'ok',
         'last_trap_oper_status_code': 1,
         'last_trap_spa_type': 'EPA-18X1GE',
         'last_trap_spa_type_hex': '0xC55',
         'non_zero_spa_power_sensors': 'all power sensor indices are zero',
         'non_zero_spa_temp_sensors': {
             '0': 1546,
         },
         'non_zero_spa_volt_sensors': {
             '0': 1558,
             '1': 1559,
             '2': 1560,
             '3': 1561,
             '4': 1562,
             '5': 1563,
         },
         'oper_status': 'ok',
         'oper_status_code': 1,
         'resync_count': 0,
         'resync_reqd': False,
         'spa_container_index': 1028,
         'spa_physical_index': 1520,
         'spa_type': 'EPA-18X1GE',
         'spa_type_hex': '0xC55',
         'subslot': '0/1',
         'transceiver': {
             '0': {
                 'chassis_index': 0,
                 'container_index': 1571,
                 'operational_status': 'ok',
                 'operational_status_code': 2,
             },
             '1': {
                 'chassis_index': 0,
                 'container_index': 1583,
                 'operational_status': 'ok',
                 'operational_status_code': 2,
             },
             '10': {
                 'chassis_index': 0,
                 'container_index': 1691,
                 'operational_status': 'missing',
                 'operational_status_code': 6,
             },
             '11': {
                 'chassis_index': 0,
                 'container_index': 1703,
                 'operational_status': 'missing',
                 'operational_status_code': 6,
             },
             '12': {
                 'chassis_index': 0,
                 'container_index': 1715,
                 'operational_status': 'missing',
                 'operational_status_code': 6,
             },
             '13': {
                 'chassis_index': 0,
                 'container_index': 1727,
                 'operational_status': 'ok',
                 'operational_status_code': 2,
             },
             '14': {
                 'chassis_index': 0,
                 'container_index': 1739,
                 'operational_status': 'ok',
                 'operational_status_code': 2,
             },
             '15': {
                 'chassis_index': 0,
                 'container_index': 1751,
                 'operational_status': 'missing',
                 'operational_status_code': 6,
             },
             '16': {
                 'chassis_index': 0,
                 'container_index': 1763,
                 'operational_status': 'missing',
                 'operational_status_code': 6,
             },
             '17': {
                 'chassis_index': 0,
                 'container_index': 1775,
                 'operational_status': 'missing',
                 'operational_status_code': 6,
             },
             '2': {
                 'chassis_index': 0,
                 'container_index': 1595,
                 'operational_status': 'ok',
                 'operational_status_code': 2,
             },
             '3': {
                 'chassis_index': 0,
                 'container_index': 1607,
                 'operational_status': 'disabled',
                 'operational_status_code': 3,
             },
             '4': {
                 'chassis_index': 0,
                 'container_index': 1619,
                 'operational_status': 'ok',
                 'operational_status_code': 2,
             },
             '5': {
                 'chassis_index': 0,
                 'container_index': 1631,
                 'operational_status': 'disabled',
                 'operational_status_code': 3,
             },
             '6': {
                 'chassis_index': 0,
                 'container_index': 1643,
                 'operational_status': 'disabled',
                 'operational_status_code': 3,
             },
             '7': {
                 'chassis_index': 0,
                 'container_index': 1655,
                 'operational_status': 'ok',
                 'operational_status_code': 2,
             },
             '8': {
                 'chassis_index': 0,
                 'container_index': 1667,
                 'operational_status': 'missing',
                 'operational_status_code': 6,
             },
             '9': {
                 'chassis_index': 0,
                 'container_index': 1679,
                 'operational_status': 'ok',
                 'operational_status_code': 2,
             },
         },
     },
 }

