expected_output = {
	    'vrf': {'default': {'instance': {'1': {'1.1.1.1': {'network': {'count': 0,
                                                                'delete': 0,
                                                                'maxage': 0},
                                                    'opaque_area': {'count': 0,
                                                                    'delete': 0,
                                                                    'maxage': 0},
                                                    'opaque_as': {'count': 0,
                                                                  'delete': 0,
                                                                  'maxage': 0},
                                                    'opaque_link': {'count': 0,
                                                                    'delete': 0,
                                                                    'maxage': 0},
                                                    'router': {'count': 2,
                                                               'delete': 0,
                                                               'maxage': 0},
                                                    'summary_asbr': {'count': 0,
                                                                     'delete': 0,
                                                                     'maxage': 0},
                                                    'summary_net': {'count': 2,
                                                                    'delete': 0,
                                                                    'maxage': 0},
                                                    'total': {'count': 5,
                                                              'delete': 0,
                                                              'maxage': 0},
                                                    'type_5_ext': {'count': 1,
                                                                   'delete': 0,
                                                                   'maxage': 0},
                                                    'type_7_ext': {'count': 0,
                                                                   'delete': 0,
                                                                   'maxage': 0}},
                                        '2.2.2.2': {'network': {'count': 2,
                                                                'delete': 0,
                                                                'maxage': 0},
                                                    'opaque_area': {'count': 0,
                                                                    'delete': 0,
                                                                    'maxage': 0},
                                                    'opaque_as': {'count': 0,
                                                                  'delete': 0,
                                                                  'maxage': 0},
                                                    'opaque_link': {'count': 0,
                                                                    'delete': 0,
                                                                    'maxage': 0},
                                                    'router': {'count': 2,
                                                               'delete': 0,
                                                               'maxage': 0},
                                                    'summary_asbr': {'count': 2,
                                                                     'delete': 0,
                                                                     'maxage': 0},
                                                    'summary_net': {'count': 2,
                                                                    'delete': 0,
                                                                    'maxage': 0},
                                                    'total': {'count': 8,
                                                              'delete': 0,
                                                              'maxage': 0},
                                                    'type_5_ext': {'count': 0,
                                                                   'delete': 0,
                                                                   'maxage': 0},
                                                    'type_7_ext': {'count': 0,
                                                                   'delete': 0,
                                                                   'maxage': 0}
                                                                   }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
