expected_output = {
   "interfaces":{
      "Ethernet1/1":{
         "name":"KeepAlive",
         "status":"connected",
         "vlan":"routed",
         "duplex_code":"full",
         "port_speed":"10G",
         "type":"10g"
      },
      "Ethernet1/2":{
         "name":"AOTLXPRISS10004",
         "status":"connected",
         "vlan":"trunk",
         "duplex_code":"full",
         "port_speed":"10G",
         "type":"10g"
      },
      "mgmt0":{
         "name":"--",
         "status":"connected",
         "vlan":"routed",
         "duplex_code":"full",
         "port_speed":"1000",
         "type":"--"
      }
   }
}