expected_output = \
{'connections': {1: {'protocol': 'tcp',
                     'local_address': '6.6.6.6',
                     'local_port': 646,
                     'foreign_address': '192.168.1.5',
                     'foreign_port': 38540,
                     'program_name': '[IOS] Unknown',
                     'state': 'ESTAB',
                     'pid': 0},
                 2: {'protocol': 'tcp',
                     'local_address': '6.6.6.6',
                     'local_port': 17024,
                     'foreign_address': '192.168.1.6',
                     'foreign_port': 179,
                     'program_name': '[IOS] Unknown',
                     'state': 'ESTAB',
                     'pid': 0},
                 3: {'protocol': 'tcp',
                     'local_address': '::',
                     'local_port': 21111,
                     'foreign_address': '::',
                     'foreign_port': '*',
                     'program_name': '[IOS]HTTP CORE',
                     'state': 'LISTEN',
                     'pid': 318},
                 4: {'protocol': 'tcp',
                     'local_address': '*',
                     'local_port': 21111,
                     'foreign_address': '*',
                     'foreign_port': '*',
                     'program_name': '[IOS]HTTP CORE',
                     'state': 'LISTEN',
                     'pid': 318},
                 5: {'protocol': 'tcp',
                     'local_address': '*',
                     'local_port': 179,
                     'foreign_address': '192.168.1.6',
                     'foreign_port': '*',
                     'program_name': '[IOS]TCP Listener',
                     'state': 'LISTEN',
                     'pid': 612},
                 6: {'protocol': 'tcp',
                     'local_address': '*',
                     'local_port': 179,
                     'foreign_address': '192.168.1.1',
                     'foreign_port': '*',
                     'program_name': '[IOS]TCP Listener',
                     'state': 'LISTEN',
                     'pid': 612},
                 7: {'protocol': 'tcp',
                     'local_address': '*',
                     'local_port': 23,
                     'foreign_address': '*',
                     'foreign_port': '*',
                     'program_name': '[IOS]Telnet',
                     'state': 'LISTEN'},
                 8: {'protocol': 'tcp',
                     'local_address': '::',
                     'local_port': 23,
                     'foreign_address': '::',
                     'foreign_port': '*',
                     'program_name': '[IOS]Telnet',
                     'state': 'LISTEN'},
                 9: {'protocol': 'tcp',
                     'local_address': '*',
                     'local_port': 22,
                     'foreign_address': '*',
                     'foreign_port': '*',
                     'program_name': '[IOS]SSH',
                     'state': 'LISTEN'},
                 10: {'protocol': 'tcp',
                      'local_address': '::',
                      'local_port': 22,
                      'foreign_address': '::',
                      'foreign_port': '*',
                      'program_name': '[IOS]SSH',
                      'state': 'LISTEN'},
                 11: {'protocol': 'udp',
                      'local_address': '1.2.43.1',
                      'local_port': 646,
                      'foreign_address': '*',
                      'foreign_port': '*',
                      'program_name': '[IOS]LDP Hello',
                      'pid': 593},
                 12: {'protocol': 'udp',
                      'local_address': '1.2.43.1',
                      'local_port': 3503,
                      'foreign_address': '*',
                      'foreign_port': '*',
                      'program_name': '[IOS]LSP Verification Manager',
                      'pid': 601},
                 13: {'protocol': 'tcp',
                      'local_address': '0.0.0.0',
                      'local_port': 830,
                      'foreign_address': '0.0.0.0',
                      'foreign_port': '*',
                      'program_name': 'ncsshd',
                      'state': 'LISTEN',
                      'pid': 3547},
                 14: {'protocol': 'tcp6',
                      'local_address': '::',
                      'local_port': 830,
                      'foreign_address': '::',
                      'foreign_port': '*',
                      'program_name': 'ncsshd',
                      'state': 'LISTEN',
                      'pid': 3547},
                 15: {'protocol': 'tcp',
                      'local_address': '127.0.0.1',
                      'local_port': 8281,
                      'foreign_address': '0.0.0.0',
                      'foreign_port': '*',
                      'program_name': 'ncsshd',
                      'state': 'LISTEN',
                      'pid': 3547}}}
