expected_output = {
    "ospf3-database-information": {
        "ospf3-database": [
            {
                "@heading": "Type       ID               Adv Rtr           Seq         Age  Cksum  Len",
                "advertising-router": "192.168.219.235",
                "age": "1379",
                "checksum": "0xd3b0",
                "lsa-id": "0.0.0.9",
                "lsa-length": "56",
                "lsa-type": "Link",
                "ospf3-link-lsa": {
                    "linklocal-address": "fe80::20c:2900:3367:243d",
                    "ospf3-options": "0x33",
                    "ospf3-prefix": "2001:db8:dae9:cf16::/64",
                    "ospf3-prefix-options": "0x0",
                    "prefix-count": "1",
                    "router-priority": "20",
                },
                "our-entry": True,
                "sequence-number": "0x80000b10",
            },
            {
                "@heading": "Type       ID               Adv Rtr           Seq         Age  Cksum  Len",
                "advertising-router": "192.168.219.235",
                "age": "1979",
                "checksum": "0x974d",
                "lsa-id": "0.0.0.10",
                "lsa-length": "56",
                "lsa-type": "Link",
                "ospf3-link-lsa": {
                    "linklocal-address": "fe80::20c:2900:3467:243d",
                    "ospf3-options": "0x33",
                    "ospf3-prefix": "2001:db8:dae9:c9df::/64",
                    "ospf3-prefix-options": "0x0",
                    "prefix-count": "1",
                    "router-priority": "128",
                },
                "our-entry": True,
                "sequence-number": "0x80000b0f",
            },
            {
                "@heading": "Type       ID               Adv Rtr           Seq         Age  Cksum  Len",
                "advertising-router": "192.168.219.235",
                "age": "1829",
                "checksum": "0x94c2",
                "lsa-id": "0.0.0.11",
                "lsa-length": "56",
                "lsa-type": "Link",
                "ospf3-link-lsa": {
                    "linklocal-address": "fe80::20c:2900:3667:2465",
                    "ospf3-options": "0x33",
                    "ospf3-prefix": "2001:db8:dae9:d3e9::/64",
                    "ospf3-prefix-options": "0x0",
                    "prefix-count": "1",
                    "router-priority": "20",
                },
                "our-entry": True,
                "sequence-number": "0x80000b0f",
            },
            {
                "@heading": "Type       ID               Adv Rtr           Seq         Age  Cksum  Len",
                "advertising-router": "192.168.219.235",
                "age": "1679",
                "checksum": "0x5660",
                "lsa-id": "0.0.0.12",
                "lsa-length": "56",
                "lsa-type": "Link",
                "ospf3-link-lsa": {
                    "linklocal-address": "fe80::20c:2900:3767:2465",
                    "ospf3-options": "0x33",
                    "ospf3-prefix": "2001:db8:dae9:cf16::/64",
                    "ospf3-prefix-options": "0x0",
                    "prefix-count": "1",
                    "router-priority": "128",
                },
                "our-entry": True,
                "sequence-number": "0x80000b0f",
            },
            {
                "@heading": "Type       ID               Adv Rtr           Seq         Age  Cksum  Len",
                "advertising-router": "192.168.219.235",
                "age": "2729",
                "checksum": "0xd0a6",
                "lsa-id": "0.0.0.7",
                "lsa-length": "44",
                "lsa-type": "Link",
                "ospf3-link-lsa": {
                    "linklocal-address": "fe80::20c:290f:fc40:a033",
                    "ospf3-options": "0x33",
                    "prefix-count": "0",
                    "router-priority": "128",
                },
                "our-entry": True,
                "sequence-number": "0x80000f62",
            },
        ],
        "ospf3-intf-header": [
            {"ospf-area": "0.0.0.0", "ospf-intf": "ge-0/0/2.0"},
            {"ospf-area": "0.0.0.0", "ospf-intf": "ge-0/0/2.1"},
            {"ospf-area": "0.0.0.0", "ospf-intf": "ge-0/0/3.0"},
            {"ospf-area": "0.0.0.0", "ospf-intf": "ge-0/0/3.1"},
            {"ospf-area": "0.0.0.0", "ospf-intf": "lo0.0"},
        ],
    }
}
