expected_output =  {
    'bind_information': {
        'iqp_counter_oid': '0x0',
        'iqp_counter_size': 0,
        'meter_set_info': {
            '0': {
                'action_profile_oid': '0x110',
                'cir': 9808593920,
                'eir': 9808593920,
                'profile_oid': '0x8EF',
            },
            '1': {
                'action_profile_oid': '0x110',
                'cir': 9808593920,
                'eir': 9808593920,
                'profile_oid': '0x8EF',
            },
            '2': {
                'action_profile_oid': '0x8F0',
                'cir': 4904296960,
                'eir': 4904296960,
                'profile_oid': '0x8EF',
            },
            '3': {
                'action_profile_oid': '0xFFFFFFFF',
                'cir': 0,
                'eir': 0,
                'profile_oid': '0xFFFFFFFF',
            },
        },
        'meter_set_oid': '0x8CF',
        'meter_type': 'EXACT',
        'no_of_meters': 4,
        'port_internal_state': 'Active',
        'port_oid': '0x0',
        'port_type': 'L3',
        'speed': 10000000000,
        'system_port_oid': '0x0',
    },
    'interface': {
        'HundredGigE1/0/5': {
            'cgid': '0x738310',
            'filter_state': 'UP TO DATE',
            'no_of_classes': 4,
            'tcg_ref_count': 1,
            'vmr_state': 'UP TO DATE',
        },
    },
    'ipv4_acl': {
        'ace': {
            0: {
                'class_id': '0x0',
                'dscp': '0x8',
                'dscp_mask': '0x3f',
                'dst_port_end': '0x0',
                'dst_port_start': '0x0',
                'ip_flags': '0x0',
                'ip_mask': '0x0',
                'ipv4_dst_address': '0.0.0.0',
                'ipv4_dst_mask': '0.0.0.0',
                'ipv4_src_address': '0.0.0.0',
                'ipv4_src_mask': '0.0.0.0',
                'protocol': '0x0',
                'protocol_mask': '0x0',
                'result_action': {
                    'drop_precedence': 'G',
                    'encap_value': '0',
                    'meter_counter_offset': '0',
                    'meter_enabled': 'Y',
                    'overwrite_encap': 'N',
                    'overwrite_fwd_tag': 'N',
                    'overwrite_phb': 'N',
                    'overwrite_qos_group': 'N',
                    'qos_group': '0',
                    'remark_value': '0',
                    'traffic_class': '0',
                },
                'src_port_end': '0x0',
                'src_port_start': '0x0',
                'tcp_flags': '0x0',
                'tcp_mask': '0x0',
                'ttl_end': '0x0',
                'ttl_start': '0x0',
            },
            1: {
                'class_id': '0x0',
                'dscp': '0x10',
                'dscp_mask': '0x3f',
                'dst_port_end': '0x0',
                'dst_port_start': '0x0',
                'ip_flags': '0x0',
                'ip_mask': '0x0',
                'ipv4_dst_address': '0.0.0.0',
                'ipv4_dst_mask': '0.0.0.0',
                'ipv4_src_address': '0.0.0.0',
                'ipv4_src_mask': '0.0.0.0',
                'protocol': '0x0',
                'protocol_mask': '0x0',
                'result_action': {
                    'drop_precedence': 'G',
                    'encap_value': '0',
                    'meter_counter_offset': '1',
                    'meter_enabled': 'Y',
                    'overwrite_encap': 'N',
                    'overwrite_fwd_tag': 'N',
                    'overwrite_phb': 'N',
                    'overwrite_qos_group': 'N',
                    'qos_group': '0',
                    'remark_value': '0',
                    'traffic_class': '0',
                },
                'src_port_end': '0x0',
                'src_port_start': '0x0',
                'tcp_flags': '0x0',
                'tcp_mask': '0x0',
                'ttl_end': '0x0',
                'ttl_start': '0x0',
            },
            2: {
                'class_id': '0x0',
                'dscp': '0x28',
                'dscp_mask': '0x3f',
                'dst_port_end': '0x0',
                'dst_port_start': '0x0',
                'ip_flags': '0x0',
                'ip_mask': '0x0',
                'ipv4_dst_address': '0.0.0.0',
                'ipv4_dst_mask': '0.0.0.0',
                'ipv4_src_address': '0.0.0.0',
                'ipv4_src_mask': '0.0.0.0',
                'protocol': '0x0',
                'protocol_mask': '0x0',
                'result_action': {
                    'drop_precedence': 'G',
                    'encap_value': '0',
                    'meter_counter_offset': '2',
                    'meter_enabled': 'Y',
                    'overwrite_encap': 'N',
                    'overwrite_fwd_tag': 'N',
                    'overwrite_phb': 'Y',
                    'overwrite_qos_group': 'N',
                    'qos_group': '0',
                    'remark_value': '0',
                    'traffic_class': '6',
                },
                'src_port_end': '0x0',
                'src_port_start': '0x0',
                'tcp_flags': '0x0',
                'tcp_mask': '0x0',
                'ttl_end': '0x0',
                'ttl_start': '0x0',
            },
        },
        'number_of_aces': 3,
        'oid': '0x849',
    },
    'ipv6_acl': {
        'ace': {
            0: {
                'class_id': '0x0',
                'dscp': '0x8',
                'dscp_mask': '0x3f',
                'dst_port_end': '0x0',
                'dst_port_start': '0x0',
                'ip_flags': '0x0',
                'ip_mask': '0x0',
                'ipv6_dst_address': '::',
                'ipv6_dst_mask': '::',
                'ipv6_src_address': '::',
                'ipv6_src_mask': '::',
                'protocol': '0x0',
                'protocol_mask': '0x0',
                'result_action': {
                    'drop_precedence': 'G',
                    'encap_value': '0',
                    'meter_counter_offset': '0',
                    'meter_enabled': 'Y',
                    'overwrite_encap': 'N',
                    'overwrite_fwd_tag': 'N',
                    'overwrite_phb': 'N',
                    'overwrite_qos_group': 'N',
                    'qos_group': '0',
                    'remark_value': '0',
                    'traffic_class': '0',
                },
                'src_port_end': '0x0',
                'src_port_start': '0x0',
                'tcp_flags': '0x0',
                'tcp_mask': '0x0',
                'ttl_end': '0x0',
                'ttl_start': '0x0',
            },
            1: {
                'class_id': '0x0',
                'dscp': '0x10',
                'dscp_mask': '0x3f',
                'dst_port_end': '0x0',
                'dst_port_start': '0x0',
                'ip_flags': '0x0',
                'ip_mask': '0x0',
                'ipv6_dst_address': '::',
                'ipv6_dst_mask': '::',
                'ipv6_src_address': '::',
                'ipv6_src_mask': '::',
                'protocol': '0x0',
                'protocol_mask': '0x0',
                'result_action': {
                    'drop_precedence': 'G',
                    'encap_value': '0',
                    'meter_counter_offset': '1',
                    'meter_enabled': 'Y',
                    'overwrite_encap': 'N',
                    'overwrite_fwd_tag': 'N',
                    'overwrite_phb': 'N',
                    'overwrite_qos_group': 'N',
                    'qos_group': '0',
                    'remark_value': '0',
                    'traffic_class': '0',
                },
                'src_port_end': '0x0',
                'src_port_start': '0x0',
                'tcp_flags': '0x0',
                'tcp_mask': '0x0',
                'ttl_end': '0x0',
                'ttl_start': '0x0',
            },
            2: {
                'class_id': '0x0',
                'dscp': '0x28',
                'dscp_mask': '0x3f',
                'dst_port_end': '0x0',
                'dst_port_start': '0x0',
                'ip_flags': '0x0',
                'ip_mask': '0x0',
                'ipv6_dst_address': '::',
                'ipv6_dst_mask': '::',
                'ipv6_src_address': '::',
                'ipv6_src_mask': '::',
                'protocol': '0x0',
                'protocol_mask': '0x0',
                'result_action': {
                    'drop_precedence': 'G',
                    'encap_value': '0',
                    'meter_counter_offset': '2',
                    'meter_enabled': 'Y',
                    'overwrite_encap': 'N',
                    'overwrite_fwd_tag': 'N',
                    'overwrite_phb': 'Y',
                    'overwrite_qos_group': 'N',
                    'qos_group': '0',
                    'remark_value': '0',
                    'traffic_class': '6',
                },
                'src_port_end': '0x0',
                'src_port_start': '0x0',
                'tcp_flags': '0x0',
                'tcp_mask': '0x0',
                'ttl_end': '0x0',
                'ttl_start': '0x0',
            },
        },
        'number_of_aces': 3,
        'oid': '0x84A',
    },
    'markdown_table': {
        'dscp': {
            '0': {
                'green': 0,
                'red': 0,
                'yellow': 0,
            },
            '1': {
                'green': 1,
                'red': 1,
                'yellow': 1,
            },
            '10': {
                'green': 10,
                'red': 10,
                'yellow': 10,
            },
            '11': {
                'green': 11,
                'red': 11,
                'yellow': 11,
            },
            '12': {
                'green': 12,
                'red': 12,
                'yellow': 12,
            },
            '13': {
                'green': 13,
                'red': 13,
                'yellow': 13,
            },
            '14': {
                'green': 14,
                'red': 14,
                'yellow': 14,
            },
            '15': {
                'green': 15,
                'red': 15,
                'yellow': 15,
            },
            '16': {
                'green': 16,
                'red': 32,
                'yellow': 32,
            },
            '17': {
                'green': 17,
                'red': 17,
                'yellow': 17,
            },
            '18': {
                'green': 18,
                'red': 18,
                'yellow': 18,
            },
            '19': {
                'green': 19,
                'red': 19,
                'yellow': 19,
            },
            '2': {
                'green': 2,
                'red': 2,
                'yellow': 2,
            },
            '20': {
                'green': 20,
                'red': 20,
                'yellow': 20,
            },
            '21': {
                'green': 21,
                'red': 21,
                'yellow': 21,
            },
            '22': {
                'green': 22,
                'red': 22,
                'yellow': 22,
            },
            '23': {
                'green': 23,
                'red': 23,
                'yellow': 23,
            },
            '24': {
                'green': 24,
                'red': 24,
                'yellow': 24,
            },
            '25': {
                'green': 25,
                'red': 25,
                'yellow': 25,
            },
            '26': {
                'green': 26,
                'red': 26,
                'yellow': 26,
            },
            '27': {
                'green': 27,
                'red': 27,
                'yellow': 27,
            },
            '28': {
                'green': 28,
                'red': 28,
                'yellow': 28,
            },
            '29': {
                'green': 29,
                'red': 29,
                'yellow': 29,
            },
            '3': {
                'green': 3,
                'red': 3,
                'yellow': 3,
            },
            '30': {
                'green': 30,
                'red': 30,
                'yellow': 30,
            },
            '31': {
                'green': 31,
                'red': 31,
                'yellow': 31,
            },
            '32': {
                'green': 32,
                'red': 24,
                'yellow': 24,
            },
            '33': {
                'green': 33,
                'red': 33,
                'yellow': 33,
            },
            '34': {
                'green': 34,
                'red': 34,
                'yellow': 34,
            },
            '35': {
                'green': 35,
                'red': 35,
                'yellow': 35,
            },
            '36': {
                'green': 36,
                'red': 36,
                'yellow': 36,
            },
            '37': {
                'green': 37,
                'red': 37,
                'yellow': 37,
            },
            '38': {
                'green': 38,
                'red': 38,
                'yellow': 38,
            },
            '39': {
                'green': 39,
                'red': 39,
                'yellow': 39,
            },
            '4': {
                'green': 4,
                'red': 4,
                'yellow': 4,
            },
            '40': {
                'green': 40,
                'red': 24,
                'yellow': 24,
            },
            '41': {
                'green': 41,
                'red': 41,
                'yellow': 41,
            },
            '42': {
                'green': 42,
                'red': 42,
                'yellow': 42,
            },
            '43': {
                'green': 43,
                'red': 43,
                'yellow': 43,
            },
            '44': {
                'green': 44,
                'red': 44,
                'yellow': 44,
            },
            '45': {
                'green': 45,
                'red': 45,
                'yellow': 45,
            },
            '46': {
                'green': 46,
                'red': 46,
                'yellow': 46,
            },
            '47': {
                'green': 47,
                'red': 47,
                'yellow': 47,
            },
            '48': {
                'green': 48,
                'red': 56,
                'yellow': 56,
            },
            '49': {
                'green': 49,
                'red': 49,
                'yellow': 49,
            },
            '5': {
                'green': 5,
                'red': 5,
                'yellow': 5,
            },
            '50': {
                'green': 50,
                'red': 50,
                'yellow': 50,
            },
            '51': {
                'green': 51,
                'red': 51,
                'yellow': 51,
            },
            '52': {
                'green': 52,
                'red': 52,
                'yellow': 52,
            },
            '53': {
                'green': 53,
                'red': 53,
                'yellow': 53,
            },
            '54': {
                'green': 54,
                'red': 54,
                'yellow': 54,
            },
            '55': {
                'green': 55,
                'red': 55,
                'yellow': 55,
            },
            '56': {
                'green': 56,
                'red': 56,
                'yellow': 56,
            },
            '57': {
                'green': 57,
                'red': 57,
                'yellow': 57,
            },
            '58': {
                'green': 58,
                'red': 58,
                'yellow': 58,
            },
            '59': {
                'green': 59,
                'red': 59,
                'yellow': 59,
            },
            '6': {
                'green': 6,
                'red': 6,
                'yellow': 6,
            },
            '60': {
                'green': 60,
                'red': 60,
                'yellow': 60,
            },
            '61': {
                'green': 61,
                'red': 61,
                'yellow': 61,
            },
            '62': {
                'green': 62,
                'red': 62,
                'yellow': 62,
            },
            '63': {
                'green': 63,
                'red': 63,
                'yellow': 63,
            },
            '7': {
                'green': 7,
                'red': 7,
                'yellow': 7,
            },
            '8': {
                'green': 8,
                'red': 16,
                'yellow': 16,
            },
            '9': {
                'green': 9,
                'red': 9,
                'yellow': 9,
            },
        },
        'encapexp': {
            '0': {
                'green': 0,
                'red': 0,
                'yellow': 0,
            },
            '1': {
                'green': 1,
                'red': 1,
                'yellow': 1,
            },
            '2': {
                'green': 2,
                'red': 2,
                'yellow': 2,
            },
            '3': {
                'green': 3,
                'red': 3,
                'yellow': 3,
            },
            '4': {
                'green': 4,
                'red': 4,
                'yellow': 4,
            },
            '5': {
                'green': 5,
                'red': 5,
                'yellow': 5,
            },
            '6': {
                'green': 6,
                'red': 6,
                'yellow': 6,
            },
            '7': {
                'green': 7,
                'red': 7,
                'yellow': 7,
            },
        },
        'exp': {
            '0': {
                'green': 0,
                'red': 0,
                'yellow': 0,
            },
            '1': {
                'green': 1,
                'red': 1,
                'yellow': 1,
            },
            '2': {
                'green': 2,
                'red': 2,
                'yellow': 2,
            },
            '3': {
                'green': 3,
                'red': 3,
                'yellow': 3,
            },
            '4': {
                'green': 4,
                'red': 4,
                'yellow': 4,
            },
            '5': {
                'green': 5,
                'red': 5,
                'yellow': 5,
            },
            '6': {
                'green': 6,
                'red': 6,
                'yellow': 6,
            },
            '7': {
                'green': 7,
                'red': 7,
                'yellow': 7,
            },
        },
        'oid': '0x855',
        'pcpdei': {
            '0': {
                'green': 0,
                'red': 0,
                'yellow': 0,
            },
            '1': {
                'green': 1,
                'red': 1,
                'yellow': 1,
            },
            '10': {
                'green': 10,
                'red': 10,
                'yellow': 10,
            },
            '11': {
                'green': 11,
                'red': 11,
                'yellow': 11,
            },
            '12': {
                'green': 12,
                'red': 12,
                'yellow': 12,
            },
            '13': {
                'green': 13,
                'red': 13,
                'yellow': 13,
            },
            '14': {
                'green': 14,
                'red': 14,
                'yellow': 14,
            },
            '15': {
                'green': 15,
                'red': 15,
                'yellow': 15,
            },
            '2': {
                'green': 2,
                'red': 2,
                'yellow': 2,
            },
            '3': {
                'green': 3,
                'red': 3,
                'yellow': 3,
            },
            '4': {
                'green': 4,
                'red': 4,
                'yellow': 4,
            },
            '5': {
                'green': 5,
                'red': 5,
                'yellow': 5,
            },
            '6': {
                'green': 6,
                'red': 6,
                'yellow': 6,
            },
            '7': {
                'green': 7,
                'red': 7,
                'yellow': 7,
            },
            '8': {
                'green': 8,
                'red': 8,
                'yellow': 8,
            },
            '9': {
                'green': 9,
                'red': 9,
                'yellow': 9,
            },
        },
    },
    'qos_profile_information': {
        'cos_dei': {
            '0': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 0,
                'tc': 0,
            },
            '1': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 1,
                'tc': 0,
            },
            '10': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 10,
                'tc': 7,
            },
            '11': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 11,
                'tc': 7,
            },
            '12': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 12,
                'tc': 0,
            },
            '13': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 13,
                'tc': 0,
            },
            '14': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 14,
                'tc': 0,
            },
            '15': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 15,
                'tc': 0,
            },
            '2': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 2,
                'tc': 0,
            },
            '3': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 3,
                'tc': 0,
            },
            '4': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 4,
                'tc': 0,
            },
            '5': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 5,
                'tc': 0,
            },
            '6': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 6,
                'tc': 0,
            },
            '7': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 7,
                'tc': 0,
            },
            '8': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 8,
                'tc': 7,
            },
            '9': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 9,
                'tc': 7,
            },
        },
        'dscp': {
            '0': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 0,
                'tc': 0,
            },
            '1': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 1,
                'tc': 0,
            },
            '10': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 10,
                'tc': 0,
            },
            '11': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 11,
                'tc': 0,
            },
            '12': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 12,
                'tc': 0,
            },
            '13': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 13,
                'tc': 0,
            },
            '14': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 14,
                'tc': 0,
            },
            '15': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 15,
                'tc': 0,
            },
            '16': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 16,
                'tc': 7,
            },
            '17': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 17,
                'tc': 0,
            },
            '18': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 18,
                'tc': 0,
            },
            '19': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 19,
                'tc': 0,
            },
            '2': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 2,
                'tc': 0,
            },
            '20': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 20,
                'tc': 0,
            },
            '21': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 21,
                'tc': 0,
            },
            '22': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 22,
                'tc': 0,
            },
            '23': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 23,
                'tc': 0,
            },
            '24': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 24,
                'tc': 7,
            },
            '25': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 25,
                'tc': 0,
            },
            '26': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 26,
                'tc': 0,
            },
            '27': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 27,
                'tc': 0,
            },
            '28': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 28,
                'tc': 0,
            },
            '29': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 29,
                'tc': 0,
            },
            '3': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 3,
                'tc': 0,
            },
            '30': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 30,
                'tc': 0,
            },
            '31': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 31,
                'tc': 0,
            },
            '32': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 32,
                'tc': 7,
            },
            '33': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 33,
                'tc': 0,
            },
            '34': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 34,
                'tc': 0,
            },
            '35': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 35,
                'tc': 0,
            },
            '36': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 36,
                'tc': 0,
            },
            '37': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 37,
                'tc': 0,
            },
            '38': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 38,
                'tc': 0,
            },
            '39': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 39,
                'tc': 0,
            },
            '4': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 4,
                'tc': 0,
            },
            '40': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 40,
                'tc': 7,
            },
            '41': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 41,
                'tc': 0,
            },
            '42': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 42,
                'tc': 0,
            },
            '43': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 43,
                'tc': 0,
            },
            '44': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 44,
                'tc': 0,
            },
            '45': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 45,
                'tc': 0,
            },
            '46': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 46,
                'tc': 7,
            },
            '47': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 47,
                'tc': 0,
            },
            '48': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 48,
                'tc': 7,
            },
            '49': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 49,
                'tc': 0,
            },
            '5': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 5,
                'tc': 0,
            },
            '50': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 50,
                'tc': 0,
            },
            '51': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 51,
                'tc': 0,
            },
            '52': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 52,
                'tc': 0,
            },
            '53': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 53,
                'tc': 0,
            },
            '54': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 54,
                'tc': 0,
            },
            '55': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 55,
                'tc': 0,
            },
            '56': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 56,
                'tc': 7,
            },
            '57': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 57,
                'tc': 0,
            },
            '58': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 58,
                'tc': 0,
            },
            '59': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 59,
                'tc': 0,
            },
            '6': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 6,
                'tc': 0,
            },
            '60': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 60,
                'tc': 0,
            },
            '61': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 61,
                'tc': 0,
            },
            '62': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 62,
                'tc': 0,
            },
            '63': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 63,
                'tc': 0,
            },
            '7': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 7,
                'tc': 0,
            },
            '8': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 8,
                'tc': 0,
            },
            '9': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 9,
                'tc': 0,
            },
        },
        'exp': {
            '0': {
                'dp': 'G',
                'encap': 0,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 0,
                'tc': 0,
            },
            '1': {
                'dp': 'G',
                'encap': 1,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 1,
                'tc': 0,
            },
            '2': {
                'dp': 'G',
                'encap': 2,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 2,
                'tc': 0,
            },
            '3': {
                'dp': 'G',
                'encap': 3,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 3,
                'tc': 0,
            },
            '4': {
                'dp': 'G',
                'encap': 4,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 4,
                'tc': 0,
            },
            '5': {
                'dp': 'G',
                'encap': 5,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 5,
                'tc': 0,
            },
            '6': {
                'dp': 'G',
                'encap': 6,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 6,
                'tc': 0,
            },
            '7': {
                'dp': 'G',
                'encap': 7,
                'mc_offset': 3,
                'meter': 'Y',
                'qos_group': 0,
                'remap': 7,
                'tc': 0,
            },
        },
        'need_filter_table_update': 'UPTODATE',
        'no_of_counter': 1,
        'no_of_meters': 3,
        'oid': '0x82F',
        'ref_count': 1,
        'tunnel_mode': 'RE-EVALUATE',
    },
}