expected_output={
    'interface':{
      'HundredGigE1/0/3':{
         'if_id':'0x54B',
         'dropped_pkts':3
      },
      'HundredGigE2/0/28':{
         'if_id':'0x54F',
         'dropped_pkts':15
      },
   },
}
