expected_output ={'drop_counters': {
                    0: {'drop_th0': 0,
                         'drop_th1': 0,
                         'drop_th2': 0,
                         'q_eb_drop': 0,
                         'q_policer_drop': 0,
                         's_buf_drop': 0},
                   1: {'drop_th0': 0,
                         'drop_th1': 0,
                         'drop_th2': 0,
                         'q_eb_drop': 0,
                         'q_policer_drop': 0,
                         's_buf_drop': 0},
                   2: {'drop_th0': 0,
                         'drop_th1': 0,
                         'drop_th2': 0,
                         'q_eb_drop': 0,
                         'q_policer_drop': 0,
                         's_buf_drop': 0},
                   3: {'drop_th0': 0,
                         'drop_th1': 0,
                         'drop_th2': 0,
                         'q_eb_drop': 0,
                         'q_policer_drop': 0,
                         's_buf_drop': 0},
                   4: {'drop_th0': 0,
                         'drop_th1': 0,
                         'drop_th2': 0,
                         'q_eb_drop': 0,
                         'q_policer_drop': 0,
                         's_buf_drop': 0},
                   5: {'drop_th0': 0,
                         'drop_th1': 0,
                         'drop_th2': 0,
                         'q_eb_drop': 0,
                         'q_policer_drop': 0,
                         's_buf_drop': 0},
                   6: {'drop_th0': 0,
                         'drop_th1': 0,
                         'drop_th2': 0,
                         'q_eb_drop': 0,
                         'q_policer_drop': 0,
                         's_buf_drop': 0},
                   7: {'drop_th0': 0,
                         'drop_th1': 0,
                         'drop_th2': 0,
                         'q_eb_drop': 0,
                         'q_policer_drop': 0,
                         's_buf_drop': 0}},
 'enqueue_counters': {0: {'buffers_count': 0,
                            'enqueue_th0': 0,
                            'enqueue_th1': 13114,
                            'enqueue_th2': 129171972,
                            'q_policer': 0},
                      1: {'buffers_count': 0,
                            'enqueue_th0': 0,
                            'enqueue_th1': 0,
                            'enqueue_th2': 546062296,
                            'q_policer': 0},
                      2: {'buffers_count': 0,
                            'enqueue_th0': 0,
                            'enqueue_th1': 0,
                            'enqueue_th2': 0,
                            'q_policer': 0},
                      3: {'buffers_count': 0,
                            'enqueue_th0': 0,
                            'enqueue_th1': 0,
                            'enqueue_th2': 0,
                            'q_policer': 0},
                      4: {'buffers_count': 0,
                            'enqueue_th0': 0,
                            'enqueue_th1': 0,
                            'enqueue_th2': 0,
                            'q_policer': 0},
                      5: {'buffers_count': 0,
                            'enqueue_th0': 0,
                            'enqueue_th1': 0,
                            'enqueue_th2': 0,
                            'q_policer': 0},
                      6: {'buffers_count': 0,
                            'enqueue_th0': 0,
                            'enqueue_th1': 0,
                            'enqueue_th2': 0,
                            'q_policer': 0},
                      7: {'buffers_count': 0,
                            'enqueue_th0': 0,
                            'enqueue_th1': 0,
                            'enqueue_th2': 0,
                            'q_policer': 0}}}


