expected_output = {
    'tm_traps': {
        'trap_10_asic_0': {
            'asic': '0',
            'current': 129492,
            'delta': 0,
            'prev': 129492,
            'tm_trap': 'RXPDR_RXRQ1_VN_OVERFLOW',
            'trap_id': '10',
        },
        'trap_11_asic_0': {
            'asic': '0',
            'current': 129819,
            'delta': 0,
            'prev': 129819,
            'tm_trap': 'RXPDR_RXRQ2_OVERFLOW',
            'trap_id': '11',
        },
        'trap_12_asic_0': {
            'asic': '0',
            'current': 105216,
            'delta': 0,
            'prev': 105216,
            'tm_trap': 'RXPDR_RXRQ3_OVERFLOW',
            'trap_id': '12',
        },
        'trap_13_asic_0': {
            'asic': '0',
            'current': 105847,
            'delta': 0,
            'prev': 105847,
            'tm_trap': 'SRC_CGM_SQ_OR_SQG',
            'trap_id': '13',
        },
        'trap_14_asic_0': {
            'asic': '0',
            'current': 93005,
            'delta': 0,
            'prev': 93005,
            'tm_trap': 'SRC_CGM_CTC_OR_CTCG',
            'trap_id': '14',
        },
        'trap_15_asic_0': {
            'asic': '0',
            'current': 105796,
            'delta': 0,
            'prev': 105796,
            'tm_trap': 'SRC_CGM_HEADROOM',
            'trap_id': '15',
        },
        'trap_16_asic_0': {
            'asic': '0',
            'current': 143393,
            'delta': 0,
            'prev': 143393,
            'tm_trap': 'VOQ_CGM_TOTAL_EVICTED_BUFFERS_YELLOW',
            'trap_id': '16',
        },
        'trap_17_asic_0': {
            'asic': '0',
            'current': 106203,
            'delta': 0,
            'prev': 106203,
            'tm_trap': 'VOQ_CGM_TOTAL_EVICTED_BUFFERS_GREEN',
            'trap_id': '17',
        },
        'trap_18_asic_0': {
            'asic': '0',
            'current': 117619,
            'delta': 0,
            'prev': 117619,
            'tm_trap': 'VOQ_CGM_SMS_WRED_BUFFERS_GREEN',
            'trap_id': '18',
        },
        'trap_19_asic_0': {
            'asic': '0',
            'current': 129716,
            'delta': 0,
            'prev': 129716,
            'tm_trap': 'VOQ_CGM_SMS_WRED_BUFFERS_YELLOW',
            'trap_id': '19',
        },
        'trap_20_asic_0': {
            'asic': '0',
            'current': 117170,
            'delta': 0,
            'prev': 117170,
            'tm_trap': 'VOQ_CGM_SMS_PDS_YELLOW',
            'trap_id': '20',
        },
        'trap_21_asic_0': {
            'asic': '0',
            'current': 93896,
            'delta': 0,
            'prev': 93896,
            'tm_trap': 'VOQ_CGM_SMS_PDS_GREEN',
            'trap_id': '21',
        },
        'trap_22_asic_0': {
            'asic': '0',
            'current': 92587,
            'delta': 0,
            'prev': 92587,
            'tm_trap': 'VOQ_CGM_DRAM_BUFFERS_YELLOW',
            'trap_id': '22',
        },
        'trap_23_asic_0': {
            'asic': '0',
            'current': 130765,
            'delta': 0,
            'prev': 130765,
            'tm_trap': 'VOQ_CGM_DRAM_BUFFERS_GREEN',
            'trap_id': '23',
        },
        'trap_24_asic_0': {
            'asic': '0',
            'current': 105748,
            'delta': 0,
            'prev': 105748,
            'tm_trap': 'VOQ_CGM_DRAM_WRED_YELLOW',
            'trap_id': '24',
        },
        'trap_25_asic_0': {
            'asic': '0',
            'current': 105652,
            'delta': 0,
            'prev': 105652,
            'tm_trap': 'VOQ_CGM_DRAM_WRED_GREEN',
            'trap_id': '25',
        },
        'trap_26_asic_0': {
            'asic': '0',
            'current': 130484,
            'delta': 0,
            'prev': 130484,
            'tm_trap': 'VOQ_CGM_PD_COUNTERS_OVERFLOW',
            'trap_id': '26',
        },
        'trap_27_asic_0': {
            'asic': '0',
            'current': 118942,
            'delta': 0,
            'prev': 118942,
            'tm_trap': 'VOQ_CGM_CANNOT_EVICT_TO_DRAM',
            'trap_id': '27',
        },
        'trap_28_asic_0': {
            'asic': '0',
            'current': 130736,
            'delta': 0,
            'prev': 130736,
            'tm_trap': 'VOQ_CGM_NON_GUARANTEED_SPACE_OVERFLOW',
            'trap_id': '28',
        },
        'trap_29_asic_0': {
            'asic': '0',
            'current': 117939,
            'delta': 0,
            'prev': 117939,
            'tm_trap': 'RXPDR_J_COUNTER_OVERFLOW',
            'trap_id': '29',
        },
        'trap_2_asic_0': {
            'asic': '0',
            'current': 4333278472,
            'delta': 4214818838,
            'prev': 118459634,
            'tm_trap': 'STATISTICAL_METER_PACKET_GOT_DROPPED_DUE_TO_STATISTICAL_METER',
            'trap_id': '2',
        },
        'trap_30_asic_0': {
            'asic': '0',
            'current': 143258,
            'delta': 0,
            'prev': 143258,
            'tm_trap': 'RXPDR_RXRQ0_DSP_OVERFLOW',
            'trap_id': '30',
        },
        'trap_31_asic_0': {
            'asic': '0',
            'current': 130531,
            'delta': 0,
            'prev': 130531,
            'tm_trap': 'RXPDR_RXRQ0_VN_OVERFLOW',
            'trap_id': '31',
        },
        'trap_32_asic_0': {
            'asic': '0',
            'current': 118114,
            'delta': 0,
            'prev': 118114,
            'tm_trap': 'RXPDR_RXRQ_DEQ_MC_DROP',
            'trap_id': '32',
        },
        'trap_3_asic_0': {
            'asic': '0',
            'current': 19143,
            'delta': 0,
            'prev': 19143,
            'tm_trap': 'ETHERNET_METERS_PACKET_OUT_OF_RATE',
            'trap_id': '3',
        },
        'trap_4_asic_0': {
            'asic': '0',
            'current': 130267,
            'delta': 0,
            'prev': 130267,
            'tm_trap': 'RXPDR_A_COUNTER_DSP_OVERFLOW',
            'trap_id': '4',
        },
        'trap_5_asic_0': {
            'asic': '0',
            'current': 106303,
            'delta': 0,
            'prev': 106303,
            'tm_trap': 'RXPDR_A_COUNTER_VN_OVERFLOW',
            'trap_id': '5',
        },
        'trap_6_asic_0': {
            'asic': '0',
            'current': 118590,
            'delta': 0,
            'prev': 118590,
            'tm_trap': 'RXPDR_A_COUNTER_MCID_OVERFLOW',
            'trap_id': '6',
        },
        'trap_7_asic_0': {
            'asic': '0',
            'current': 117073,
            'delta': 0,
            'prev': 117073,
            'tm_trap': 'RXPDR_B_COUNTER_OVERFLOW',
            'trap_id': '7',
        },
        'trap_9_asic_0': {
            'asic': '0',
            'current': 119440,
            'delta': 0,
            'prev': 119440,
            'tm_trap': 'RXPDR_RXRQ1_DSP_OVERFLOW',
            'trap_id': '9',
        },
    },
}