expected_output = {
    "vrf": {
        "VRF default": {
            "address_family": {
                "ipv6": {
                    "instance": {
                        "mpls1": {
                            "area": {
                                0: {
                                    "neighbor_router_id": {
                                        "10.94.1.1": {
                                            "interface": {
                                                "GigabitEthernet0/0/0/0.1": {
                                                    "Neighbor": {
                                                        "interface-id": 14,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:38",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/46/46,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.2": {
                                                    "Neighbor": {
                                                        "interface-id": 15,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:34",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/3/3,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.3": {
                                                    "Neighbor": {
                                                        "interface-id": 16,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:37",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/30/30,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.4": {
                                                    "Neighbor": {
                                                        "interface-id": 17,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:31",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/36/36,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.5": {
                                                    "Neighbor": {
                                                        "interface-id": 18,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:35",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/6/6,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.6": {
                                                    "Neighbor": {
                                                        "interface-id": 19,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:39",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/22/22,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.7": {
                                                    "Neighbor": {
                                                        "interface-id": 20,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:39",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/62/62,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.8": {
                                                    "Neighbor": {
                                                        "interface-id": 21,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:36",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/33/33,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.9": {
                                                    "Neighbor": {
                                                        "interface-id": 22,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:34",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/50/50,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.10": {
                                                    "Neighbor": {
                                                        "interface-id": 23,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:34",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/56/56,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.11": {
                                                    "Neighbor": {
                                                        "interface-id": 24,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:33",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/59/59,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.12": {
                                                    "Neighbor": {
                                                        "interface-id": 25,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:38",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/63/63,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.13": {
                                                    "Neighbor": {
                                                        "interface-id": 26,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:39",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/7/7,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.14": {
                                                    "Neighbor": {
                                                        "interface-id": 27,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:30",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/5/5,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.15": {
                                                    "Neighbor": {
                                                        "interface-id": 28,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:38",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/20/20,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.16": {
                                                    "Neighbor": {
                                                        "interface-id": 29,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:36",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/64/64,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.17": {
                                                    "Neighbor": {
                                                        "interface-id": 30,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:35",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/11/11,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.18": {
                                                    "Neighbor": {
                                                        "interface-id": 31,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:39",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/55/55,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.19": {
                                                    "Neighbor": {
                                                        "interface-id": 32,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:35",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/29/29,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.20": {
                                                    "Neighbor": {
                                                        "interface-id": 33,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:33",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/14/14,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.21": {
                                                    "Neighbor": {
                                                        "interface-id": 34,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:33",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/15/15,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.22": {
                                                    "Neighbor": {
                                                        "interface-id": 35,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:35",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/47/47,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.23": {
                                                    "Neighbor": {
                                                        "interface-id": 36,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:39",
                                                    "neighbor_uptime": "00:31:45",
                                                    "index": "1/2/2,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                                "GigabitEthernet0/0/0/0.24": {
                                                    "Neighbor": {
                                                        "interface-id": 37,
                                                        "link-local_address": "fe80::20c:29ff:fe6b:1a0",
                                                    },
                                                    "priority": 1,
                                                    "state": "full",
                                                    "state_changes": 6,
                                                    "options": "0x13",
                                                    "dead_timer": "00:00:34",
                                                    "neighbor_uptime": "00:31:44",
                                                    "index": "1/45/45,",
                                                    "statistics": {
                                                        "retransmission_queue_length": 0,
                                                        "number_of_retransmissions": 0,
                                                        "last_retrans_scan_length": 0,
                                                        "last_retrans_max_scan_length": 0,
                                                    },
                                                    "first": "0(0)/0(0)/0(0)",
                                                    "next": "0(0)/0(0)/0(0)",
                                                },
                                            }
                                        }
                                    }
                                }
                            },
                            "total_neighbor_count": 24,
                        }
                    }
                }
            }
        }
    }
}
