expected_output = {'portgroup': {1: {'intf': {'tengigabitethernet6/0/1': {'group_max_bw': '120G',
                                                        'intf_bw': '10G',
                                                        'portgroup': 1,
                                                        'status': 'up'},
                            'tengigabitethernet6/0/10': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 1,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/11': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 1,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/12': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 1,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/2': {'group_max_bw': '120G',
                                                        'intf_bw': '10G',
                                                        'portgroup': 1,
                                                        'status': 'up'},
                            'tengigabitethernet6/0/3': {'group_max_bw': '120G',
                                                        'intf_bw': '10G',
                                                        'portgroup': 1,
                                                        'status': 'up'},
                            'tengigabitethernet6/0/4': {'group_max_bw': '120G',
                                                        'intf_bw': '10G',
                                                        'portgroup': 1,
                                                        'status': 'up'},
                            'tengigabitethernet6/0/5': {'group_max_bw': '120G',
                                                        'intf_bw': '10G',
                                                        'portgroup': 1,
                                                        'status': 'up'},
                            'tengigabitethernet6/0/6': {'group_max_bw': '120G',
                                                        'intf_bw': '10G',
                                                        'portgroup': 1,
                                                        'status': 'up'},
                            'tengigabitethernet6/0/7': {'group_max_bw': '120G',
                                                        'intf_bw': '10G',
                                                        'portgroup': 1,
                                                        'status': 'up'},
                            'tengigabitethernet6/0/8': {'group_max_bw': '120G',
                                                        'intf_bw': '10G',
                                                        'portgroup': 1,
                                                        'status': 'up'},
                            'tengigabitethernet6/0/9': {'group_max_bw': '120G',
                                                        'intf_bw': '10G',
                                                        'portgroup': 1,
                                                        'status': 'up'}}},
               2: {'intf': {'tengigabitethernet6/0/13': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/14': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/15': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/16': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/17': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/18': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/19': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/20': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/21': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/22': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/23': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/24': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 2,
                                                         'status': 'up'}}},
               3: {'intf': {'tengigabitethernet6/0/25': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/26': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/27': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/28': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/29': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/30': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/31': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/32': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/33': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/34': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/35': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/36': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 3,
                                                         'status': 'up'}}},
               4: {'intf': {'tengigabitethernet6/0/37': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/38': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/39': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/40': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/41': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/42': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/43': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/44': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/45': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/46': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/47': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'},
                            'tengigabitethernet6/0/48': {'group_max_bw': '120G',
                                                         'intf_bw': '10G',
                                                         'portgroup': 4,
                                                         'status': 'up'}}}}
    }

