
expected_output = {'neighbor': {'10.186.0.3': {'address_family': {'l2vpn evpn': {'bgp_table_version': 1509868,
                                                         'neighbor_version': 1509868,
                                                         'path': {'accepted_paths': 70456,
                                                                  'memory_usage': 8736544,
                                                                  'total_entries': 18989},
                                                         'send_community': 'extended',
                                                         'session_state': 'established',
                                                         'third_party_nexthop': True}},
                       'bgp_negotiated_capabilities': {'dynamic_capability': 'advertised '
                                                                             '(mp, '
                                                                             'refresh, '
                                                                             'gr) '
                                                                             'received '
                                                                             '(mp, '
                                                                             'refresh, '
                                                                             'gr)',
                                                       'dynamic_capability_old': 'advertised '
                                                                                 'received',
                                                       'graceful_restart': 'advertised '
                                                                           'received',
                                                       'route_refresh': 'advertised '
                                                                        'received',
                                                       'route_refresh_old': 'advertised '
                                                                            'received'},
                       'bgp_negotiated_keepalive_timers': {'hold_time': 180,
                                                           'keepalive_interval': 60,
                                                           'keepalive_timer': 'expiry '
                                                                              'due '
                                                                              '00:00:43',
                                                           'last_read': '00:00:22',
                                                           'last_written': '00:00:16'},
                       'bgp_neighbor_counters': {'messages': {'received': {'bytes_in_queue': 0,
                                                                           'capability': 3,
                                                                           'keepalives': 8631,
                                                                           'notifications': 0,
                                                                           'opens': 2,
                                                                           'route_refresh': 0,
                                                                           'total': 122732,
                                                                           'total_bytes': 31462937,
                                                                           'updates': 114096},
                                                              'sent': {'bytes_in_queue': 0,
                                                                       'capability': 3,
                                                                       'keepalives': 8716,
                                                                       'notifications': 1,
                                                                       'opens': 2,
                                                                       'route_refresh': 2,
                                                                       'total': 39121,
                                                                       'total_bytes': 6141326,
                                                                       'updates': 30397}}},
                       'bgp_session_transport': {'connection': {'dropped': 1,
                                                                'established': 2,
                                                                'last_reset': 'never',
                                                                'reset_by': 'peer',
                                                                'reset_reason': 'no '
                                                                                'error'},
                                                 'transport': {'fd': '85',
                                                               'foreign_host': '10.186.0.3',
                                                               'foreign_port': '179',
                                                               'local_host': '10.186.0.1',
                                                               'local_port': '63174'}},
                       'bgp_version': 4,
                       'peer_fab_type': 'fabric-internal',
                       'graceful_restart_paramters': {'restart_time_advertised_by_peer_seconds': 120,
                                                      'restart_time_advertised_to_peer_seconds': 120,
                                                      'stale_time_advertised_by_peer_seconds': 300},
                       'link': 'ibgp',
                       'local_as': 'None',
                       'peer_index': 1,
                       'received_bytes_queue': 0,
                       'received_messages': 122732,
                       'received_notifications': 0,
                       'remote_as': 1,
                       'retry_time': 'None',
                       'router_id': '10.186.0.3',
                       'sent_bytes_queue': 0,
                       'sent_messages': 39121,
                       'sent_notifications': 1,
                       'session_state': 'established',
                       'shutdown': False,
                       'up_time': '6d01h',
                       'update_source': 'loopback0'},
          '10.186.0.4': {'address_family': {'l2vpn evpn': {'bgp_table_version': 1509868,
                                                         'neighbor_version': 1509868,
                                                         'path': {'accepted_paths': 70456,
                                                                  'memory_usage': 8736544,
                                                                  'total_entries': 18989},
                                                         'send_community': 'extended',
                                                         'session_state': 'established',
                                                         'third_party_nexthop': True}},
                       'bgp_negotiated_capabilities': {'dynamic_capability': 'advertised '
                                                                             '(mp, '
                                                                             'refresh, '
                                                                             'gr) '
                                                                             'received '
                                                                             '(mp, '
                                                                             'refresh, '
                                                                             'gr)',
                                                       'dynamic_capability_old': 'advertised '
                                                                                 'received',
                                                       'graceful_restart': 'advertised '
                                                                           'received',
                                                       'route_refresh': 'advertised '
                                                                        'received',
                                                       'route_refresh_old': 'advertised '
                                                                            'received'},
                       'bgp_negotiated_keepalive_timers': {'hold_time': 180,
                                                           'keepalive_interval': 60,
                                                           'keepalive_timer': 'expiry '
                                                                              'due '
                                                                              '00:00:43',
                                                           'last_read': '00:00:22',
                                                           'last_written': '00:00:16'},
                       'bgp_neighbor_counters': {'messages': {'received': {'bytes_in_queue': 0,
                                                                           'capability': 2,
                                                                           'keepalives': 8631,
                                                                           'notifications': 0,
                                                                           'opens': 1,
                                                                           'route_refresh': 0,
                                                                           'total': 119972,
                                                                           'total_bytes': 29264135,
                                                                           'updates': 111338},
                                                              'sent': {'bytes_in_queue': 0,
                                                                       'capability': 2,
                                                                       'keepalives': 8715,
                                                                       'notifications': 0,
                                                                       'opens': 1,
                                                                       'route_refresh': 2,
                                                                       'total': 38031,
                                                                       'total_bytes': 5259433,
                                                                       'updates': 29311}}},
                       'bgp_session_transport': {'connection': {'dropped': 0,
                                                                'established': 1,
                                                                'last_reset': 'never',
                                                                'reset_by': 'peer',
                                                                'reset_reason': 'no '
                                                                                'error'},
                                                 'transport': {'fd': '83',
                                                               'foreign_host': '10.186.0.4',
                                                               'foreign_port': '179',
                                                               'local_host': '10.186.0.1',
                                                               'local_port': '62918'}},
                       'bgp_version': 4,
                       'peer_fab_type': 'fabric-internal',
                       'graceful_restart_paramters': {'restart_time_advertised_by_peer_seconds': 120,
                                                      'restart_time_advertised_to_peer_seconds': 120,
                                                      'stale_time_advertised_by_peer_seconds': 300},
                       'link': 'ibgp',
                       'local_as': 'None',
                       'peer_index': 2,
                       'received_bytes_queue': 0,
                       'received_messages': 119972,
                       'received_notifications': 0,
                       'remote_as': 1,
                       'retry_time': 'None',
                       'router_id': '10.186.0.4',
                       'sent_bytes_queue': 0,
                       'sent_messages': 38031,
                       'sent_notifications': 0,
                       'session_state': 'established',
                       'shutdown': False,
                       'up_time': '6d02h',
                       'update_source': 'loopback0'}}}
