expected_output = {
    "my_state": "13 -ACTIVE",
    "peer_state": "1  -DISABLED",
    "mode": "Simplex",
    "unit": "Primary",
    "unit_id": 48,
    "redundancy_mode_operational": "Non-redundant",
    "redundancy_mode_configured": "sso",
    "redundancy_state": "Non Redundant",
    "manual_swact": "disabled",
    "manual_swact_reason": "system is simplex (no peer unit)",
    "communications": "Down",
    "communications_reason": "Simplex mode",
    "client_count": 84,
    "client_notification_tmr_msec": 30000,
    "rf_debug_mask": "0x0",
}
