expected_output = {
        'Ethernet2/1':
            {'auto_mdix': 'off',
             'auto_negotiate': False,
             'admin_state': 'up',
             'bandwidth': 768,
             'beacon': 'off',
             'counters':
                 {'in_bad_etype_drop': 0,
                  'in_broadcast_pkts': 0,
                  'in_crc_errors': 0,
                  'in_discard': 0,
                  'in_errors': 0,
                  'in_if_down_drop': 0,
                  'in_ignored': 0,
                  'in_jumbo_packets': 0,
                  'in_mac_pause_frames': 0,
                  'in_multicast_pkts': 0,
                  'in_no_buffer': 0,
                  'in_octets': 0,
                  'in_overrun': 0,
                  'in_oversize_frame': 0,
                  'in_pkts': 0,
                  'in_runts': 0,
                  'in_short_frame': 0,
                  'in_storm_suppression_packets': 0,
                  'in_underrun': 0,
                  'in_unicast_pkts': 0,
                  'in_unknown_protos': 0,
                  'in_watchdog': 0,
                  'in_with_dribble': 0,
                  'last_clear': 'never',
                  'out_babble': 0,
                  'out_broadcast_pkts': 0,
                  'out_collision': 0,
                  'out_deferred': 0,
                  'out_discard': 0,
                  'out_errors': 0,
                  'out_jumbo_packets': 0,
                  'out_late_collision': 0,
                  'out_lost_carrier': 0,
                  'out_mac_pause_frames': 0,
                  'out_multicast_pkts': 0,
                  'out_no_carrier': 0,
                  'out_octets': 0,
                  'out_pkts': 0,
                  'out_unicast_pkts': 0,
                  'rate':
                      {'in_rate': 0,
                       'in_rate_bps': 0,
                       'in_rate_pkts': 0,
                       'in_rate_pps': 0,
                       'load_interval': 0,
                       'out_rate': 0,
                       'out_rate_bps': 0,
                       'out_rate_pkts': 0,
                       'out_rate_pps': 0},
                  'rx': True,
                  'tx': True},
             'delay': 3330,
             'dedicated_interface': True,
             'description': 'desc-1',
             'duplex_mode': 'full',
             'efficient_ethernet': 'n/a',
             'enabled': True,
             'encapsulations':
                 {'encapsulation': 'arpa'},
             'ethertype': '0x8100',
             'flow_control':
                 {'receive': False, 'send': False},
             'interface_reset': 1,
             'ipv4':
                 {'10.4.4.4/24':
                      {'ip': '10.4.4.4',
                       'prefix_length': '24',
                       'route_tag': '10',
                       'secondary': True}},
             'last_link_flapped': '00:00:29',
             'link_state': 'up',
             'mac_address': 'aaaa.bbff.8888',
             'medium': 'broadcast',
             'mtu': 1600,
             'oper_status': 'up',
             'port_channel':
                 {'port_channel_member': False},
             'phys_address': '5254.00ff.8506',
             'port_mode': 'routed',
             'port_speed': '1000',
             'reliability': '255/255',
             'rxload': '1/255',
             'switchport_monitor': 'off',
             'txload': '1/255',
             'types': '10/100/1000 Ethernet'},
        'Ethernet2/1.10':
            {'auto_mdix': 'off',
             'admin_state': 'down',
             'bandwidth': 768,
             'delay': 10,
             'dedicated_interface': True,
             'enabled': False,
             'encapsulations':
                 {'encapsulation': 'dot1q',
                  'first_dot1q': '10'},
             'ethertype': '0x8100',
             'link_state': 'down',
             'mac_address': '5254.00ff.8534',
             'medium': 'broadcast',
             'mtu': 1600,
             'oper_status': 'down',
             'port_channel':
                 {'port_channel_member': False},
             'parent_interface': 'Ethernet2/1',
             'phys_address': '5254.00ff.8506',
             'port_mode': 'routed',
             'reliability': '255/255',
             'rxload': '1/255',
             'txload': '1/255',
             'types': '10/100/1000 Ethernet'},
        'Ethernet2/1.20':
            {'auto_mdix': 'off',
             'admin_state': 'up',
             'bandwidth': 768,
             'delay': 10,
             'dedicated_interface': True,
             'enabled': True,
             'encapsulations':
                 {'encapsulation': 'dot1q',
                  'first_dot1q': '20'},
             'ethertype': '0x8100',
             'link_state': 'up',
             'mac_address': '5254.00ff.8534',
             'medium': 'p2p',
             'mtu': 1600,
             'oper_status': 'up',
             'port_channel':
                 {'port_channel_member': False},
             'parent_interface': 'Ethernet2/1',
             'phys_address': '5254.00ff.8506',
             'port_mode': 'routed',
             'reliability': '255/255',
             'rxload': '1/255',
             'txload': '1/255',
             'types': '10/100/1000 Ethernet'},
        'Ethernet2/2':
            {'auto_mdix': 'off',
             'auto_negotiate': False,
             'admin_state': 'up',
             'bandwidth': 1000000,
             'beacon': 'off',
             'counters':
                 {'in_bad_etype_drop': 0,
                  'in_broadcast_pkts': 0,
                  'in_crc_errors': 0,
                  'in_discard': 0,
                  'in_errors': 0,
                  'in_if_down_drop': 0,
                  'in_ignored': 0,
                  'in_jumbo_packets': 0,
                  'in_mac_pause_frames': 0,
                  'in_multicast_pkts': 0,
                  'in_no_buffer': 0,
                  'in_octets': 0,
                  'in_overrun': 0,
                  'in_oversize_frame': 0,
                  'in_pkts': 0,
                  'in_runts': 0,
                  'in_short_frame': 0,
                  'in_storm_suppression_packets': 0,
                  'in_underrun': 0,
                  'in_unicast_pkts': 0,
                  'in_unknown_protos': 0,
                  'in_watchdog': 0,
                  'in_with_dribble': 0,
                  'last_clear': 'never',
                  'out_babble': 0,
                  'out_broadcast_pkts': 0,
                  'out_collision': 0,
                  'out_deferred': 0,
                  'out_discard': 0,
                  'out_errors': 0,
                  'out_jumbo_packets': 0,
                  'out_late_collision': 0,
                  'out_lost_carrier': 0,
                  'out_mac_pause_frames': 0,
                  'out_multicast_pkts': 0,
                  'out_no_carrier': 0,
                  'out_octets': 0,
                  'out_pkts': 0,
                  'out_unicast_pkts': 0,
                  'rate':
                      {'in_rate': 0,
                       'in_rate_bps': 0,
                       'in_rate_pkts': 0,
                       'in_rate_pps': 0,
                       'load_interval': 0,
                       'out_rate': 0,
                       'out_rate_bps': 0,
                       'out_rate_pkts': 0,
                       'out_rate_pps': 0},
                  'rx': True,
                  'tx': True},
             'delay': 10,
             'dedicated_interface': True,
             'duplex_mode': 'full',
             'efficient_ethernet': 'n/a',
             'enabled': True,
             'encapsulations':
                 {'encapsulation': 'arpa'},
             'ethertype': '0x8100',
             'flow_control':
                 {'receive': False, 'send': False},
             'interface_reset': 1,
             'last_link_flapped': '00:07:28',
             'link_state': 'up',
             'mac_address': '5254.00ff.62da',
             'medium': 'broadcast',
             'mtu': 1500,
             'oper_status': 'up',
             'port_channel':
                 {'port_channel_member': False},
             'phys_address': '5254.00ff.62da',
             'port_mode': 'trunk',
             'port_speed': '1000',
             'reliability': '255/255',
             'rxload': '1/255',
             'switchport_monitor': 'off',
             'txload': '1/255',
             'types': '10/100/1000 Ethernet'},
        'mgmt0':
            {'auto_mdix': 'off',
             'auto_negotiate': True,
             'admin_state': 'up',
             'bandwidth': 1000000,
             'counters':
                 {'in_multicast_pkts': 2,
                  'in_unicast_pkts': 0,
                  'in_broadcast_pkts': 4,
                  'in_pkts': 2,
                  'in_octets': 4726,
                  'rate':
                      {'in_rate': 0,
                       'in_rate_pkts': 0,
                       'load_interval': 1,
                       'out_rate': 24,
                       'out_rate_pkts': 0},
                  'rx': True,
                  'tx': True},
             'delay': 10,
             'duplex_mode': 'full',
             'enabled': True,
             'encapsulations':
                 {'encapsulation': 'arpa'},
             'ethertype': '0x0000',
             'link_state': 'up',
             'mac_address': '5254.00ff.9c38',
             'medium': 'broadcast',
             'mtu': 1500,
             'oper_status': 'up',
             'port_channel':
                 {'port_channel_member': False},
             'phys_address': '5254.00ff.9c38',
             'port_mode': 'routed',
             'port_speed': '1000',
             'reliability': '255/255',
             'rxload': '1/255',
             'txload': '1/255',
             'types': 'Ethernet'},
        'Ethernet1/1':
            {'bandwidth': 10000000,
             'beacon': 'off',
             'counters':
                 {'in_bad_etype_drop': 0,
                  'in_broadcast_pkts': 0,
                  'in_crc_errors': 0,
                  'in_discard': 0,
                  'in_errors': 0,
                  'in_if_down_drop': 0,
                  'in_ignored': 0,
                  'in_mac_pause_frames': 0,
                  'in_multicast_pkts': 260,
                  'in_no_buffer': 0,
                  'in_octets': 35017,
                  'in_overrun': 0,
                  'in_oversize_frame': 0,
                  'in_jumbo_packets': 0,
                  'in_storm_suppression_bytes': 0,
                  'in_pkts': 260,
                  'in_runts': 0,
                  'in_short_frame': 0,
                  'in_underrun': 0,
                  'in_unicast_pkts': 0,
                  'in_unknown_protos': 0,
                  'in_watchdog': 0,
                  'in_with_dribble': 0,
                  'last_clear': '13:44:29',
                  'out_babble': 0,
                  'out_broadcast_pkts': 0,
                  'out_collision': 0,
                  'out_deferred': 0,
                  'out_discard': 0,
                  'out_errors': 0,
                  'out_jumbo_packets': 0,
                  'out_late_collision': 0,
                  'out_lost_carrier': 0,
                  'out_mac_pause_frames': 0,
                  'out_multicast_pkts': 0,
                  'out_no_carrier': 0,
                  'out_octets': 0,
                  'out_pkts': 0,
                  'out_unicast_pkts': 0,
                  'rate':
                      {'in_rate': 0,
                       'in_rate_bps': 0,
                       'in_rate_pkts': 0,
                       'in_rate_pps': 0,
                       'load_interval': 30,
                       'out_rate': 0,
                       'out_rate_bps': 0,
                       'out_rate_pkts': 0,
                       'out_rate_pps': 0},
                  'rx': True,
                  'tx': True},
             'delay': 10,
             'dedicated_interface': True,
             'description': 'Connection to pe1',
             'duplex_mode': 'auto',
             'enabled': True,
             'encapsulations': {'encapsulation': 'arpa'},
             'ethertype': '0x8100',
             'flow_control': {'receive': False, 'send': False},
             'interface_reset': 0,
             'ipv4': {'10.229.1.112/16': {'ip': '10.229.1.112',
                                          'prefix_length': '16'}},
             'last_link_flapped': '13:23:37',
             'link_state': 'down',
             'mac_address': '002a.6aff.4571',
             'medium': 'broadcast',
             'mtu': 1500,
             'oper_status': 'down',
             'media_type': '10G',
             'phys_address': '002a.6aff.451d',
             'port_channel': {'port_channel_member': False},
             'port_speed': '10',
             'reliability': '255/255',
             'rxload': '1/255',
             'switchport_monitor': 'off',
             'txload': '1/255',
             'types': '1000/10000 Ethernet'},
        'nve1':
            {'enabled': True,
             'link_state': 'up',
             'oper_status': 'up',
             'port_channel':
                 {'port_channel_member': False}}}