expected_output = {
    'aom_dependency_sanity_check': 'PASS',
    'aom_obj_id': 213643,
    'buckets': [
        {'id': 0, 'link': 'GigabitEthernet0/0/1'},
        {'id': 1, 'link': 'GigabitEthernet0/0/1'},
        {'id': 2, 'link': 'GigabitEthernet0/0/1'},
        {'id': 3, 'link': 'GigabitEthernet0/0/1'},
        {'id': 4, 'link': 'GigabitEthernet0/0/2'},
        {'id': 5, 'link': 'GigabitEthernet0/0/2'},
        {'id': 6, 'link': 'GigabitEthernet0/0/2'},
        {'id': 7, 'link': 'GigabitEthernet0/0/2'},
        {'id': 8, 'link': 'GigabitEthernet0/0/3'},
        {'id': 9, 'link': 'GigabitEthernet0/0/3'},
        {'id': 10, 'link': 'GigabitEthernet0/0/3'},
        {'id': 11, 'link': 'GigabitEthernet0/0/3'},
        {'id': 12, 'link': 'GigabitEthernet0/0/4'},
        {'id': 13, 'link': 'GigabitEthernet0/0/4'},
        {'id': 14, 'link': 'GigabitEthernet0/0/4'},
        {'id': 15, 'link': 'GigabitEthernet0/0/4'}
    ],
    'dirty': 'unknown',
    'ether_channel_id': 32,
    'flags': ['ipv4'],
    'frr_linkdown_id': 65535,
    'icmp6_flags': ['unreachables', 'redirects'],
    'icmp_flags': ['unreachables', 'redirects', 'no-info-reply', 'no-mask-reply'],
    'id': 2337,
    'ip_address': '100.0.0.3',
    'ipv6_address': '2001:100::3',
    'load_balancing_method': 'Flow',
    'members': [
        'GigabitEthernet0/0/1',
        'GigabitEthernet0/0/2',
        'GigabitEthernet0/0/3',
        'GigabitEthernet0/0/4'
    ],
    'mtu': 1530,
    'name': 'Port-channel32',
    'number_of_buckets': 16,
    'number_of_member_links': 4,
    'qfp_id': 1017,
    'schedules': 4096,
    'smi_protocols': ['UNKNOWN'],
    'snmp_id': 2581,
    'state': 'enabled',
    'type': 'EC',
    'vnet_extra_info': 0,
    'vnet_tag': 0
}
