expected_output = {
    "mfib":{
        1:{
            "attrs":{
                "asic":{
                    0:{
                        "mcid_oid_asic":7771
                    }
                },
                "cpu_credit":0,
                "ec_seed":2,
                "fset_aux_urid":"0x0",
                "fset_urid_hash":"0x300000000000e552 ( ed49bd13 )",
                "gid":10293,
                "hw_asic_info":{
                    0:{
                        "enable_rpf_check":1,
                        "punt_and_forward":0,
                        "punt_on_rpf_fail":1,
                        "rpf_port_oid":7744,
                        "rpfid":0,
                        "use_rpfid":0
                    }
                },
                "hw_flag":"InHw",
                "ios_f_ifs":1,
                "mlist_f_ifs":1,
                "mlist_flags":"None",
                "mlist_hndl_id":"0x118835bd3b8 ( 0x40003edd )",
                "mlist_urid":"0x100000000000acb6",
                "npi_mroute_ent":"0x118835bdc58",
                "oif_count":2,
                "oif_details":[
                    {
                        "adjid":"0xf8005441",
                        "interface":"Vl109",
                        "flags":[
                            "F",
                            "NS"
                        ],
                        "intf_type":"SVI_IF",
                        "msg_type":"NORMAL"
                    },
                    {
                        "adjid":"0xf8005451",
                        "interface":"Vl119",
                        "flags":[
                            "A"
                        ],
                        "intf_type":"SVI_IF",
                        "msg_type":"NORMAL"
                    }
                ],
                "pps_approx":0,
                "rpf_adjacency_id":"0xf8005451",
                "svi_fwd_ifs":2,
                "total_packets":0
            },
            "group":"232.1.1.1",
            "mvrf":0,
            "source":"119.1.1.2"
        }
    }
}