expected_output ={
    "mfib":{
        1:{
            "attrs":{
                "asic":{
                    0:{
                        "mcid_oid_asic":3098
                    },
                    1:{
                        "mcid_oid_asic":3060
                    }
                },
                "cpu_credit":0,
                "ec_seed":4,
                "fset_aux_urid":"0x0",
                "fset_urid_hash":"0x3000000000000b87 ( 45b1cea1 )",
                "gid":8199,
                "hw_asic_info":{
                    0:{
                        "cookie":"0x30::b87",
                        "enable_rpf_check":1,
                        "ip_mcid_oid":3098,
                        "punt_and_forward":0,
                        "punt_on_rpf_fail":1,
                        "rpf_port_oid":3087,
                        "rpfid":0,
                        "use_rpfid":0
                    },
                    1:{
                        "cookie":"0x30::b87",
                        "enable_rpf_check":1,
                        "ip_mcid_oid":3060,
                        "punt_and_forward":0,
                        "punt_on_rpf_fail":1,
                        "rpf_port_oid":3056,
                        "rpfid":0,
                        "use_rpfid":0
                    }
                },
                "hw_flag":"InHw",
                "ios_f_ifs":1,
                "mlist_f_ifs":1,
                "mlist_flags":"None",
                "mlist_hndl_id":"0x11881242190 ( 0x152 )",
                "mlist_urid":"0x1000000000000c5a",
                "npi_mroute_ent":"0x11881603d98",
                "oif_count":2,
                "oif_details":[
                    {
                        "adjid":"0xf8005582",
                        "interface":"Vl369",
                        "flags":[
                            "F",
                            "NS"
                        ],
                        "intf_type":"SVI_IF",
                        "msg_type":"NORMAL"
                    },
                    {
                        "adjid":"0xf8005592",
                        "interface":"Vl379",
                        "flags":[
                            "A"
                        ],
                        "intf_type":"SVI_IF",
                        "msg_type":"NORMAL"
                    }
                ],
                "rpf_adjacency_id":"0xf8005592",
                "svi_fwd_ifs":2
            },
            "group":"ff35::1",
            "mvrf":12,
            "source":"2000:149:1:1:1::2"
        }
    }
}