expected_output={
   "vrf":{
      "default":{
         "address_family":{
            "ipv4":{
               "multicast_group":{
                  "225.1.1.1":{
                     "source_address":{
                        "192.168.1.10":{
                           "expire":"00:01:51",
                           "flags":"FTp",
                           "incoming_interface_list":{
                              "Vlan2001":{
                                 "rpf_nbr":"0.0.0.0"
                              }
                           },
                           "msdp_learned":False,
                           "outgoing_interface_list":{
                              "LISP0.1":{
                                 "expire":"00:02:43",
                                 "flags":"p",
                                 "lisp_mcast_source":"100.99.99.99",
                                 "pkts":2,
                                 "state_mode":"forward/sparse",
                                 "uptime":"02:00:04"
                              },
                              "LISP0.1-1":{
                                 "expire":"00:03:24",
                                 "flags":"p",
                                 "lisp_mcast_source":"100.22.22.22",
                                 "pkts":2,
                                 "state_mode":"forward/sparse",
                                 "uptime":"02:00:04"
                              },
                              "LISP0.1-2":{
                                 "expire":"00:02:48",
                                 "flags":"p",
                                 "lisp_mcast_source":"100.33.33.33",
                                 "pkts":2,
                                 "state_mode":"forward/sparse",
                                 "uptime":"02:00:04"
                              },
                              "LISP0.1-3":{
                                 "expire":"00:03:28",
                                 "flags":"p",
                                 "lisp_mcast_source":"100.154.154.154",
                                 "pkts":2,
                                 "state_mode":"forward/sparse",
                                 "uptime":"02:00:04"
                              }
                           },
                           "rp_bit":False,
                           "rpf_nbr":"0.0.0.0",
                           "uptime":"02:00:04"
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
