expected_output = {
    "index": {
        1: {
            "ip1": "10.10.1.166",
            "ip2": "66.220.146.224",
            "port1": 52059,
            "port2": 80,
            "l3_proto": 1,
            "l4_proto": 6,
            "vrf_vlan": 0,
            "timeout_sec": 60,
            "timeout_hl": "HW",
            "app_name": "unknown",
            "tuple_type": "Full",
            "flow_type": "Real Flow",
            "is_swapped": "Yes",
            "clients": "0x01",
            "bypass_type": True,
            "final": True,
            "pkts": 40,
            "bypass_pkt": 2,
            "seg_index": {
                0: {
                    "if_id": 1050,
                    "opst_if": 1050,
                    "seg_dir": "Ingress",
                    "vlan": 0,
                    "fif_dir": True,
                    "seen": True,
                    "is_set": True,
                    "dop_id": 0,
                    "nfl_hdl_st": "0        VV",
                    "bps_pnd": 0,
                    "app_pnd": 0,
                    "frst_ts": 1758196432000,
                    "last_ts": 1758196531000,
                    "bytes": 24190,
                    "pkts": 292,
                    "tcp_flgs": 0,
                },
                1: {
                    "if_id": 1050,
                    "opst_if": 1050,
                    "seg_dir": "Ingress",
                    "vlan": 0,
                    "fif_dir": False,
                    "seen": True,
                    "is_set": True,
                    "dop_id": 0,
                    "nfl_hdl_st": "0        VV",
                    "bps_pnd": 0,
                    "app_pnd": 0,
                    "frst_ts": 1758196432000,
                    "last_ts": 1758196531000,
                    "bytes": 24190,
                    "pkts": 292,
                    "tcp_flgs": 0,
                },
            },
        },
        2: {
            "ip1": "20.0.0.1",
            "ip2": "30.0.0.1",
            "port1": 80,
            "port2": 52059,
            "l3_proto": 1,
            "l4_proto": 6,
            "vrf_vlan": 0,
            "timeout_sec": 360,
            "timeout_hl": "HW",
            "app_name": "http",
            "tuple_type": "Full",
            "flow_type": "Real Flow",
            "is_swapped": "Yes",
            "clients": "0x01",
            "bypass_type": True,
            "final": True,
            "pkts": 20,
            "bypass_pkt": 3,
            "seg_index": {
                0: {
                    "if_id": 1050,
                    "opst_if": "----",
                    "seg_dir": "Ingress",
                    "vlan": 0,
                    "fif_dir": True,
                    "seen": True,
                    "is_set": True,
                    "dop_id": 0,
                    "nfl_hdl_st": "4        VV",
                    "bps_pnd": 0,
                    "app_pnd": 0,
                    "frst_ts": 1758196434000,
                    "last_ts": 1758196529000,
                    "bytes": 193824,
                    "pkts": 180,
                    "tcp_flgs": 0,
                }
            },
        },
        3: {
            "ip1": "20.0.0.1",
            "ip2": "30.0.0.1",
            "port1": 52059,
            "port2": 80,
            "l3_proto": 1,
            "l4_proto": 6,
            "vrf_vlan": 0,
            "timeout_sec": 360,
            "timeout_hl": "HW",
            "app_name": "facebook",
            "tuple_type": "Full",
            "flow_type": "Real Flow",
            "is_swapped": "Yes",
            "clients": "0x01",
            "bypass_type": True,
            "final": True,
            "pkts": 20,
            "bypass_pkt": 3,
            "seg_index": {
                0: {
                    "if_id": 1050,
                    "opst_if": "----",
                    "seg_dir": "Ingress",
                    "vlan": 0,
                    "fif_dir": True,
                    "seen": True,
                    "is_set": True,
                    "dop_id": 0,
                    "nfl_hdl_st": "3        VV",
                    "bps_pnd": 0,
                    "app_pnd": 0,
                    "frst_ts": 1758196434000,
                    "last_ts": 1758196527000,
                    "bytes": 12642,
                    "pkts": 151,
                    "tcp_flgs": 0,
                }
            },
        },
    }
}
