expected_output = {
    'alarm-in1': 'GREEN',
    'alarm-in2': 'GREEN',
    'alarm-out': 'GREEN',
    'console': 'BLACK',
    'dc_a': 'GREEN',
    'dc_b': 'BLACK',
    'express_setup': 'BLACK',
    'number_of_ports_in_status': '14',
    'poe': 'BLACK',
    'status': {
        'GigabitEthernet1/10': 'BLINK_GREEN',
        'GigabitEthernet1/3': 'BLACK',
        'GigabitEthernet1/4': 'BLACK',
        'GigabitEthernet1/5': 'BLACK',
        'GigabitEthernet1/6': 'BLACK',
        'GigabitEthernet1/7': 'BLINK_GREEN',
        'GigabitEthernet1/8': 'BLACK',
        'GigabitEthernet1/9': 'BLINK_AMBER',
        'TenGigabitEthernet1/1': 'BLACK',
        'TenGigabitEthernet1/2': 'BLACK',
        'TwoGigabitEthernet2/1': 'BLACK',
        'TwoGigabitEthernet2/2': 'BLACK',
        'TwoGigabitEthernet2/3': 'BLINK_GREEN',
        'TwoGigabitEthernet2/4': 'BLACK',
    },
    'system': 'GREEN',
}
