expected_output = {
    'alarm-in1': 'GREEN',
    'alarm-in2': 'GREEN',
    'alarm-out': 'GREEN',
    'current_mode': 'STATUS',
    'dc_a': 'BLACK',
    'dc_b': 'GREEN',
    'express_setup': 'BLACK',
    'number_of_ports_in_status': '28',
    'poe': 'BLACK',
    'status': {
        'GigabitEthernet1/1': 'FLASH_GREEN',
        'GigabitEthernet1/10': 'ACT_GREEN',
        'GigabitEthernet1/11': 'ACT_GREEN',
        'GigabitEthernet1/2': 'FLASH_GREEN',
        'GigabitEthernet1/3': 'FLASH_GREEN',
        'GigabitEthernet1/4': 'ACT_GREEN',
        'GigabitEthernet1/5': 'BLACK',
        'GigabitEthernet1/6': 'ACT_GREEN',
        'GigabitEthernet1/7': 'BLACK',
        'GigabitEthernet1/8': 'BLACK',
        'GigabitEthernet1/9': 'ACT_GREEN',
        'GigabitEthernet2/1': 'ACT_GREEN',
        'GigabitEthernet2/10': 'BLACK',
        'GigabitEthernet2/11': 'BLACK',
        'GigabitEthernet2/12': 'BLACK',
        'GigabitEthernet2/13': 'ACT_GREEN',
        'GigabitEthernet2/14': 'BLACK',
        'GigabitEthernet2/15': 'BLACK',
        'GigabitEthernet2/16': 'ACT_GREEN',
        'GigabitEthernet2/2': 'BLACK',
        'GigabitEthernet2/3': 'BLACK',
        'GigabitEthernet2/4': 'BLACK',
        'GigabitEthernet2/5': 'ACT_GREEN',
        'GigabitEthernet2/6': 'BLACK',
        'GigabitEthernet2/7': 'BLACK',
        'GigabitEthernet2/8': 'ACT_AMBER',
        'GigabitEthernet2/9': 'ACT_GREEN',
    },
    'system': 'GREEN',
}




